### ISSUE TITLE
2.0. Xamarin. Replicator fails to get out of Connecting State when connecting to unreachable host

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-net#1000]
The Couchbase Lite .NET issue tracker is reserved for bug reports and enhancement 
requests. For general questions, please use the Couchbase forums:
https://forums.couchbase.com/c/mobile/ . Thank you!

### Library Version

2.0.0-db023  (Beta 2) 
### .NET Runtime

Xamarin Android (Version: 8.2.0.15 (Visual Studio Community)
Xamarin iOS(Version: 11.8.1.28)

### Operating System

mac OS 10.12
### Log Output

Look for "PushPull Replicator:Will connect to _" in the logs 
- [Xamarin Android logs ](https://gist.github.com/rajagp/862397192bae96b3cbaa642233b41d89)
- [Xamarin iOS Logs](https://gist.github.com/rajagp/14d0430713a97b68d56df6474bfba0ef)
### Expected behavior

Replicator should have gone to "Stopped" status and suitable exception logged
### Actual behavior

Replicator remains in "Connecting" state on both Xamarin Android and iOS
- On Android, no exception is logged. 
- On iOS, exception " Could not resolve host '..' " is logged
### Steps To Reproduce

1. Configure the CBL app with a Sync GW endpoint to an invalid Address
2. Run the app and attempt to connect to SGW

### Reproduction Project

You can test it with the [Travel Sample App](https://github.com/couchbaselabs/mobile-travel-sample) master branch

Also, reported on Forums :  https://forums.couchbase.com/t/couchbase-lite-net-2-0-replication-to-unknown-host-on-android/16192/3

**Comment by borrrden** [comment]
Possibly related to #992 which affects the beta but had been resolved. I’ll try that out when I get back to the office on Tuesday. 

Note:  operating system means the OS you are running the travel sample app on, not the OS you build on :)

**Comment by borrrden** [comment]
Oh, unless this is a one shot replication?

**Comment by rajagp** [comment]
@borrrden If there is a version I can pull from internal nuget feeds to test, let me know. It was a continuous replication and all I did was attempt to connect to an non-existent  SGW.

Since you were checking, how would the behavior be different for one-shot. What state does it transition into if it fails to connect

**Comment by borrrden** [comment]
Continuous replication should go offline, one shot should stop.  2.1.0-128 has these changes.
