### ISSUE TITLE
system proxy is not being used for replication UWP

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-net#1002]
### Library Version
2.0.0-636

### .NET Runtime
UWP on Win 10

### Operating System
Windows 10 Fall Creator's Update

### Expected behavior
CBL .net should use system proxy if configured

### Actual behavior
CBL .net is not using system proxy.
The same test works fine with Android

### Steps To Reproduce
- Set up nginx as a proxy (192.168.33.21) to forward requests to SG (192.168.33.22)
- Set 192.168.33.21 as the system proxy - port 4984 for "HTTP" and port 4985 for "Secure" in the Win 10 VM.
- Add an iptables rule at the SG node to drop all incoming requests from 192.168.33.24 (Win 10 client).
- Open a web browser in the win 10 VM and type 192.168.33.22:4985
-> I can get to the SG and I see a log message in the nginx log file for the request - firefox is using system proxy to get to SG.
- Run a replication test case, LiteCore seems to be trying to talk directly to SG and fails: 
```
INFO) Sync (Replicator) [11] 2018-03-20T13:17:15.3835527-07:00 Replicator[<*> ws://192.168.33.22:4984/db] is Connecting, progress 0/0
INFO) Sync {Repl#2} activityLevel=connecting: connectionState=1
INFO) Sync {Repl#2} Told to stop!
INFO) LiteCore {Connection#1} Close connection
```

**Comment by djpongh** [comment]
@raghusarangapani the is .NET only?

**Comment by raghusarangapani** [comment]
The same test works fine with Android. I mentioned the same under Actual Behavior. Yet to try out with iOS, I am having issues with deploying the app to the device.

**Comment by borrrden** [comment]
Is this pytest?

**Comment by raghusarangapani** [comment]
Sent an email to @borrrden with details on how to reproduce the issue

**Comment by borrrden** [comment]
I am worried about this one because the "system proxy" is something unique to .NET Framework.  There doesn't appear to be a supported way to get access to it on .NET Core, and I have not tried UWP yet but I worry that it has the same problem.  This might be infeasible if it has the same issue.

**Comment by borrrden** [comment]
As I feared, this functionality is just not there for .NET in general.  There are lots of open tickets right now revolving around making a cross platform .NET proxy class (notably https://github.com/dotnet/corefx/issues/26494 ) , and a web socket class that can go through proxies.  Barring that, this will take a long time to implement and won't make it into 2.0 for our current schedule.
