### ISSUE TITLE
getting while creating view.

### ISSUE THREAD

**Issue by RamNalluri** [couchbase/couchbase-lite-net#1003]
Getting syntax error No property AsList<string>().
any one help what i missed just i copied code from couch doc.
Below are the code.
// Create a view and register its map and reduce functions:
let phoneView = database.GetView("phones");
phoneView.SetMapReduce((doc, emit) =>
{
    var phones = doc["phones"].AsList<string>();
    foreach(var phone in phones) 
    {
        emit(phone, doc["name"]);
    }
}, (keys, values, rereduce) => {
    if (rereduce) 
    {
        return View.TotalValues(values.ToList());
    } 
    else 
    {
        return values.ToList().Count;
    }
}, "2.0");

**Comment by borrrden** [comment]
The GitHub issue tracker is for reporting bugs, and not for questions.  The issue template should have told you about that as the first paragraph.  Please ask this at https://forums.couchbase.com/c/mobile
