### ISSUE TITLE
[db023/Android 5.1.1 (API 22)] InputDispatcher: .MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

### ISSUE THREAD

**Issue by thomas1983** [couchbase/couchbase-lite-net#1004]
### Library Version

Both
CouchbaseLite/2.0.0 (.NET; Android 5.1.1 [API 22]; LGE Nexus 4) Build/636 LiteCore/732 Commit/c18ebea
and own build:
CouchbaseLite/0.0.0 (.NET; Android 5.1.1 [API 22]; LGE Nexus 4) Build/0 LiteCore/732 Commit/b415d08

### .NET Runtime
(Microsoft Visual Studio Enterprise 2017 Version 15.6.3)
Xamarin.Android SDK   8.2.0.16 (HEAD/a78295902)

### Operating System

Windows 10 enterprise version 1709

### Log Output
[catlogandvsoutput.log](https://github.com/couchbase/couchbase-lite-net/files/1837052/catlogandvsoutput.log)

### Expected behavior

Replication of all buckets

### Actual behavior

App crashes without any notice on screen or in debug in the middle of a bucket replication. The first buckets with a low amount of and simple structured documents seem to do fine. Problem occurs always with high amount of documents (500+) and sometimes with complex structured documents (see example in attached files)

[complexdocument.txt](https://github.com/couchbase/couchbase-lite-net/files/1837086/complexdocument.txt)

Only hint is

```
03-22 10:51:06.945: W/InputDispatcher(556): channel '22c874bd com.companyname.ReplicationTest/md584f0757e160eb302f61ea570c782d337.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
03-22 10:51:06.945: E/InputDispatcher(556): channel '22c874bd com.companyname.ReplicationTest/md584f0757e160eb302f61ea570c782d337.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
```
Could indicate too much threads
### Steps To Reproduce

1. Start application
2. Begin replication of one bucket
3. When the current finishes start the next bucketreplication. (indicator: `completed == total and status == stopped`

### Reproduction Project
Encrypted. Simplification.
Renamed from .zip.pgp to .zip for upload purposes
[ReplicationTest.zip](https://github.com/couchbase/couchbase-lite-net/files/1837090/ReplicationTest.zip)

**Comment by borrrden** [comment]
Thanks for the test case.  If you find out anything else let me know.  I'd be interested in what the crash actually comes from (the portions you have pasted are the result).  Alternatively, I guess it is possible that somehow too much work is being done on the main thread (though replication works with background threads instead, and posts its callbacks on the thread pool by default).

**Comment by borrrden** [comment]
Also I recently found that the updated LiteCore was causing crashes in the commit you mentioned, and I resolved some of that in later commits.  The latest master (commit e58bd01f) is what I am submitting as a candidate for GA to our QE department, so perhaps the issue is resolved already.

**Comment by borrrden** [comment]
I extracted the reproduction project but I don't have access to perform the replication and so I cannot run it.  Is there a public data set available to test this?  If not then I think that this will come out during our Xamarin functional testing.

**Comment by thomas1983** [comment]
ah @borrrden  my bad, I thought you guys test with your own data sets. I don't have the means to set up a public sgw or cbs server.

Well, what's odd, as you might remember we test on different devices. On the Honeywell with Android 4.4 and the Motorola with 7.1 it replicates fine (except the occasional freeze at status busy) up til now. It was on my main device, Google Nexus 4 with 5.1.1 things always go sideways. Very odd indeed. So no hurry here anymore except for curiosity and liable runs on all versions of Android.

The only thing that bugs my application now is open connection to the database when I want to stop continuous replication and start a not-continuous one. But that's another issue altogether.

**Comment by hrajput89** [comment]
I was able to run the project on windows machine with latest .net build (676). The test complete in around 45 mins.

https://www.dropbox.com/s/8j8w6vljrkfswc0/Screenshot%202018-03-23%2015.00.38.png?dl=0

**Comment by borrrden** [comment]
@hrajput89 This is a different issue, I think you meant to post this on 996 instead.

**Comment by borrrden** [comment]
We do have some data sets, but not quite as complex as the ones you have (9 buckets each with differing levels of complex data).  Although QE is working on a test to simulate what you are doing as well.

**Comment by hrajput89** [comment]
I'm able to replicate 500+ doc with the doc content similar to what @thomas1983  has attached. I randomised few fields and even tried to do some mutation (in bulks) after the replication finished. I tested the scenario on android with 454 and .net with 676 builds.

**Comment by thomas1983** [comment]
@hrajput89 , I changed the title to better reflect the current title. It happens to our 5.1.1 device only. Sorry if that wasn't clear. We expect to test replication on bigger buckets (200 000+) somewhere next week, should you be interested.

**Comment by borrrden** [comment]
One question I had is that is it 5.1.1 device only or 5.1.1 device / emulator?  If the latter we can more easily set up this test for that target.

**Comment by thomas1983** [comment]
Hi @borrrden 

We only test on devices, not on emulators. So I don't really know if the problem holds on emulators. As I said before it could just be my device. It's already a good 5 years old. Oldtimer in techtime :-)

**Comment by borrrden** [comment]
With regards to freezing at busy, I have a better handle on some of the causes of that now.  I've been working with Xamarin Android to find out exactly what happens when things go offline and it's a different socket error than other .NET platforms so including that in the list of transient errors to recognize helped out, as well as detecting repeated inability to read from the remote stream as a closure (otherwise it was an infinite loop basically...).  This solves some of the more common stuck busy cases I've faced with Xamarin.  

We will probably put out some kind of 2.1 preview soon (DB, beta, or otherwise since we have only about 2 months total to ship including all dev and testing) and I think the Xamarin story will be a lot better (not to mention we are still on track to incorporating Xamarin builds into the functional test suite that we have).  I'd be curious to see what effect this has on this.
