### ISSUE TITLE
[xamarin-android] Replicator stuck in busy state with test_no_conflicts_update_with_revs_limit[sync_gateway_revs_conflict_configurable-100-35]

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-net#1009]
### Library Version
2.0.0-676

### .NET Runtime
```
Version: 8.3.0.5 (Visual Studio Community)
Android SDK: /$HOME/Library/Android/sdk
	Supported Android versions:
		5.1 (API level 22)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL
```

### Operating System
Android 8.1.0 running on Nexus 6P

### Log Output
https://gist.github.com/raghusarangapani/1d4080e1f3466a8bfda558bbf7a9dafd

### Expected behavior
Replication should complete. This test passes with UWP.

### Actual behavior
The below 3 tests causes replicator to get stuck in a busy state.

test_no_conflicts_update_with_revs_limit[sync_gateway_revs_conflict_configurable-10-25] FAILED
test_no_conflicts_update_with_revs_limit[sync_gateway_revs_conflict_configurable-100-35] FAILED
test_no_conflicts_update_with_revs_limit[sync_gateway_revs_conflict_configurable-100-50] FAILED

### Steps To Reproduce
```
pytest -s --mode=cc --server-version=5.1.0-5552 --sync-gateway-version=2.0.0-823 --liteserv-platform=net-msft --liteserv-host=10.17.4.145 --liteserv-port=8080 --xattrs --create-db-per-test=pull-test testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_no_conflicts_cbl.py --no-conflicts --liteserv-version=2.0.0-b0676 --sg-ssl --timeout 1800 --skip-provisioning -k 'test_no_conflicts_update_with_revs_limit[sync_gateway_revs_conflict_configurable-100-35]'
```

**Comment by borrrden** [comment]
This is because of the socket bug I reported to Google....it's going to cause a lot of problems because basically the socket silently dies, doesn't inform and acts like it is still open so any further messages just go into the void....

Actually, if it is not a LAN IP then this should work.

**Comment by borrrden** [comment]
Consolidated to #1011
