### ISSUE TITLE
Replication got stuck to busy for more than 12 hrs

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-net#1013]
Example:
2.0.0-b705

### .NET Runtime

.NET Core - more than 3 days

### Operating System

 Windows 10

### Log Output

Logs are too big. Added last 10k lines from .net logs.
[system_test_dotnet.log](https://github.com/couchbase/couchbase-lite-net/files/1868563/system_test_dotnet.log)

### Expected behaviour

System test should not get stuck at any place

### Actual behaviour

Replicator got stuck to busy for more than 12hrs and had to kill app forcefully

### Steps To Reproduce

Run System test for longer period of time, say 4 days

### Reproduction Project

pytest -rsx -s --mode=cc --server-version=5.5.0-1992 --sync-gateway-version=2.0.0-823 --liteserv-platforms=dotnet --liteserv-versions=
2.0.0-703 --liteserv-hosts=localhost --liteserv-port=55555 --xattrs --create-db-per-suite="suite_db"  --timeout=432000   --no-db-delete  -k test_system testsuites/CBLTester
/System_test_multiple_device/test_system_testing.py --skip-provisioning

PS: Use --resume-cluster  if the data(1M Docs) is already populated.

**Comment by borrrden** [comment]
There is not enough information here to diagnose what is going on (Need the other side of the conversation, sync gateway logs to see if there are any issues going on there).  Getting stuck in a busy state is very hard to diagnose without a reproduction case, and running something for 3 days is not a viable way.  The only thing I see here is that the Pusher has some pending sequences remaining.  

Also, I see the last statement is a timeout.  Was that when the test was quit?

**Comment by borrrden** [comment]
P.S. Be careful, the RC3 build is 713, not 703

**Comment by hrajput89** [comment]
I collected the files from SGCollect, but for some reason all files are empty with a binary file of 21mb only. We are currently running with the latest RC3 build. Will update the issue.

**Comment by hrajput89** [comment]
I ran system test for 5 days and I was not able to reproduce the issue. Hence closing it for now. Will re-open if I'll be able to reproduce the issue in future.
