### ISSUE TITLE
InnerJoin is not working 

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-net#1014]
### Library Version

2.0.0-713

### .NET Runtime

.NET Core  - less than a min (with travel-sample data available in CBS and CBL APP)

### Operating System

e.g. Windows 10 

### Expected behavior

Inner Join should generate Schema be like this (schema from android and iOS) -

> {"WHAT":[[".route.airline"],[".route.sourceairport"],[".airline.country"]],"LIMIT":10,"FROM":[{"AS":"route"},{"AS":"airline"**,"JOIN":"INNER"**,"ON":["AND",["AND",["=",[".airline.icao"],[".route.destinationairport"]],["=",[".airline.country"],"United States"]],["=",[".route.stops"],0]]}]}

### Actual behavior

Inner Join is  generating Schema like this (schema from .net logs) -
 
> {"WHAT":[[".route.airline"],[".route.sourceairport"],[".airline.country"]],"LIMIT":10,"FROM":[{"AS":"route"},{"AS":"airline","ON":["AND",["AND",["=",[".airline.icao"],[".route.destinationairport"]],["=",[".airline.country"],"United States"]],["=",[".route.country"],0]]}]}

### Steps To Reproduce

Test this Query Call - QueryInnerJoin

```
using (IQuery query = QueryBuilder
                       .Select(
                           SelectResult.Expression(Expression.Property(prop1).From(main)),
                           SelectResult.Expression(Expression.Property(prop2).From(main)),
                           SelectResult.Expression(Expression.Property(prop3).From(secondary)))
                       .From(DataSource.Database(db).As(main))
                       .Join(Join.InnerJoin(DataSource.Database(db).As(secondary))
                             .On(Expression.Property(joinKey1).From(secondary).EqualTo(Expression.Property(joinKey2).From(main))
                                 .And(Expression.Property(whrKey1).From(secondary).EqualTo(Expression.String(whrVal1)))
                                 .And(Expression.Property(whrKey2).From(main).EqualTo(Expression.Int(whrVal2)))))
                       //.OrderBy(Ordering.Expression(Expression.Property(prop1).From(main)).Ascending())
                       .Limit(Expression.Int(limit)))

```
### Reproduction Project

pytest -rsx -s --mode=cc --server-version=5.5.0-2368 --sync-gateway-version=2.0.0-832 --liteserv-platform=dotnet --liteserv-version=2.0.0-713 --liteserv-host=localhost --liteserv-port=8080 --xattrs --create-db-per-suite="suite_db"  --timeout=216000 --skip-provisioning -k test_query_inner_join testsuites/CBLTester/CBL_Functional_tests/SuiteSetup_FunctionalTests/test_query.py

**Comment by borrrden** [comment]
I don't understand this test.  Is it purely to check the generated query JSON?  It seems to be running against an empty database.  Regardless there are two issues, neither of which are couchbase lite issues:

1. "JOIN": "INNER" is missing.  This is OK, as this is the default and it is optional
2. Incorrect ["=",[".route.country"],0].  This is a test issue from the following typo:

```
// Both use whr_key1
var whrKey1 = postBody["whr_key1"].ToString();
var whrKey2 = postBody["whr_key1"].ToString();
```

**Comment by raghusarangapani** [comment]
I can confirm that changing `var whrKey2 = postBody["whr_key2"].ToString();` passes the test. I have pushed the change to git.
