### ISSUE TITLE
p2p replication with attachments fails with incorrect digest error

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-net#1016]
### Library Version
CBL 1.4.1.1-116 (or 1.4.1-107)

### .NET Runtime
LiteServ - .net core

### Operating System
Windows 10 Fall Creator's Update

### Log Output
```
ERROR) SYNC (MultipartDocumentReader): Attachment 'c642e7d7-adee-4e75-850c-c48a07ef9329.png' has incorrect digest (sha1-vSjVubNOLNSVWKh+TclnASIFhFw=; should be either sha1-w1foPNjrpFheXkiiHMUmvZAbCOI= or md5-WHcrcvVYe50dqTnVyw1Lag==), throwing CouchbaseLiteException (AttachmentError)
INFO) ROUTER (CouchbaseLiteRouter): Processing response for /ls_db1/test_ls_db2_47...
WARN) SYNC (RemoteSession): SendAsyncMultipartDownloaderRequest got an exception, aborting...:
Couchbase.Lite.CouchbaseLiteException: Attachment 'c642e7d7-adee-4e75-850c-c48a07ef9329.png' has incorrect digest (sha1-vSjVubNOLNSVWKh+TclnASIFhFw=; should be either sha1-w1foPNjrpFheXkiiHMUmvZAbCOI= or md5-WHcrcvVYe50dqTnVyw1Lag==)
   at Couchbase.Lite.Support.MultipartDocumentReader.RegisterAttachments()
   at Couchbase.Lite.Internal.RemoteSession.<>c__DisplayClass44_1.<SendAsyncMultipartDownloaderRequest>b__0(Task`1 responseMessage)
INFO) ROUTER (CouchbaseLiteResponse): Response closed
```

### Expected behavior
Replication should succeed

### Actual behavior
p2p replication with attachments fails with incorrect digest error between net-windows and net-mono.
The same test passes with net-windows and MacOSX 1.4.1-88.
The same test also passed with net-mono and net-mono 1.4.0.1-4.

### Steps To Reproduce
`
pytest -s --liteserv-one-platform=net-msft --liteserv-one-version=1.4.1.1-116 --liteserv-one-host=192.168.33.24 --liteserv-one-port=59840 --liteserv-one-storage-engine=SQLCipher --liteserv-two-platform=net-mono --liteserv-two-version=1.4.1.1-116 --liteserv-two-host=192.168.33.1 --liteserv-two-port=59840 --liteserv-two-storage-engine=SQLCipher testsuites/listener/shared/client_client/ -k 'test_peer_2_peer_sanity_pull[50-False-attachments_generator1]'
`

**Comment by borrrden** [comment]
I think you mean .net framework 4.5. 1.x does not support .NET Core. 

What about the official 1.4.1 release (107)?

**Comment by raghusarangapani** [comment]
The test passes with net-msft 1.4.1-107 and macosx 1.4.1-88.
The test fails with net-msft 1.4.1-107 and net-mono 1.4.1-107.

**Comment by djpongh** [comment]
Won't be getting to this in 1.x.
