### ISSUE TITLE
CBL 2.0.0.1 - Xamarin Android Missing LiteCore.Interop.ILiteCore

### ISSUE THREAD

**Issue by jklaus** [couchbase/couchbase-lite-net#1017]
The Couchbase Lite .NET issue tracker is reserved for bug reports and enhancement 
requests. For general questions, please use the Couchbase forums:
https://forums.couchbase.com/c/mobile/ . Thank you!

### Library Version
2.0.0.1

### .NET Runtime
Xamarin Android 27.0.2

### Operating System
Windows 10 Pro 
Version: 1709
OS Build: 16299.371

### Code
```
Context context = this.ApplicationContext;
Couchbase.Lite.Support.Droid.Activate(context);
var db = new Couchbase.Lite.Database("test");
```

### Issue
The follow exception is thrown when the database constructor executes.

Unhandled Exception:

System.TypeInitializationException: The type initializer for 'Couchbase.Lite.Sync.HTTPLogic' threw an exception. ---> System.DllNotFoundException: LiteCore\n  at (wrapper managed-to-native) LiteCore.Interop.NativeRaw.c4_getVersion()\n  at LiteCore.Interop.Native.c4_getVersion () [0x00000] in C:\\Jenkins\\workspace\\couchbase-lite-net-edition-build\\couchbase-lite-net-ee\\couchbase-lite-net\\src\\LiteCore\\src\\LiteCore.Shared\\Interop\\Common\\C4Base_native.cs:109 \n  at LiteCore.Interop.LiteCoreImpl.c4_getVersion () [0x00000] in C:\\Jenkins\\workspace\\couchbase-lite-net-edition-build\\couchbase-lite-net-ee\\couchbase-lite-net\\src\\LiteCore\\src\\LiteCore.Shared\\Interop\\LiteCore_impl.cs:41 \n  at Couchbase.Lite.Interop.Native.c4_getVersion () [0x00000] in C:\\Jenkins\\workspace\\couchbase-lite-net-edition-build\\couchbase-lite-net-ee\\couchbase-lite-net\\src\\LiteCore\\src\\LiteCore.Shared\\Interop\\LiteCore_shell.cs:43 \n  at Couchbase.Lite.Sync.HTTPLogic.GetUserAgent () [0x00152] in C:\\Jenkins\\workspace\\couchbase-lite-net-edition-build\\couchbase-lite-net-ee\\couchbase-lite-net\\src\\Couchbase.Lite.Shared\\Sync\\HTTPLogic.cs:242 \n  at Couchbase.Lite.Sync.HTTPLogic..cctor () [0x00000] in C:\\Jenkins\\workspace\\couchbase-lite-net-edition-build\\couchbase-lite-net-ee\\couchbase-lite-net\\src\\Couchbase.Lite.Shared\\Sync\\HTTPLogic.cs:47 \n   --- End of inner exception stack trace ---\n  at Couchbase.Lite.Database..ctor (System.String name, Couchbase.Lite.DatabaseConfiguration configuration) [0x0007b] in C:\\Jenkins\\workspace\\couchbase-lite-net-edition-build\\couchbase-lite-net-ee\\couchbase-lite-net\\src\\Couchbase.Lite.Shared\\API\\Database\\Database.cs:251 \n  at HelloWorld2.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00036] in c:\\users\\jklaus\\source\\repos\\HelloWorld2\\HelloWorld2\\HelloWorld2.Android\\MainActivity.cs:29

**Comment by borrrden** [comment]
Operating System means the Android OS in this case.  What are the details of where you are trying to deploy?

**Comment by jklaus** [comment]
Its a device I created to mimic my moto x4.  CPU/ABI: Intel Atom x86_64

**Comment by borrrden** [comment]
That's not an ABI that we directly support, but my theory is that it should pick up the x86 version since it is backwards compatible.  Can you try on an x86 based device instead?

**Comment by borrrden** [comment]
Have you had a chance to review my previous comment @jklaus ?

**Comment by jklaus** [comment]
If this has been removed from 2.1.2 - should it be closed?

**Comment by borrrden** [comment]
It is closed and removed from the milestone due to inability to reproduce and lack of response.  If you have more information that can help reproduce then please let us know.
