### ISSUE TITLE
Was encryption removed from version 2?

### ISSUE THREAD

**Issue by alexrainman** [couchbase/couchbase-lite-net#1024]
I was using options to create an encrypted database:

```
var opts = new DatabaseOptions();
opts.EncryptionKey = new SymmetricKey("key", "salt", 201);
```

It seems this is not possible anymore.

**Comment by djpongh** [comment]
You are correct, encryption was not in the 2.0 release. Our recently released developer build, 2.1 DB01 has encryption support.

**Comment by rajagp** [comment]
yes, it is pre-release nuget package

**Comment by alexrainman** [comment]
I cannot see them on nuget, different name?

**Comment by rajagp** [comment]
No, same name. Be sure to check the right nuget source - http://mobile.nuget.couchbase.com/nuget/Developer/

**Comment by alexrainman** [comment]
When this is going to be officially released?

**Comment by alexrainman** [comment]
Can you tell me how to enable encryption?

**Comment by borrrden** [comment]
The snippet that you provided in the first comment is the way, with some adjustments on the constructor for simplification.  If you are having trouble please post a question on the forum, or if you have found a bug then report it here.

**Comment by alexrainman** [comment]
I don't see how that code snippet can work as DatabaseConfiguration doesn't have a property to provide EncryptionKey and SymmetricKey is not con Couchbase.Lite namespace. I cannot find DatabaseOptions neither.

**Comment by alexrainman** [comment]
You guys are awesome. Thanks.

**Comment by alexrainman** [comment]
I can see that Encryption will be an Enterprise Edition feature https://forums.couchbase.com/t/database-encryption-removed-from-couchbase-lite-2-0/16698/7

Not good. Not good at all.
