### ISSUE TITLE
Lot of packages installed on Android and iOS since version 2

### ISSUE THREAD

**Issue by alexrainman** [couchbase/couchbase-lite-net#1026]
Please, take a look a this screenshot:

<img width="260" alt="screen shot 2018-05-26 at 8 54 03 am" src="https://user-images.githubusercontent.com/3793554/40576940-8498b34e-60c3-11e8-9fff-18fd36eac559.png">

I am seeing this in another packages like Json.Net so, it is not just Couchbase.Lite. Maybe because multi-target projects are something new?

There's no reason to have Net Standard and all those dependencies installed on platform specific projects. This is making package managing in Android and iOS a mess.

Some links:

https://montemagno.com/converting-xamarin-libraries-to-sdk-style-multi-targeted-projects/

https://montemagno.com/new-plugin-for-xamarin-multi-target-templates-for-visual-studio-2017/

https://github.com/alexrainman/ModernHttpClient

**Comment by borrrden** [comment]
Closing this for #1027
