### ISSUE TITLE
Docs are not getting deleted for delete in CBL app for test_default_conflict_scenario_delete_win Test

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-net#1045]
### Library Version

Example:
2.1.0-db207

### .NET Runtime
.NET Core 207

### Operating System / Device Details
 Windows 10 

### Log Output

[test_default_conflict_scenario_delete_wins.log](https://github.com/couchbase/couchbase-lite-net/files/2249361/test_default_conflict_scenario_delete_wins.log)

### Expected behavior

docs should get deleted from SG as they got deleted from CBL app

### Actual behavior

Docs from SG is not getting deleted.

### Steps To Reproduce
        1. Create docs in CBL.
        2. Replicate docs to SG with push_pull and continous False
        3. Wait until replication is done and stop replication
        4. update doc in Sg and delete doc in CBL/ delete doc in Sg and update doc in CBL
        5. Verify delete wins

Run below command - 
 pytest -s --timeout 3600 --liteserv-version=2.1.0-207 --liteserv-host=172.23.120.178 --liteserv-port=8080 --sg-ssl --sync-gateway-vers
ion=2.1.0-121 --mode=cc --server-version=5.5.0-2958 --liteserv-platform=net-msft --create-db-per-test=cbl-test testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTes
ts/ -k test_default_conflict_scenario_delete_wins 

### Reproduction Project

git clone https://github.com/couchbaselabs/mobile-testkit.git
git checkout feature/diff-cbl20-master

**Comment by djpongh** [comment]
@hrajput89 , why are you testing 2.0 and not 2.1?

**Comment by borrrden** [comment]
By the way log output means CBL log output.  Putting the test output just confirms that a problem happened but doesn't provide much insight.

**Comment by borrrden** [comment]
Also does it fail without the `--sg-ssl` option?

**Comment by borrrden** [comment]
I found the issue, so a new RC build will be needed.  Very strange that this fails now but didn't fail for 2.0 (maybe a change in LiteCore triggered it).  It's quite possible the cause is the same for the other issues filed.

**Comment by hrajput89** [comment]
Tested with 221 build. Tests are passing now. Hence closing the issue.
