### ISSUE TITLE
Couchbase Lite parsing nested value as UInt64 then throwing exception on update.

### ISSUE THREAD

**Issue by rob-glas** [couchbase/couchbase-lite-net#1048]
### Library Version

2.0.3

### .NET Runtime

Xamarin iOS .NET Standard 2.0

### Operating System / Device Details

iOS Simulator iOS 11.4

### Log Output

[stack trace.txt](https://github.com/couchbase/couchbase-lite-net/files/2250943/stack.trace.txt)

### Expected behavior

Either value should have been parse by couchbase lite as a uint rather than UInt64 or couchbase lite should accept UInt64 as a valid upload type (maybe cast under the hood?).

### Actual behavior

Couchbase lite parses non floating type values as UInt64 which then are rejected when an update is requested. (See method `mutableDoc.SetValue(key, value);`).

### Steps To Reproduce

1. Create a dictionary where one of the values is another dictionary that has at least one whole number as a value. This can be passed in as a double but when it is uploaded to couchbase server it will have no decimal points in the json.
2. Get the document you've created using the couchbase id and get the dictionary from it using `document.ToDictionary();`
3. Dont change the number value in the nested dictionary but still use the mutableDocument `SetValue` method to update the nested dictionary value. You will see the crash.

**Comment by borrrden** [comment]
@djpongh Can I sneak this into 2.1?  It's very small but saves a lot of hassle if it's there.  All that is required is adding a type to the list of acceptable CBL types.

**Comment by rob-glas** [comment]
I did some more investigation, it seems any 64 bit type (double, Uint64) gets parsed as a UInt64 when being read by CBL. It occurs on both Android and iOS. My work around at the moment is to downgrade precision and store the doubles as floats.

**Comment by djpongh** [comment]
@borrrden, sorry too late for this release.

**Comment by borrrden** [comment]
I am having trouble reproducing this actually.  Can you reproduce it locally without any replication involved?  This snippet works for me:

```c#
var data = new Dictionary<string, object>
{
    ["nested"] = new Dictionary<string, object>
        { ["answer"] = Int64.MaxValue },
    ["top_level"] = 723L
};

using (var doc = new MutableDocument("test_nested")) {
    doc.SetData(data);
    Db.Save(doc);
}

using (var doc = Db.GetDocument("test_nested"))
using (var mutable = doc.ToMutable()) {
    var nestedDict = doc["nested"].Dictionary.ToMutable();
    nestedDict["new_key"].String = "new_value";
    mutable["nested"].Value = nestedDict;
    Db.Save(mutable);
}
```
I tried several other variations as well (including `doc.ToDictionary()` / `SetData()`)

**Comment by borrrden** [comment]
Well I added the type anyway, and added a test to make sure that ulong can be inserted.  However, there is no API to directly insert ulong so if it exceeds the signed 64-bit max value the only way to retrieve it will be through the untyped `GetValue`
