### ISSUE TITLE
doc can be retrieved after the delete

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-net#1050]
### Library Version
2.1.0-221

### .NET Runtime
.NET Core 2.1.0-221

### Operating System / Device Details

Windows 10

### Log Output

[dotnet.log](https://github.com/couchbase/couchbase-lite-net/files/2259696/dotnet.log)

### Expected behavior

getDocument call for deleted doc returning doc

### Actual behavior

getDocument call for deleted doc shouldn't return doc

### Steps To Reproduce

```
@pytest.mark.parametrize("db_name, doc_id", [
        (random_string(1), random_string(6)),
        (random_string(6), random_string(6)),
        (random_string(128), random_string(6)),
        ("_{}".format(random_string(6)), random_string(6)),
        ("{}_".format(random_string(6)), random_string(6)),
        ("_{}_".format(random_string(6)), random_string(6)),
        (random_string(6, digit=True), random_string(6)),
        (random_string(6).capitalize(), random_string(6)),
        (random_string(6).upper(), random_string(6))
    ])
    def test_delete_doc(self, db_name, doc_id):
        '''
        @summary: Testing delete method of Database API
        '''
        if len(db_name) >= 128 and (self.liteserv_platform != "ios" or self.liteserv_platform != "android"):
            pytest.skip("Test not supported on .net platforms or the db name is longer than or equal to 128 characters")

        db_name = db_name.lower()
        db = self.db_obj.create(db_name)

        doc = self.doc_obj.create(doc_id=doc_id)
        self.doc_obj.setString(doc, "key", "value")
        self.db_obj.saveDocument(db, doc)
        doc_res = self.db_obj.getDocument(db, doc_id)
        assert doc_res is not None
        assert self.doc_obj.getId(doc_res) == doc_id
        assert self.db_obj.getCount(db) == 1
        assert self.doc_obj.getString(doc_res, "key") == "value"

        self.db_obj.delete(document=doc, database=db)
        doc_res = self.db_obj.getDocument(db, doc_id)
        assert self.db_obj.getCount(db) == 0
        doc_res = self.db_obj.getDocument(db, doc_id)
        assert doc_res == -1
        assert self.db_obj.deleteDB(db) == -1
```

### Reproduction Project

git clone https://github.com/couchbaselabs/mobile-testkit.git
git checkout feature/diff-cbl20-master
pytest -rsx -s --mode=cc --server-version=5.5.0-2958 --sync-gateway-version=2.1.0-121 --skip-provisioning --timeout=3600  --no-conflicts --xattrs --liteserv-version=2.1.0-221 --liteserv-host=localhost --liteserv-port=8080 --liteserv-platform=net-msft --create-db-per-test=cbl-test --create-db-per-suite=suite-test -k test_delete_doc testsuites/CBLTester/CBL_Functional_tests/APITests/test_database.py

https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/CBLTester/CBL_Functional_tests/APITests/test_database.py#L153

**Comment by borrrden** [comment]
Please only file issues against the current RC (currently 2.1.0-b0221)

**Comment by hrajput89** [comment]
I ran the test against 221 only, just pasted the wrong build no.s. Updated the build no. in info. Log files also shows build no. as 221.

**Comment by borrrden** [comment]
The method you have written for this test already existed, so now there are two methods (the other one is DocumentDelete).  Anyway, inside of the DatabaseGetDocument method you are always storing.  The return value is actually null, so null is getting stored in the memory map and assigned an ID.  You need to check if it is null and return -1 in that case.  I tried to make adjustments but I can't make sense of the serialization method that the QE app uses.

**Comment by hrajput89** [comment]
It's a issue in QE Test. Will Fix it. Hence closing the issue.
