### ISSUE TITLE
peer2peer test : replication got stuck as busy on xamarin-ios

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-net#1054]
### Library Version
2.1.0-db0223

### .NET Runtime
Xamarin iOS  - 2.1.0-db-223

### Operating System / Device Details
xamarin ios on mac

### Steps To Reproduce
1.  Start the server
2. Create docs on client
3. Start replication with continuous True, push_pull using MessageEndPoint from client to server.

### Expected behavior

Verify all docs got replicated to server by counting docs in server and content

### Actual behavior
Replication got stucked as busy 

### Reproduction Project
mobile-testkit branch on feature/peer2peer-test
https://github.com/couchbaselabs/mobile-testkit/blob/feature/peer2peer-test/testsuites/CBLTester/System_test_multiple_device/test_peer_to_peer.py#L29

First test. just run with first combination of parameters

This is the command . 
 pytest -rsx -s -k test_peer_to_peer_1to1_valid_values --mode=cc --server-version=5.5.0-2473 --sync-gateway-version=2.1.0-121  --liteserv-ports=8080,8080 --liteserv-version=2.1.0-168 --liteserv-hosts=10.17.5.4,localhost --liteserv-platforms=ios,ios --xattrs --create-db-per-test="test" --skip-provisioning testsuites/CBLTester/System_test_multiple_device/

--liteserv-hosts=10.17.5.4,localhost => 10.17.5.4 will be ip address of device and localhost will be simulator

automatic download and install code is already commented out on System_test_multiple_device/conftest.py file. Just manually deploy the app on device and simulator.

Manually download and install and deploy app on device and simulator

**Comment by sridevi-15** [comment]
sometimes I still see that replicator is in busy state when I test with URLEndPoint. MessageEndPoint looks good. Sometimes it works with URLEndPoint and sometime it gets stucks at busy state, it is not consistent.

**Comment by borrrden** [comment]
What test is this with?  Is the device the client or the server?  Does it make a difference?  Anything showing in the logs?  Any exceptions while debugging?

**Comment by sridevi-15** [comment]
@borrrden , Here is the gist tested on xamarin ios
https://gist.github.com/sridevi-15/6262c7430e29d2650ecc8d60f6e85789

This is the test test_peer_to_peer_1to1_valid_values with parameters -> (100, False, "push", False, "URLEndPoint")

This is the file : https://github.com/couchbaselabs/mobile-testkit/blob/feature/peer2peer-test/testsuites/CBLTester/System_test_multiple_device/test_peer_to_peer.py

This is the command to run: client as simulator and server as device

pytest -rsx -s -k test_peer_to_peer_1to1_valid_values --mode=cc --server-version=5.5.0-2473 --sync-gateway-version=2.1.0-121 --liteserv-ports=8080,8080 --liteserv-version=2.1.0-263 --liteserv-hosts=10.17.1.84,localhost --liteserv-platforms=android,android --xattrs --create-db-per-test="test" --skip-provisioning testsuites/CBLTester/System_test_multiple_device/

**Comment by sridevi-15** [comment]
There is some code adding for debugging purpose which was added to debug this bug while debuggin on previous build. After removing that logic on peer2peer client code, it worked fine.
