### ISSUE TITLE
doc getting disappeared when update happened with wifi off

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-net#1056]
### Library Version
2.1.0-232

### .NET Runtime
UWP <version>
Xamarin Android <version>

### Operating System / Device Details
Windows 10 

### Steps To Reproduce

1. User1 Turn off the wifi off on UWP, user2 turn off the wifi off on xamarin Android.
2. user1 updated doc1 5 times, user2 updated doc1 10 times.
3. User1 and user2 tunred on wifi. 

### Expected behavior
All users should get the update of user2 as user2 updated 10 times 

### Actual behavior

doc1 is disappeared for both user1 and user2
For all other users, doc1 has update of user1, but not user2's updates.

### Reproduction Project
use test fest todo app to reproduce

**Comment by borrrden** [comment]
Tracked this down to an issue in the test fest todo app.  After fixing there I could no longer reproduce.

**Comment by sridevi-15** [comment]
As it is fixed on todo app and it is fixed now, closing this issue.
