### ISSUE TITLE
Replication Eventing

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-net#1059]
Make it easy for apps to take appropriate actions on documents depending on status of sync. For instance to purge synced documents.

**Comment by djpongh** [comment]
Step 1: look over the current spec and see what details need to be added

**Comment by borrrden** [comment]
- [ ] Write PRD
- [ ] Write Spec
- [ ] Finalize API
- [ ] Implement functionality
- [ ] Write tests

**Comment by Sandychuang8** [comment]
Merge replication eventing feature after https://github.com/couchbase/couchbase-lite-net/pull/1081 is approved.
