### ISSUE TITLE
Xamarin-ios -  docs did not replicate to sync gateway from CBL with sync gateway restart

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-net#1060]
### Library Version
.Net build -> 2.1.1-6

### .NET Runtime
Xamarin iOS   
### Operating System / Device Details
iphone 6 ios 11.4.1

### Log Output
visual studio of xamarin ios did not provide any log output

### Steps To Reproduce
1. Have SG
        2. Create docs in CBL.
        3. push replication to SG
        4. update docs in SG.
        5. Restart sg in one thread
        6. do replication with pull in other thread to cbl
 

### Expected behavior

Verify number of docs in sync-gateway is same as number of docs in cbl.

### Actual behavior

Number of docs in sync-gateway became 0 , cbl has expected number of docs 

### Reproduction Project

Mobile testkit test : https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_replication.py#L2107

test name : test_CBL_push_pull_with_sg_down

Note : It passed on simulator

**Comment by sridevi-15** [comment]
This is happening on xamarin-android too on the device

**Comment by Sandychuang8** [comment]
Hi Sridevi,


Is there any error message? Does network work on both phones?

________________________________

**Comment by sridevi-15** [comment]
Yes Sandy, network works on both phones. I connected phones to wifi

**Comment by djpongh** [comment]
@Sandychuang8, can you try and reproduce outside of the test environment?

**Comment by borrrden** [comment]
This is probably https://github.com/couchbase/couchbase-lite-net/issues/1057 for Android FYI.  I expect iOS has something similar to deal with.

**Comment by Sandychuang8** [comment]
My observation is:
1. ios phone app update data 6 times while connected to the sync gateway, sync gateway update the data count to 6
2. restart sync gateway, ios phone app lost the connection
3. update sync gateway data twice 
4. ios phone connects to the sync gateway again and gets the 2 data update from sync gateway

The data flow looks right to me.

**Comment by sridevi-15** [comment]
Hi Sandy , slight change in my test scenario. Sorry i have mistaken and added more steps. Here are the right steps. 
1. Have SG
        2. Create docs in CBL.
        3. push_pull replication with continuous True in one thread 
        4. Restart sg in another  thread
        7. Verify all docs replicated successfully to cbl and SGW

At step 7, number of docs in SGW is 0

**Comment by Sandychuang8** [comment]
Increased the document size to 5k on each end, after re-started the sg, I can see partial data got transferred to the sg from cbl (iOS Xamarin) which is verified using SG Rest API.
