### ISSUE TITLE
xamarin-ios: replication fails with multiple sync gateway when running with ssl enabled on sync gateway

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-net#1062]
### Library Version
2.1.1-6

### .NET Runtime
Xamarin-ios
### Operating System / Device Details
iOS : 11.4

### Log Output
https://gist.github.com/sridevi-15/baedbe75ed4d01811c99e24c6be44962
### sync gateway config to enable ssl
```
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "logging": {"debug": {"enabled": true} },
    "cluster_config": {
        "server":"http://192.168.0.120:8091",
        "data_dir":".",
        "bucket":"data-bucket-1",
        "username":"data-bucket-1",
        "password": "password"
    },
    "SSLCert": "sg_cert.pem",
    "SSLKey": "sg_privkey.pem",
    "databases":{
        "sg_db1":{
            
            "allow_conflicts": false,
            "revs_limit": 30,
            
            "num_index_replicas": 0,
            "server":"http://192.168.0.120:8091",
            "bucket":"data-bucket-1",
            "username":"data-bucket-1",
            "password": "password",
            "channel_index":{
                "server":"http://192.168.0.120:8091",
                "bucket":"index-bucket-1",
                "username":"index-bucket-1",
                "password": "password",
                "writer":false
            }
        },
        "sg_db2":{
            
            
            "num_index_replicas": 0,

            "server":"http://192.168.0.120:8091",
            "bucket":"data-bucket-2",
            "username":"data-bucket-2",
            "password": "password",
            "allow_conflicts": false,
            "revs_limit": 30,
            "channel_index":{
                "server":"http://192.168.0.120:8091",
                "bucket":"index-bucket-2",
                "username":"index-bucket-2",
                "password": "password",
                "writer":false
            }
        }
    }
}

```
### Steps To Reproduce
 1. Create 2 DBs in 2 SGS and Create docs in CBL
2. set up sync gateway with ssl 
        2. Set up 1 SG with revs limit 30 and SG2 with revs limit 25.
        3. Do push replication to two SGS(each DB
        to each SG).
### Expected behavior
It should replicate successfully without any issue

### Actual behavior
Replication fails with error 

"Couchbase.Lite.CouchbaseWebsocketException: CouchbaseLiteException (WebSocketDomain / 1008): policy violation."

### Reproduction Project

https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/CBLTester/topology_specific_tests/multiple_sync_gateways/test_replication_multiple_sgs.py

Both tests in this file are failing with same reason

Note : It is failing on device and simulator
It passed with ssl is disabled on sync-gateway. 
Though the test server app is pointed to wss:sync-gateway_url with ssl enabled, couchbase lite points to ws:// based on logs

**Comment by borrrden** [comment]
I would debug the test app to make sure that wss is getting passed in.  This look suspiciously like ws is accidentally getting passed in (which would result in SSL handshake confusing the replicator)

**Comment by sridevi-15** [comment]
Hi Jim,
      When I tested this, I made sure to make change on TestServer app and mobile testkit and added wss and tested it out. I can run once again

**Comment by borrrden** [comment]
"Make these changes to TestServer app / mobile testkit and run" is uncomfortable.  Are these changes merged?

**Comment by borrrden** [comment]
Test server receives a *NON-SSL* target URL erroneously as in the following:

<img width="1123" alt="screen shot 2018-10-04 at 12 02 04" src="https://user-images.githubusercontent.com/2470288/46450657-64503000-c7cd-11e8-8453-45ad0d60f737.png">

This is a test server issue.

**Comment by sridevi-15** [comment]
I missed at one place to change it to wss. It worked fine after making that fix.
