### ISSUE TITLE
xamarin-ios: number of revisions are missing on sync-gateway with large number of docs 

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-net#1063]
### Library Version
2.1.1-6
### .NET Runtime
Xamarin-ios

### Operating System / Device Details
iOS 11.4

### Log Output
https://gist.github.com/sridevi-15/f22013a041a1f0b3c254927d2f59f7ad

### SG config:
```
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",


    "logging": {"debug": {"enabled": true} },
    "databases":{
        "sg_db1":{



            "revs_limit": 30,

            "num_index_replicas": 0,
            "server":"http://192.168.0.120:8091",
            "bucket":"data-bucket-1",
            "username":"data-bucket-1",
            "password": "password"
        },
        "sg_db2":{



            "revs_limit": 25,

            "num_index_replicas": 0,

            "server":"http://192.168.0.120:8091",
            "bucket":"data-bucket-2",
            "username":"data-bucket-2",
            "password": "password"
        }
    }
}

```

### Steps To Reproduce
1. Create 2 DBs in 2 SGS and Create docs in CBL
        2. Set up 1 SG with revs limit 30 and SG2 with revs limit 25.
        3. Do push replication to two SGS(each DB
        to each SG).
        4. Do updates on CBL for 35 times.
        5. Continue push replication to SGs
     
### Expected behavior

Verify that revs maintained on two SGS according to revs_limit.

### Actual behavior

few docs are missing revisions, it shows 2 revisions for 30 revisions. Only few docs, but most of the docs have 30 revisions for sync gateway 1

### Reproduction Project

https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/CBLTester/topology_specific_tests/multiple_sync_gateways/test_replication_multiple_sgs.py#L23
test_multiple_sgs_with_differrent_revs_limit

Note : This issue is only on device. This test passed with 10 docs, it failed with 100 docs and 1000 docs

**Comment by rajagp** [comment]
@sridevi-15  can you clarify the behavior that you observe on SGW1 and SGW2. 
Can you confirm  that this works when you are replicating to a single upstream SGW with any number of documents (10, 100+ )
 Does this happen on Android as well (on device)?

**Comment by Sandychuang8** [comment]
@sridevi-15 what version of sync gateway you are using for the test?

**Comment by sridevi-15** [comment]
1.2.0-121

**Comment by rajagp** [comment]
@sridevi-15  To double check - Does this happen on a single SGW or is it only a 2 SGW case?

**Comment by borrrden** [comment]
I can't get this test to run properly:

> fatal: [sg1]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'revs_limit' is undefined"}
fatal: [sg2]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'revs_limit' is undefined"}

**Comment by sridevi-15** [comment]
@rajagp , this is happening with 2 SGWs, it works fine with 1 SGW

@borrrden , sorry, it is 2.1.0, typo
Can you pull latest changes from master , that has the fix for AnsibleUndefined Variable

**Comment by borrrden** [comment]
I saw this test fail once, then pass once.  I wonder if it is an issue with "wait for idle".  This seems to be a common theme.  It might be better if the test suite, in general, waits for a "sustained idle" (i.e. idle that persists for X number of seconds).  That way it's more likely to be an actual idle and not a transient idle.

**Comment by sridevi-15** [comment]
@borrrden , I can add for 2 seconds for idle state is maintained and then I can come out of the loop. Do you think 2 seconds is good enough for 1000 docs?

**Comment by borrrden** [comment]
2 seconds would probably be safe, 5 seconds would be better

**Comment by sridevi-15** [comment]
@borrrden , I tested on iOS and I see same issue. It is happening with 100 and 1000 docs.
It passed once after running more than 10 times. I put 60 seconds wait time after replicator is in idle state, but docs never gets replicated. I do not see this issue on Android Though.  Do you think it is lite core issue?

**Comment by borrrden** [comment]
I was able to see the issue less when I made sure that Couchbase Server had at least the minimum requirements for what it's worth (i.e. 4 cores and several GB of memory)

**Comment by sridevi-15** [comment]
Test has passed after adding more time after idle
