### ISSUE TITLE
 xamarin-android : app crash while updating more than 100 docs repeatedly 

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-net#1064]
### Library Version

2.1.1-6

### .NET Runtime
Xamarin Android <version>

### Operating System / Device Details
Android physical device. Nexus 6P

### Log Output

https://gist.github.com/sridevi-15/8c17f05589a70ec85804d345631269b5

### Steps To Reproduce
1. Start SG without allow_conflicts set and revs_limit set.
        2. Create 500 docs in CBL
        3. Update the doc 5 times in CBL.
        4. Do push and pull replication with continuous
        5. Create a conflicts in SG
        6. Now enable allow_conflicts = false in SG config
        7. Check the revision list for the doc and the active revision
        8. update docs in CBL

### Expected behavior

Docs should update successfully

### Actual behavior

app Crashed

Note : This is not happening all the time. After running few times, I see this crash. 

Reproduction project : https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_no_conflicts_cbl.py#L321

test_migrate_conflicts_to_noConflicts_CBL  with 500 , 5 parametes
I am able to get app crash with this test too
test_no_conflicts_update_with_revs_limit[sync_gateway_revs_conflict_configurable-100-50]

**Comment by borrrden** [comment]
Please either make a simpler test case, or post the invocation for this one.

**Comment by sridevi-15** [comment]
pytest -s -rsx -k test_migrate_conflicts_to_noConflicts_CBL --timeout 1800  --liteserv-version=2.1.1-6 --liteserv-host=10.17.1.76 --liteserv-port=8080 --sync-gateway-version=2.1.0-121 --mode=cc --server-version=5.5.0-2473 --liteserv-platform=xamarin-android --create-db-per-test=cbl-test --device testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests

**Comment by borrrden** [comment]
I finally got this command to work.  I am trying to figure out how to determine if the app crashed since it gets killed at the end of the test normally.

**Comment by sridevi-15** [comment]
I usually comment testserver.stop on conftest file

**Comment by Sandychuang8** [comment]
@sridevi-15 , I probably need your help to setup the test tool on my Windows machine for me to use the same environment to reproduce the issue.

**Comment by borrrden** [comment]
Since this has not been reliably reproduced yet, pushing to Iridium.

**Comment by sridevi-15** [comment]
I tried couple of times on device with 2.1.2-13 on xamarin android. I do not see any crash so far
