### ISSUE TITLE
Replication Filters

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-net#1068]
A ticket for tracking the implementation of filtered replication (and possibly the pull validation function)

- [X] Write PRD
- [x] Write Spec
- [x] Finalize API
- [x] Implement functionality
- [ ] Write tests <-- no unit tests for this feature.

**Comment by borrrden** [comment]
@Sandychuang8 Please keep this ticket updated

**Comment by Sandychuang8** [comment]
Merge to master branch after couchbase/couchbase-lite-net#1074 is approved.
