### ISSUE TITLE
test_migrate_conflicts_to_noConflicts_CBL is failing for .net 2.1.2

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-net#1072]
### Library Version

2.1.2-7

### .NET Runtime

.NET Core <2.1.2-7>

### Operating System / Device Details
Windows 10 Fall 

### Log Output
[dotnet_app_migrate_to_no_conflict.log](https://github.com/couchbase/couchbase-lite-net/files/2514232/dotnet_app_migrate_to_no_conflict.log)
[python_client_migrate_to_no_conflict.log](https://github.com/couchbase/couchbase-lite-net/files/2514233/python_client_migrate_to_no_conflict.log)
[sgcollect_info.zip](https://github.com/couchbase/couchbase-lite-net/files/2514254/sgcollect_info.zip)

### Expected behavior
Test should raise conflict for this code execution - https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_no_conflicts_cbl.py#L402

> GET http://172.23.109.132:4984/db/no-conflicts_0?conflicts=true&revs=true&show_exp=true 200
> PUT http://172.23.109.132:4984/db/no-conflicts_0?new_edits=false 409

### Actual behavior

Test is not raising conflict for this code execution - https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_no_conflicts_cbl.py#L402

> GET http://172.23.109.132:4984/db/no-conflicts_0?conflicts=true&revs=true&show_exp=true 200
> PUT http://172.23.109.132:4984/db/no-conflicts_0?new_edits=false 201

### Steps To Reproduce
pytest -rsx -s --skip-provisioning --timeout 3600 --liteserv-version=2.1.2-7 --liteserv-host=172.23.121.57 --liteserv-port=8080  --sync-gateway-version=2.1.1 --mode=cc --server-version=5.5.0-2473 --liteserv-platform=net-msft --create-db-per-test=cbl-test testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_no_conflicts_cbl.py -k test_migrate_conflicts_to_noConflicts_CBL

### Reproduction Project

git clone https://github.com/couchbaselabs/mobile-testkit.git

**Comment by hrajput89** [comment]
> Is this a regression? This test seems familiar but there is something odd about it:
> 
> Is this test expecting that the replicator survives a sync gateway restart? It is started on 375, and then Sync Gateway is restarted on 395 before this logic takes place.

Yes, this is regression. I ran the same test on android and it's passing.

**Comment by Sandychuang8** [comment]
I cannot repro, I am getting 409 every time.

**Comment by Sandychuang8** [comment]
Cannot repro using UWP app
Note: I never restart the UWP app during the test.

My repro steps: 

1. start sg without allow_conflicts set & revs_limit set
2. create docs in cbl
3. update docs few times in cbl
4. create conflicts in sg via Postman
5. enable allow_conflicts = false and save in sg config 
6. restart sg
7. getting 200 from ?conflicts=true&revs=true&show_exp=true 
8. update docs few times in cbl
9. cbl push & pull when docs are updated
10. create conflict on sg and got 409 response

**Comment by borrrden** [comment]
Status?
