### ISSUE TITLE
CouchBase.Lite 2.x LINQ support roadmap?

### ISSUE THREAD

**Issue by dfarrNTST** [couchbase/couchbase-lite-net#1073]
Is there a timetable for adding full LINQ support to the 2.x implementation of CouchBase.Lite?

**Comment by borrrden** [comment]
The Couchbase Lite .NET issue tracker is reserved for bug reports and enhancement 
requests. For general questions, please use the Couchbase forums:
https://forums.couchbase.com/c/mobile/ . Thank you!
