### ISSUE TITLE
Stop Offline Replicator

### ISSUE THREAD

**Issue by DanielSchmitt94** [couchbase/couchbase-lite-net#1077]
A Replicator running in continuous PushAndPull mode can't be stopped if the replicator status is offline.
Looks similar to the issue [https://github.com/couchbase/couchbase-lite-net/issues/1020](url).

Depending on https://forums.couchbase.com/t/continuous-replication-offline-vs-stopped/17227/2 the replicator should be stoppable at any time.

Is this still a bug?

### Library Version

2.1.1

### .NET Runtime

Xamarin Android v28

### Operating System / Device Details

Android OS 9

### Expected behavior

The replicator should be stoppable at any time.

### Actual behavior

The replicator can not be stopped. Status is Offline.

### Steps To Reproduce

* Phone in airplane mode
* Start replication
```
this.replicator.Stop();
while (this.replicator.Status.Activity != ReplicatorActivityLevel.Stopped)
{
       await Task.Delay(500);
}
```
This will be an endless loop.

**Comment by borrrden** [comment]
This has been fixed in 2.1.2 which will be out in a couple weeks. There is a DB out for it (two of them actually).
