### ISSUE TITLE
[CBSE-6069] - .net UWP is crashing during replication in release mode

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-net#1085]
Similar to issue - https://issues.couchbase.com/browse/CBSE-6069

### Log Output
<img width="1440" alt="screenshot 2018-11-28 11 07 50" src="https://user-images.githubusercontent.com/18100038/49133877-ab5b2d00-f307-11e8-9d55-821bd591636e.png">

[uwp_failure.log](https://github.com/couchbase/couchbase-lite-net/files/2623212/uwp_failure.log)

### Expected behavior

Replication should run without any crash

### Actual behavior

UWP app is crashing when starting replication

### Steps To Reproduce
pytest -rsx -s --skip-provisioning --timeout 3600 --liteserv-version=2.1.2-13 --liteserv-host=localhost --liteserv-port=8080 --xattrs --sg-ssl --sync-gateway-version=2.1.1 --mode=cc --server-version=5.5.0-2473 --liteserv-platform=net-uwp --create-db-per-test=cbl-test  testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_cbl_log_redaction.py -k test_mask_password_in_logs

### Reproduction Project

https://github.com/couchbaselabs/mobile-testkit.git

**Comment by borrrden** [comment]
@hrajput89 Please close this once it has been tested

**Comment by hrajput89** [comment]
I've ran regression test for .net uwp with Released mode. Tests are passing without any issues.
Hence closing the request.
