### ISSUE TITLE
Replicator Never Leaves Busy State

### ISSUE THREAD

**Issue by blimkemann** [couchbase/couchbase-lite-net#1086]
This is a follow-up to forum post 19286 where the expected behavior of a replicator is to enter the Idle (or not Busy) state when complete but it instead remains in the Busy state forever.

Repro is attached below. It's a console app that seems to hang quite regularly during the download and not just at the end like happens in a Xamarin environment.

I thought it might be due to a lack of a synchronization context, so I added Nito.AsyncEx but the result is the same.

[Repl.zip](https://github.com/couchbase/couchbase-lite-net/files/2626815/Repl.zip)

**Comment by borrrden** [comment]
What version of Sync Gateway are you using?

**Comment by blimkemann** [comment]
2.1.1

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Sandychuang8** [comment]
Thanks for the app. I tested it and it took around 8 min to finish replicating 385 mb worth of blobs. I took a look at the log under C:\Temp\CouchbaseDownload. `INFO) Sync 2018-11-28T14:38:03.7091389-08:00 {Repl#2} Connected!
VERBOSE) Sync 2018-11-28T14:38:03.7101365-08:00 {Repl#2} Requesting remote checkpoint
INFO) Sync 2018-11-28T14:38:03.7101365-08:00 {Repl#2} activityLevel=busy: connectionState=2
INFO) Sync 2018-11-28T14:38:03.7101365-08:00 {Repl#2} now busy ..........................................................................................................................................................................INFO) Sync 2018-11-28T14:46:35.8303536-08:00 (Replicator) [26] Replicator[<* ws://api.redbookfuneraldirectory.com:4984/ebook] is Idle, progress 432045231/432045324` Looks like the replication is out of busy state and went into idle. However, I do see bytes are not matching up. This is actually an issue we are trying to fix at this moment.

**Comment by Sandychuang8** [comment]
base on the code I am seeing, you only put DownloadProgress?.Invoke under case ReplicatorActivityLevel.Busy callback, if you out a break in case ReplicatorActivityLevel.Idle, you should be able to see it hit when the replication is completed.

**Comment by blimkemann** [comment]
Right you are! Have you run this outside of the debugger? I cannot get it to successfully complete if I run it from a command prompt. If I run it in the debugger it completes - outside of it the replication hangs at random points. Any ideas there?

**Comment by borrrden** [comment]
How fast is your internet?  Are you sure the "hangs" are not just your connection downloading a large blob?

**Comment by blimkemann** [comment]
150MB. No - it hangs. I can leave it and it sits forever. Or, it goes almost instantly from Busy to Idle...

**Comment by Sandychuang8** [comment]
on the console screen screenshot, looks like there is no more documents to be replicated. So it instantly went from busy to idle.

**Comment by blimkemann** [comment]
So I can get this fail fail every time on UWP now. Works perfectly when run through the debugger but fails when running outside of it. The same code works perfectly in Android, iOS and even a console app. 

Attached is a log output from the UWP app. Does this tell us anything? The replicator hangs in a Busy state at a random point and refuses to download anything further.
[Log-20181203-174500115.zip](https://github.com/couchbase/couchbase-lite-net/files/2641585/Log-20181203-174500115.zip)

**Comment by borrrden** [comment]
The logs do contain something odd which reveals that the library didn't receive (or thinks that it didn't receive) certain messages from the server and is waiting for them.  The real question is why, but for that we can only guess unless we can reproduce here.

**Comment by blimkemann** [comment]
Jim, I have attached a repro. Again, you need to run the UWP app OUTSIDE of the debugger and it will stop at a random point stuck in the Busy state and refuse to download anything further. Works fine when run through the debugger...

[ReplUWP.zip](https://github.com/couchbase/couchbase-lite-net/files/2643995/ReplUWP.zip)

**Comment by Sandychuang8** [comment]
I tested the uwp program (downgrade the .Net framework from 4.7.1 to 4.6) and compiled it under Debug x86. Then ran TestXF.UWP.exe in the Debug folder. The application completed in ~3 min without any issue. 
[Log-20181204-123543142.zip](https://github.com/couchbase/couchbase-lite-net/files/2646098/Log-20181204-123543142.zip)

**Comment by blimkemann** [comment]
Well that's odd. The net framework version is only for the console app that I included so that should make no difference at all. What happens when you run it using Ctrl+F5 from Visual Studio (make sure to uninstall it first to force a new download). It ALWAYS hangs for me doing it that way. VS 15.9.3 a UWP is targeting 16299. Below is screenshot of the app.

![image](https://user-images.githubusercontent.com/10390357/49472812-6428dc80-f7de-11e8-822b-b6a7759dff08.png)

**Comment by borrrden** [comment]
I had a theory about too much data being received and a problem in the throttle, but I see the throttle messages in Sandy's logs as well.  I also ran the application.  It ran a lot more slowly for me but it did complete on the first try after about 10 minutes.

**Comment by blimkemann** [comment]
Maybe it's my connection speed? Since it works when in the debugger (which I know slows things down) not when run outside of it, maybe the fact that I have 150MB download Internet matters? Is it possible that the throttling isn't waiting long enough?

**Comment by blimkemann** [comment]
I tried on a slower connection and it "seems" to have completed. I say "seems", because there should be 2748 files in the attachments folder and the app claimed to be complete ("idle") after downloading only 1597. So something is up. How many attachments did you get?

**Comment by borrrden** [comment]
Throttling does not wait for a given amount of time, but it waits for the processing of the documents to catch up if the network is receiving faster than the docs can be written and stored.  Note that re: the attachment number that if any attachments on your documents are the same content they will not have separate files (similar to Git).  That could explain the discrepancy.

**Comment by djpongh** [comment]
@blimkemann, if you get the info feel free to reopen.
