### ISSUE TITLE
Values with large number in documents are mismatching in SGW and CBL .net client

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-net#1115]
### Library Version

2.5.0-b0121

### .NET Runtime
.NET Core 
UWP 
Xamarin Android 
Xamarin iOS 

### Operating System / Device Details
tested on xamarin ios and .Net Core

### Steps To Reproduce

1.  Create a doc in CBL with value for one of the key in json doc : -63081350000000
2. Do push replication with continous true to SGW

### Expected behavior
Both SGW and CBL should have same value for the key 

### Actual behavior
SGW has value, -63081400000000  which is round figure to -63081350000000
some other samples which I tested : 3.80654e+13(SGW) - 38065390000000.0(CBL)

I tested on iOS and Android and it worked fine. 

### Reproduction Project
It is new test which is in my local machine. Above steps are

**Comment by borrrden** [comment]
This has been reported before.  @adamcfraser Has there been changes to the way that SGW marshals large numbers since the last time this was reported?

**Comment by borrrden** [comment]
I don't understand what this issue is about then.  Is the value also that way locally on CBL?  Otherwise why would an incorrect value in SGW be filed as a bug here?

**Comment by adamcfraser** [comment]
I assume it's here because iOS/Android aren't showing the same behaviour.

**Comment by borrrden** [comment]
@sridevi-15 Is it true that iOS and Android don't show this behavior?

**Comment by djpongh** [comment]
@sridevi-15 have you had a chance to look into this yet?

**Comment by sridevi-15** [comment]
I tested once again with large value . This time I tested with and without delta sync.  I tested without delta sync and it worked fine, but failed when delta sync is on.  It is not just .Net issue, it is happening on all platforms now. Will move to lite core once it is confirmed

**Comment by sridevi-15** [comment]
I am closing this ticket and reopened on SGW
