### ISSUE TITLE
xamarin-android app crashes on 2.5.0 version 

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-net#1116]
### Library Version
2.5.0-b0124

### .NET Runtime
Xamarin Android <version>

### Operating System / Device Details
Android

### Log Output

`Could not load signature of LiteCore.Interop.LiteCoreImpl:c4repl_new due to: Could not resolve type with token 01000024 (from typeref, class/assembly LiteCore.Interop.C4Slice, Couchbase.Lite, Version=2.1.2.0, Culture=neutral, PublicKeyToken=null) assembly:Couchbase.Lite, Version=2.1.2.0, Culture=neutral, PublicKeyToken=null type:LiteCore.Interop.C4Slice member:(null) signature:<none>
'
### Steps To Reproduce

1. Take testserver app and load it in Visual code.
2.Add packages of 2.5.0.121 to TestServer project, .NetCore and uwp projects
2. Build the app , launch the app 

### Expected behavior

It should successfully launch the app and app should be reachable with ip address and port
### Actual behavior

It throws an error
Activity class {TestServer.Android/md57aea67c4d08319974f101b0b09ff509e.MainActivity} does not exist

Check for exact lite core error on log section

### Reproduction Project
our mobile testkit app , it should fail at launch itself. no need to run test

**Comment by borrrden** [comment]
If this is true, then how is @hrajput89 using it?

**Comment by borrrden** [comment]
Judging by the fact that your error message is attempting to load 2.1.2 my guess is that you didn't update the package on the TestServer.Android package.

**Comment by sridevi-15** [comment]
I verified by kicking off jobs on Jenkins. I see same issue. app is not getting launched. This is for 121 build on Jenkins.

**Comment by borrrden** [comment]
I don't understand, is the issue with Jenkins or locally or both?  I tried both locally and with the Jenkins build and had no issue.

**Comment by sridevi-15** [comment]
Here is the Jenkins job which show failure that app got installed, but app failed to launch. I got the error locally and also on Jenkins. 

http://uberjenkins.sc.couchbase.com:8080/job/xamarin-Android-Listener-TestServer-Functional-tests/78/

**Comment by sridevi-15** [comment]
I tested with latest build and with full clean run localy  . It worked fine now. Need to check if latest build works on Jenkins
