### ISSUE TITLE
Xamarin.iOS pull replication on large data sets taking very long time

### ISSUE THREAD

**Issue by rob-glas** [couchbase/couchbase-lite-net#1123]
### Library Version

CouchbaseLite/2.1.2 (.NET; iOS 12.1.0; iPhone) Build/13 LiteCore/2.1.0 (15) Commit/9aebf28

### .NET Runtime

Xamarin.iOS

### Operating System / Device Details

Mac OS 10.14.3

### Log Output

See attached file.
[Xamarin-logs.log](https://github.com/couchbase/couchbase-lite-net/files/2889208/Xamarin-logs.log)

### Expected behavior

Expect pull replication to complete quicker like Xamarin.Android behaviour

### Actual behavior

Pull replication took several minutes to complete (logs indicated a lot of threads spawned).

### Steps To Reproduce

Start pull replication on Xamarin.iOS against a large database (744,461 items)

### Reproduction Project

N/A

**Comment by borrrden** [comment]
Could you be more specific about the difference in time taken?  Also "Mac OS 10.14.3" is not an iOS operating system.  I assume you are using a simulator.  What version of Xamarin iOS and what OS on the simulator?

**Comment by djpongh** [comment]
@rob-glas, Are you able to get the info @borrrden asked for?

**Comment by borrrden** [comment]
I setup a server with 998,408 documents, and this was the result:

Xamarin iOS on iPhone 6S+ took exactly 13 minutes to complete
Xamarin Android on Nexus 5 (API 23) which is several years older took 30 minutes to download 730k.  

I don't have a comparable Android device to the iPhone 6S+ to compare equivalently but I don't see any evidence of a significant performance gap.  Unless some new evidence is present this will be closed at the end of the week.

**Comment by djpongh** [comment]
@rob-glas, if you are able to get more info for us, feel free to reopen.
