### ISSUE TITLE
UWP proxy implementation violates WACK

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-net#1125]
Need to either remove or replace it with an implementation based on [Proxy Configuration](https://docs.microsoft.com/en-us/uwp/api/windows.networking.connectivity.proxyconfiguration)

**Comment by djpongh** [comment]
@borrrden this is fixed, correct?

**Comment by borrrden** [comment]
Yes it's just not merged into master yet which is why it is still open.
