### ISSUE TITLE
Mark Predictive Query as beta in the API doc

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#1128]
Mark Predictive Query as beta in the API doc

**Comment by rajagp** [comment]
The official term is “Developer Preview” ( yes there is a change in use of these terms , so DP refers to pre GA features that appear in GA releases )

**Comment by borrrden** [comment]
I'd say just add "[Developer Preview]" to the beginning of the relevant doc comments.

**Comment by borrrden** [comment]
This should be on the EE repo, it is done now
