### ISSUE TITLE
Unable to set expiration date

### ISSUE THREAD

**Issue by mathieumack** [couchbase/couchbase-lite-net#1129]
### Library Version

2.1.2

### .NET Runtime

.net standard 2.0

### Expected behavior

Be able to call the SetDocumentExpiration method from the couchbase.lite api.
This method exists in the github repository, but it's not visible since I have added the nuget package in my project.

### Actual behavior

The method is not visible for the Database object.

### Reproduction Project

Check this commit :
https://github.com/mathieumack/NoSqlRepositories/commit/38d738b8d21312dc060187e642fc68e0f426639e
Normally, the method exists (https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/API/Database/Database.cs)

Is it a limitation from the v2, available only for Entreprise level ?

**Comment by Sandychuang8** [comment]
Hi @mathieumack TTL feature including set document expiration date will be available in version 2.5 which will be out this late April. It's not an Enterprise only feature.

**Comment by mathieumack** [comment]
Ok, thank for the answer.
Have a nice day !
