### ISSUE TITLE
IgnoreAccents(false) with FTS not working

### ISSUE THREAD

**Issue by 1Cor125** [couchbase/couchbase-lite-net#1134]
[I posted this issue on the Couchbase forum](https://forums.couchbase.com/t/ignoreaccents-false-with-fts-not-working/20643) and @borrrden recommended that I bug it.

### Library Version

CouchbaseLite/2.1.2 Build/13 LiteCore/2.1.0 (15)

### .NET Runtimes

Reproduced in both .NET Core 2.1.2 and Xamarin iOS: 12.2.1.16

### Operating System / Device Details

Mac OS X 10.14.3; .NETCore 2.1.2; iOS 12.1.0

### Expected behavior

Given the FTS index, the entries saved to the database, and given the query string in the attached project, only one result should be returned, the one with the accent.

### Actual behavior

Two results are returned, as if the accents are being ignored.

### Steps To Reproduce

1. Restore packages to attached solution.
2. Run `dotnet test` in the `Couchbase.FTS/Couchbase.FTS.TestRunner.Netcore` folder of the attached solution.
3. *Test fails*

### Reproduction Project

For simplification, I did not include the Xamarin.iOS project in the attached solution.

[Couchbase.FTS.zip](https://github.com/couchbase/couchbase-lite-net/files/3000475/Couchbase.FTS.zip)

**Comment by borrrden** [comment]
This is a [bug in LiteCore](https://github.com/couchbase/couchbase-lite-core/issues/723)
