### ISSUE TITLE
P2P Pull replication is not able to filter documents with attachements properly

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-net#1135]
### Library Version

2.5.0-180

### .NET Runtime

.NET Core - P2P
UWP - P2P

### Operating System / Device Details
 Windows 10 Fall 

### Log Output

[pytest client.log](https://github.com/couchbase/couchbase-lite-net/files/3019456/pytest.client.log)
[Client logs.zip](https://github.com/couchbase/couchbase-lite-net/files/3019464/Client.logs.zip)
[Server logs.zip](https://github.com/couchbase/couchbase-lite-net/files/3019465/Server.logs.zip)

### Expected behavior
 All those docs that has new_field_1 set to true should be replicated to client. 

### Actual behavior

All the docs which were originally created on server with new_field_1 value set to true are updated on client. However, all the docs which were created on client, and later replicated to Server and modified on it with "new_field_1" value set to true is not replicated.

### Steps To Reproduce

So this is the scenario we are testing. 
1. We have one app as client and another app as server. We add some docs (say 5), in both server and client apps and then replicate using with push and pull replicator. Let the replication finish and stop it. Check that both server and client have all the docs(now 10 on each app)
2. We modify all docs on server by adding new fields to the doc. We will start the pull replication with the filter such that only docs that has one of the new fields value set to true. Any doc for which "new_field_1" value is False, will be rejected.

### Reproduction Project

The above behaviour is only observed when we are updating docs with attachments.
 
pytest -rsx  -s --skip-provisioning  --timeout 3600 --liteserv-versions=2.5.0-180,2.5.0-180 --liteserv-hosts=<net-msft-ip>,<net-uwp-ip> --liteserv-ports=8080,8080  --sync-gateway-version=2.5.0-235 --mode=cc --server-version=6.0.0-1693 --liteserv-platforms=net-uwp,net-msft --create-db-per-test=cbl-test -k test_p2p_replication_push_pull_filtering[100-pull-True-MessageEndPoint] testsuites/CBLTester/System_test_multiple_device/test_p2p_replication_filtering.py

Below 2 tests test the scenario mentioned - 
(100, "pull", True, "URLEndPoint"),
(100, "pull", True, "MessageEndPoint"),

**Comment by borrrden** [comment]
Does a similar test fail during CBL <-> SG or is it just P2P?  There are no errors in the logs or anything...

**Comment by borrrden** [comment]
Hmmm I take it back there are a lot of JSON encode / decode errors written at the info level for some reason....

**Comment by borrrden** [comment]
The test command is full of copy paste errors (wrong test name, wrong platforms, wrong version numbers, why is there a sync gateway version and server version, etc) so instead I wrote two sides of a program to recreate this scenario.  

1. Create 50 docs on the passive side with random boolean values in 'new_field_1' and 256 Kb of random data in a blob called 'blob', and start a listener
2. Create 50 docs on the active side with random boolean values in 'new_field_1' and 256 Kb of random data in a blob called 'blob', and do a one-shot push/pull replication with the passive side.
3. Verify 100 documents on the passive side and modify each 'new_field_1' with a random boolean value (if the random value is the same as the current, don't save).  Keep track of which flipped from true -> false and which flipped from false -> true
4. Store the results for all documents that are true, and all those that are false currently on the active side.  Do a filtered pull replication on the active side that will reject any documents with a false value in 'new_field_1'
5. Compare the documents that are true after the replication with those that were true before, and observe that the list of changed ones is the same as on the passive side.  Ensure that the false documents have not changed at all.

This works fine for me, so I am not sure what is going on.  If you want I can provide the program that I used.

**Comment by sridevi-15** [comment]
@borrrden , Can you try this command?

pytest -s -rsx -k test_p2p_replication_push_pull_filtering[100-pull-True-MessageEndPoint] --timeout 1800 --liteserv-version=2.5.0-175 --liteserv-host=10.100.174.141,10.100.174.165 --liteserv-port=8080,8080  --sync-gateway-version=2.5.0-265 --mode=cc --server-version=6.0.1-2037 --liteserv-platform=xamarin-ios,xamarin-android --create-db-per-test=cbl-test testsuites/CBLTester/System_test_multiple_device/

for this above command, we set up ios and android . You need to provide ip address of simulator and Emulator. We used geny motion for emulator.

**Comment by borrrden** [comment]
Reported platforms are .NET Core and UWP.  It's unclear which is passive and which is active.

**Comment by borrrden** [comment]
After digging really deep through some test server weirdness that was unrelated, I found out what is going on.  Closing this in favor of https://github.com/couchbase/couchbase-lite-core/issues/732

**Comment by borrrden** [comment]
Actually I will leave this open so that I can add the verify tag later!

**Comment by hrajput89** [comment]
Updated issue summary with correct command.

**Comment by borrrden** [comment]
Fix is in 2.5.0-b0183

**Comment by hrajput89** [comment]
Tests are passing with build 2.5.0-b0183. Hence closing the issue.
