### ISSUE TITLE
Invalid numeric value

### ISSUE THREAD

**Issue by blimkemann** [couchbase/couchbase-lite-net#1141]
### .NET Runtime

Xamarin Forms
UWP / Android / iOS

### Log Output

The following QueryBuilder expression gives a "Invalid numeric valu" (spelling is wrong too) message (note that the Latitude and Longitude properties are double and that the N1QL version of this query runs perfectly on the server):

var srcLat = Expression.Double(41.482343);//zip.Latitude);
					var srcLong = Expression.Double(-81.794563);//zip.Longitude);

					//AND acos(sin(radians(srcLat)) * sin(RADIANS(Latitude)) + cos(RADIANS(srcLat)) * cos(RADIANS(Latitude)) * cos(RADIANS(srcLong) - RADIANS(Longitude))) * 3955
					var formula = Function.Acos(Function.Sin(Function.Radians(srcLat))
														.Multiply(Function.Sin(Function.Radians(Expression.Property(nameof(Directory.Latitude)))))
														.Add(Function.Cos(Function.Radians(srcLat)))
														.Multiply(Function.Cos(Function.Radians(Expression.Property(nameof(Directory.Latitude)))))
														.Multiply(Function.Cos(Function.Radians(srcLong).Subtract(Function.Radians(Expression.Property(nameof(Directory.Longitude)))))))
					                      .Multiply(Expression.Double(3955));
					where = where.And(formula.LessThanOrEqualTo(Expression.Double(10)));//(int)PostalCodeRadius)));

Output of query.Explain() is:
SELECT fl_result(key) FROM kv_default WHERE ((((fl_value(body, 'Type') = 'Directory' AND fl_value(body, 'GroupGuid') = 'cb87110f-94e1-e511-80e5-002590701742') AND fl_value(body, 'CountryGuid') = '2c48717e-f7e5-e511-80e5-002590701742') AND fl_value(body, 'BusinessTypeGuid') = '5045717e-f7e5-e511-80e5-002590701742') AND acos(((sin(radians(41.482343)) * sin(radians(fl_value(body, 'Latitude'))) + cos(radians(41.482343))) * cos(radians(fl_value(body, 'Latitude')))) * cos(radians(-81.794562999999997) - radians(fl_value(body, 'Longitude')))) * 3955 <= 10) AND (flags & 1) = 0
0|0|0| SEARCH TABLE kv_default USING INDEX IX_Type_RowId (<expr>=?)

### Expected behavior

This should result in a valid query.

### Actual behavior

Exception thrown

**Comment by borrrden** [comment]
I won't be able to verify this without a complete querybuilder statement, and a document to test it on.

**Comment by blimkemann** [comment]
Here is a complete query and attached is a JSON file of data.

var srcLat = Expression.Double(41.482343);//zip.Latitude);
var srcLong = Expression.Double(-81.794563);//zip.Longitude);

var formula = Function.Acos(Function.Sin(Function.Radians(srcLat))
													.Multiply(Function.Sin(Function.Radians(Expression.Property(nameof(Directory.Latitude)))))
													.Add(Function.Cos(Function.Radians(srcLat)))
													.Multiply(Function.Cos(Function.Radians(Expression.Property(nameof(Directory.Latitude)))))
													.Multiply(Function.Cos(Function.Radians(srcLong).Subtract(Function.Radians(Expression.Property(nameof(Directory.Longitude)))))))
				                      .Multiply(Expression.Double(3955));
var where = formula.LessThanOrEqualTo(Expression.Double(10));
QueryBuilder.Select(SelectResult.Expression(Meta.ID))
										   .From(DataSource.Database(Database))
										   .Where(where);
[data.zip](https://github.com/couchbase/couchbase-lite-net/files/3094142/data.zip)

**Comment by Sandychuang8** [comment]
@blimkemann
I tried the query and data you gave me and created a test with our latest CBL version 2.5 and I did not experience any exception. However, I did not get any result from the query.
`[Fact]
        public void TestQueryCoordination()
        {
            SaveGPSCorrdnationDoc();

            var Latitude = "Latitude";
            var Longitude = "Longitude";

            var srcLat = Expression.Double(41.482343);//zip.Latitude);
            var srcLong = Expression.Double(-81.794563);//zip.Longitude);

            var formula = Function.Acos(Function.Sin(Function.Radians(srcLat))
            .Multiply(Function.Sin(Function.Radians(Expression.Property(Latitude))))
            .Add(Function.Cos(Function.Radians(srcLat)))
            .Multiply(Function.Cos(Function.Radians(Expression.Property(Latitude))))
            .Multiply(Function.Cos(Function.Radians(srcLong).Subtract(Function.Radians(Expression.Property(Longitude))))))
            .Multiply(Expression.Double(3955));

            var where = formula.LessThanOrEqualTo(Expression.Double(10));

            using (var query = QueryBuilder.Select(SelectResult.Expression(Meta.ID))
            .From(DataSource.Database(Db))
            .Where(where)) {
                var res = query.Execute().AllResults();
                var cnt = res.Count();
            }
        }

        private void SaveGPSCorrdnationDoc()
        {
            List<Dictionary<string, object>> coordinationDict =
                new List<Dictionary<string, object>>() {
            new Dictionary<string, object> () {
                {"CityName", "Cleveland"},
                {"Dist", 3.056916550331197},
                {"Latitude", 41.470294},
                {"Longitude", -81.737685},
                {"PostalCode", "44102"}
            },
            new Dictionary<string, object> (){
                { "CityName", "Lakewood" },
                { "Dist", 0 },
                {"Latitude", 41.482343},
                {"Longitude", -81.794563},
                {"PostalCode", "44107 -3714"}
            },
            new Dictionary<string, object>(){
                {"CityName", "Cleveland"},
                {"Dist", 0},
                {"Latitude", 41.482343},
                {"Longitude", -81.794563},
                {"PostalCode", "44107"}
            },
            new Dictionary<string, object>(){
                {"CityName", "Cleveland"},
                {"Dist", 1.6301329127951614},
                {"Latitude", 41.459888},
                {"Longitude", -81.784804},
                {"PostalCode", "44111" }
            },
            new Dictionary<string, object>(){
                {"CityName", "Cleveland"},
                {"Dist", 3.056916550331197},
                {"Latitude", 41.470294},
                {"Longitude", -81.737685},
                {"PostalCode", "44102"}
            },
            new Dictionary<string, object>(){
                {"CityName", "Cleveland"},
                {"Dist", 3.3289094948168008},
                {"Latitude", 41.434425},
                {"Longitude", -81.80182},
                {"PostalCode", "44135"}
            },
            new Dictionary<string, object>(){
                {"CityName", "Cleveland"},
                {"Dist", 1.6301329127951614},
                {"Latitude", 41.459888},
                {"Longitude", -81.784804},
                {"PostalCode", "44111 -3006"}
            },
            new Dictionary<string, object>(){
                {"CityName", "Cleveland"},
                {"Dist", 1.6301329127951614},
                {"Latitude", 41.459888},
                {"Longitude", -81.784804},
                {"PostalCode", "44111 -3172"}
            },
            new Dictionary<string, object>(){
                {"CityName", "Brook Park"},
                {"Dist", 3.3289094948168008},
                {"Latitude", 41.434425},
                {"Longitude", -81.80182},
                {"PostalCode", "44135"}
            },
            new Dictionary<string, object>{
                {"CityName", "Fairview Park"},
                {"Dist", 4.059203658865748},
                {"Latitude", 41.446483},
                {"Longitude", -81.856757},
                {"PostalCode", "44126 -2021"}
            },
            new Dictionary<string, object>{
                {"CityName", "Cleveland"},
                {"Dist", 3.056916550331197},
                {"Latitude", 41.470294},
                {"Longitude", -81.737685},
                {"PostalCode", "44102 -4631"}
            },
            new Dictionary<string, object>{
                {"CityName", "Cleveland"},
                {"Dist", 3.3289094948168008},
                {"Latitude", 41.434425},
                {"Longitude", -81.80182},
                {"PostalCode", "44135"}
            },
            new Dictionary<string, object>{
                {"CityName", "Cleveland"},
                {"Dist", 0},
                {"Latitude", 41.482343},
                {"Longitude", -81.794563},
                {"PostalCode", "44107"}
            },
            new Dictionary<string, object>{
                {"CityName", "Lakewood"},
                {"Dist", 0 },
                {"Latitude", 41.482343},
                {"Longitude", -81.794563},
                {"PostalCode", "44107"}
            },
            new Dictionary<string, object>(){
                {"CityName", "Lakewood"},
                {"Dist", 0},
                {"Latitude", 41.482343},
                {"Longitude", -81.794563},
                {"PostalCode", "44107"}
            },
            new Dictionary<string, object>(){
                {"CityName", "Fairview Park"},
                {"Dist", 3.5510749602257885},
                {"Latitude", 41.467062},
                {"Longitude", -81.860125},
                {"PostalCode", "44116 -3205"}
            },
            new Dictionary<string, object>(){
                {"CityName", "Lakewood"},
                {"Dist", 0},
                {"Latitude", 41.482343},
                {"Longitude", -81.794563},
                {"PostalCode", "44107 -4523"}
            },
            new Dictionary<string, object>(){
                {"CityName", "Brook Park"},
                {"Dist", 3.3289094948168008},
                {"Latitude", 41.434425},
                {"Longitude", -81.80182},
                {"PostalCode", "44135"}
            },
            new Dictionary<string, object>(){
                {"CityName", "Cleveland"},
                {"Dist", 3.3289094948168008},
                {"Latitude", 41.434425},
                {"Longitude", -81.80182},
                {"PostalCode", "44135-2552"}
            },
            new Dictionary<string, object>(){
                {"CityName", "Lakewood"},
                {"Dist", 0},
                {"Latitude", 41.482343},
                {"Longitude", -81.794563},
                {"PostalCode", "44107-5005"}
            },
            new Dictionary<string, object>(){
                {"CityName", "Cleveland"},
                {"Dist", 3.3289094948168008},
                {"Latitude", 41.434425},
                {"Longitude", -81.80182},
                {"PostalCode", "44135-1109"}
            },
            new Dictionary<string, object>(){
                {"CityName", "Cleveland"},
                {"Dist", 3.056916550331197},
                {"Latitude", 41.470294},
                {"Longitude", -81.737685},
                {"PostalCode", "44102-2406"}
            },
            new Dictionary<string, object>(){
                {"CityName", "Cleveland"},
                {"Dist", 3.056916550331197},
                {"Latitude", 41.470294},
                {"Longitude", -81.737685},
                {"PostalCode", "44102-4630"}
            },
            new Dictionary<string, object>(){
                {"CityName", "Cleveland"},
                {"Dist", 3.056916550331197},
                {"Latitude", 41.470294},
                {"Longitude", -81.737685},
                {"PostalCode", "44102-4406" }
            }};

            foreach(var coord in coordinationDict) {
                var doc = new MutableDocument(coord);
                Db.Save(doc);
            }
            
        }`

**Comment by blimkemann** [comment]
Then I wonder if this is an order of operations issue. The formula below works perfectly in Couchbase Server and generated the value for the Dist property in all the data elements I provided. However, in my Couchbase Lite implementation, the values are in the 1,800 range. To me it looks like I translated it properly. Am I missing something?

This is what needs to be translated into a Couchbase Lite expression:
acos(sin(radians(41.482343)) * sin(RADIANS(Latitude)) + cos(RADIANS(41.482343)) * cos(RADIANS(Latitude)) * cos(RADIANS(-81.794563) - RADIANS(Longitude))) * 3955

**Comment by Sandychuang8** [comment]
@blimkemann, if I remove Where statement, I was able to get result count 18 from query.Execute().AllResults(). 

var where = formula.LessThanOrEqualTo(Expression.Double(10)); doesn't look right to me. What do you plan to achieve here?

**Comment by blimkemann** [comment]
The acos... formula should be giving a calculation (in miles) from 41.482343 / -81.794563, so the <= 10 gives me everything whose Latitude / Longitude are within 10 miles. Again, this formula and logic work perfectly in Couchbase Server query workbench. So I know the logic is sound.

**Comment by Sandychuang8** [comment]
Hi @blimkemann, Still looking into it. In the mean time recommend you to set QueryBuilder this way:
`var query = QueryBuilder
                .Select(SelectResult.Expression(formula).As("Distance"), 
                        SelectResult.Expression(Expression.Property("CityName")))
                .From(DataSource.Database(Db))`

**Comment by blimkemann** [comment]
But that doesn't allow me to filter properly. Note that my real data does not contain the Distance property -  I included it here for example purposes. So selecting the formula as a property won't get me anywhere. I need it purely as a filter. Thanks,

**Comment by Sandychuang8** [comment]
Hi @blimkemann, Try this one. I modified your expression a bit to get it to work.
var formula = Function.Acos(Function.Sin(Function.Radians(srcLat))
            .Multiply(Function.Sin(Function.Radians(Expression.Property(Latitude))))
            .Add(Function.Cos(Function.Radians(srcLat)).Multiply(Function.Cos(Function.Radians(Expression.Property(Latitude))))
            .Multiply(Function.Cos(Function.Radians(srcLong).Subtract(Function.Radians(Expression.Property(Longitude)))))))
            .Multiply(Expression.Double(3955));

**Comment by blimkemann** [comment]
Thanks @Sandychuang8 that works perfectly!
