### ISSUE TITLE
Error MT5202: Native linking failed. Please review the build log.

### ISSUE THREAD

**Issue by snehalsilicus** [couchbase/couchbase-lite-net#1142]
**Following build errors are occurring in release mode only in Xamarin iOS for architecture armV7 and armV7s
Please update me asap. I have successfully developed an application for android and iOS using this lib. Released android version and now about to release iOS and facing this build error in release mode only. Kindly look into this urgent**

- iOS/obj/iPhone/Release/mtouch-cache/libsqlcipher.a, missing required architecture armv7s in file /Users/sjadhav/Documents/ACI_GPS/Project/ACIGPSTFS25April/ACI-GPS TFS1/ACI-GPS-Mobile/ACI_GPS/iOS/obj/iPhone/Release/mtouch-cache/libsqlcipher.a (4 slices) (ACI_GPS.iOS) Native linking
- _Error MT5214: Native linking failed, undefined symbol: sqlite3_enable_load_extension. This symbol was referenced by the managed member SQLitePCL.SQLite3Provider_internal/NativeMethods.sqlite3_enable_load_extension. Please verify that all the necessary frameworks have been referenced and native libraries linked. (MT5214)
- /iOS/MTOUCH: Error MT5214: Native linking failed, undefined symbol: _sqlite3_load_extension. This symbol was referenced by the managed member SQLitePCL.SQLite3Provider_internal/NativeMethods.sqlite3_load_extension. Please verify that all the necessary frameworks have been referenced and native libraries linked. (MT5214)
- /iOS/MTOUCH: Error MT5202: Native linking failed. Please review the build log. (MT5202) (ACI_GPS.iOS)

**Comment by borrrden** [comment]
armv7s is not a supported architecture for Couchbase Lite.  If you remove it from the supported architectures section of your iOS build options the problem should go away.

**Comment by snehaljadhavgit** [comment]
@borrrden, armv7s is supported by the iPhone 5 series. Does it mean application won't run on iPhone 5, 5C, 5S?

**Comment by borrrden** [comment]
No, armv7 instructions will run on armv7s

**Comment by snehaljadhavgit** [comment]
@borrrden, Thanks a ton!!!!!! You saved me! I was trying to build with armv7s for iPhone 5 since 3 days.
