### ISSUE TITLE
CBL push replication is not failing for 20mb+ doc

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-net#1143]
### Library Version

2.5.0-190

### .NET Runtime

.NET Core 2.5.0-190

### Operating System / Device Details
Windows 10

### Log Output

Couchbase Server logs - 
[cbs_log.zip](https://github.com/couchbase/couchbase-lite-net/files/3126613/cbs_log.zip)

Sync Gateway logs - 
[sgcollect_info.zip](https://github.com/couchbase/couchbase-lite-net/files/3126617/sgcollect_info.zip)

Python Client logs -
[python_client.log](https://github.com/couchbase/couchbase-lite-net/files/3126624/python_client.log)

CBL Net Core Logs -
[log_1556526513.6719.zip](https://github.com/couchbase/couchbase-lite-net/files/3126637/log_1556526513.6719.zip)

### Expected behavior

Push replication should fail with some error

### Actual behavior
Push replication passed and doc got replicated successfully

### Steps To Reproduce

pytest -rsx  -s --skip-provisioning  --timeout 3600 --enable-file-logging --liteserv-version=2.5.0-190 --liteserv-host=172.23.121.51 --liteserv-port=8080 --sync-gateway-version=2.5.0-239 --mode=cc --server-version=5.5.0 --liteserv-platform=net-core --create-db-per-test=cbl-test testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_replication_eventing.py -k test_push_replication_for_20mb_doc

### Reproduction Project
https://github.com/couchbaselabs/mobile-testkit/tree/feature/cbl2.5-20mb-doc

https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl2.5-20mb-doc/testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_replication_eventing.py#L497

PS: We get error (error code - 10413) for 2nd scenario where attachment size is 20mb+, but not for 3rd scenario where attachment is of small size.

**Comment by Sandychuang8** [comment]
@hrajput89 @sridevi-15 
I am not sure what the 3rd scenario is. I need info for 3rd scenario.

**Comment by hrajput89** [comment]
@Sandychuang8 

Here are the scenario as the test is parameterised -


1.    [None, None], - (20mb+ doc, no attachment)
2.   [load_from_data_dir, ["Sample_Image_30mb.jpg"]], - (20mb+ doc, 20mb+ attachment)
3.    [generate_2_png_100_100, None], - (20mb+ doc, small attachment)

**Comment by Sandychuang8** [comment]
Thanks @hrajput89 So does that mean, I will need test saving two 15mb attachments before the push replication?

**Comment by hrajput89** [comment]
> Thanks @hrajput89 So does that mean, I will need test saving two 15mb attachments before the push replication?

Sandy, the project mentioned in the description, has 20mb+ doc and 20mb+ attachment. if you want to use any other attachment of your choice you can pass, like we did in second scenario.

All attachment files are available at - https://github.com/couchbaselabs/mobile-testkit/tree/feature/cbl2.5-20mb-doc/resources/data

**Comment by Sandychuang8** [comment]
I was not able to reproduce the issue. I verified both scenario 2 and scenario 3. Both tests received HTTP 500 'Internal error: network error' response from Sync Gateway. Please make sure the document size on the scenario 3 is actually over 20 MB.

**Comment by hrajput89** [comment]
https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl2.5-20mb-doc/resources/data/Sample_Image_30mb.jpg - has size of 29.4mb exactly.

https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl2.5-20mb-doc/resources/data/20mb_doc.json - has size of 28.1mb exactly.

What is the issue about size?

**Comment by Sandychuang8** [comment]
I took a look at the log files you attached here. In your cbl_info log line 398, I see `[Sync]: (Replicator) [235] Replicator[<> ws://172.23.121.195:4984/db]: error pushing 'cbl_docs_0' : 0 ()` which means pushing cbl_docs_0 failed.

**Comment by Sandychuang8** [comment]
@euniceatcouchbase and I spent a LONG time to debug this issue. And this is what we found out from running the test case on TestServer. When pushing the large document, Sync gateway actually received/stored it (NO ERROR MSG). Please look at sg_info.log in the attachment you sent me. It actually shows `[INF] Cache: Received #2 after 958ms ("cbl_docs_0" / "1-cb2a167480d71fac97b37b8044a294d10acadc68")
2019-04-29T04:35:20.820-04:00` 

So the conclusion we have is the file size is actually less than 20mb when you pushed because there is no rejection/error message came from sync gateway, therefore, app side has no error to catch.

**Comment by euniceatcouchbase** [comment]
Interesting to repro whatever @hrajput89 has: the 29MB json doc has been successfully pushed to SGW without experiencing any error. I am able to GET this doc from SGW, however, the actual size became 13.7MB. I have compared the file contents between the 2 files (original one in resources/ and the one I GET from SGW) they are almost identical except some metadata difference.

@hrajput89 in the test case, you may add some code to get the document from SGW if error code is not presented, in that way you can verify if the document got pushed to SGW successfully or CBL swallowed the error code gives a fake success. 

@Sandychuang8 has SGW hosted on Windows server, so she DID see the HTTP 500 error code running the same scenario, my SGW is on CentOS, I believe @hrajput89 has the same setup as mine. We should consult Adam to get ideas why this happens?

**Comment by hrajput89** [comment]
So I tried with new Json doc which doesn't have indentation (basically skipping the extra MBs from whitespace). I'm seeing that we are getting 10500 as error code for this doc. So we are good to go. Hence closing this issue.

**Comment by rajagp** [comment]
@hrajput89 Did you confirm that this error reported up via replication event ?

**Comment by hrajput89** [comment]
Yes, I got the error in replication event. I checked the event listener using debugger for detailed info.

<img width="1426" alt="Screenshot 2019-05-07 12 07 50" src="https://user-images.githubusercontent.com/18100038/57276901-7f1ab800-70c0-11e9-8315-6ef9325346a5.png">
