### ISSUE TITLE
Database.CreateIndex fails with existing FullTextIndex

### ISSUE THREAD

**Issue by blimkemann** [couchbase/couchbase-lite-net#1149]
### Library Version

2.5.0

### .NET Runtime

UWP 1803

### Expected behavior
The following line should be a no-op if FT_CityName exists already and was prior to 2.5.0.
Database.CreateIndex("FT_CityName", IndexBuilder.FullTextIndex(FullTextIndexItem.Property("CityName")).IgnoreAccents(true));
### Actual behavior

The CreateIndex line throws an exception stating that the index already exists.

Couchbase debugger output is:
2019-5-3 11:25:16.175-04:00 [10]| ERROR)  [Database] SQLite error (code 1): table "kv_default::FT_CityName" already exists in "CREATE VIRTUAL TABLE "kv_default::FT_CityName" USING fts4("Name", tokenize=unicodesn "stopwords=en" "stemmer=en" "remove_diacritics=1")"
2019-5-3 11:25:16.178-04:00 [10]| ERROR)  [Database] table "kv_default::FT_CityName" already exists (1/1)

And there is no way to check for this index since Database.GetIndexes does NOT return any full-text indexes. If this a regression or intended behavior?

### Steps To Reproduce
Just run the following code on a Database object:
Database.CreateIndex("FT_CityName", IndexBuilder.FullTextIndex(FullTextIndexItem.Property("CityName")).IgnoreAccents(true));
Database.CreateIndex("FT_CityName", IndexBuilder.FullTextIndex(FullTextIndexItem.Property("CityName")).IgnoreAccents(true));

**Comment by Sandychuang8** [comment]
Hi @blimkemann, I tested the steps to reproduce and I did not get any exception on v2.5. 
When you create same index twice, the 2nd index creation will be ignored which is a no-op as you stated.

**Comment by blimkemann** [comment]
Two more things to try:
1. Try running that same code on a database that already has the index on it. This is actually where it fails for me. I have a database on my device created with the prior version that has that full-text index. When I open that database and run the CreateIndex against it, an exception is thrown even though it should just be a no-op.
2. Try it on UWP. It definitively fails on UWP using 2.5 for me every time.

**Comment by Sandychuang8** [comment]
Hi @blimkemann, 

On UWP, I tested creating 2.1 db and creating index on updated 2.5 db, index was created...
```VERBOSE)  [Database] {DB#1} begin transaction
INFO)  [Database] Upgrading database to use 'indexes' table...
INFO)  [Query] Creating value index "myindex"
VERBOSE)  [Database] {DB#1} commit transaction
INFO)  [Query] Created index 'myindex' in 0.009 sec```

creating index with same name 2nd time, I see

```VERBOSE)  [Database] {DB#1} begin transaction
INFO)  [Database] {DB#1} Transaction exiting scope without explicit commit; aborting
VERBOSE)  [Database] {DB#1} abort transaction```

No exception throw. All logs are showing expected behavior.  What `prior version` cbl you were using?

**Comment by blimkemann** [comment]
I created the database using 2.1. I have Pull replication turned on for this database if it matters. 
Here is my log output pertaining to the index:
2019-5-6 06:25:45.041-04:00 [10]| INFO)  [Query] Deleting value index 'FT_City_CityName'
2019-5-6 06:25:45.043-04:00 [10]| INFO)  [Query] Creating full-text index "FT_City_CityName"
2019-5-6 06:25:45.045-04:00 [10]| ERROR)  [Database] SQLite error (code 1): table "kv_default::FT_City_CityName" already exists in "CREATE VIRTUAL TABLE "kv_default::FT_City_CityName" USING fts4("Name", tokenize=unicodesn "stopwords=en" "stemmer=en" "remove_diacritics=1")"
2019-5-6 06:25:45.047-04:00 [10]| ERROR)  [Database] table "kv_default::FT_City_CityName" already exists (1/1)

Remember that this is a full-text index.

**Comment by Sandychuang8** [comment]
Sorry, I just re-run creating a full text index twice on my UWP app and here are the result (with push/pull replication behind):

```VERBOSE)  [Database] {DB#1} begin transaction
INFO)  [Query] Creating full-text index "FT_CityName4"
VERBOSE)  [Database] {DB#1} commit transaction
INFO)  [Query] Created index 'FT_CityName4' in 0.019 sec
VERBOSE)  [Database] {DB#1} begin transaction
INFO)  [Database] {DB#1} Transaction exiting scope without explicit commit; aborting
VERBOSE)  [Database] {DB#1} abort transaction```

still no exception.

**Comment by borrrden** [comment]
There is actually an odd clue in that log output.  It claims that you had a *value* index with the name `FT_City_CityName` existing in the database when you tried to create the FTS index.  This should work, but it's unclear why a virtual table would exist because value indexes don't use them.  Are you switching between value and FTS indexes on the same index name?  Have you ever had problems deleting an index on 2.1?

**Comment by blimkemann** [comment]
It never was a value index. Was always full text. So that's really odd

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by borrrden** [comment]
If you have a copy of the database as it exists before this situation, try opening it with a SQLite editor and running the following query:

`SELECT type FROM indexes WHERE name='FT_City_CityName'`

If an FTS index exists `type` will be 1 (value index is 0)

**Comment by blimkemann** [comment]
Its type is 0, but I've already run the CreateIndex methods against it using version 2.5. So if this index was always full-text, and things were fine in 2.1 then what might be going on?

**Comment by borrrden** [comment]
The type being 0 is a problem.  That means it is registered as a value index, not a full text index.  Without knowing how it got into that state it is difficult to figure out what to do to fix it.  As noted above, every way we've tried to reproduce this has failed to show the problem.  Are you able to reproduce this with a new database, or only this one that you have?

**Comment by blimkemann** [comment]
So if I uninstall the app and run it from scratch the database is created properly. Running it a second time avoids the error so it looks like the index is created properly from scratch. What I don't know is how it happened. But, I need a way to solve this for my installed user base. Since GetIndexes does not list it, how can I go about deleting the index (or testing if it exists)? I can catch an exception for each full-text index I guess but that seems a bit extreme. I would rather figure out a way to actually find and delete/fix it. Thoughts?

**Comment by borrrden** [comment]
The problem here is that since it thinks it is a value index, it will go through the value index deletion procedures.  This will not touch any virtual tables because they should not exist (the question is why do they exist...).  `GetIndexes` should list it in the normal case (where no error happens) as we have tests for that in our test suite.  The reason it doesn't show up I believe is because after deletion, it appears deleted to the method that `GetIndexes` uses to retrieve it.  It's not throwing an error because the *index* already exists.  It's throwing an error because of the unexpected condition that the virtual table already exists.  I don't think there is any clear way to fix this via any API that we provide.  The easiest workaround would be to raise the white flag and rename the index to something else.

**Comment by Sandychuang8** [comment]
@blimkemann Please let us know if @borrrden has provided you a good solution/workaround for this issue.

**Comment by blimkemann** [comment]
Yes, @Sandychuang8, @borrrden 's sugestion of just using a different name for the index altogether worked fine.
