### ISSUE TITLE
Change to WebSocket timeout in LiteCore

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#1150]
Per this couchbase/couchbase-lite-ios#2447, the WebScoket implementation in LiteCore has implemented the timeout. To avoid conflict or duplication, we should disable WebSocket (read/write) timeout from the platform code. If it cannot be disabled, we probably need to set it to be longer that what LiteCore is using.

**Comment by borrrden** [comment]
Migrated to https://issues.couchbase.com/browse/CBL-39
