### ISSUE TITLE
Copy method of Database class is not able to copy encrypted db

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-net#1161]
### Library Version
2.5.0-191

### .NET Runtime

.NET Core - 2.5.0-191

### Operating System / Device Details
Windows 10 

### Log Output

Python client logs - 

[python_client.log](https://github.com/couchbase/couchbase-lite-net/files/3252483/python_client.log)

CBL Logs -

[log_1559653367.50243.zip](https://github.com/couchbase/couchbase-lite-net/files/3252497/log_1559653367.50243.zip)

### Expected behavior

copy method should copy encrypted db with proper db config

### Actual behavior

copy method is not copying encrypted db with proper db config

### Steps To Reproduce
Test command -
1. git clone https://github.com/couchbaselabs/mobile-testkit.git
2. git checkout feature/cbl-upgrade-testing
3. pytest -rsx -s  --skip-provisioning --timeout 3600 --liteserv-version=2.5.0-191 --liteserv-host=172.23.120.163 --liteserv-port=8080 --sync-gateway-version=2.5.0-269 --mode=cc --server-version=6.0.0-1693 --liteserv-platform=net-msft --create-db-per-test=cbl-test  --enable-file-logging testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_database.py::test_copy_prebuilt_database[True]

PS: This issue is not specific to .net, I'm seeing this issue in every platform

**Comment by borrrden** [comment]
By the way we have a JIRA project internally now so in the future you can use that instead of GH.  I will migrate this once confirmed.

**Comment by borrrden** [comment]
Also the logs folder is empty...

**Comment by borrrden** [comment]
One thing, make sure that the path you are sending for "old path" ends in a backslash (or forward slash on non-Windows).  I was able to take the DB you created and use the copy method on it without error.

**Comment by hrajput89** [comment]
I've tried with appending "/" to the db path, but I'm still getting the exception for iOS. One thing I've observed that if I use copy database in the same code flow in which I've created the encrypted db, I don't get any error, however, copying it database folder and then using copy method to copy it from there, I'm getting same exception.

-- Copy method woks in below scenario __

```
    base_url = params_from_base_suite_setup["base_url"]
    db = Database(base_url)
    db_config = db.configure(password="password")
    cbl_db = db.create("PrebuiltDB-encrypted", config=db_config)
    db.create_bulk_docs(number=5, id_prefix="cbl", db=cbl_db)
    db.create_bulk_docs(number=5, id_prefix="cbl2", db=cbl_db)
    print db.getCount(cbl_db)
    path = db.getPath(cbl_db)
    db.copyDatabase(path, "new_copied_db", db_config)
```

Logs from Xcode:

[ios_app.log](https://github.com/couchbase/couchbase-lite-net/files/3255063/ios_app.log)

**Comment by borrrden** [comment]
This is not the appropriate place to write about iOS issues.  If the .NET issue is verified please close this issue and file it on the iOS repo.

**Comment by hrajput89** [comment]
I've attached the logs copied from console into the Jira ticket. It seems file logging is not log as effective as I've thought. I'll log a separate ticket for it.

https://issues.couchbase.com/browse/CM-170

**Comment by borrrden** [comment]
Your response does not make sense to me...what is the new ticket for?  What is going to happen with this one?

**Comment by hrajput89** [comment]
Closing this ticket, as there was a issue in test code.
