### ISSUE TITLE
Store Entity directly to couchbase lite

### ISSUE THREAD

**Issue by sriman94** [couchbase/couchbase-lite-net#1167]
Earlier when we were using couchbase lite 1.3.1 it allowed us to store object (a class in our project  ) directly using dictionary but after migrating 2.5 community edition I don't see any such option and I am getting below error whenever I am using dictionary.

Test is not a valid type. You may only pass byte, sbyte, short, ushort, int, uint, long, ulong, float, double, bool, DateTimeOffset, Blob, 
or one-dimensional arrays or dictionaries containing the above types

var testDoc = new Test { Id = "test", Name = "test" };
            try
            {
                var documentIdentifier = "test";
                var doc = new MutableDocument(documentIdentifier);
                var properties = new Dictionary<string, object>();
                
                properties.Add(documentIdentifier,  testDoc);             
                doc.SetData(properties);
                test.DbContext.DbInstance.Save(doc);
            }
            catch (Exception ex)
            {

            }

We have requirement to store our entity without serialization and directly, kindly suggest the alternative

**Comment by borrrden** [comment]
There is no built in alternative. One of our dev advocates has made a library on top of Couchbase for though. Perhaps it can help you out. 

https://www.nuget.org/packages/Couchbase.Lite.Mapping

**Comment by sriman94** [comment]
I tried that but even with this I am getting an exception DateTime is not a valid type (I am using DateTime in my entity), any ideas on this ?

**Comment by borrrden** [comment]
I'd suggest opening an issue there if that is the case.  I know that JSON .NET has a setting for that but I'm not sure if that's been exposed in the library or not.

**Comment by sriman94** [comment]
Thanks for the update. Will do the needful

**Comment by borrrden** [comment]
@sriman94 Any update on this?

**Comment by borrrden** [comment]
Closing due to lack of response
