### ISSUE TITLE
Unable to delete Attachment

### ISSUE THREAD

**Issue by sriman94** [couchbase/couchbase-lite-net#1168]
Created couple of blobs and the files are residing in Attachment folder but when I am trying to delete the DB folder which was copied to a temp folder attachments are not getting delete as I was getting unauthorized exception.

Am I missing something or any ideas on this ?

**Comment by borrrden** [comment]
Please do not delete the issue template, as it has a lot of useful information such as runtimes and operating systems.  Also please show *how* you are creating and deleting everything.  My gut guess would be that you are not disposing things that are `IDisposable` and it is leaving file connections open.

**Comment by borrrden** [comment]
@sriman94 Are you able to provide more info on this?

**Comment by borrrden** [comment]
Closing due to lack of response
