### ISSUE TITLE
Caught exception handling incoming BLIP message: properties excessively large

### ISSUE THREAD

**Issue by NithyaArumugham** [couchbase/couchbase-lite-net#1199]
Hi Team,

when we try to sync the documents using the pull operation in the CB lite for the Xamarin forms application getting the below error:

"2020-01-03 15:32:23.718330+0530  {BLIPIO#1}==> litecore::blip::BLIPIO ->wss://******/_blipsync @0x7f86ec6053d8
| ERROR)  [Network] {BLIPIO#1} Caught exception handling incoming BLIP message: properties excessively large
 WARNING)  [Database] Caught unexpected C++ runtime_error("properties excessively large")
Thread started:  #156"

CB lite version :2.5.3
Kindly heliport on the workaround here.

**Comment by Sandychuang8** [comment]
Hi @NithyaArumugham 
Looks like the issue is related to https://github.com/couchbase/couchbase-lite-core/pull/802 and the fix should be in CBL 2.6.0.

**Comment by borrrden** [comment]
Actually I can't confirm that it made it into 2.6.0....but it is definitely in 2.7.0 which is in the final stages of release prep

**Comment by Sandychuang8** [comment]
The issue is fixed in the later release.
