### ISSUE TITLE
MutableArray.AddValue is not working as expected

### ISSUE THREAD

**Issue by TheFo2sh** [couchbase/couchbase-lite-net#1225]
### Library Version

Latest on nuget 
https://www.nuget.org/packages/Couchbase.Lite/
2.7.1 (Build/17) Commit/c8a408f6
-->

### .NET Runtime

.NET Core 3.0
UWP 19041

-->

### Operating System / Device Details
Windows 10

### Log Output

2020-6-15 02:06:43.705+02:00 [1]| INFO)  [Database] (Startup) [1] CouchbaseLite/2.7.1 (.NET; Microsoft Windows 10.0.18362) Build/17 LiteCore/2.7.1 (16) Commit/c8a408f6
2020-6-15 02:06:43.734+02:00 [1]| WARNING)  [Database] (Logging) [1] Database.Log.File.Config is null, meaning file logging is disabled.  Log files required for product support are not being generated.

### Expected behavior

MutableArray.AddValue(Parameter) should add the Parameter value at the end of the array.

### Actual behavior
MutableArray.AddValue() replace all the array values with null and add the new value at the end of the array.

### Steps To Reproduce
Consider running this code in a console app 

`            var db = new Database("1");
           
            var mutabledocument=new MutableDocument("Document");
            mutabledocument.SetArray("List", new MutableArrayObject(new StringCollection() {"Test"}));
            db.Save(mutabledocument);

            var document = db.GetDocument("Document");
            Console.WriteLine(string.Join(",", document.GetArray("List").Cast<string>()));

            var mutable = document.ToMutable();
            var list = mutable.GetArray("List");
            list.AddString("asasa2");
            db.Save(mutable);

            var document2 = db.GetDocument("Document");
            Console.WriteLine(string.Join(",",document2.GetArray("List").Cast<string>()));
            Console.ReadLine();
        }`

Expected Output is
Test
Test,asasa2

Actual Output is
Test
,asasa2

**Comment by TheFo2sh** [comment]
This issue is very urgent as it cause data lose, please consider unpublishing the package  if it will take time for fix

**Comment by Sandychuang8** [comment]
Thanks for reporting. We were able to reproduce the issue and filed a ticket.

**Comment by TheFo2sh** [comment]
any updates ?

**Comment by Sandychuang8** [comment]
@TheFo2sh The latest release 2.8 should contain the fix.

**Comment by Sandychuang8** [comment]
CBL .Net 2.8 has the fix.
