### ISSUE TITLE
Updating SimpleInjector throws MissingFieldException: Field not found : 'SimpleInjector.Lifestyle.Singleton'.

### ISSUE THREAD

**Issue by NgyAnthony** [couchbase/couchbase-lite-net#1228]
### Library Version

Latest on nuget
https://www.nuget.org/packages/Couchbase.Lite/
2.7.1 (Build/17) Commit/c8a408f6

### .NET Runtime

.NET Framework 4.8 (WPF Application)

### Operating System / Device Details

Windows 10 Home

### Log Output

  ```
System.TypeInitializationException
  HResult=0x80131534
  Message=An exception was raised by the type initializer for 'Couchbase.Lite.Database'.
  Source=Couchbase.Lite
  StackTrace:
   at Couchbase.Lite.Database..ctor(String name, DatabaseConfiguration configuration)
   at TestingAPP.MainWindow..ctor() in C:\Users\MyUser\source\repos\TestingAPP\TestingAPP\MainWindow.xaml.cs:line 27

Inner Exception 1:
TypeInitializationException: An exception was raised by the type initializer for 'Couchbase.Lite.DI.Service'.

Inner Exception 2:
MissingFieldException: Field not found : 'SimpleInjector.Lifestyle.Singleton'.
```

### Expected behavior

Creating a new database should throw no error.
### Actual behavior

Database was not created because of an incompatibility with the latest version of SimpleInjector, error thrown.

### Steps To Reproduce
1. Create a new WPF project with .NET Framework 4.8
2. Add the latest version of Couchbase.Lite
3. Update SimpleInjector to the latest version
4. Add `var database = new Database("mydb")` to MainWindow.cs
5. Expect an error.

### Note

I'm still a Junior dev so I wasn't aware that updating my packages would break my other dependencies (but it makes sense when I think about it). Maybe this isn't an issue at all and it's just expected behavior, but I'm still submitting an issue to let people find  this issue because I haven't seen it anywhere.

For people having the same issue as me:
If reinstalling the 4.0.12 version of SimpleInjector doesn't work and your build doesn't find your assembly file even though it's clearly there, I fixed it by creating a new project and re-imported my original files (I couldn't fix it manually so after a few hours I gave up).

**Comment by dfarrNTST** [comment]
Getting same error on DatabaseConfiguration.  Will this library be updated with the latest 5.x version of SimpleInjector?

**Comment by Sandychuang8** [comment]
Yes. We plan on upgrading SimpleInjector in the future release.

**Comment by Sandychuang8** [comment]
SimpleInjector version has updated to 5.2.
