### ISSUE TITLE
The type initializer for 'Couchbase.Lite.DI.Service' threw an exception.

### ISSUE THREAD

**Issue by Dinglebarry9** [couchbase/couchbase-lite-net#1233]
Thrown at new DatabaseConfiguration(). I copied and pasted directly from the UserProfileDemo

**Comment by Sandychuang8** [comment]
Did you try clone the project instead of copy and paste?

**Comment by Dinglebarry9** [comment]
Sorry, I copied and pasted the relevant parts of the project into a new project, i.e. DatabaseManager.cs, BaseRepository.cs, etc.

When I checked everything against the cloned UserProfileDemo I found that the only difference was my project had a newer version of SimpleInjector. When I downgraded SimpleInjector to 4.5.1 now it works, soooo IDK I guess closed.

**Comment by Sandychuang8** [comment]
We have a plan on updating the SimpleInjector version in the future.  But currently it only works with older SimpleInjector.

**Comment by Dinglebarry9** [comment]
Thanks, this was killing me for days.

**Comment by borrrden** [comment]
FYI to help you in the future both here an elsewhere:  `TypeInitializationException` will tell developers nothing.  `TypeInitializationException` literally just means "the static constructor threw an exception" (with the expectation that you will check the InnerException to see what _actually_ happened).  If reporting an exception, you should recursively also list all the inner exceptions as well.  The SimpleInjector issue has been reported before, and it would have been recognizable if we had seen the inner exception.
