### ISSUE TITLE
Port fix for returning 404 for _changes request on empty DB issue in Router [Router]

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#126]
Commit https://github.com/couchbase/couchbase-lite-java-core/commit/14ed9ae5c5ba1dc594326d6ba860ac15d0128466

**Comment by borrrden** [comment]
These two implementations have drifted apart and many of these port fixes have been made.  It's difficult to confirm at this point whether or not they are 100%, so I'm closing these porting issues until they become a problem again.
