### ISSUE TITLE
Broke links

### ISSUE THREAD

**Issue by FreakTheMighty** [couchbase/couchbase-lite-net#1315]
The releases page points to a new location to view release notes, but the link is broken. https://github.com/couchbase/couchbase-lite-net/releases/tag/2.7.0

Additionally the readme points to waffle.io which is fully offline. It would be helpful to see roadmap or priorities.

The last broke link I see is the “about rep branch” link. 
——

This may be a bit silly, but the disrepair of the readme gives some concerns about the level of maintenance dedicated to the project. To this end, what is the best place to get a read on what work is planned. Is the project in maintenance mode, or will additional features be added such as object mapping?

**Comment by borrrden** [comment]
Unfortunately, the README is one of the final things to be updated ever.  It's probably the last thing on a developer's mind (whether or not that is good behavior set aside from a moment).  If you want to look at the "level of maintenance" on the project, why not use something like "how recent was the last commit?" or "how often are commits made?".  No one has left this project behind, but I'll have someone fix the README for sure.

We migrated a while back from waffle to using [JIRA](https://issues.couchbase.com/secure/Dashboard.jspa) to track our work.  This is the source of truth on what is being worked on.  I can't speak to the experience of using it outside the company but I'm pretty sure that outside users are able to create accounts and even file issues (but you can still file issues here and they will be migrated by us).  

As for information on what we are planning beyond what is captured in our JIRA tickets, those are probably covered in blog posts on our website but I have to admit I am not sure, that's not in dev's wheelhouse.  Maybe @rajagp can point you in the right direction.

**Comment by Sandychuang8** [comment]
I  just updated the links. https://docs.couchbase.com/couchbase-lite/current/csharp/release-notes.html
We no longer have GH releases.
