### ISSUE TITLE
Couchbase.Lite.Enterprise 2.8.6 NuGet Package still referencing SimpleInjector 4.0.12

### ISSUE THREAD

**Issue by dfarrNTST** [couchbase/couchbase-lite-net#1320]
Issue https://github.com/couchbase/couchbase-lite-net/issues/1228 states that Couchbase.Lite has been updated with the 5.x version of SimpleInjector but using the NuGet package it is still using 4.0.12 with the 2.8.6 version of the Couchbase.Lite.Enterprise and Couchbase.Lite NuGet packages.

Can we please get these updated, built, and published with the latest version of SimpleInjector?

**Comment by Sandychuang8** [comment]
CBL .Net 3.0+ contains later SimpleInjector version.

**Comment by dfarrNTST** [comment]
@Sandychuang8  Where do we get Couchbase.Lite.Enterprise NuGet package 3.0+?  The only one we see online is 2.8.6.

**Comment by Sandychuang8** [comment]
@dfarrNTST 
Official release of CBL 3.0 will be early 2022.
