### ISSUE TITLE
Alias seems to break query

### ISSUE THREAD

**Issue by SchroterQuentin** [couchbase/couchbase-lite-net#1344]
### Library Version

3.0.0

### .NET Runtime

.NET Core 5.0.406

### Operating System / Device Details

Ubuntu 20.04

### Log Output

> 2022-4-8 12:18:20.776+02:00 [1]| INFO)  [Database] (Startup) [1] CouchbaseLite/3.0.0 (.NET; Linux 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022) Build/124 LiteCore/b018a12db01222d451b4f7b95478d4825bc19954 (191) Commit/f733cb70
> 2022-4-8 12:18:20.795+02:00 [1]| WARNING)  [Database] (Logging) [1] Database.Log.File.Config is null, meaning file logging is disabled.  Log files required for product support are not being generated.
> 2022-4-8 12:18:20.894+02:00 [1]| ERROR)  [Database] SQLite error (code 1): no such column: Label2 in "SELECT fl_result(fl_value(machines.body, 'Id')), fl_result(fl_value(machines.body, 'Label')) AS Label2, fl_result(fl_value(machines.body, 'ModelId')), fl_result(Label2) AS ModelLabel
> 2022-4-8 12:18:20.895+02:00 [1]| ERROR)  [Database] no such column: Label2 (1/1)
> 2022-4-8 12:18:20.895+02:00 [1]| WARNING)  [Database] {DB#1} SQLite error compiling statement "SELECT fl_result(fl_value(machines.body, 'Id')), fl_result(fl_value(machines.body, 'Label')) AS Label2, fl_result(fl_value(machines.body, 'ModelId')), fl_result(Label2) AS ModelLabel FROM kv_default AS machines LEFT OUTER JOIN kv_default AS models ON (fl_value(models.body, 'Id') = fl_value(machines.body, 'ModelId')) AND (models.flags & 1 = 0) WHERE (fl_value(machines.body, 'Type') = 'machine' AND (fl_value(machines.body, 'Disabled') = fl_bool(0) OR NOT (isvalued(fl_value(machines.body, 'Disabled'))))) AND (machines.flags & 1 = 0)": no such column: Label2
> Unhandled exception. Couchbase.Lite.CouchbaseSQLiteException: CouchbaseLiteException (SQLiteDomain / 1): no such column: Label2.
>    at LiteCore.Interop.NativeHandler.ThrowOrHandle()
>    at LiteCore.Interop.NativeHandler.Execute(C4TryLogicDelegate1 block)
>    at LiteCore.LiteCoreBridge.Check(C4TryLogicDelegate1 block)
>    at Couchbase.Lite.Support.ThreadSafety.DoLockedBridge(C4TryLogicDelegate1 a)
>    at Couchbase.Lite.Internal.Query.XQuery.Check()
>    at Couchbase.Lite.Internal.Query.XQuery.Explain()
>    at CouchbaseJoinBug.Program.Main(String[] args) in /home/quentin/Temps/CouchbaseJoinBug/Program.cs:line 71

### Expected behavior

The query should return what it is expected ^^.

### Actual behavior

It fails

### Steps To Reproduce

if you alias a property to the name of another property that comes later in the query, it fails

```cs
using (var query = QueryBuilder.Select(
  SelectResult.Expression(Expression.Property(nameof(MachineDTO.Label)).From(MACHINES)).As("Label2"), // removing alias or putting an other value fix the issue
  SelectResult.Expression(Expression.Property(nameof(ModelDTO.Label2)).From(MODELS)).As("ModelLabel")
```

### Reproduction Project

https://github.com/Billuc/CouchbaseJoinBug

**Comment by Billuc** [comment]
We tried to circumvent the problem by using SQL++, but unfortunately, we still get the same issue.

**Code :**
```csharp
var query = _db.CreateQuery($@"
    SELECT 
        {MACHINES}.{nameof(MachineDTO.Id)} AS Id,
        {MACHINES}.{nameof(MachineDTO.Label)} AS Label2,
        {MACHINES}.{nameof(MachineDTO.ModelId)} AS ModelId,
        {MODELS}.{nameof(ModelDTO.Label2)} AS ModelLabel
    FROM
        _ AS {MACHINES}
        LEFT OUTER JOIN _ AS {MODELS}
        ON {MODELS}.{nameof(ModelDTO.Id)} = {MACHINES}.{nameof(MachineDTO.ModelId)}
    WHERE
        {MACHINES}.{nameof(MachineDTO.Type)} = ""{MachineDTO.TYPE}"" AND
        {MODELS}.{nameof(ModelDTO.Type)} = ""{ModelDTO.TYPE}"";
");
var result = query.Execute().AllResults();
```

**Comment by Sandychuang8** [comment]
Hi there,
After review the attached repro project (Thanks for creating it for us to id the issue you are having.). I noticed "Label2" has already used as a key in your document creation. Therefore, in order to fix your query, just rename the alias from "Label2" to something else such as "ModelDTOLabel2" for example.

**Comment by Billuc** [comment]
Hi, 
Thanks for your answer ! 

We didn't have any issue previously. It appeared when we upgraded Couchbase Lite from version 2.7.0 to 3.0.0.
Do you have any idea as to why everything was fine previously and it breaks now ? Is it wanted ?

BTW, we kinda solved our problem by specifically not aliasing variables that don't need it. For instance, instead of writing
```sql
SELECT
    machines.Label AS Label,
    models.Label As ModelLabel
```
we just write
```sql
SELECT
    machines.Label,
    models.Label AS ModelLabel
```
The 2 snippets ultimately do the same thing (we get the Machine Label named as Label and the Model Label named as ModelLabel) but the second does not throw an exception.

**Comment by SchroterQuentin** [comment]
Hi @Sandychuang8 

If you could help me find where the bug seems to happen, I'd love to fix it and provide a PR.

**Comment by jianminzhao** [comment]
[CBL-3040](https://issues.couchbase.com/browse/CBL-3040)

**Comment by Sandychuang8** [comment]
This indeed is a LiteCore issue and it is triaged under https://github.com/couchbase/couchbase-lite-core/issues/1444
