### ISSUE TITLE
`TypeInitializationException` when Couchbase.Lite.Support.NetDesktop.dll is less two directories deep

### ISSUE THREAD

**Issue by mgaffigan** [couchbase/couchbase-lite-net#1384]
### Library Version

    <PackageReference Include="Couchbase.Lite" Version="3.0.0" />
    3.0.0-b0124
    Built 1/11/2022

### .NET Runtime

.NET Core 6.0

### Operating System / Device Details

Win 10 Enterprise LTSC 21H2 19044.1706

### Log Output

No log output is generated.  Event log yields:

<pre>
Application: MyCbLiteExe.exe
CoreCLR Version: 6.0.522.21309
.NET Version: 6.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'Couchbase.Lite.Database' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'LiteCore.Interop.Native' threw an exception.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'paths')
   at System.IO.Path.Combine(String[] paths)
   at Couchbase.Lite.Support.NetDesktop.LoadLiteCore()
   at LiteCore.Interop.Native..cctor()
   --- End of inner exception stack trace ---
   at LiteCore.Interop.Native.c4log_getDomain(Byte* name, Boolean create)
   at Couchbase.Lite.Logging.FileLogger.SetupDomainObjects()
   at Couchbase.Lite.Logging.FileLogger..ctor()
   at Couchbase.Lite.Logging.Log..ctor()
   at Couchbase.Lite.Database..cctor()
   --- End of inner exception stack trace ---
   at Couchbase.Lite.Database.get_Log()
   at Itt.Medbox.StationKiosk.KioskApp.Program.Main(String[] args) in C:\dev\gitroot\Itt.Medbox\source\app\Itt.Medbox.StationKiosk.KioskApp\Program.cs:line 40
</pre>

### Expected behavior

No type load exception occurs on startup.

### Actual behavior

Any use of the library causes a type load exception when Couchbase.Lite.Support.NetDesktop.dll is less two directories deep.

This seems to be caused by the assumption that [Couchbase.Lite.Support.NetDesktop/Activate.cs:90](https://github.com/couchbase/couchbase-lite-net/blob/bbf52ea82ba73426ea03581a6a44f6ba86695fd4/src/Couchbase.Lite.Support.NetDesktop/Activate.cs#L90) will not yield null.  Exception occurs when this result is passed to `Path.Combine` on [Couchbase.Lite.Support.NetDesktop/Activate.cs:95](https://github.com/couchbase/couchbase-lite-net/blob/bbf52ea82ba73426ea03581a6a44f6ba86695fd4/src/Couchbase.Lite.Support.NetDesktop/Activate.cs#L95).

### Workaround

Place Couchbase.Lite.Support.NetDesktop.dll at least two directories deep and load via `Assembly.LoadFrom` or locate the entire app at least two directories deep.

### Steps To Reproduce

1. Add nuget reference to `<PackageReference Include="Couchbase.Lite" Version="3.0.0" />`
2. Add `Couchbase.Lite.Database.Log.ToString();' to an otherwise empty program.cs
3. Copy the build output to a folder in the root of a drive (e.g.: `c:\onlyonedir\`)

**Comment by Sandychuang8** [comment]
Thanks for bring this up for our attention. We will get the fix into later official Couchbase Lite release.

**Comment by borrrden** [comment]
Looks like the internal bug was not linked to this ticket, has this been fixed?

**Comment by Sandychuang8** [comment]
It's fixed in part of this commit: https://github.com/couchbase/couchbase-lite-net/commit/587cd681c510b02ddc61043965fc029ba2327983

**Comment by borrrden** [comment]
Hey!  Thanks for confirming 😄 I will close this ticket then.
