### ISSUE TITLE
Mutable document is not accepting Decimal values

### ISSUE THREAD

**Issue by SagarThakare7** [couchbase/couchbase-lite-net#1413]
### Library Version
"Couchbase.Lite.Enterprise" version="2.8.6"

Using Xamarin.forms Version 5.0.0.2515, Getting error while running on Android 12 (API Level 32)

### Operating System / Device Details
Pixel 4a OS - Android 12 (API Level 32)

### Error Message 
Decimal is not a valid type. You may only pass byte, sbyte, short, ushort, int, uint, long, ulong, float, double, bool, DateTimeOffset, Blob,, Blob, a one-dimensional array or a dictionary whose members are one of the preceding types.

### Expected behaviour
Mutable document should be created successfully.

### Actual behaviour
While creating Mutable document with below code snippet getting the error on line - "mutableDocument = new MutableDocument(value.Id, valueProps);"

            MutableDocument mutableDocument = null;
            IDictionary<string, object> valueProps;
           
                if (WaitForInitialization())
                {
                    ValidateAndConfigureSaveParameters(value, useDefaultMetaData);
                    var doc = _db.GetDocument(value.Id);  //Get the document if it already exists or null if it is deleted.

                    //Save the updated values to this document.
                    valueProps = value.ToJsonDictionary();

                    if (valueProps != null)
                    {
                        mutableDocument = doc?.ToMutable();
                        if (mutableDocument == null)
                        {
                            mutableDocument = new MutableDocument(value.Id, valueProps);
                        }
                        else
                        {
                            mutableDocument.SetData(valueProps);
                        }

                        return SaveMutableDocument(value, doc, mutableDocument, useDefaultMetaData, failOnConflict);
                    }
                }
 NOTE :- 
 1. We don't have any data with Decimal type in ValueProps
 2. It was working fine on Android 11 (API Level 30) with same code and "Couchbase.Lite.Enterprise" version="2.8.6".
 Attached Stacktrace.
[Stacktrace .pdf](https://github.com/couchbase/couchbase-lite-net/files/9302286/Stacktrace.pdf)

**Comment by Sandychuang8** [comment]
@SagarThakare7 
Can you please provide the value you passed in as valueProps so I can repro it in my end.
Thanks!

**Comment by Sandychuang8** [comment]
And if you have also filed this forum question: https://forums.couchbase.com/t/mutabledocument-are-not-accepting-decimal-values/34176/7, I suggest you to stay on following the thread there since Coucubase team has already provide you the answer/solution.

**Comment by neha993185** [comment]
Thanks for your response. We have already tried  "https://forums.couchbase.com/t/mutabledocument-are-not-accepting-decimal-values/34176/7", but its still not working and we don't have any data with Decimal type in ValueProps.

It was working earlier with Android SDK version 30 but after updating to 31, we are facing this issue.
