### ISSUE TITLE
Typo in nuspec

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-net#1426]
https://github.com/couchbase/couchbase-lite-net/blob/4896965ff216451b92e9a9424569cd6b17aa7232/packaging/nuget/couchbase-lite.nuspec#L67

Should be `AsyncInterfaces`

**Comment by Sandychuang8** [comment]
https://issues.couchbase.com/browse/CBL-3683

**Comment by Sandychuang8** [comment]
Issue has fixed.
