### ISSUE TITLE
Update Newtonsoft.Json to 13.0.1 (or newer)

### ISSUE THREAD

**Issue by wdcossey** [couchbase/couchbase-lite-net#1445]
There's a High Severity warning for `Newtonsoft.Json` < 13.0.1, please see the advisory repost below

https://github.com/advisories/GHSA-5crp-9r3c-p9vr

Whilst not specific to `Couchbase.Lite`, it's unlikely that you may encounter that particular issue, it's worth taking a look at.

**Comment by Sandychuang8** [comment]
It's already update in the upcoming release. Thanks!

**Comment by wdcossey** [comment]
@Sandychuang8 does the next release include fixes for MAUI?

PS: Apologies for replying on a closed ticket (didn't see the need to open a new one).
If there's a roadmap available that would be great to have a look at!

**Comment by Sandychuang8** [comment]
Thanks for asking. Next CBL .NET release also includes Maui support.

**Comment by dangrieshaber** [comment]
> Thanks for asking. Next CBL .NET release also includes Maui support.

@Sandychuang8 any update on when the new release will be available? We're running into serious issues using CBL on Maui.
