### ISSUE TITLE
Support for .NET 6.0/7.0

### ISSUE THREAD

**Issue by kavitap8101** [couchbase/couchbase-lite-net#1455]
Hi,
I am using Couchbase.Lite.Enterprise with my Xamarin.Forms application, and it is working fine. Version in use - 2.8.6
But soon, we will be migrating to .NET MAUI. In your documentation, I do not see that even the latest version i.e., 3.0.2 is supporting .NET 6.0 or .NET 7.0 

Can you please confirm what is the plan to support .NET 6.0/7.0? So, that we can plan to migrate to. MAUI

**Comment by Sandychuang8** [comment]
.Net 6 is planed to be supported in next CBL major release 4.x.

**Comment by AzharEmB** [comment]
@Sandychuang8 When is that release planned? Do you share the timeline?

**Comment by kavitap0810** [comment]
@Sandychuang8  Also, is there any plan to support .Net 7  with any upcoming release ? If yes, then when that will be released
