### ISSUE TITLE
ETA on MAUI version?

### ISSUE THREAD

**Issue by wdcossey** [couchbase/couchbase-lite-net#1461]
Hi,

Is there an ETA on a MAUI compatible version?

Thanks.

**Comment by wdcossey** [comment]
Hi again,

I really need an ETA on a MAUI compatible version, could you please provide some updates?

Thanks.

**Comment by Sandychuang8** [comment]
Sorry I don't have a time frame. If you are an EE customer, please contact our product team for a better idea.
