### ISSUE TITLE
Add Stream-based overloads of Manager.ReplaceDatabase

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#153]
Updated Manager replaceDatabase to take InputStreams for source DB...
https://github.com/couchbase/couchbase-lite-java-core/commit/58b2e45bfc2fe9bf690cf4738e41c639c20a8f59

**Comment by borrrden** [comment]
This issue appears to be completed as of 2160286a61434a2ea7dcb3c6436e25117ac91842
