### ISSUE TITLE
Couchbase Lite support for .NET 6.0/7.0

### ISSUE THREAD

**Issue by kavitap081** [couchbase/couchbase-lite-net#1566]
Hi,
We are using Couchbase.Lite.Enterprise with our Xamarin.Forms application, version in use - 2.8.6
We are planning to migrate to .NET MAUI. In your documentation, I do not see that even the latest version i.e., 3.0.2 is supporting .NET 6.0 or .NET 7.0. However, read that there's plan to support .NET 6.0 in your 4.* release. 

Can you please confirm when is the plan to release 4.x?

**Comment by kavitap081** [comment]
Any update on this ticket. Also, is there any plan to support .NET 7 and .NET 8.If yes, then when that will be released?

**Comment by borrrden** [comment]
Sorry this sat here, I am usually in charge of this repo but I'm on extended leave at the moment.  Anyway, since this is a question it belongs on the forums anyway and I see [you found the forums anyway](https://www.couchbase.com/forums/t/couchbase-lite-support-for-net-6-0-7-0-8-0/37387/3)
