### ISSUE TITLE
.Net Maui Deployment to iPhone

### ISSUE THREAD

**Issue by JeffHarms** [couchbase/couchbase-lite-net#1576]
### Library Version
Couchbase.Lite 3.1.1

### .NET Runtime

Xamarin.iOS and Xamarin.Mac SDK   16.4.0.18 (9d266025e)
--On Mac--
XCode 14.3(14E222b)

### Operating System / Device Details

Windows 11
### Expected behavior
When using Windows VS 2022 (17.7.7) (which is the latest!) and deploying app to an iPhone it should deploy without errors

### Actual behavior
When using Couchbase.Lite release 3.1.1, an error occurs during the deployment.  

IF I change the Couchbase.Lite to release 3.0.15 it works.
### Steps To Reproduce

1.  Create a VS 2022 Maui App.  Just do the default.
2.  Pair to a Mac so you can test.  Make sure you can run it on either a simulator or a real iPhone
3.  Manage NuGet packages.  Add Couchbase.Lite 3.0.15.  It works
4. Now upgrade Couchbase.Lite to 3.1.1  You will see the error in the output.  Here is what I received

Error MT7091 File 'obj/Debug/net7.0-ios/ios-arm64/device-builds/iphone9.1-15.7.9/frameworks/LiteCore.xcframework.zip/LiteCore.xcframework/ios-arm64/LiteCore.framework/LiteCore' is not a valid framework: Unable to read beyond the end of the stream.

### Reproduction Project

[Test.zip](https://github.com/couchbase/couchbase-lite-net/files/13370969/Test.zip)

**Comment by borrrden** [comment]
I see this sort of error sometimes but really have no idea under what circumstances it happens.  I've never really trusted VS pairing with mac to do the job correctly so we always build directly on a mac machine.  I wonder if your test project works there?  If so it might be an actual issue with the pairing not correctly transmitting the native library.  Thanks for the test project though, I'll ask someone to take a look since I am on extended leave atm.

**Comment by JeffHarms** [comment]
So I have loaded the app on my Mac and it does compile but does not run as
expected.  i have a suspicion that it has to do with Apple removing some
key libraries in their latest release. (v15)  Just a hunch.

Is there anything I can do do help figure this out?  Works fantastic on
Windows and Android.  Also, MS is not supporting Visual Studio on Mac any
longer.  So gotta get this working on Windows with the pairing.

Jeff

**Comment by borrrden** [comment]
I talked to @pasin who is helping with things in my absence and he has stated that this happens only with .NET 7 but not with .NET 8 or Rider so a quick thing to try would be giving .NET 8 a shot (it went GA a few days ago).

**Comment by JeffHarms** [comment]
I'll do it today and let you know!!

Thanks.

**Comment by JeffHarms** [comment]
BINGO!  Upgrading to .Net8 did the trick!

Thanks SO much for your help.

Jeff
