### ISSUE TITLE
Changes to `Manager.ReplaceDatabase` and `CreateHttpClient`.

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#159]
Updated ManagerTest to use new Manager replaceDatabase method signature
https://github.com/couchbase/couchbase-lite-java-core/commit/51a3b71e375ac7f630ff29dea454a8f3baa41cd1

**Comment by borrrden** [comment]
These two implementations have drifted apart and many of these port fixes have been made.  It's difficult to confirm at this point whether or not they are 100%, so I'm closing these porting issues until they become a problem again.
