### ISSUE TITLE
Check for invalid file path in Database ctor

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#162]
Why does Database ever let this.name be null?
Issue: https://github.com/couchbase/couchbase-lite-java-core/issues/111
Commit: https://github.com/couchbase/couchbase-lite-java-core/commit/8147cba33019e8a26c34b671d92ab8c56e447aa2

**Comment by borrrden** [comment]
These two implementations have drifted apart and many of these port fixes have been made.  It's difficult to confirm at this point whether or not they are 100%, so I'm closing these porting issues until they become a problem again.
