### ISSUE TITLE
Port fix for issue #231 [Upstream issue is still open]

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#164]
Unexpected local checkpoint behavior
Issue: https://github.com/couchbase/couchbase-lite-java-core/issues/231
Commit: https://github.com/couchbase/couchbase-lite-java-core/commit/002e26342fb99991afa837e2900020472eb14923
Commit: https://github.com/couchbase/couchbase-lite-java-core/commit/ba7fb4c6507d9a3f3c75b764ec0a8930c94644bb

**Comment by borrrden** [comment]
These two implementations have drifted apart and many of these port fixes have been made.  It's difficult to confirm at this point whether or not they are 100%, so I'm closing these porting issues until they become a problem again.
