### ISSUE TITLE
Database.KNOWN_SPECIAL_KEYS should contain "_local_seq"

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#176]
Database.KNOWN_SPECIAL_KEYS should contain "_local_seq"
Issue: https://github.com/couchbase/couchbase-lite-java-core/issues/54
Commit: https://github.com/couchbase/couchbase-lite-java-core/commit/f59fa0b7e88c72f4e902278af1c72c0425beda82

**Comment by borrrden** [comment]
It looks like this was added as of https://github.com/couchbase/couchbase-lite-net/commit/ab53c43029619e206b9095b42c08df512083083e
