### ISSUE TITLE
Remove the HTTP/HTTPS URL restriction in Replication commands [Router]

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#179]
Please remove the HTTP/HTTPS URL restriction in Replication commands
Issue: https://github.com/couchbase/couchbase-lite-java-core/issues/42
Commit: https://github.com/couchbase/couchbase-lite-java-core/commit/dae6dd3740da7cdb32967ddc30bb18bbf0b59771

**Comment by borrrden** [comment]
These two implementations have drifted apart and many of these port fixes have been made.  It's difficult to confirm at this point whether or not they are 100%, so I'm closing these porting issues until they become a problem again.
