### ISSUE TITLE
ReplicationTest.TestGetReplication sometimes fails

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-net#18]
When `TestGetReplication` runs by itself, or with the other tests in `ReplicationTest` it always passes. However, when running all 87 tests it always fails. When it fails, it fails because it calls `replication.Stop()` but `replication.IsActive` returns true.

**Comment by borrrden** [comment]
This doesn't seem to be the case anymore.  Will re-open if I notice it again.
