### ISSUE TITLE
Database.Delete() should remove all files/folder that were created

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#180]
delete() database should remove all files/folder that were created
https://github.com/couchbase/couchbase-lite-java-core/commit/b5b74e9cd2f4edbecb112bbc47e2c44337e10a22

**Comment by borrrden** [comment]
These two implementations have drifted apart and many of these port fixes have been made.  It's difficult to confirm at this point whether or not they are 100%, so I'm closing these porting issues until they become a problem again.
