### ISSUE TITLE
Port Puller.ChangeTracker use POST requests when sync gateway version >= 0.93

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#181]
changes with doc ids as post request 
Issue: couchbase/couchbase-lite-android#137
Commit: https://github.com/couchbase/couchbase-lite-java-core/commit/4955faf6ca26f2f1d2b9c40bf9298b94b48ee058
Commit: https://github.com/couchbase/couchbase-lite-java-core/commit/afc746e6f3c352bad5a415ee2d0e00d427d09e86
Commit: https://github.com/couchbase/couchbase-lite-java-core/commit/0c7e80ceeb7cf874286dbd6a48efc46fc6fe955f

**Comment by borrrden** [comment]
This seems related to Issue #71
