### ISSUE TITLE
Port Synchronization on non-final variables in Replication

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#183]
Synchronization on non-final variable
Issue: https://github.com/couchbase/couchbase-lite-java-core/issues/128
Commit: https://github.com/couchbase/couchbase-lite-java-core/commit/febdc6cce37d0f1eea86d2722f17053319a55dad

**Comment by borrrden** [comment]
Not applicable.  There is a separate object for sync on .NET and it is already read only.
