### ISSUE TITLE
Refactor Replication.setChangesCount

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#184]
Please remove assert in Replication/setChangesCount
Issue: https://github.com/couchbase/couchbase-lite-java-core/issues/129
Commit: https://github.com/couchbase/couchbase-lite-java-core/commit/3b0563e855e66ac0603db400b65a4714ace900e8
Commit: https://github.com/couchbase/couchbase-lite-java-core/commit/79cd0bed26499fbf7a2ddeadb4c07b59e17b1c30

**Comment by borrrden** [comment]
These two implementations have drifted apart and many of these port fixes have been made.  It's difficult to confirm at this point whether or not they are 100%, so I'm closing these porting issues until they become a problem again.
