### ISSUE TITLE
Fix unit test for continuous pull replication

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#186]
Issue: https://github.com/couchbase/couchbase-lite-java-core/issues/243
Commit: https://github.com/couchbase/couchbase-lite-java-core/commit/2832d1bb71d2b26d23fa8ede1127d129ecd2db8f
Commit: https://github.com/couchbase/couchbase-lite-java-core/commit/96a87f8d0419133196b8e7e1e1b75f118e041e00

**Comment by borrrden** [comment]
These two implementations have drifted apart and many of these port fixes have been made.  It's difficult to confirm at this point whether or not they are 100%, so I'm closing these porting issues until they become a problem again.
