### ISSUE TITLE
After deleting a document, its currentRevision is not null

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#187]
After deleting a document, its currentRevision is not nil 
Issue: https://github.com/couchbase/couchbase-lite-java-core/issues/92
Commit: https://github.com/couchbase/couchbase-lite-java-core/commit/1b83c1191b0c73077f4801bd6ac1f589d1c9ff6f
** There are a lot more commits linked inside the issue (Need review).

**Comment by borrrden** [comment]
These two implementations have drifted apart and many of these port fixes have been made.  It's difficult to confirm at this point whether or not they are 100%, so I'm closing these porting issues until they become a problem again.
