### ISSUE TITLE
Deleted leaf revisions should not appear as conflicts

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#188]
This change fixes lower level unit test
Issue: https://github.com/couchbase/couchbase-lite-java-core/issues/106
Commit: https://github.com/couchbase/couchbase-lite-java-core/commit/4a86cea609663916542d47bd80c59b9c88dff4d8
Commit: https://github.com/couchbase/couchbase-lite-java-core/commit/cfa2b966b118fae13cea9e28418e6e6d6193f709
Commit: https://github.com/couchbase/couchbase-lite-android/commit/773dea31a7288f7570d71d7ffebebd44c8f1eef2

**Comment by borrrden** [comment]
These two implementations have drifted apart and many of these port fixes have been made.  It's difficult to confirm at this point whether or not they are 100%, so I'm closing these porting issues until they become a problem again.
