### ISSUE TITLE
DELETE failing because clearDbRef gets called twice

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#190]
DELETE failing because clearDbRef gets called twice
Issue: https://github.com/couchbase/couchbase-lite-java-core/issues/136
https://github.com/couchbase/couchbase-lite-java-core/commit/bfed99863fc8374e6559b138b5a4eb59a973845f

**Comment by borrrden** [comment]
These two implementations have drifted apart and many of these port fixes have been made.  It's difficult to confirm at this point whether or not they are 100%, so I'm closing these porting issues until they become a problem again.
