### ISSUE TITLE
LiveQuery of query for rows without sourceDocumentId does not update properly.

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#191]
LiveQuery of query for rows without sourcedocument does not update properly
Issue: https://github.com/couchbase/couchbase-lite-java-core/issues/29
https://github.com/couchbase/couchbase-lite-java-core/commit/06b51ba667af4c80d07749bf3047637c85c64fde

**Comment by borrrden** [comment]
This looks like it has been ported already
