### ISSUE TITLE
Replicator should treat some errors as transient, and retry later

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#195]
Replicator should treat some errors as transient, and retry later
https://github.com/couchbase/couchbase-lite-android/issues/247
https://github.com/couchbase/couchbase-lite-java-core/commit/6ec655dc4e283254d2092b7cfe26028cba25d6ec
https://github.com/couchbase/couchbase-lite-java-core/commit/63fb72621f2806c8b5cec3915eb29359df085e5c
https://github.com/couchbase/couchbase-lite-java-core/commit/471fd53f6c70f155527fd034a2ce023ee377e631

**Comment by borrrden** [comment]
These two implementations have drifted apart and many of these port fixes have been made. It's difficult to confirm at this point whether or not they are 100%, so I'm closing these porting issues until they become a problem again.
