### ISSUE TITLE
Further alignment to iOS's Database.PutRevision

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#197]
Further alignment to iOS imll
https://github.com/couchbase/couchbase-lite-java-core/commit/f420e359110c9329d9ebae0f1aca8a72f3667da6

**Comment by borrrden** [comment]
These two implementations have drifted apart and many of these port fixes have been made. It's difficult to confirm at this point whether or not they are 100%, so I'm closing these porting issues until they become a problem again.
