### ISSUE TITLE
Fixes issues with unit tests

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#200]
Fixes issues with unit tests
https://github.com/couchbase/couchbase-lite-java-core/commit/f9f8e4d56b0d4791c49f3a9bebd37d17bb65895c

**Comment by borrrden** [comment]
These two implementations have drifted apart and many of these port fixes have been made. It's difficult to confirm at this point whether or not they are 100%, so I'm closing these porting issues until they become a problem again.
