### ISSUE TITLE
Minor cleanup

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#201]
Minor cleanup
https://github.com/couchbase/couchbase-lite-java-core/commit/093e8dc8ff77d4e1779f8f9649d19dd6d82a4116

**Comment by borrrden** [comment]
These two implementations have drifted apart and many of these port fixes have been made. It's difficult to confirm at this point whether or not they are 100%, so I'm closing these porting issues until they become a problem again.
