### ISSUE TITLE
Delete fails due to non-existent Journal file

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#203]
Delete fails due to non-existent Journal file
https://github.com/couchbase/couchbase-lite-java-core/issues/134
https://github.com/couchbase/couchbase-lite-java-core/commit/9b7a3afd86190e806a1138a0ca73d3aa5c114ed2

**Comment by borrrden** [comment]
These two implementations have drifted apart and many of these port fixes have been made. It's difficult to confirm at this point whether or not they are 100%, so I'm closing these porting issues until they become a problem again.
