### ISSUE TITLE
Indexing optimization: don't load attachments when unnecessary

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#204]
Indexing optimization: don't load attachments when unnecessary
https://github.com/couchbase/couchbase-lite-java-core/issues/133
https://github.com/couchbase/couchbase-lite-java-core/commit/c9718f1f69b1ac9d9421d13003100345ab173e4b
https://github.com/couchbase/couchbase-lite-java-core/commit/b7bdefe67ab1b8f4c44dbab67564d90d6148343f

**Comment by borrrden** [comment]
These two implementations have drifted apart and many of these port fixes have been made. It's difficult to confirm at this point whether or not they are 100%, so I'm closing these porting issues until they become a problem again.
