### ISSUE TITLE
View results do not seem to handle conflicts correctly

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#205]
Fixes #131 by porting iOS changes. Unit test now passing.
https://github.com/couchbase/couchbase-lite-java-core/issues/131
https://github.com/couchbase/couchbase-lite-java-core/commit/a3a6e9aaced39a7150238eaa7e28bfc7fab2f19d

**Comment by borrrden** [comment]
These two implementations have drifted apart and many of these port fixes have been made. It's difficult to confirm at this point whether or not they are 100%, so I'm closing these porting issues until they become a problem again.
