### ISSUE TITLE
Ignore special doc fields like _id and _rev when loading cookies from persistent store

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#212]
Ignore special doc fields like _id and _rev
couchbase/couchbase-lite-android#269
https://github.com/couchbase/couchbase-lite-java-core/commit/7dd4ebeb97aef90ae364dfd158b24979f12539ee

**Comment by borrrden** [comment]
These two implementations have drifted apart and many of these port fixes have been made. It's difficult to confirm at this point whether or not they are 100%, so I'm closing these porting issues until they become a problem again.
