### ISSUE TITLE
Support _removed parameter for sync gateway channel removal

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#219]
Fixes #281 by porting changes from iOS
https://github.com/couchbase/couchbase-lite-android/issues/281
https://github.com/couchbase/couchbase-lite-java-core/commit/cc1e264a29c5881abef51ea2c9b4c59f120ba8e0

**Comment by borrrden** [comment]
These two implementations have drifted apart and many of these port fixes have been made. It's difficult to confirm at this point whether or not they are 100%, so I'm closing these porting issues until they become a problem again.
