### ISSUE TITLE
Port unnecessarily pushing attachments fix

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#223]
unnecessarily pushing attachments
couchbase/couchbase-lite-android#66
https://github.com/couchbase/couchbase-lite-java-core/commit/a50d99cc230026d8e2df932b14758dd9a0867a4f

**Comment by borrrden** [comment]
Verified via TestPushUpdatedDocWithoutReSendingAttachment (See Issue #332)
