### ISSUE TITLE
Remove log noise in BulkDownloader

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#227]
Remove log noise
https://github.com/couchbase/couchbase-lite-java-core/commit/56c422457bd10f45f2ade5c3777197806ba0b241

**Comment by borrrden** [comment]
These two implementations have drifted apart and many of these port fixes have been made. It's difficult to confirm at this point whether or not they are 100%, so I'm closing these porting issues until they become a problem again.
