### ISSUE TITLE
Better handling of UnsupportedType when uploading multipart

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#228]
Better handling of kCBLStatusUnsupportedType when uploading multipart
https://github.com/couchbase/couchbase-lite-java-core/issues/188
https://github.com/couchbase/couchbase-lite-java-core/commit/80adf561996396c97cd2154e7f78d142ca2ab5f2

**Comment by borrrden** [comment]
These two implementations have drifted apart and many of these port fixes have been made. It's difficult to confirm at this point whether or not they are 100%, so I'm closing these porting issues until they become a problem again.
