### ISSUE TITLE
Fixes a sporadic failure in TestLiveQueryStop

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#231]
testLiveQueryStop sporadic failure 
https://github.com/couchbase/couchbase-lite-android/issues/304
https://github.com/couchbase/couchbase-lite-java-core/commit/a0fdfd35c073a63983b37c072b5292692ba2241f

**Comment by borrrden** [comment]
These two implementations have drifted apart and many of these port fixes have been made. It's difficult to confirm at this point whether or not they are 100%, so I'm closing these porting issues until they become a problem again.
