### ISSUE TITLE
TestContinuousPusherWithAttachment fails against CouchDB

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-net#255]
@jonlipsky created this replication test, which fails for him when running against CouchDB, but passes when run against Sync Gateway.

**Comment by borrrden** [comment]
@jonlipsky This test passes for me using CouchDB 1.6.1.  Can you confirm the issue in 1.6.1?

**Comment by jonlipsky** [comment]
@borrrden That issue was fixed a while ago.  It now passes for me.

**Comment by borrrden** [comment]
Excellent.  I will close this issue then.
