### ISSUE TITLE
Not all new documents get queued for pushing to the server sometimes

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#319]
This happens when there are new documents created while the push replication is still not done starting. This can be tested by running ReplicationTest.TestPushNewDocuments a few times on the actual device. Normally there will be only 1 or 2 documents missing.

**Comment by borrrden** [comment]
@pasin I don't see the test you mentioned.  Did you mean TestPushManyNewDocuments?  I know this is old, so if you can't remember that's fine.

**Comment by pasin** [comment]
Yes, I actually mean 'TestPushManyNewDocuments'.

**Comment by zgramana** [comment]
Haven't seen this test fail ever,  and was fixed with other replication changes.
