### ISSUE TITLE
Intermittent deadlock during perf test 

### ISSUE THREAD

**Issue by lichenyang2** [couchbase/couchbase-lite-net#335]
This problem happens from time to time, usually in the heavy load testing that the system would freeze without any error or exception.

Pasin did a screen captured (see attached file) that shows the stack trace. At time of error, the test case running is Test03CreateDocsWithAttachments, iteration #16, creation of 10000 documents, each with 500 Bytes size. 

Similar problem also happens on replication test cases Test06PullReplication and Test07PushReplication.  Need to run it multiple times with the test device (iphone 5c) to reproduce the problem.

![deadlock](https://cloud.githubusercontent.com/assets/6787554/4672539/6638821c-5591-11e4-8390-294d0bf274a0.png)

**Comment by borrrden** [comment]
These locks have been eliminated in the issue-348 branch, so I don't think this will be a problem anymore.
