### ISSUE TITLE
Changes performed offline don't sync when going online.

### ISSUE THREAD

**Issue by gmanny** [couchbase/couchbase-lite-net#358]
When you cut off the internet and perform some changes to the DB, `SendAsyncRequest` in `Pusher.ProcessInbox` returns an error as expected, but when going online, none of those changes are ever synced back to the server (new ones do sync), unless the new Push replication is created and started.

From the code it seems that's the designed behavior because revisions are permanently removed from the `Batcher's` `inbox`. But the documentation [clearly states](http://developer.couchbase.com/mobile/develop/guides/couchbase-lite/):

> user can even modify data while offline, and it’ll be synced to the server as soon as possible.

Also, the replication doesn't ever go into `Offline` mode [described in the doc](http://developer.couchbase.com/mobile/develop/guides/couchbase-lite/native-api/replication/index.html#observing):

> Offline: The remote server is not reachable. Most often this happens because there's no network connection, but it can also occur if the server's inside an intranet or home network but the device isn't. (The replication will monitor the network state and will try to connect when the server becomes reachable.)

My question is, if and when it's planned for implementation? (Java lib also exhibits the same behavior.)

I may implement it for you, but would need some pointers to cut the time I'll spend reading the code.

**Comment by borrrden** [comment]
Possibly related:  The Android network connectivity manager does not work for me (thus GoOnline and GoOffline are not fired)

**Comment by zgramana** [comment]
Good news is that the previous issue in Xamarin.Android has been resolved, so we can remove the `#ifdef` lines in the reachability manager.
