### ISSUE TITLE
Support for Unity 3D

### ISSUE THREAD

**Issue by jessliu** [couchbase/couchbase-lite-net#360]
Specifically, 4.x (which is planned for continued maintenance till the end of 2014; depending on when the support is added, this may or may not still be relevant) and 5.

**Comment by zgramana** [comment]
Won't happen until Unity 5, with release of .NEt 4.5 support.

**Comment by borrrden** [comment]
Hilariously enough, Unity 5 did not change anything on this front (it may eventually but not with 5.0).  The only choice is to target .NET 3.5
