### ISSUE TITLE
Windows javascript app in troubles with '.NET Core' and '.NET Framework'

### ISSUE THREAD

**Issue by desarrollospyro** [couchbase/couchbase-lite-net#367]
Hi,

I have a cordova app developed in Javascript running on Windows 8.1. I want to use couchbase-lite in this app. I try to make a Windows Runtime Component to add couchbase-lite-net but it seems that my app and couchbase-lite-net are build in different platforms. Various messages appears when I try to use couchbase-lite-net. One of these message is:
"The project is for '.NET Core', but the file reference is to '.NET Framework'."

It seems that I need a couchbase-lite-net prepared for a Windows Store app. Because I want to upload my app to the Windows Store. So, is there any way to solve this issue?

Thanks in advance.

**Comment by borrrden** [comment]
We don't have support for Windows Store Applications yet, but it is on the roadmap.  There are still a number of issues that need to be dealt with before this can be possible.  The only .NET support right now is full .NET 4.5.

**Comment by zgramana** [comment]
You can follow our UAP/UWP conversation on https://github.com/couchbase/couchbase-lite-net/issues/535.
