### ISSUE TITLE
Xamarin Forms solution/project - unable to add Couchbase Lite 1.0.4.1 package

### ISSUE THREAD

**Issue by ltaljaard** [couchbase/couchbase-lite-net#371]
I'm creating a brand new Forms based solution in Xamarin Studio, and then trying to add the CBLite package to the Forms project. I've logged this with Xamarin thinking the problem might be on their end, but they have confirmed that the problem lies with the CBLite package: https://bugzilla.xamarin.com/show_bug.cgi?id=26263

This is the error that I get:

Adding 'Couchbase.Lite 1.0.4.1' to cblite_try1.
Could not install package 'Couchbase.Lite 1.0.4.1'. You are trying to install
this package into a project that targets
'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10',
but the package does not contain any assembly references or content files that
are compatible with that framework. For more information, contact the package
author.

Please advise. If this is not something that is supported right now, what kind of timelines are we talking about for you guys to enable it? Also, are there any workarounds for me in the mean time? I need to add Couchbase code to the PCL/shared Forms project, not to the iOS or Android projects directly (there are three projects created as part of any newly created Xamarin Forms-based Solution - the PCL/shared one, one for iOS and one for Android).

**Comment by zgramana** [comment]
It's not supported at this time, but will sometime in the 1st quarter.

As a workaround, I recommend using the Repository pattern. Put your interface in the PCL, and link the source file of the concrete implementation in your iOS and Android projects. For an example, see https://github.com/FireflyLogic/couchbase-connect-14.

**Comment by ltaljaard** [comment]
Thanks Zach. What is the easiest way to add the entire interface (all methods, properties etc) of CBLite into my PCL project please? I've been looking at the cb-connect-14 sample and it doesn't exactly jump out at me! In the end, I'd like to write code like this in my PCL project - would this be possible at all?

Using Couchbase.Lite;
Database Db;
...

**Comment by zippo227** [comment]
I was able to go to edit references in the shared project and manually add a reference to the .Net45 Couchbase.Lite.dll. The only thing extra I had to do was then direct add the JSON.Net(Newtonsoft) to my shared project. 

NOTE: This was after I successfully installed the Couchbase Lite packages to the iOS and Android projects.

**Comment by emendamus** [comment]
I've got a question concerning your setup. Is it valid to have a pcl that has a reference to couchbase(.net45) and the ios project has a reference to that pcl project and a reference to couchbase(iOS)? So what couchbase file will be in the final assembly?

**Comment by luzimar** [comment]
Worked for me, add the dll direct, in add reference, open archive in browser and add
