### ISSUE TITLE
Update CouchbaseConnect2014 to use iOS Unified API

### ISSUE THREAD

**Issue by ltaljaard** [couchbase/couchbase-lite-net#375]
Hello

When updating the Xamarin.Forms NuGet package in your demo CouchbaseConnect2014 solution (and specifically in the CouchbaseConnect2014.iOS project), I get the following error: "Could not install package 'Couchbase.Lite 1.0.4.1'. You are trying to install this package into a project that targets 'MonoTouch,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

I need to update to the latest Xamarin.Forms package as I need access to recently released Xamarin.Forms features.

PS: I have also tried adding the Couchbase Lite NuGet package to a new PCL based project, but apparently PCL is not supported as of yet ( couchbase/couchbase-lite-net#371 ). Hence, as an alternative, I'm trying to copy the CBConnect2014 demo app and just adapting it to my needs from there - but if I can't update to the latest Xamarin.Forms, this approach would be futile as well...

Please advise.

**Comment by zgramana** [comment]
You can work around this issue by converting the iOS project to target the new Unified API (I.e. Xamarin.iOS.dll).
