### ISSUE TITLE
Add HttpListener implementation

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-net#380]
Need to implement the HttpListener capabilities to support PhoneGap and peer-to-peer functionality in the .NET version.

Acceptance Criteria:
* Fully interoperable with listeners from CBL.iOS and CBL.Android.
* Works in all target platforms.
* Can handle multiple concurrent requests.
* (optional) OWIN-compliance

Notes:
* Dependency on https://github.com/couchbase/couchbase-lite-net/issues/83

**Comment by Steven-Mark-Ford** [comment]
@zgramana if I have 2 apps loaded on an android device is it possible to use the httplistener for the apps to talk to one another without a network connection or is this pure http/s?

**Comment by zgramana** [comment]
Yes, you should be able to do this via localhost. If you can't, it's a bug.

**Comment by Steven-Mark-Ford** [comment]
@zgramana Great! Where would I find the documentation specific to this, i.e. which article/s under http://developer.couchbase.com/mobile/develop...? I don't quiet understand how this would be achieved.
