### ISSUE TITLE
VS can not load sample

### ISSUE THREAD

**Issue by bholmes** [couchbase/couchbase-lite-net#406]
There is an issue with the project file 

https://github.com/couchbase/couchbase-lite-net/blob/85c966c5744982fd47a14c48b5c8fb0476d2ebb1/samples/SimpleAndroidSync/SimpleAndroidSync.csproj#L44-L46

There are some characters that are causing problems when loading SimpleAndroidSync in Visual Studio.  

@zgramana I have patched the sample on our server.  Can you follow up and verify this for the next release?

**Comment by zgramana** [comment]
@bholmes Yep. We'll be pushing a 1.1 release in a couple of weeks, so the fix will go out then if that works for you.

**Comment by bholmes** [comment]
That works fine for us.  Thanks!
