### ISSUE TITLE
Add migration support for iOS 1.1 SQLite db schema

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-net#409]

**Comment by pasin** [comment]
Please make sure that the database schema version is synced across platform.

Changes in iOS v1.1.0:

https://github.com/couchbase/couchbase-lite-ios/blob/release/1.1.0/Source/CBL_SQLiteStorage.m#L285-L291

https://github.com/couchbase/couchbase-lite-ios/blob/release/1.1.0/Source/CBL_SQLiteStorage.m#L365-L371
