### ISSUE TITLE
C# Threading bug(?)

### ISSUE THREAD

**Issue by lzbonz** [couchbase/couchbase-lite-net#416]
I think the library is supposed to be thread safe in c#? . I can't figure out how to build the raw and ugly stuff to investigate this further but heres the code that fails to work on occasion:
  
        var m = Manager.SharedInstance;

         var load = new byte[1024* 200];
         var db = m.GetDatabase("test");
         if (db.DocumentCount < 5)
         {
            Console.WriteLine("Seeding");
            for (int num = 0; num < 1000; num++)
            {
               var d = db.CreateDocument();
               Dictionary<string, object> prop = new Dictionary<string, object>(){
                    {"prop1", load   }                        
                    ,{"time", DateTime.Now}
               };
               d.PutProperties(prop);
            }
         }

         var q = db.CreateAllDocumentsQuery();
         q.Prefetch = false;
         var t = q.Run().Select(i => i.DocumentId).ToArray();
         
         var res = t.AsParallel().Select(
            n =>
            {
               return new
                  {
                     Prop = db.GetExistingDocument(n).UserProperties["time"]
                  };
            });
         Console.WriteLine("running");
         var final = res.ToArray();

It appears to fail around  here:
SqlitePclRawStorageEngine, line 632 : int err = raw.sqlite3_prepare_v2(db, sql, out command) (???) with index out of range exception

**Comment by borrrden** [comment]
Related to https://github.com/couchbase/couchbase-lite-net/pull/413

**Comment by borrrden** [comment]
@lzbonz Is this issue still happening with the latest master?

**Comment by zgramana** [comment]
@lzbonz please let us know if this re-appears.

**Comment by lzbonz** [comment]
Sorry Ive been on holiday. Im stopped using this due to the reliance on the sqlite ugly thing. I got the source code for it and its impossible to build - even the author says good luck. Using something I can't build and debug myself does not suit my project.

Anyway, I posted the code that results in the error if you care to use it for testing purposes.
