### ISSUE TITLE
Pull sync not working after upgrade from 1.04 to 1.1-pre2 in C# service

### ISSUE THREAD

**Issue by zebra1024** [couchbase/couchbase-lite-net#421]
I have a C# service which syncs from a CouchBase DB to a CouchBase Lite DB. The code was working using 1.04 of CBL and sync gateway. I upgraded to the build at https://groups.google.com/forum/#!topic/mobile-couchbase/GCC3KrGpkM8

I upgraded both sync gateway and the CBL libraries which I build from the source as part of my solution.

I start the sync and it looks like it is finding changes because the replication event is triggered with messages like this (my custom logging)

Pull Replication from [http://dev-ccsync-01:4984/sync_gateway] local DB:[compuclean] - Pending:[15963], Completed:[0]
 
But the completed count never goes up and the sqlite DB files never grows after the initial creation.

I see the following (possibly related) log messages.
Replication: *** BEGIN ProcessInbox (19 sequences) 
Thread Name: 6 
Date Time:   5/17/2015 3:29:32 AM 
Puller: Offline, so skipping inbox process 
Thread Name: 6 
Date Time:   5/17/2015 3:29:32 AM 
Replication: *** END ProcessInbox (lastSequence=0) 

I also log out the status of the pull sync (shown below) and the status is offline. 
SyncService.CouchbaseManager.CheckSync - couchbase - Last Sync Times: Pull:[5/17/2015 12:10:20 AM] Status[Offline] Continuous mode is [True] ([41.1697549] Seconds ago), Push:[5/17/2015 12:10:20 AM] Status[Offline] Continuous mode is [True] ([91.2330929] Seconds ago) 

I currently have 1 manager with 2 databases and neither is syncing.

I can send a link to the entire log file if you think it would be helpful.
The code is running on a Windows Server 2012 VM

**Comment by borrrden** [comment]
@zebra1024 Is that the correct URL?  http://dev-ccsync-01:4984/sync_gateway does not look like a valid URL to me.  Couchbase Lite tests URL availability by checking to see if it can open a connection to the URL provided in the puller (this is a new way of doing it) so if it cannot do that then the pull replication will not start.  

Can you open a connection to the sync gateway instance you have running via browser?

**Comment by zebra1024** [comment]
It is an internal URL to a server running sync gateway. Below is the results when I access through a browser (after authenticating using basic authentication)
{
  "committed_update_seq": 19101,
  "compact_running": false,
  "db_name": "sync_gateway",
  "disk_format_version": 0,
  "instance_start_time": 1431811910638080,
  "purge_seq": 0,
  "update_seq": 19101
}

This configuration works fine if I use the 1.04 version.

**Comment by borrrden** [comment]
Can you try using the IP address of the machine instead and let me know the result of that?  I changed some reachability logic in 1.1 so that it attempts to open an HTTP connection to the server to check if it is reachable before starting all the replication logic.  It might be that the logic is failing for some reason.  Also the entire log file would most likely be helpful, thanks!

**Comment by zebra1024** [comment]
I see plenty of logging in the sync gateway so I believe it is connecting properly.
The full logs are in a zip file at http://1drv.ms/1HnhThe

**Comment by borrrden** [comment]
Thanks for the logs.  I think I know exactly what is going on now.  It won't take long to fix!

**Comment by borrrden** [comment]
Give the latest release/1.1 commit a shot and let me know if it works.

**Comment by zebra1024** [comment]
Thanks @borrrden ,

This fixed the issue. It looks like the issue was related to my code using basic authentication with the sync gateway and a 401 being returned by the HTTP call in NetworkReachabilityManager.CanReach.

 Logging is shown below.
NetworkReachabilityManager: Didn't get successful connection to http://dev-ccsync-01:4984/sync_gateway 
NetworkReachabilityManager: Exception:  
System.Net.WebException: The remote server returned an error: (401) Unauthorized. 
at System.Net.HttpWebRequest.GetResponse() 
Couchbase.Lite.NetworkReachabilityManager.CanReach(String remoteUri) in \Couchbase.Lite.Shared\Manager\NetworkReachabilityManager.cs:line 49

**Comment by borrrden** [comment]
Yes, I often forget that C# makes those into exceptions.  Glad things are working for you.
