### ISSUE TITLE
CouchbaseSample.Android doesn't build with lastest Xamarin

### ISSUE THREAD

**Issue by kjeremy** [couchbase/couchbase-lite-net#429]
`Mono.Android.Support.v4` doesn't exist anymore.  The project needs the `Xamarin.Android.Support.v4` nuget package.

**Comment by borrrden** [comment]
I don't see anywhere that references that package.  Have you checked out the latest master?  I vaguely remember it used to exist, but I'm not terribly familiar with the Android specific stuff.

**Comment by zgramana** [comment]
@kjeremy did you get sorted out? I just rebuilt in master and it works fine.
