### ISSUE TITLE
[Listener] Internal server error when doing a GET with attachments

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-net#431]
I have a database on one device (A) that I am setting as a replication endpoint

```
var listener = new CouchbaseLiteTcpListener(MainActivity.DBManager, m_connectionInfo.Port) { ReadOnly = false };
listener.Start();
```

I am able to issue GET requests to this database via the endpoint and am able to see the various saved documents on A. However when I try to issue a pull replication from another device (B) to this endpoint, I get the below error.

```
06-18 14:35:00.178 I/mono-stdout(23043):     Got error InternalServerError
Replication
06-18 14:35:00.178 I/mono-stdout(23043): Replication
06-18 14:35:00.188 I/mono-stdout(23043):     Request was for: Method: GET, RequestUri: 'http://192.168.0.19:7938/syncpoint/8e447079-20be-4f60-b0da-02b0c2ea4dee?rev=1-125206c5f037bb7241d0193159f3d95c&revs=true&attachments=true', Version: 1.1, Content: <null>, Headers:
    Request was for: Method: GET, RequestUri: 'http://192.168.0.19:7938/syncpoint/8e447079-20be-4f60-b0da-02b0c2ea4dee?rev=1-125206c5f037bb7241d0193159f3d95c&revs=true&attachments=true', Version: 1.1, Content: <null>, Headers:
    {
    Accept: */*
    }
06-18 14:35:00.188 I/mono-stdout(23043):     {
06-18 14:35:00.188 I/mono-stdout(23043):     Accept: */*
06-18 14:35:00.188 I/mono-stdout(23043):     }
```

Manually issuing the request fails, however, if you change ...&attachments=false, it succeeds.

I am very new Couchbase to this so this may entirely be user error but decided to pass on the information.

My database only has one document with a couple of properties.
Requests and result:
```
http://192.168.0.19:7938/syncpoint
{"db_name":"syncpoint","doc_count":1,"update_seq":1,"committed_update_seq":1,"purge_seq":0,"disk_size":72600,"start_time":1434667480346000}
```
```
http://192.168.0.19:7938/syncpoint/_all_docs
{"rows":[{"key":"6c7a94e8-0672-4c6c-ad37-94f263668e57","value":{"rev":"1-955cb4fe6a50f92dbcc31168877903e0"},"id":"6c7a94e8-0672-4c6c-ad37-94f263668e57"}],"total_rows":1,"offset":0}
```
```
http://192.168.0.19:7938/syncpoint/6c7a94e8-0672-4c6c-ad37-94f263668e57
{"message":"Hello Couchbase Lite","created_at":"2015-06-18T22:44:44.1702090Z","_id":"6c7a94e8-0672-4c6c-ad37-94f263668e57","_rev":"1-955cb4fe6a50f92dbcc31168877903e0"}
```

Let me know if you need anymore information.

Thanks!

**Comment by SunilDhaker** [comment]
I am also having  the same issue along with some other issue . I posted  them as new issue #435 .

**Comment by borrrden** [comment]
Hey @sethrosetter thanks for the detailed report.  Are those logs and that error from the same session, because the ID doesn't match up between the two (the former is 8e447079-20be-4f60-b0da-02b0c2ea4dee and the latter is 6c7a94e8-0672-4c6c-ad37-94f263668e57)

I assume you just copied and pasted from two different runs since the first one crashed.  I've made some fixes and committed them.  I can see that the replicator will hit the URL you describe with no problem.  Could you try it out again with the latest commit to master?  Also if it happens again could you grab the log output from the listener as well as the client?  Thanks.

**Comment by sethrosetter** [comment]
@borrrden After building master and referencing built .dlls, I was able to to complete a successful push replication from one device to another. :smile: Thanks for the fixes! I'm still experiencing some issues when trying to create a pull replication from one device to another, but have not verified this being a problem with my code or the listener. I will keep you updated.

**Comment by borrrden** [comment]
@sethrosetter Have a look at issue #435 and see if it looks similar

**Comment by sethrosetter** [comment]
This has been resolved for me. Feel free to close.

**Comment by sethrosetter** [comment]
@borrrden for future reference, where can I find all the necessary information that would be useful for you in filing these issues (i. e. log locations for listener and client, version numbers, os information, etc).

**Comment by borrrden** [comment]
@sethrosetter The logs should be good enough.  Usually that information alone is enough for me to determine the OS information.  There are no version numbers except in the official builds.  All others are simply "Unofficial".  I was relying on MSBuildTasks to include the git commit hash but MSBuildTasks doesn't work with Mono 4.x so I might start exploring other ways to do that.

All of the logs are written to stdout (the console for desktop environments, the iOS log for iOS and logcat for Android).  Debug builds will log more than release builds and builds with the TRACE directive will log even more.
