### ISSUE TITLE
Enable SSL support in Listener

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-net#433]

**Comment by borrrden** [comment]
Every time I try to accomplish this I get stumped.  An automatically generated SSL certificate will never work on Windows without launching an external process or using platform specific native methods (requiring admin access).  The other platforms may or may not work depending on how good the Mono implementation is.  There is no pure .NET way to generate an x509 certificate from what I can tell so a third party library will be needed.

**Comment by borrrden** [comment]
It even turns out that the external processes that are needed to install a certificate into the store are not easy to find because even if they are there they are likely not in the system path.  I'll have to come back to this but it looks like Windows may need to have manual setup before the program is run.

**Comment by borrrden** [comment]
This needs to stay open.  So here is the issue:

HTTPS via HttpListener is hardcoded to use client certificates in Mono (https://bugzilla.xamarin.com/show_bug.cgi?id=21895)

However, the official way to use client certificates in HttpClient is not implemented in Mono yet (https://github.com/mono/mono/blob/3813ebc551efb505866ac1d2116753fd51da9e84/mcs/class/System.Net.Http.WebRequest/System.Net.Http.WebRequest/WebRequestHandler.cs#L83-L86) and has not been touched since its initial commit back in 2013.  

So short of recompiling and redistributing mono (kind of like we do with the TPL and Http backport) this issue is blocked.

**Comment by borrrden** [comment]
Update:  The websocket-sharp project looks very promising but it reveals the ultimate problem with mono at this stage.  Mono is very behind on its TLS support and currently only supports up to TLS 1.0.  After several hours I finally figured out that the nuget version of Mono.Security is interfering with TLS downgrades, but if that version is left out and replaced with the GAC version the downgrades are fine.  

Furthermore, websocket-sharp requires a few modifications to work as I intend it to:

1) The "Server" header is sent as websocket-sharp/1.0 if authentication fails (there is no way to intercept this)
2) Either Basic or Digest authentication must be specified, not both at once

I have been able to modify both of these and I plan to send a PR to the project owner soon.

**Comment by jamiltz** [comment]
Just tried this PR on Windows .NET 4.5 and it's working great. As mentioned above, Basic Auth must be enabled on the Listener at this time.

**Comment by borrrden** [comment]
What I meant by that was that either digest or basic can be selected but not both at once. I fixed that issue anyway and you are perfectly free to use no auth. Is having no auth an issue?

**Comment by jamiltz** [comment]
Yes, have to set a username/password on the listener (https://github.com/jamiltz/ListenerSSLExample/blob/master/ListenerSSLExample/Program.cs#L31).

Otherwise getting the following exception:

```
System.IO.IOException was unhandled by user code
  HResult=-2146232800
  Message=The handshake failed due to an unexpected packet format.
  Source=System
  StackTrace:
       at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
       at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
       at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
       at WebSocketSharp.Net.HttpConnection.FinishAuth(IAsyncResult result) in C:\Users\S401309\Developer\couchbase-lite-net\src\Couchbase.Lite.Shared\vendor\websocket-sharp\websocket-sharp\Net\HttpConnection.cs:line 172
       at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
       at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
       at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
       at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
       at System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
       at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
       at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
  InnerException: 
```

**Comment by borrrden** [comment]
I'll file a separate ticket for that

**Comment by borrrden** [comment]
Also make sure you are using https for your Uri and not http as in your program.cs file.

**Comment by jamiltz** [comment]
Ok will do thanks.

Another question, I've noticed that the listener will accept the P2P replication if AllowBasicAuth is passed in the Listener init. But since we're now passing AllowTLS, does this imply AllowBasicAuth is also set to true? Or can we pass both options in the init?

**Comment by borrrden** [comment]
These are flags, so you need to pass both (UseTLS | AllowBasicAuth).  Basic Auth is insecure by nature and so I wanted to make an explicit need to switch it on.  However, if you are using TLS, then the insecurity becomes no longer relevant so don't be afraid to turn it on.

**Comment by jamiltz** [comment]
Great thanks
