### ISSUE TITLE
Create a C# version of the integration test suite

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-net#437]

**Comment by borrrden** [comment]
@sethrosetter Is this what is considered the "Node.js tests" ?

**Comment by sethrosetter** [comment]
https://github.com/couchbaselabs/sync-gateway-tests

**Comment by borrrden** [comment]
What I'm getting at is:  is this ticket worth keeping open or will this end up all being robot tests.

**Comment by sethrosetter** [comment]
@borrrden I think this is being tracked elsewhere and has hard closing criteria. I would close it.
