### ISSUE TITLE
Can we add the REST API listener to this?

### ISSUE THREAD

**Issue by dbergan** [couchbase/couchbase-lite-net#443]
Please see the thread:

https://forums.couchbase.com/t/couchbase-lite-set-up-rest-listener-on-unity/4365

As soon as possible, please.

Kind regards,
David

**Comment by zgramana** [comment]
There will be 3 zips for Lite, Listener, and Bonjour.

**Comment by borrrden** [comment]
Ok I put it out https://github.com/couchbase/couchbase-lite-net/releases/unity_v1.0-beta3
