### ISSUE TITLE
Array order is ignored on QueryEnumerator and IDictionary<string,object>

### ISSUE THREAD

**Issue by reyalpsirc** [couchbase/couchbase-lite-net#447]
I have the following Document on my couchDB server:

	{
		[...]
		"starttime": [ 2015, 6, 14, 1, 10, 0],
		[...]
	}

Before updating my Couchbase to the current version on the repository, I had the following code that was getting the array values and converting them to `DateTime`:

	private DateTime ConvertToDate(string document_id, JArray dateArr){
		DateTime result=DateTime.MinValue;
		try{
			if (dateArr [0] == null || dateArr [1] == null || dateArr [2] == null || dateArr [3] == null || dateArr [4] == null || dateArr [5] == null)
				return result;
			int year = (int)dateArr [0];
			int month = Clamp((int)dateArr [1],1,12);
			int day = Clamp((int)dateArr [2],1,31);
			int hour = Clamp((int)dateArr [3],0,23);
			int minute = Clamp((int)dateArr [4],0,59);
			int second = Clamp((int)dateArr [5],0,59);
			result = new DateTime (year, month, day, hour, minute, second);
		} catch (Exception ex){
			Debug.WriteLine ("Date error on \""+document_id+"\": " + dateArr.ToString ());
		}
		return result;
	}

This was working nice until the update based on the current repo because currently, instead of getting the array in the same order that it is on couchdb server, I get it in this order:

	{
		[...]
		"starttime": [ 0, 1, 6, 10, 14, 2015],
		[...]
	}

And of course, it is crashing on my `ConvertToDate` function.
Is there a way to keep the order of the arrays?

**Comment by borrrden** [comment]
Hm this is certainly no good.   It seems like a sorting method somewhere is getting a little overzealous since I was easily able to write a short test method to reproduce this.  Expect a fix shortly.

**Comment by borrrden** [comment]
Well that took me all of one minute to find.  Things should be set now.
