### ISSUE TITLE
QueryEnumerator should be an ObservableCollection

### ISSUE THREAD

**Issue by jchris** [couchbase/couchbase-lite-net#452]
If we did this, then we'd be able to map a LiveQuery into the data inputs of Xamarin Forms List Views without even having to set an event listener.

**Comment by borrrden** [comment]
The problem with this is that on ForestDB this is not a collection, but a generator function which only holds one element at a time and it would be more efficient to have SQLite be this way as well.  So actually this functionality is useful but it should be on a different class.  This will probably be a good candidate for 2.0.  I'll keep it here to remind myself.

**Comment by djpongh** [comment]
Won't be getting to this.
