### ISSUE TITLE
Listner is not working inside windows service 

### ISSUE THREAD

**Issue by SunilDhaker** [couchbase/couchbase-lite-net#453]
When I try to run CouchbaseLiteTcpListener inside a windows service it give  "Service Unavailable
HTTP Error 503. The service is unavailable." . On requesting  ip:port/db_name/  from browser

I already ran urlacl command . And the same code is working fine in WPF app. 
Does HttpListner is not supported in service or am I missing something ?

**Comment by borrrden** [comment]
I've never tried running it inside of a service, but a 503 error wouldn't be coming from inside of the Couchbase Lite code.  It is likely a configuration issue (i.e. is the service started?  Does it have appropriate permissions, etc?).

**Comment by zgramana** [comment]
@SunilDhaker, can you please paste the exact command you used to install it as a service?

**Comment by SunilDhaker** [comment]
When I tried installing it with installutils i.e ( installutil SyncService.exe ) it didn't work however installing programatically with [this](https://dl.dropboxusercontent.com/u/152585/ServiceInstaller.cs) code snippets worked for me .

While I was installing service  with installutil it was installed/running "SYSTEM" as user but the url reservation were done for current user (i.e. "sdhaker" in my case) . So this thing may be creating the issue

**Comment by SunilDhaker** [comment]
As it has nothing to do with couchbase so closing the issue
