### ISSUE TITLE
Pull Replication with DocIds is returning all documents

### ISSUE THREAD

**Issue by reyalpsirc** [couchbase/couchbase-lite-net#455]
When I make a Pull Replication with specific `DocIds`, I'm getting all the documents on the remote CouchDB server instead of getting only the ones with the ids that I specified. Is this normal behaviour? If so, can someone explain to me when `DocIds` is used?

This is the code I'm using:

	pullReplication = _db.CreatePullReplication (server);
	pullReplication.Continuous = true;
	pullReplication.DocIds = new List<string> (){ "myid1", "myid2" };
	pullReplication.Start();

**Comment by borrrden** [comment]
Aright so this issue is a little unfamiliar for me, but it seems like there is support for this option on the puller, but it was disabled at some point.  Sync Gateway does not implement this API so again I will need to talk internally about whether or not to include this into master (although I don't think it will be a problem).  We are in the middle of something important at the moment so the dicussion will be postponed.  I pushed the change I made into `issue/455`

**Comment by reyalpsirc** [comment]
Nice, that fix works fine to me :).
Please let me know if this will be merged on main or not.

**Comment by reyalpsirc** [comment]
@borrrden this works fine but it has a little problem. If you want a normal replication that does not use docIds, you need to pass `replication.DocIds = new List<string> ();` in order to make it work. Not doing so results in the following:

	Replication: Error
	    System.ArgumentNullException: Argument cannot be null.
	    Parameter name: source
	        at System.Linq.Check.Source (System.Object source) [0x00006] in <filename unknown>:0 
	        at System.Linq.Enumerable.ToList[String] (IEnumerable`1 source) [0x00000] in <filename unknown>:0 
	        at Couchbase.Lite.Replicator.Puller.BeginReplicating () [0x00148] in <filename unknown>:0 
	        at Couchbase.Lite.Replication+<FetchRemoteCheckpointDoc>c__AnonStorey3.<>m__0 (System.Object response, System.Exception e) [0x0014a] in <filename unknown>:0 

So my guess is that there's a need in the code to put that as default value ;)

**Comment by borrrden** [comment]
Thanks, I corrected that issue.

**Comment by borrrden** [comment]
@reyalpsirc This has been merged into master

**Comment by reyalpsirc** [comment]
Thanks =)
