### ISSUE TITLE
Two LiveQueries over one view cause duplication of new rows

### ISSUE THREAD

**Issue by Shaddix** [couchbase/couchbase-lite-net#457]
I create a view and in some point of my application I need to create two LiveQueries to it (with different Key filter).
Then when I add documents to database, in each query.Changed handler I receive that documents as 2 completely identical rows (Id's are the same).
If I have only one LiveQuery everything works correct and documents are not duplicated.

These duplication persists over application restarts (even if I run normal Query against that view). But if I change Version field of the view and DB gets reindexed, there's no duplication (as expected, because there's only one doc in DB).

Is that a known problem? I could provide a small repro if needed, but just want to be sure it's not a known issue and it's not by design.

In pseudo-code:

```
var view = _database.GetView("dummy")
_database.SetMap((props, emit) => emit(props["Type"], null), "1");
var query1 = view.CreateQuery().ToLiveQuery();
query1.Start();
var query2 = view.CreateQuery().ToLiveQuery();
query2.Start();

...

var doc = _database.CreateDocument();
doc.PutProperties(new Dictionary<string, object>() {
 {"Type", "Project"},
});


```

after that in Changed event handler I receive duplicated rows.

I use latest Couchbase Lite package from nuget (1.1.0.1)

**Comment by borrrden** [comment]
Yes, this is known and was corrected.  More information [here](https://github.com/couchbase/couchbase-lite-net/issues/430) (it doesn't explicitly state this, but this is the reason that I had to make changed to UpdateIndex)

**Comment by borrrden** [comment]
In the master branch, [this unit test](https://github.com/couchbase/couchbase-lite-net/blob/e0b8719240ac9007e931cc3f6c1646547b68a760/src/Couchbase.Lite.Tests.Shared/ViewsTest.cs#L1456-L1499) is now in place to check for this condition.
