### ISSUE TITLE
External DELETE of document does not get replicated

### ISSUE THREAD

**Issue by reyalpsirc** [couchbase/couchbase-lite-net#461]
I'm using CouchDB and once I do a DELETE of a document, the CouchBase Lite .Net Api does not get any information on the replication.
Even if I start my app again, I still have the deleted record on the app while it is clearly deleted on the CouchDB server. At least, I should have a flag of "_deleted:true" but if I debug the record, I get all the data of the deleted record without that flag there.

Is this normal behavior of the API? If so, how can I track if a document has been removed externally to the app side?

**Comment by borrrden** [comment]
Hmmm, good question.  I'm not quite sure how CouchDB propagates deletions.  In theory it should be the way you describe.  I'll have a look at some point today.

**Comment by reyalpsirc** [comment]
Thanks. I though it was automatically but, after clearing the logs just before deleting the document, I saw that they remained empty after the deletion.

**Comment by borrrden** [comment]
Alright, I tried this real quick and I am seeing that the correct behavior is getting executed.  So could you tell me what behavior you expect vs what behavior is happening in more detail?

**Comment by reyalpsirc** [comment]
Well, the event on my pull replication is not getting called once I delete a record on CouchDB to me (I have a Debug.WriteLine there and it works for other cases).

**Comment by borrrden** [comment]
The scenario you described is working fine for me:

```c#
var pull = _db.CreatePullReplication(new Uri(_url));
pull.Continuous = true;
pull.Changed += (sender, e) => {
    Console.WriteLine("{0}: {1}/{2}", pull.Status, pull.ChangesCount, pull.CompletedChangesCount);
};
 pull.Start();
```

When I add a document via Futon I get the callback, as well as if I delete it.

**Comment by reyalpsirc** [comment]
Hmm, that's weird. This is the code I have about the replications when I tested that:

	Replication userDataRepPull = _db.CreatePullReplication (server);
	userDataRepPull.SetCookie (c.Name, c.Value, c.Path, c.Expires, c.Secure, c.HttpOnly);
	userDataRepPull.Continuous = true;
	userDataRepPull.Changed+= (object sender, ReplicationChangeEventArgs e) => {
		Debug.WriteLine("Pulled doc");
	};
	userDataRepPull.Filter = "studio/main_replication";
	userDataRepPull.FilterParams = new Dictionary<string, object> { { "name", "my_usermae"}};
	userDataRepPull.Start ();

	Replication userDataRepPush = _db.CreatePushReplication (server);
	userDataRepPush.SetCookie (c.Name, c.Value, c.Path, c.Expires, c.Secure, c.HttpOnly);
	userDataRepPush.Continuous = true;
	userDataRepPush.Changed+= (object sender, ReplicationChangeEventArgs e) => {
		Debug.WriteLine("Pushed doc");
	};
	userDataRepPush.Start ();

Might the SetCookie be related to it? Or maybe the filter?

**Comment by borrrden** [comment]
Perhaps the filter.  As an experiment try doing it without those two things and see if it work, and then methodically adding them back.

**Comment by reyalpsirc** [comment]
Sorry for the delay. I made the test by removing the filter and it worked. So this means that the deletes are just not being sent to replications when filters are involved.

This is the filter I have:

    function(doc,req) {
        if (doc.type=="event" || (doc.name==req.query.name && doc.type=="user")){
            return true;
        }
    }

Is there anything else that I need to do in order to get the deletes to be received by the replication when using a filter?

**Comment by borrrden** [comment]
I found a note about this on the [CouchDB wiki](https://wiki.apache.org/couchdb/Replication).  This is actually different from Sync Gateway so I wasn't aware of it.  This should solve your problem

>Note: When using filtered replication you should not use the DELETE method to remove documents, but instead use PUT and add a _deleted:true field to the document, preserving the fields required for the filter. Your Document Update Handler should make sure these fields are always present. This will ensure that the filter will propagate deletions properly.

**Comment by reyalpsirc** [comment]
Hmm, interesting. That means that when I delete test documents through Futon, those deletions are not replicated to the devices that might already have them.
How is this handled on Sync Gateway? Are they propagated also when we use DELETE instead of PUT? For this project I can't switch but, for later projects I'm interested on using Sync Gateway (as long as it allows REST calls too for some searches that do not need replication of documents on device side).

**Comment by borrrden** [comment]
Sync Gateway is more of a middleman between the local device and Couchbase Server.  It doesn't normally store any data itself, but instead brokers it between Couchbase Lite and Couchbase Server.  Thus, it doesn't have the concept of arbitrary server side filters and is not affected by this problem.  CouchDB, as you saw, will also replicate deletions.  The problem is that it removes all properties first, so your filter sees it as a non-replication document.  That is the purpose of the note I showed you.  If you do a PUT instead, then it will save the properties while also flagging it as a deletion (via the `_deleted` property)

If you are curious about Sync Gateway and have questions then I suggest that you check out our [Sync Gateway Forum](https://forums.couchbase.com/c/mobile/sync-gateway)

**Comment by reyalpsirc** [comment]
I will close this then since it is related to CouchDB itself
