### ISSUE TITLE
Expose CBLView.totalRows to public

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#465]
Accessing CBLView.totalRows property will return the number of rows or documents associated with the view. The view's index will be updated to reflect current status of the database prior getting and returning the property value.

iOS Issue:
https://github.com/couchbase/couchbase-lite-ios/issues/808
iOS Commits:
https://github.com/couchbase/couchbase-lite-ios/commit/a574c15b2184cd1f51cf1c51e58c4fd42fdd3f06
https://github.com/couchbase/couchbase-lite-ios/commit/bae82585a3a68e7a7186a083a2e0fa6834f0c636

**Comment by borrrden** [comment]
This property is already public, closing.
