### ISSUE TITLE
Router should support "?stale=" parameter on view query requests

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#468]
I have added this parity ticket to java but not .NET. I'm not sure if this has already been implemented on .NET or not but it's better to verify.

iOS Issue: https://github.com/couchbase/couchbase-lite-ios/issues/584
Commit: https://github.com/couchbase/couchbase-lite-ios/commit/36b7fd6314fa39755ad148d9fb216e5d2e85f4ca

**Comment by borrrden** [comment]
This has already made it in, thanks !
