### ISSUE TITLE
1.1.1 testing

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-net#475]

**Comment by borrrden** [comment]
-[X] .NET 4.5 OS X
-[ ] .NET 4.5 Windows
-[ ] .NET 4.5 Linux
-[X] .NET 3.5 OS X
-[ ] .NET 3.5 Windows
-[ ] .NET 3.5 Linux
-[ ] iOS
-[ ] Android

**Comment by borrrden** [comment]
The issues remaining on Linux are few and possibly related to the way the unit tests are set up and not the library itself.  Also I am not aware of anyone who is even using it on Linux (if you are, speak up!) so I'm not going to delay the release on the account of the remaining Linux issues.
