### ISSUE TITLE
Replicate attachment with IChallengeResponseAuthenticator

### ISSUE THREAD

**Issue by v3yr0n** [couchbase/couchbase-lite-net#477]
Hi!
I've created a oauth authenticator class for couchdb that implements IChallengeResponseAuthenticator. It worked well for documents without attachments but with attachments I get an "you are not authorized to access this db" message and the document and attachments are not replicated. I've downloaded the couchbase.lite project and searched for the problem.
I think the problem is related with the lack of this code on the SendAsyncMultipartRequest method, on the Replication.cs class.
```
    var challengeResponseAuth = Authenticator as IChallengeResponseAuthenticator;
    if (challengeResponseAuth != null) {
       var authHandler = clientFactory.Handler as DefaultAuthHandler;
            if (authHandler != null) {
                 authHandler.Authenticator = challengeResponseAuth;
            }
            challengeResponseAuth.PrepareWithRequest(message);
    }
```
I've tested and it works fine now. 

Please let me know if you can fix this on the next couchbase.lite release.

Thanks!

**Comment by borrrden** [comment]
Nice catch, this will go in very soon.

**Comment by v3yr0n** [comment]
Cool! thanks!

**Comment by v3yr0n** [comment]
Does anyone knows when this will be done? :)

**Comment by borrrden** [comment]
This is on the schedule for this week

**Comment by v3yr0n** [comment]
OK, thanks!

**Comment by borrrden** [comment]
I've put this into the release/1.1.1 branch.  It will be merged into master after the prerelease package goes up onto Nuget.
