### ISSUE TITLE
[Unity Demo] _bulk_get deadlocks on Unity.iOS

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-net#481]

**Comment by borrrden** [comment]
Turns out it's not just `_bulk_get` but also `_changes` sometimes too.  It's hard to say why this problem happens because it only happens about 50% of the time and only on iOS.

**Comment by borrrden** [comment]
Looks like another IL2CPP problem, most likely.  Filed a bug report with Unity (Case 718885).

**Comment by borrrden** [comment]
Just got an email this morning indicating a fix to 718885 has been written and should land in either next week's patch release or the following.  I will keep an eye on the patch release notes.

**Comment by borrrden** [comment]
Confirmed that the fix will land in 5.2.2p3 (two weeks from now)
