### ISSUE TITLE
NuGet Package For .NET 3.5

### ISSUE THREAD

**Issue by jeremyswitzer** [couchbase/couchbase-lite-net#482]
I thought .NET 3.5 support was supposed to be available in the 1.1 release, but it doesn't appear to have been added as a supported framework in the latest `Couchbase.Lite` NuGet package. Was this left out intentionally? I'd be happy to update the packaging script and create a pull request if it was just an oversight.

**Comment by borrrden** [comment]
It's not in the nuget package (I forget why, but I do vaguely remember there being a reason) but it's compilable.  @zgramana Is there a reason we didn't put this in or am I remembering wrong?

**Comment by zgramana** [comment]
I believe we were just waiting to see how Unity GA shook out.

**Comment by borrrden** [comment]
Hmmmm, well since there is interest I guess I'll see what it will take to make a nuget spec for it.  Keep in mind it is going to include quite a few prebuilt DLLs that don't come from nuget.

**Comment by jeremyswitzer** [comment]
To be honest, all I really need is .NET 4.0 support. Since SqlitePCL now has 4.0 support in their package, it doesn't look like there will be that much difference in the code except for the dependency frameworks. Probably the easier of the two options if you ask me.

I was planning on pulling down the code anyway to see if it will work, so I can go ahead and fork/PR if you guys want. Any particular branch I should work off of?

**Comment by borrrden** [comment]
.NET 4.0 is a bit of an oddity because it has the TPL, so the backport is not strictly needed, but I think we use some features that are 4.5 only in our 4.5 project so those may possibly be needed.  You are welcome to take a look and see though.  I'm a bit busy at the moment creating the 1.1.1 release but after that I can look at it again.

**Comment by zgramana** [comment]
If you go look you might find the old 4.0 csproj in the history somewhere. It will give you a starting point.

**Comment by borrrden** [comment]
Well at any rate I've release a Nuget package for .NET 3.5 so I'm going to close this ticket
