### ISSUE TITLE
Delete document only on device database

### ISSUE THREAD

**Issue by v3yr0n** [couchbase/couchbase-lite-net#483]
Hi!

How can I delete a document only on the device database?
I have pull/push replications active...
From what I can see the Database.DeleteLocalDocument only deletes documents created locally. If I delete the document (via document.delete()) it replicates that deletion. But I don't what that... 
Basically what I need is drop some documents when I don't need them anymore.

Any help? :)

Thanks!

**Comment by borrrden** [comment]
See https://forums.couchbase.com/t/deleting-documents-locally-while-keeping-them-in-server/4253/2

**Comment by v3yr0n** [comment]
OK, I think document.Purge() solves the problem :)

Thanks!
