### ISSUE TITLE
Replication deadlocking on Linux

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-net#486]
Both x86 ad x64.  Reason still unclear.  Especially on TestPullerChangedEvent.

**Comment by borrrden** [comment]
Update:  This doesn't look like a deadlock.  Something else is likely going on.  A call to `SendAsync` appears to be simply getting lost.  Right around the same time, it appears that a GC is happening.  I wonder if the native calls to socket, etc are being interfered with since mono uses a "power failure" signal and "too much cpu usage" signal to halt and restart threads during a GC.  Or perhaps the request objects are being prematurely GC'd?  I noticed `HttpClient` only keeps around the latest one it received.

**Comment by borrrden** [comment]
Filed a bug report with Xamarin:  https://bugzilla.xamarin.com/show_bug.cgi?id=33286

**Comment by zgramana** [comment]
Known issue in 1.1.1.

**Comment by borrrden** [comment]
FWIW, this issue seems to have gone away at least mostly with the beta Mono 4.2 release (at least I think it is beta, since on Linux it is not divided into channels but 4.2 is not yet in the stable channel update on OS X)

**Comment by borrrden** [comment]
4.2 has been released into stable, and I haven't seen this issue since.  Probably going to close this in the near future.
