### ISSUE TITLE
Unable to replicate using Facebook authenticator

### ISSUE THREAD

**Issue by pham0167** [couchbase/couchbase-lite-net#489]
When I try to replicate using the Facebook authenticator, the user and session gets created correctly in Sync Gateway, but I am unable to login.  Subsequent attempts to replicate after the user and session have been created also fails with a 401 Login Required.

Note that replicating with basic authenticator works correctly.

Client is Xamarin iOS app running Couchbase Lite version 1.1.0.1
Couchbase Server Community Edition 3.0.1 running on a Windows machine with firewalls turned off.
Sync Gateway version 1.1.0

Here's the sync console output:
HTTP:  #002: GET /sync_gateway/_session
HTTP:  #003: POST /sync_gateway/_facebook
go-couchbase: call to ViewCustom("sync_gateway", "access") in github.com/couchbase/sync_gateway/db.(*DatabaseContext).ComputeChann
elsForPrincipal took 473ms
HTTP:  #004: GET /sync_gateway/_local/82b5437a4586262d94a5866682aec15ad0f63d23
HTTP: #004:     --> 401 Login required  (1.0 ms)

**Comment by borrrden** [comment]
Alright, sorry this took so long to respond to!  I got sucked into another issue for an extraordinarily long time.  I will set up a test to try to reproduce this, though I doubt it will take much.  I'll let you know more soon.

**Comment by borrrden** [comment]
Update:  Looks like the cookie saving mechanism needs some attention.  I should have a fix out tomorrow.

**Comment by borrrden** [comment]
@pham0167 Check out the `issue/498` branch.  I replicated the issue and corrected it so let me know if this solves your problem.

**Comment by pham0167** [comment]
@borrrden Will this fix be available in a release on NuGet soon?  I'm currently consuming this in a Xamarin mobile project as a nuget package.

**Comment by borrrden** [comment]
@pham0167 It is not likely that we will make another Nuget release for a while.  It's possible that we may start using another distribution system to release nightly, or at least periodical builds but that is still under discussion.  Does this mean that the branch in question has solved your problem?
