### ISSUE TITLE
Views lost after complete recreation of database

### ISSUE THREAD

**Issue by reyalpsirc** [couchbase/couchbase-lite-net#490]
My App has a login and logout functionality that needs to destroy the database completely when an user logs out. I'm using this code to accomplish that:

	db.Manager.ForgetDatabase(db);
	db.Delete ();
	db = Manager.SharedInstance.GetDatabase (db_name);

The problem is that when I do a login and logout action multiple times a bit fast, I see errors on the log like this:

	View 'userEvents' not found in database.

Worth mention that my database also has 2 replications running (one for pull with filter and another for push).
I tried to use the `GetView` only for creating the views after the logout (and then use the `GetExistingView` when I want to make a query on it) but the error still happens. What's wrong?

**Comment by borrrden** [comment]
Try to avoid posting question style things here, if you have a question head over to the forums.  If you have a reproducible issue please update this ticket with it.

**Comment by reyalpsirc** [comment]
Ah sorry, I made the description as question but the thing is that this seems intermittent.
I can give the example of how I have the calls to my views:

	var the_view = _db.GetView ("userEvents");
	the_view.SetMap (delegate(IDictionary<string, object> document, EmitDelegate emit) {
		try {
			if (document.ContainsKey ("type") && document ["type"].ToString () == "event" && document.ContainsKey ("starttime") && document.ContainsKey ("endtime")) {
				emit (null, document);
			}
		} catch (Exception ex) {
			Debug.WriteLine (ex);
		}
	}, "0.1.6");
	var query = the_view.CreateQuery ();

So, correct me if I'm wrong but, if I delete the database and recreate it, I should not get errors like this:

	View 'userEvents' not found in database.

That's why I reported as an issue.
Unless that error is related to the destroyed Database, it is a bug right?

I can probably make a simple code for this with a while loop that contains the replication, the view call and the recreation of the DB but I will only be able to do that later.

**Comment by borrrden** [comment]
Can you be sure that you are not trying to call GetExistingView on _db after you delete and recreate it, but before you add the view?  That seems like the most likely scenario.

**Comment by reyalpsirc** [comment]
I'm sure for 2 reasons:

1. The code I had to access the views was always using the GetView.
2. I changed the code to try to bypass that error and I put all the GetView's in a CreateViews function and put that call immediately after the code that recreates the DB.

**Comment by reyalpsirc** [comment]
Ok, one thing I forgot to mention is that my `userEvents` view works with a Live Query.
Based on that, I tried to setup an example test to show the problem to you but, I currently facing another one related to this:

    [SQLiteLog] (21) API called with NULL prepared statement
    [SQLiteLog] (21) misuse at line 63243 of [00bb9c9ce4]
    SqlitePCLRawStorageEngine: Error executing raw query 'SELECT key, value, docid, revs.sequence FROM 'maps_0', revs, docs WHERE 1    AND revs.sequence = 'maps_0'.sequence AND docs.doc_id = revs.doc_id ORDER BY key, docid LIMIT ? OFFSET ?'
        21: 
        SQLitePCL.Ugly.ugly+sqlite3_exception: Exception of type 'SQLitePCL.Ugly.ugly+sqlite3_exception' was thrown.
            at SQLitePCL.Ugly.ugly.step (SQLitePCL.sqlite3_stmt stmt) [0x00017] in <filename unknown>:0 
            at Couchbase.Lite.Cursor..ctor (SQLitePCL.sqlite3_stmt stmt) [0x0001d] in <filename unknown>:0 
            at Couchbase.Lite.SqlitePCLRawStorageEngine+<IntransactionRawQuery>c__AnonStorey2.<>m__0 () [0x0005f] in <filename unknown>:0 
    SqliteCouchStore: Exception in RunInTransaction
        21: 
        SQLitePCL.Ugly.ugly+sqlite3_exception: Exception of type 'SQLitePCL.Ugly.ugly+sqlite3_exception' was thrown.
            at SQLitePCL.Ugly.ugly.step (SQLitePCL.sqlite3_stmt stmt) [0x00017] in <filename unknown>:0 
            at Couchbase.Lite.Cursor..ctor (SQLitePCL.sqlite3_stmt stmt) [0x0001d] in <filename unknown>:0 
            at Couchbase.Lite.SqlitePCLRawStorageEngine+<IntransactionRawQuery>c__AnonStorey2.<>m__0 () [0x0005f] in <filename unknown>:0 

This is the gist that can replicate the issue (on the logs that it generates): https://gist.github.com/reyalpsirc/56bf565412bb462aba61

I'm not sure if this is an issue or not and that's why I wrote here before creating any other issue (since I was trying to show the main description of this issue when I found that one).

**Comment by reyalpsirc** [comment]
Any news about this?

**Comment by borrrden** [comment]
This has been tagged with 1.2 so it got added to the backlog while I finished 1.1.1 issues and also we just finished our conference in Tokyo so I haven't had the time to get to this one yet but I should this week for sure.

**Comment by borrrden** [comment]
@reyalpsirc I've put some work on this into `issue/490`.  I was getting the second error you mentioned before but now I get neither that nor the original issue.  However, I recommend that you stop calling `Manager.ForgetDatabase` directly.  I am going to recommend that this method be made internal, as I don't think there is any benefit for the user calling it (only problems).

**Comment by reyalpsirc** [comment]
Yes, this seems solved now with that work. Thanks :+1:
