### ISSUE TITLE
Problem with view

### ISSUE THREAD

**Issue by v3yr0n** [couchbase/couchbase-lite-net#491]
Hi!

I'm having some problem with a view. I get this exception:
````
Database: Exception in RunInTransaction
     
 System.NullReferenceException: Object reference not set to an instance of an object
 
     
   at Couchbase.Lite.Internal.UpdateJob.Wait () [0x00001] in <filename unknown>:0 
 
     
   at Couchbase.Lite.View.UpdateIndex () [0x00061] in <filename unknown>:0 
 
     
   at Couchbase.Lite.Database.QueryViewNamed (System.String viewName, Couchbase.Lite.QueryOptions options, Int64 ifChangedSince, Couchbase.Lite.Util.ValueTypePtr`1 outLastSequence, Couchbase.Lite.Status outStatus) [0x00077] in <filename unknown>:0 
 
     
   at Couchbase.Lite.Query+<Run>c__AnonStorey2.<>m__0 () [0x0000d] in <filename unknown>:0 
 
     
   at Couchbase.Lite.Database+<RunInTransaction>c__AnonStorey0.<>m__0 () [0x00000] in <filename unknown>:0 
 
     
   at Couchbase.Lite.Database.RunInTransaction (System.Func`1 block) [0x00027] in <filename unknown>:0 
 
 SqlitePCLRawStorageEngine: RawQuery sql: SELECT revid, deleted, json FROM revs WHERE sequence=? (120)
 Database:     CANCEL transaction (level 1)
 SqlitePCLRawStorageEngine: RawQuery sql: SELECT revid, deleted, json FROM revs WHERE sequence=? (86)
 SingleTaskThreadpoolScheduler
     
Task 13 faulted System.AggregateException: One or more errors occurred. ---> Couchbase.Lite.CouchbaseLiteException: Failed to query view named all-messages

`````
I've tried updating the view version and I get the same problem. 

The weird thing is this view sometimes works well...
Any idea? 

I forgot to say that i'm on the latest build (release 1.1.1 branch)

Thanks!

**Comment by v3yr0n** [comment]
Any updates? 
Someone knows what the problem can be?

Thanks!

**Comment by borrrden** [comment]
I have an idea of how to fix this, I will commit it today.

**Comment by v3yr0n** [comment]
ok, i'll be waiting! Thanks!

**Comment by borrrden** [comment]
This should take care of that null reference exception (on the release/1.1.1 branch).  Let me know if you still run into it, I will close this ticket after I merge this to master if I don't hear anything from you.

**Comment by v3yr0n** [comment]
Ok, i'll test and let you know. 

Thanks!

**Comment by v3yr0n** [comment]
Well, I think it's not working.. My app now freezes frequently. I tried with the code from the master branch and it does not freeze. 
Maybe the Task you edited is never ending?

**Comment by borrrden** [comment]
Does it help if you change `_task.Start()` in `UpdateJob` to `_task.Start(TaskScheduler.Default);` ?

**Comment by borrrden** [comment]
@v3yr0n I have made this change.  Let me know if you still see the issue.

**Comment by v3yr0n** [comment]
Hi! 
Thanks by the efforts, but your solution does not work for me.
I've solved the problem using the master branch with a tweak on my code. I'm only calling the view once and I save the result into a variable. That way it's working well for me :)
