### ISSUE TITLE
Attachment blob file name is not uppercase

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#493]
For platform compatibility, the attachment blob file name needs to be uppercased. From the 1.1.0 database given by @borrrden to test, the attachment file name is still lowercased.

**Comment by borrrden** [comment]
I guess I gave you that database a long time ago, because 1.1 already does uppercase attachment names (Starting at least in commit 0421c189b09540d7d4c250d3df90ebfcc6d59855 on 2015/05/07)
