### ISSUE TITLE
Dates should stringify with 8601 format

### ISSUE THREAD

**Issue by jchris** [couchbase/couchbase-lite-net#496]
I am fairly sure that when I do this:

```cs
properties["begin"] = new DateTime(session.start);
```

and then save, sync, and load the document, the string value of the "begin" field is something like

![ios simulator screen shot aug 21 2015 3 36 03 pm](https://cloud.githubusercontent.com/assets/253/9420422/5901d9dc-481a-11e5-81c6-9a9910366ab1.png)

It [should be formatted like this](http://stackoverflow.com/questions/10286204/the-right-json-date-format):

`2012-04-23T18:25:43.511Z`

**Comment by borrrden** [comment]
@jchris 

I wrote a simple test for this and it passed:

```
var now = DateTime.UtcNow;
    var doc = new Dictionary<string, object> {
     { "begin", now }
};
                
// The following line resulted in {"begin":"2015-09-04T00:33:02.960719Z"}
 var json = Manager.GetObjectMapper().WriteValueAsString(doc); 

// Note that "now.ToString()" prints 9/4/2015 12:33:02 AM
```

I think what is going on here is that when you are putting the item into your list view, you are simply calling `ToString()` which results in the format you see in the screenshot (in other words, the default string representation of a `DateTime` object).  You may also be using `String.Format()` or something that uses it internally.  The `DateTime` object in question should be fully serialized back to a `DateTime` object and not a `string` anyway.  Let me know a little more about this.
