### ISSUE TITLE
Query.Limit default value is not 0, and 0 does not mean unlimited

### ISSUE THREAD

**Issue by ryanthompson0123** [couchbase/couchbase-lite-net#502]
The CB lite documentation says that Query.Limit default value is 0, which means 'unlimited'. In both the source and in practice, this does not seem to be true.

In practice, setting Query.Limit = 0 actually limits the number of returned rows to 0.

In the source code, the default value for limit is clearly set to int.MaxValue. 

From Query.cs:89
```
/// <summary>The maximum number of rows to return.</summary>
/// <remarks>The maximum number of rows to return. Default value is 0, meaning 'unlimited'.
///     </remarks>
private int limit = int.MaxValue;
```

I had a wrapper function that allows the rest of my app to specify the skip and limit, defined like this:
```
public IEnumerable<SomeObject> DoQuery(int skip = 0, int limit = 0)
{
    using (var query = database.GetView("some_view"_.CreateQuery())
    {
        query.Skip = skip;
        query.Limit = limit;

        var rows = query.Run();
    }
}
```

That way if the app wants to default to unlimited, it can just call `DoQuery()`. But instead, that returns 0 rows. I don't know if it's a bug, or the documentation is just wrong, but I lost about half a day to this. Would be nice to see a fix.

**Comment by borrrden** [comment]
You aren't the first person to comment about this.  This documentation has grown stale and I was hoping it would be fixed in the latest updates to our docs but it seems that it has not.  I will double check just to make sure it's not a problem with my code base.

**Comment by snej** [comment]
Correct, 0 means zero. Pretty sure the incorrect doc-comment is my fault; I'm pretty sure that's what it used to say in the Cocoa header before I fixed it to read:

`/** The maximum number of rows to return. Defaults to 'unlimited' (UINT_MAX). */`

**Comment by borrrden** [comment]
I filed an issue in our docs portal.  It's a private repo though so I can't share the link.  I will push up a fix to the comment in the source though I don't see it on the line you mentioned.  I did find it somewhere else though.
