### ISSUE TITLE
[Unity] createAllDocumentsQuery().toLiveQuery() Throws Exception

### ISSUE THREAD

**Issue by z000z** [couchbase/couchbase-lite-net#505]
This was changed/fixed in the Android branch it looks like:
https://github.com/couchbase/couchbase-lite-android/issues/237

In this repo the change looks to need slightly more changes to make, it needs the removal of the null View check in the ToLiveQuery of Query.cs (line number 482) [this change was what they merged into the Android branch]

In addition it requires removal of the Null View check in LiveQuery.cs line number 347.  That appears all that is required to allow this to work.

This also appears to work with the delete case I had.  Although it's a bit slow.

**Comment by borrrden** [comment]
I had been waiting to see if this was actually a valid use case, since really you would just use the database changed event instead.  The ticket you linked said yes though so I will make sure that it can work.

**Comment by z000z** [comment]
Yeah this is just a little nicer since it does all the work of creating the document rows etc for you.
