### ISSUE TITLE
invalid type x for instance field y after updating from 1.1.0.1

### ISSUE THREAD

**Issue by dgcaron** [couchbase/couchbase-lite-net#509]
we are coming from 1.0.4.2 and upgraded to 1.1.0.1 and then upgraded to 1.1.1.1. After the last update we are receiving the messages below on Mac OSX (with the latest stable Mono version). reverting to 1.1.0.1 removes these messages. 

Invalid type Couchbase.Lite.Replication for instance field Couchbase.Lite.Database+<AddReplication>c__AnonStorey11:replication
Invalid type Couchbase.Lite.Replication for instance field Couchbase.Lite.Database+<AddActiveReplication>c__AnonStorey12:replication
Invalid type Couchbase.Lite.Replication for instance field Couchbase.Lite.Manager+<ReplicationWithProperties>c__AnonStorey1:rep
Invalid type Couchbase.Lite.Replication for instance field Couchbase.Lite.Replication+<FireTrigger>c__AnonStorey0:$this
Invalid type Couchbase.Lite.Replication for instance field Couchbase.Lite.Replication+<Login>c__AnonStorey1:$this
Invalid type Couchbase.Lite.Replication for instance field Couchbase.Lite.Replication+<SendAsyncRequest>c__AnonStorey2:$this
Invalid type Couchbase.Lite.Replication for instance field Couchbase.Lite.Replication+<SendAsyncMultipartDownloaderRequest>c__AnonStorey4:$this
Invalid type Couchbase.Lite.Replication/<SendAsyncMultipartDownloaderRequest>c__AnonStorey4 for instance field Couchbase.Lite.Replication+<SendAsyncMultipartDownloaderRequest>c__AnonStorey3:<>f__ref$4
Invalid type Couchbase.Lite.Replication for instance field Couchbase.Lite.Replication+<SendAsyncMultipartRequest>c__AnonStorey5:$this
Invalid type Couchbase.Lite.Replication for instance field Couchbase.Lite.Replication+<FetchRemoteCheckpointDoc>c__AnonStorey7:$this
Invalid type Couchbase.Lite.Replication for instance field Couchbase.Lite.Replication+<SaveLastSequence>c__AnonStorey8:$this
Invalid type Couchbase.Lite.Replication for instance field Couchbase.Lite.Replication+<CheckSessionAtPath>c__AnonStoreyA:$this
Invalid type Couchbase.Lite.Replication for instance field Couchbase.Lite.Replication+<NotifyChangeListeners>c__AnonStoreyB:$this
Invalid type Couchbase.Lite.Replicator.Pusher for instance field Couchbase.Lite.Replicator.Pusher+<UploadBulkDocs>c__AnonStorey0:$this
Invalid type Couchbase.Lite.Replicator.Pusher for instance field Couchbase.Lite.Replicator.Pusher+<UploadMultipartRevision>c__AnonStorey1:$this
Invalid type Couchbase.Lite.Replicator.Pusher for instance field Couchbase.Lite.Replicator.Pusher+<UploadJsonRevision>c__AnonStorey2:$this
Invalid type Couchbase.Lite.Replicator.Pusher for instance field Couchbase.Lite.Replicator.Pusher+<StopGraceful>c__AnonStorey3:$this
Invalid type Couchbase.Lite.Replicator.Pusher for instance field Couchbase.Lite.Replicator.Pusher+<ProcessInbox>c__AnonStorey4:$this
Invalid type Couchbase.Lite.Replicator.Pusher/<ProcessInbox>c__AnonStorey4 for instance field Couchbase.Lite.Replicator.Pusher+<ProcessInbox>c__AnonStorey4+<ProcessInbox>c__AnonStorey5:<>f__ref$4

**Comment by borrrden** [comment]
This looks oddly like a problem with mismatched DLL files.  It seems to be almost always accompanied with a System.TypeLoadException.  Does this happen even with a separate (brand new) project?

**Comment by dgcaron** [comment]
i think you are right.. a fresh project doesn't show these errors.

**Comment by borrrden** [comment]
I remember your environment is quite hazardous, but if you can get more info then please let me know.  I'd like to be able to get out a better message than the one you posted.

**Comment by dgcaron** [comment]
sure, will keep you posted!

**Comment by dgcaron** [comment]
i was able to recreate the issue

System.TypeInitializationException: An exception was thrown by the type initializer for System.Collections.Generic.List`1 ---> System.Exception: Could not load type 'Couchbase.Lite.Replication[]' from assembly 'Couchbase.Lite, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null'.
  at System.Collections.Generic.List`1[Couchbase.Lite.Replication]..cctor () [0x00000] in /private/tmp/source-mono-mac-4.0.0-branch-c5sr4/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.0.4/external/referencesource/mscorlib/system/collections/generic/list.cs:47
  --- End of inner exception stack trace ---
  at Couchbase.Lite.Manager..ctor (System.IO.DirectoryInfo directoryFile, Couchbase.Lite.ManagerOptions options) [0x00044] in <filename unknown>:0
  at CBL.Test.MainClass.Main (System.String[] args) [0x00015] in

**Comment by borrrden** [comment]
By the way, have you communicated with the support team about this?  If not then please do so.  What makes you think that this is an issue with Stateless?  If it wasn't available then that should cause an error when adding it as a dependency.  

That stack trace looks like I expected for the constructor throwing an exception.  Can you see any more inner exceptions?

**Comment by borrrden** [comment]
This looks more and more like an issue with Xamarin Studio's nuget plugin.  I filed this -> https://bugzilla.xamarin.com/show_bug.cgi?id=34467

**Comment by dgcaron** [comment]
Yes, this is exactly what is happening.  i expected something was off with
the package itself.  But you are probably right.

**Comment by borrrden** [comment]
@dgcaron We are going to re-release the package without the .NET 3.5 DLL inside until this problem gets resolved.  After that I will close this ticket again.

**Comment by borrrden** [comment]
Updated the nuget package today, closing

**Comment by dgcaron** [comment]
Ok, thanks for taking the time for this
