### ISSUE TITLE
error when non-contineous sync ends.

### ISSUE THREAD

**Issue by dgcaron** [couchbase/couchbase-lite-net#517]
When we start a non-continuous push replication on a specfic channel we get the following exception.

Pusher: Unhandled exception in Pusher.ProcessInbox System.NullReferenceException Object reference not set to an instance of an object Boolean get_IsSafeToStop()   at Couchbase.Lite.Replicator.Pusher.get_IsSafeToStop () [0x00000] in <filename unknown>:0 
  at Couchbase.Lite.Replication.SafeAddToCompletedChangesCount (Int32 value) [0x00000] in <filename unknown>:0 
  at Couchbase.Lite.Replicator.Pusher+<ProcessInbox>c__AnonStorey4.<>m__1 (System.Object response, System.Exception e) [0x00000] in <filename unknown>:0  

the system does seem to keep responding, but i am not sure if this is something we should ignore. i have some extensive logging, but it's too big to attach here.

**Comment by borrrden** [comment]
That's an oversight on my part, but I don't think it will have any effect on the replication process.  When the replication catches up (i.e. the number of completed changes equals the number of total changes) then a non-continuous replication will check to see if any remaining operations are queued.  If they are not, then it will start the shutdown process.  At the end of the shutdown process it will set the object which stores operations to null.  For some reason yours is getting called again after that and when it goes to check for remaining operations it encounters a null object.  

The reason I don't think this will have an effect is that the replication has already finished at this point.  Even if I correct that property to succeed (which, of course, I will.  It will only require a change to one line) the result will be a no-op.
