### ISSUE TITLE
Filter out _removed revision from push replication

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-net#527]
https://github.com/couchbase/couchbase-lite-ios/pull/776

**Comment by Steven-Mark-Ford** [comment]
@borrrden I'm getting this issue as outlined by another user here: https://forums.couchbase.com/t/change-feed--removed-flag-causing-issues-for-a-new-replication/5058

This is a critical production issue for us, any idea when this will be resolved. Or if a patch could be provided in the interim?

I was planning on forking, fixing and issuing a pull request for this.

**Comment by borrrden** [comment]
This is scheduled to be included in 1.2. That won't be released for a few
more weeks at least but I can move the priority up to at least get it fixed
in master early next week.

**Comment by Steven-Mark-Ford** [comment]
@borrrden just to confirm would this issue have the same symptom as outlined here: https://forums.couchbase.com/t/change-feed--removed-flag-causing-issues-for-a-new-replication/5058
i.e. PULL syncs stop working (wasn't sure) or do we need to open a new issue?
