### ISSUE TITLE
Fresh clone Couchbase.Lite.Net45.VS2013.sln or Couchbase.Lite.Android.VS2013.sln build fails on windows

### ISSUE THREAD

**Issue by Steven-Mark-Ford** [couchbase/couchbase-lite-net#528]
1. Cloned fresh onto a Windows 8 pc
2. Opened Couchbase.Lite.Net45.VS2013.sln
3. Built but got 10 failures relating to dlls not found.

For details see: http://stackoverflow.com/questions/33799196/couchbase-lite-net-building-source-files-how-does-one-resolve-was-not-found-d @zgramana @borrrden

(and as per readme.md I have updated submodules and installed Shared Project Reference Manager. running Visual Studio 2013 Pro)

**Comment by Steven-Mark-Ford** [comment]
Update: Got it working by building \src\Couchbase.Lite.Shared\vendor\cbforest\CBForest.VS2015 and copying the CBForest-Interop.dll into the above location

Why are the prebuilt dlls not in the repo?

but still have 1 more build error:

Error 107 Error reading resource file 'c:\dev\repo_git\couchbase-lite-net\src\Couchbase.Lite.Net45.Tests\Assets\local-test.properties' -- 'The system cannot find the file specified. ' C:\dev\repo_git\couchbase-lite-net\src\Couchbase.Lite.Net45.Tests\CSC Couchbase.Lite.Net45.Tests

**Comment by borrrden** [comment]
The prebuilt files are not there because I plan on making them a separate release so I don't clog up git with a bunch of binary commits. Local test properties is a local file not under source control to specify your test parameters for your machine. It is only used in the unit test target. Copy pasting test properties gives a good starting point. I will update the readme.

**Comment by Steven-Mark-Ford** [comment]
@borrrden thanks! much appreciated. I fully understand the binary commit issue was just not sure how often these binaries changed etc. once could probably then look at making the dll a nuget dependency am I correct?

**Comment by borrrden** [comment]
For nuget I will include the binaries in the release and probably also make them a download on the github releases page for people who can't or don't want to build it. There is still a chance that I will make it a separate nuget though. That project is under active development right now and are changing frequently.

**Comment by Steven-Mark-Ford** [comment]
@borrrden Also you could you give me guidance on the following. I get the error "Could not find a part of the path '..\prebuilt\arm64-v8a\libCBForest-Interop.so'" I managed to build the .net project by prebuilding CBForest-Interop.dll but how would I go about obtaining the .so to build the android.net project? This is fairly urgent as I need to look at resolving a production issue we experiencing on Couchbase for the Android platform. Your help would be much appreciated. Thanks!

**Comment by borrrden** [comment]
There are build scripts for all platforms one up from the prebuilt folder.
You can build android by running "ndk-build -C jni" for that folder on the
command line. Make sure you have an android ndk folder in your path. I'll
indicate how t build all platforms once I update the README. That should be
tomorrow. This week is a holiday week in America so not a lot of things are
moving quickly.

>

**Comment by Steven-Mark-Ford** [comment]
@borrrden Thanks! an updated README would be much appreciated. 

So just to confirm: If one runs ndk-build -C on src\Couchbase.Lite.Shared\vendor\cbforest\jni (which contains Android.mk and Application.mk) it should result in the required \prebuilt\arm64-v8a\libCBForest-Interop.so file as one of the outputs?

**Comment by Steven-Mark-Ford** [comment]
@borrrden As mentioned previously I am building on Windows (I'm aware the cbforest build has only tested on linux). Just a note for windows users if you run 'ndk-build -C jni' and the jni parent path is too long the build will fail with message like 'error opening..no such file or directory' as there is a 260 max path length in windows (see https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath). The quick solution is to make the parent directory shorter. The more elegant solution would be to patch the actual .mk to not generate a copy of the entire parent path as it currently generates very long paths during the build e.g. {parent path}/obj/local/armeabi-v7a/objs/CBForest-Interop/{repeat of parent path}/jni/__/vendor/sqlite3-unicodesn/fts3_unicodesn.o.d'

**Comment by borrrden** [comment]
Do you have a resource that specifies a way to do that in the .mk file?  I've looked into this before and the only workaround I've found is to either make the path to the project shorter or mount the path as a drive letter.

**Comment by Steven-Mark-Ford** [comment]
I do not have a resource for this :/. My knowledge of .mk is very limited.

**Comment by borrrden** [comment]
Oh but as for the other comment, running that (once you succeed with it) will create four files that you need to copy to the prebuilt folder (really you can just copy the contents of the created "libs" folder to the "prebuilt" folder")

**Comment by Steven-Mark-Ford** [comment]
Yes, thanks, this is what I had to do and it worked fine.

**Comment by borrrden** [comment]
I've updated the README so I am going to close this ticket.  I included a note about the long path issue.

**Comment by Steven-Mark-Ford** [comment]
@borrrden Looks great, thanks!
