### ISSUE TITLE
Add sample code for encryption

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-net#539]

**Comment by borrrden** [comment]
```c#
var manager = Manager.SharedInstance; // Or any manager you create
var key = SymmetricKey.Create("letmein"); // Or the raw data calculated previously
var options = new DatabaseOptions();
options.EncryptionKey = key;
var db = manager.OpenDatabase("seekrit", options)
```

**Comment by jamiltz** [comment]
I used the code above to register an encryption key. With the following Nuget packages installed:

```
- Couchbase.Lite.Storage.SystemSQLite
- Couchbase.Lite.Storage.SystemSQLCipher
- Couchbase.Lite.Listener
- Couchbase.Lite
```

An exception is thrown with the message: `make sure you have installed the correct Nuget packages and added the CBL_SQLCIPHER symbol to your project's define symbols`. Any idea what might be causing this?

**Comment by borrrden** [comment]
Did you add CBL_SQLCIPHER to your projects define symbols?

**Comment by jamiltz** [comment]
Ah, maybe that's why. I'll add it and try again. Thanks

**Comment by jamiltz** [comment]
I'm not sure how to do that in Visual Studio. Can you provide instructions or a resource that explains how to define the CBL_SQLCIPHER symbol?

**Comment by zgramana** [comment]
See http://stackoverflow.com/questions/2355340/how-do-i-define-a-preprocessor-symbols-in-c-sharp-visual-studios

**Comment by jamiltz** [comment]
:+1:
