### ISSUE TITLE
Missing PrefixMatchLevel under query

### ISSUE THREAD

**Issue by roikatz** [couchbase/couchbase-lite-net#558]
On Couchbase Lite for iOS there is a property called prefixMatchLevel,
https://github.com/couchbase/couchbase-lite-ios/wiki/Query-Enhancements#prefix-matching

On the dotNet platform that property is missing.
It would be great if that will be added to the dotNet SDK.

Thanks,
Roi.

**Comment by borrrden** [comment]
You mean [this](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Query/QueryOptions.cs#L180)?

**Comment by snej** [comment]
This property should be on the Query class itself to match the public API.

Also, having a public QueryOptions is nonstandard; do you need it?

**Comment by roikatz** [comment]
So even though I can see that in the code as specified option.
I can't really use it. Not with the QueryOptions which is private or any other way to influence the query with that property.

I'm using version 1.1.1

**Comment by borrrden** [comment]
I've figured out what you mean!  Unfortunately I think it's too late to get this into 1.2 but I'll definitely get it in soon.

**Comment by roikatz** [comment]
Ok cool. maybe 1.2.1 :)

**Comment by borrrden** [comment]
Note: Was looking into this, and prefixMatchLevel does not work correctly for views so far (only all docs).
