### ISSUE TITLE
Add docs on how to include NUnit runners. 

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-net#559]
When opening Couchbase.Lite.iOS and Couchbase.Lite.Android, I get pop up warnings about Nunit runners. I would be nice to some how check these in or provide documentation for a better user experience. 

![screenshot 2016-01-25 21 05 50](https://cloud.githubusercontent.com/assets/1365736/12572951/8eb22b5a-c3a7-11e5-9723-f5ed7ff5aa44.png)

**Comment by borrrden** [comment]
The way to include them is in the main README.  I might further separate them into their own solutions at some point to avoid these warnings.
