### ISSUE TITLE
1.2 .NET Release app testing

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-net#564]
- [x] verify SimpleAndroidSync with sync_gateway 1.2
    - [x] Try with Channel Cache
    - [x] Try with Distributed Index
- [x] verify CouchbaseSample.iOS with sync_gateway 1.2
    - [x] Try with Channel Cache
    - [x] Try with Distributed Index
- [x] db online / offline spot checking

**Comment by sethrosetter** [comment]
Need to retest with final RC

**Comment by borrrden** [comment]
@sethrosetter What is the status of this ticket?

**Comment by sethrosetter** [comment]
@borrrden I have gone through this once a week ago and would like to retest with the release packages today.

**Comment by sethrosetter** [comment]
Tested today with 1.2. packages
sync_gateway - "Couchbase Sync Gateway/1.2.0(79;9df63a5)"

- [x] verify SimpleAndroidSync with sync_gateway 1.2 - Channel cache mode
    
- [x] Forest 
- [x] verify CouchbaseSample.iOS with sync_gateway 1.2 - Channel cache mode
    - [x] Try with Channel Cache
