### ISSUE TITLE
Package Custom SQLite

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-net#575]

**Comment by borrrden** [comment]
Putting in the review column not for us, but I want to go over the implementation with Eric Sink and make sure I have it all right.

**Comment by borrrden** [comment]
@michaelkwok Need to start packing this on the build server.  There is a new nuspec file called couchbase-lite-storage-customsqlite.nuspec, so just tack that one on and put it in latest builds next to the others.

**Comment by borrrden** [comment]
Gonna hold off on this.  Ran into some problems with 0.9.0, need to retest.

**Comment by borrrden** [comment]
@michaelkwok Can you add a step to the packaging job that will run against the couchbase-lite-storage-customsqlite nuspec?

**Comment by borrrden** [comment]
https://github.com/couchbase/build/pull/8
