### ISSUE TITLE
Incompatible with Xamarin PCL?

### ISSUE THREAD

**Issue by ericsink** [couchbase/couchbase-lite-net#579]
I'm trying to add the nuget package for Couchbase.Lite 1.2 to a new PCL project using Xamarin 4.

The error is (something like):

Could not install package 'Couchbase.Lite.Storage.SystemSQLite 1.2'. You are trying to install this package into a project that targets 
'portable-net45+win+wpa81+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I *think* this is because Couchbase.Lite.Storage.SystemSQLite contains only net35, MonoAndroid, and Xamarin.iOS, whereas Xamarin Studio does not let me choose a PCL profile without including other stuff.  If I bring up the Xamarin project Options and try to choose ONLY net* and android and iOS, I get:

Found multiple applicable frameworks, you need to select additional check boxes.

But if I select any other check boxes, then the resulting profile becomes incompatible with one of the dependencies of Couchbase.Lite.

Not sure if this is a bug in Xamarin or what.  Even if it is, I assume that, if I am correct in my claim that there is no Xamarin PCL project configuration which is compatible with CBLite 1.2, you guys would want to know that. :-)

**Comment by ericsink** [comment]
Hmph.  I actually can't find a config that works for CBLite 1.1 either.

Maybe CBLite simply isn't intended to be consumed by a PCL?

**Comment by ericsink** [comment]
OK I think I'm just being a bonehead.  Never mind.

**Comment by borrrden** [comment]
I didn't even realize this flash before my eyes but no, the library is not PCL compatible.  To become compatible we first have to get UWF stuff working (a gigantic task given how much I/O and networking stuff we use.  Also PCL is very clever in that you can't really get a combination that does not include UWF or Windows Phone / Store of some kind.  

Even after we get that working it will probably not be a "true" PCL, but a bait and switch library.  I notice there is a lot of missing stuff that we need from the portable subset (NetworkInformation, Sockets, Thread, X509, etc, etc).
