### ISSUE TITLE
System.BadImageFormatException when calling manager.GetDatabase("dbname") method

### ISSUE THREAD

**Issue by dhanley12** [couchbase/couchbase-lite-net#583]
Following upgrade to V1.2 of Couchbase Lite .Net I am receiving a:

Exception thrown: 'System.BadImageFormatException' in cbforest-sharp.dll

runtime error when calling manager.GetDatabase("dbname") method when debugging app in Visual Studio. 

Does any one have any ideas how I can resolve this issue?

David.

**Comment by borrrden** [comment]
Are you by any chance running a 32-bit operating system?

**Comment by dhanley12** [comment]
Jim

No, 64-bit Windows 8.1.

David Hanley

Sent from my iPhone

On 12 Feb 2016, at 22:19, Jim Borden <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you by any chance running a 32-bit operating system?

—
Reply to this email directly or view it on GitHub<https://github.com/couchbase/couchbase-lite-net/issues/583#issuecomment-183509484>.
Aggreko | Registered office: 8th Floor, 120 Bothwell Street, Glasgow, G2 7JS, Scotland
Registered in Scotland | Registration No SC177553

Confidentiality Notice: This communication and any accompanying attachments contain confidential information intended for a specific individual and purpose. This communication is private and protected by law. If you are not the intended recipient, you are hereby respectfully notified that any disclosures, copying, forwarding or distribution, or the taking of any action based on the contents of this communication is strictly prohibited

Disclaimer

The information contained in this communication from the sender is confidential. It is intended solely for use by the recipient and others authorized to receive it. If you are not the recipient, you are hereby notified that any disclosure, copying, distribution or taking action in relation of the contents of this information is strictly prohibited and may be unlawful.

This email has been scanned for viruses and malware, and may have been automatically archived by Mimecast Ltd, an innovator in Software as a Service (SaaS) for business. Providing a safer and more useful place for your human generated data. Specializing in; Security, archiving and compliance. To find out more visit the Mimecast website.

**Comment by borrrden** [comment]
Alright I've downloaded the package and it looks like somehow a 0kb file is in the package in place of the Windows native DLL.  I'll redo the ForestDB package but in the meantime if you want a result immediately you can download the precompiled native images from [here](https://github.com/couchbaselabs/cbforest/releases/tag/1.2-net) and overwrite the CBForest-Interop.dll file in the packages/build/net35 directory of your solution with the one you downloaded.

**Comment by dhanley12** [comment]
Jim

Cool, thanks for this. Will try your suggestion.

David Hanley
Technical Architect

Sent from my iPhone

On 16 Feb 2016, at 02:15, Jim Borden <notifications@github.com<mailto:notifications@github.com>> wrote:


Alright I've downloaded the package and it looks like somehow a 0kb file is in the package in place of the Windows native DLL. I'll redo the ForestDB package but in the meantime if you want a result immediately you can download the precompiled native images from here<https://github.com/couchbaselabs/cbforest/releases/tag/1.2-net> and overwrite the CBForest-Interop.dll file in the packages/build/net35 directory of your solution with the one you downloaded.

—
Reply to this email directly or view it on GitHub<https://github.com/couchbase/couchbase-lite-net/issues/583#issuecomment-184476585>.
Aggreko | Registered office: 8th Floor, 120 Bothwell Street, Glasgow, G2 7JS, Scotland
Registered in Scotland | Registration No SC177553

Confidentiality Notice: This communication and any accompanying attachments contain confidential information intended for a specific individual and purpose. This communication is private and protected by law. If you are not the intended recipient, you are hereby respectfully notified that any disclosures, copying, forwarding or distribution, or the taking of any action based on the contents of this communication is strictly prohibited

Disclaimer

The information contained in this communication from the sender is confidential. It is intended solely for use by the recipient and others authorized to receive it. If you are not the recipient, you are hereby notified that any disclosure, copying, distribution or taking action in relation of the contents of this information is strictly prohibited and may be unlawful.

This email has been scanned for viruses and malware, and may have been automatically archived by Mimecast Ltd, an innovator in Software as a Service (SaaS) for business. Providing a safer and more useful place for your human generated data. Specializing in; Security, archiving and compliance. To find out more visit the Mimecast website.

**Comment by borrrden** [comment]
P.S. I also updated the forest db package. Make sure you don't have the prefer 32-bit option checked in your project properties because the native image is 64-bit. I'll address 32-bit in a future update.

**Comment by borrrden** [comment]
@dhanley12 Has the issue been resolved?

**Comment by zgramana** [comment]
@dhanley Please re-open and if you still observe the issue.
