### ISSUE TITLE
Add CBL.NET unit test support on Jenkins

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-net#585]
#### Build
- [X] Windows
  - [X] .NET 4.5
  - [X] .NET 3.5
- [X] Xamarin.iOS
- [X] Xamarin.Android
#### Unit Test

https://wiki.jenkins-ci.org/display/JENKINS/NUnit+Plugin
- [ ] Windows
  - [ ] .NET 4.5
- [ ] Xamarin.iOS
- [ ] Xamarin.Android

**Comment by borrrden** [comment]
This ticket's information is old, so I will update with what we need now for 2.0:

An environment with Android devices, an environment with iOS devices and if possible (and applicable) a remotely accessible tvOS environment.

Once we have that, we can run the relevant test runners.  UWP and .NET Core are both finished.
