### ISSUE TITLE
Implement the ability to run peer to peer tests between Android and .NET

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-net#586]

**Comment by borrrden** [comment]
https://github.com/couchbaselabs/mobile-testkit/pull/465

**Comment by borrrden** [comment]
Tested with Mono and at least 1 test is functional.  Windows support will have to come post 1.3.

**Comment by sethrosetter** [comment]
Tracking native windows - https://github.com/couchbaselabs/mobile-testkit/issues/508
