### ISSUE TITLE
Define test profiles for Sanity, Nightly, and Release profiles

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-net#594]

**Comment by borrrden** [comment]
Sanity:
Couchbase.Lite.ApiTest.*
Couchbase.Lite.AttachmentsTest.* (Except TestUpgradeMD5)
Couchbase.Lite.AuthTest.TestAuthenticationFactory
Couchbase.Lite.AuthTest.TestBasicAuthenticator
Couchbase.Lite.AuthTest.TestGetAuthenticationHeaderValue
Couchbase.Lite.AuthTest.TestParsePersonaAssertion
Couchbase.Lite.AuthTest.TestTokenAuthenticator
Couchbase.Lite.Base64Test.*
Couchbase.Lite.BatcherTest.*
Couchbase.Lite.BlobStoreWriteTest.*
Couchbase.Lite.ChangesTest.*
Couchbase.Lite.ChangeTrackerTest.*
Couchbase.Lite.CookieStoreTest.*
Couchbase.Lite.CRUDOperationsTest.*
Couchbase.Lite.DatabaseTest.*
Couchbase.Lite.DocumentTest.*
Couchbase.Lite.EncryptionTest.*
Couchbase.Lite.JSViewCompilerTest.*
Couchbase.Lite.LocalDocsTest.*
Couchbase.Lite.LogTest.*
Couchbase.Lite.ManagerTest.*
Couchbase.Lite.MiscTest.*
Couchbase.Lite.MultipartReaderTest.*
Couchbase.Lite.MultipartTest.*
Couchbase.Lite.MultiStreamWriterTest.*
Couchbase.Lite.PeerToPeerTest.*
Couchbase.Lite.RevisionsTest.*
Couchbase.Lite.RevTreeTest.*
Couchbase.Lite.RouterTests.*
Couchbase.Lite.SequenceMapTest.*
Couchbase.Lite.StorageEngineTest.*
Couchbase.Lite.ValidationsTest.*
Couchbase.Lite.ViewsTest.* (except TestIssue490)

Nightly (requires Sync Gateway instance, can be launched with start_gateway script):
Couchbase.Lite.ReplicationTest.* (except TestPushAttachmentToCouchDB and TestUpdateToServerSavesAttachment)
Couchbase.Lite.AuthTest.TestBasicAuthenticationSuccess
Couchabse.Lite.AuthTest.TestBasicAuthenticationWrongPassword

Release (requires "nightly" Sync Gateway instance, as well as CouchDB instance):
Couchbase.Lite.PerformanceTest.* (requires manual inspection)
Couchbase.Lite.ReplicationTest.TestPushAttachmentToCouchDB
Couchbase.Lite.ReplicationTest.TestUpdateToServerSavesAttachment
Couchbase.Lite.AttachmentsTest.TestUpgradeMD5
Couchbase.Lite.ViewsTest.TestIssue490

**Comment by zgramana** [comment]
Sanity:
- What's the chosen reference platform/hardware?

Nightly:
- GrocerySync
- Performance
- ???

Device profile[s] for perf benchmarking?

**Comment by borrrden** [comment]
I updated the above list, as for the reference platform I wonder if we can choose more than 1.  If not, then I think that whatever our support customers are using the most should be the reference (Windows .NET 4.5 ?).  If so then I vote for:

Windows .NET 4.5
Xamarin.iOS

This will catch runtime specific (mono vs .net) build / test quirks, and the nightly can further flesh this out to find platform specific quirks.
