### ISSUE TITLE
Default value of reduce in REST /_design/{ddoc}/_view/{view}

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-net#597]
From CouchDB docs (http://docs.couchdb.org/en/latest/api/ddoc/views.html#get--db-_design-ddoc-_view-view): reduce (boolean) – Use the reduction function. Default is true.

Using CBL .NET, reduce=true is required in the querystring `http://localhost:5984/db/_design/foo/_view/bar?reduce=true` to query the view with reduce below:

```
database.GetView("foo/bar").SetMapReduce((doc, emit) =>
{
     emit(doc["test"], 1); 
}, BuiltinReduceFunctions.Count, "1");

View view = database.GetView("foo/bar");
Query query = view.CreateQuery();
QueryEnumerator rows = query.Run();
if (rows.Count == 1)
{
    int count = Convert.ToInt32(rows.ElementAt(0).Value);
    Debug.WriteLine($"the doc count is {count}");
}
```

**Comment by borrrden** [comment]
When I set this up on my side it worked as expected, and I had to set reduce=false explicitly for it to show the map results.  So for example I did this 

```
var database = Manager.SharedInstance.GetDatabase("db");
if (database.GetDocumentCount() < 10) {
    for (int i = 0; i < 10; i++) {
        database.CreateDocument().PutProperties(new Dictionary<string, object> { { "counter", i } });
    }
}

database.GetView("foo/bar").SetMapReduce((doc, emit) =>
{
    if(doc.ContainsKey("counter")) {
        emit(doc["counter"], 1); 
    }
}, BuiltinReduceFunctions.Count, "1");

CouchbaseLiteServiceListener listener = new CouchbaseLiteTcpListener(Manager.SharedInstance, port);
```

This was the result for `http://localhost:59840/db/_design/foo/_view/bar` and  `http://localhost:59840/db/_design/foo/_view/bar?reduce=true`
> {
>   "rows": [
>     {
>       "key": null,
>       "value": 10,
>       "id": null
>     }
>   ],
>   "total_rows": 10,
>   "offset": 0
> }

And this was the result for  `http://localhost:59840/db/_design/foo/_view/bar?reduce=false`

> {
>   "rows": [
>   {
>     "key": 0,
>     "value": 1,
>     "id": "-dblohsVqQ0iFCNIr9BGOrg"
>   },
>   {
>     "key": 1,
>     "value": 1,
>     "id": "-NBhfPmYaS0uMjAyWdduucA"
>   },
>   ...
>   "total_rows": 10,
>   "offset": 0
> }

Did you by any chance change the view logic without changing the version number or something like that?

**Comment by jamiltz** [comment]
Yes this example works fine. Turns out that in another map/reduce I was using, the map was emitting an object as the value (in fact the whole doc). Then changed the map to emit `null` as the value and it's all good now :+1:
