### ISSUE TITLE
Opening non-encrypted db with sqlcipher storage type

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-net#605]
I've got an existing database with SQLite storage type. In the next run of the app, I'm using SQLCipher storage type.

The code to create or open the SQLite database:
```
this.database = manager.GetDatabase(databaseName);
```
 The code to create or open the SQLCipher database (and SQLite the first time the app runs after switching storage type):
```
DatabaseOptions dbOptions = new DatabaseOptions();
dbOptions.EncryptionKey = new SymmetricKey(AppSettings.AesKey);
dbOptions.Create = true;
this.database = manager.OpenDatabase(databaseName, dbOptions);
```

Exception thrown on the first run with SQLCipher:
```
Couchbase.Lite.CouchbaseLiteException was unhandled
  HResult=-2146233088
  Message=Decryption of database failed
  Source=Couchbase.Lite.Storage.SQLCipher
  StackTrace:
       at Couchbase.Lite.Storage.SQLCipher.SqlitePCLRawStorageEngine.Open(String path, Boolean readOnly, String schema, SymmetricKey encryptionKey)
       at Couchbase.Lite.Storage.SQLCipher.SqliteCouchStore.Open()
       at Couchbase.Lite.Storage.SQLCipher.SqliteCouchStore.Open(String directory, Manager manager, Boolean readOnly)
       at Couchbase.Lite.Database.OpenWithOptions(DatabaseOptions options)
       at Couchbase.Lite.Manager.OpenDatabase(String name, DatabaseOptions options)
```

**Comment by borrrden** [comment]
You cannot add a password to a database simply by opening it with that password.  You need to first *change* the password via the [ChangeEncryptionKey](https://github.com/couchbase/couchbase-lite-net/blob/d62bc1a4b8eb2f4a96683710609659ffe1c74ec4/src/Couchbase.Lite.Shared/Database.cs#L770) method.

**Comment by borrrden** [comment]
@jamiltz Did that fix things?

**Comment by borrrden** [comment]
Closed this issue for lack of response, sorry!

**Comment by jamiltz** [comment]
I haven't tried it with ChangeEncryptionKey yet. Sounds good and will reopen if necessary. Thanks!
