### ISSUE TITLE
Implement remote logging interface

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-net#606]
- [X] Implement Time Series class
- [X] Implement Remote Logging class

API spec (private)
https://github.com/couchbaselabs/couchbase-lite-api/wiki/Log-and-Time-Series-Syncing

iOS branch
https://github.com/couchbase/couchbase-lite-ios/tree/feature/logging

**Comment by zgramana** [comment]
@borrrden can you please update this ticket?

**Comment by borrrden** [comment]
Updated the above.  The logic is done but one of the unit tests is failing on both sqlite and forestdb.
