### ISSUE TITLE
Listener intermittently enters hanging state

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-net#608]
CBL .Net at commit c664968 is running in a Windows service.
Sometimes, the listener enters a hanging state. The database endpoint doesn't return.
When it happens, restarting the windows service will resolve the issue and make the listener available again.

**Comment by jamiltz** [comment]
Just an idea, the issue may be caused by https://github.com/couchbase/couchbase-lite-net/issues/609.

At some point, the app purges a few thousand documents without deleting them first.

**Comment by jamiltz** [comment]
If we can reproduce the listener hanging state by purging documents on the REST API then we know that the workaround is to delete them first.

Scenario:
- Insert docs
- Purge docs
- Query the view on the REST API

Observation: the request is hanging.

**Comment by borrrden** [comment]
@jamiltz Are other devices also hitting this listener at the same time?

**Comment by jamiltz** [comment]
No, this happens independently to p2p replication.
