### ISSUE TITLE
After purging a doc, live queries are not informed of the view change

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-net#609]
See https://github.com/couchbase/couchbase-lite-ios/issues/1164

**Comment by borrrden** [comment]
@snej My testing shows that when a document is purged its revisions are removed from the revs table.  Isn't it due to the ON DELETE CASCADE statement on the view index?

**Comment by snej** [comment]
I think you mean the `maps` table?

But yeah, I'd forgotten about that bit in the schema. This applies only to SQLite though, of course. The ForestDB fix [will need to go in CBForest](https://github.com/couchbaselabs/cbforest/issues/68).

There's a related problem that does occur with SQLite, though: after a view index is altered by having purged rows removed, there's no indication that it's changed, so LiveQueries won't re-run the query or notify their observers that they changed.
