### ISSUE TITLE
Add "aggressive" replicator start/stop/restart unit tests

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-net#614]
See @pasin for some recent examples.

**Comment by borrrden** [comment]
@pasin Can you put some information about the examples on this ticket?

**Comment by pasin** [comment]
Sorry for the delay. I did several test from my sample code but I couldn't find that code anymore. The following are the test cases base on my memory:

1. While the replicator (both push and pull) is running, call Replicator.restart() multiple times (~ at least 3 times).

2. While the replicator is running, call Replicator.start() multiple times.

3. While the replicator is running, call Replicator.stop() multiple times.

4. While the replicator is running, call Replicator.start() and stop() multiple times.

6. While the replicator is running, call Replicator.start() and then restart().

5. While the replicator is running, call Replicator.stop() and then restart().

7. While the replicator is not running, call Replicator.start() and stop() multiple times.

8. While the replicator is not running, call restart() multiple times.

The following items are checked after the test:
1. Replicator status itself
2. # of Active replicators
3. # of replicators and change trackers shown in the thread dump of the test.

**Comment by borrrden** [comment]
- [X] While the replicator (both push and pull) is running, call Replicator.restart() multiple times (~ at least 3 times).
- [X] While the replicator is running, call Replicator.start() multiple times.
- [ ] While the replicator is running, call Replicator.stop() multiple times.
- [ ] While the replicator is running, call Replicator.start() and stop() multiple times.
- [ ] While the replicator is running, call Replicator.start() and then restart().
- [ ] While the replicator is running, call Replicator.stop() and then restart().
- [ ] While the replicator is not running, call Replicator.start() and stop() multiple times.
- [ ] While the replicator is not running, call restart() multiple times.
