### ISSUE TITLE
Crashing in device iOS even your sample too.

### ISSUE THREAD

**Issue by rzee7** [couchbase/couchbase-lite-net#622]
Hey Guys

I'm using this in app and its working in simulators but not working in real device got exception on this line `Manager.SharedInstance;` not stacktrace just got line number.

Note: I've tried your component sample too but same issue.

@borrrden @avsej 

Thanks
Riyaz

**Comment by borrrden** [comment]
It's most likely this -> https://forums.couchbase.com/t/strange-exception/6858

You can try the workaround listed there and this will not be an issue with 1.2.1, which is currently undergoing testing.

**Comment by rzee7** [comment]
Thank you for quick response @borrrden . I'm not using forestDB stuff but still I will try suggested repo build.

**Comment by rzee7** [comment]
Hey @borrrden Nothing work. Can you please suggest another solution for this issue? I wonder because your provided sample with component didn't work.

**Comment by borrrden** [comment]
The problem is that the main library catches the wrong exception for detecting ForestDB native components, so actually not including them is what causes it.  Did you try including them to see what would happen?  What else did you try?

**Comment by rzee7** [comment]
I'm trying a sample you guys provided with component and I tried to added ForestDB too but doesn't work. I tried this on [This](http://screencast.com/t/0FhL3lebl) Xamarin version and it works. any thought?

**Comment by borrrden** [comment]
I meant what did you try to do for a workaround.  The three suggestions that come to mind are compiling the 1.2 release yourself emitting the offending line, compiling the upcoming 1.2.1 release yourself, or adding the forestdb storage plugin.
