### ISSUE TITLE
Xamarin Android crash due to hitting max application memory while syncing large attachments

### ISSUE THREAD

**Issue by Ariemeth** [couchbase/couchbase-lite-net#625]
Created a basic Xamarin Android application and added couchbase lite 1.2 nuget package.  Using the example code from the couchbase website, I created documents and then added 50MB attachments.  After syncing between 3 and 5 of these documents with 50MB attachments the application will be terminated.  Using dumpsys meminfo I can watch the application's memory climb quickly from 60MBs to over 500 at which point Android terminates the application on a Samsung Galaxy Nexus device.
Dropping the attachment size down to 19MB will eventually still cause the memory issue, but it can take over 200 attachments.
Previously to get around this issue we have changed couchbase lite to use only 1 httpclient and not calling dispose on that client until the application is shut down.

**Comment by Ariemeth** [comment]
Here is our [test application](https://github.com/APXLabs/couchbase-lite-memory-test) that we used to run the test.

**Comment by borrrden** [comment]
I'll definitely be taking a look at this soon.  Thanks for the repro project!!

**Comment by borrrden** [comment]
I was able to get further than 3 - 5 documents on Nexus 5 but I see the high memory usage still in 1.2.1.  This is probably due to the document cache.  I'll talk to the architect and see if there are any existing APIs to reduce memory usage that I might not have implemented.

**Comment by borrrden** [comment]
Actually I think this is a more simple matter of not disposing the UnsavedRevision objects.  They are IDisposable, and calling dispose frees up the attachment memory.  @Ariemath

**Comment by borrrden** [comment]
Alright, last update.  I don't see any crashing on my device with your test repo.  I do see high memory usage, but it is all collectable stuff (which does get collected every so often).  I left it running for about 5 minutes with no crashing.  Profiling shows that all the memory use is in two places:

First, in the buffer in the stream that is used to copy the memory contents to disk and second in the buffer of the memory stream used in sending the data to the server.  Both of these seem to be eligible for GC so it's hard to tell what is going on.

**Comment by Ariemeth** [comment]
@borrrden  That is good information.  Never clicked that we should be calling dispose on an unsaved revision object.  I'll have to try that.

**Comment by borrrden** [comment]
@Ariemeth For what it's worth I'm not sure that it will make a difference in this case.  It's more for getting rid of unsaved revisions without saving them (saving them also flushes the attachment bodies out of memory and into disk)

**Comment by borrrden** [comment]
Another update, since I've received a Xamarin.Android project to test with regarding memory issues.  I've determined that I can fairly easily make a huge optimization that will reduce memory by a whole lot.  Preliminary testing shows that before I would quickly get into the high 100s of megabytes for a pull replication, now I'm less than 200.  The trick is to recycle memory streams and byte arrays instead of just throwing them away each time (I create a whole lot of them while streaming things to and from file and network).  Also, Stream.CopyTo has a hidden byte[] allocation in it, so I will try to avoid it.  Things should be looking better already but certainly by the time 1.3 is released they will be solid.

**Comment by Ariemeth** [comment]
That is great.Look forward to seeing how low you get the memory.

**Comment by borrrden** [comment]
Thanks to the Microsoft provided recyclable memory stream framework I'm currently passing 80 documents created in your test app on the latest master (using the original 50MB).  I think I will count that as a success.

**Comment by Ariemeth** [comment]
That is amazing.

**Comment by borrrden** [comment]
Alright I will close this, but if it becomes an issue again let me know.
