### ISSUE TITLE
Fallback to GET when POST is not allowed to _changes

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-net#628]
CBL .NET commit: ebab280
CBL Android version: 0.0.0-640

Steps to repro:

- Start the [java-listener app](https://github.com/couchbase/couchbase-lite-java-listener) (currently [build.gradle](https://github.com/couchbase/couchbase-lite-android-liteserv/blob/master/couchbase-lite-android-liteserv/build.gradle#L34-L37) points to 0.0.0-640)
- Add a document to the database:

  ```
  curl -vX POST 'http://192.168.2.15:5984/cblite-test' -d '{}'
  ```

- Start a pull replication with .NET Listener from Windows command prompt:

  ```
  Listener.exe --pull=http://192.168.2.15:5984/cblite-test
  ```

The document isn't replicated to the target database (.NET). The replicator logs are at: https://gist.github.com/jamiltz/ad7a175f91ad99dd86f11cef145672a6

I've only tried using Listener.exe but the same should apply to running CBL .NET on a Mac.

From running Fiddler on Windows, it looks like the POST /_changes returns 404:

![image](https://cloud.githubusercontent.com/assets/2589337/14404220/b4122570-fe81-11e5-99d3-50305335c2b3.png)

Perhaps the java-listener doesn't implement the POST /_changes route? Should the .NET replicator try GET /_changes if POST /_changes returns a 404?

Related issue: https://github.com/couchbase/couchbase-lite-java-core/issues/1188

**Comment by jamiltz** [comment]
PS I have no clue about the POST /_changes fallback to GET /_changes.

**Comment by borrrden** [comment]
@snej I don't see anywhere in the iOS implementation that attempts to fall back to GET.  So I think this might apply to iOS as well.

**Comment by snej** [comment]
The iOS fallback to GET is in `-[CBLSocketChangeTracker failedWithError:]`. If the POST fails with a 405 Method Not Allowed, it next tries GET.

**Comment by borrrden** [comment]
> Should the .NET replicator try GET /_changes if POST /_changes returns a 404?

Yes, in the short term.  In the long term Java should either return 405, or support POST requests ;)
