### ISSUE TITLE
Attachment problem in unity

### ISSUE THREAD

**Issue by IvanQuestMaster** [couchbase/couchbase-lite-net#629]
The following code

byte[] attachmentData = Encoding.UTF8.GetBytes("Just some attachment data");

Manager _manager = new Manager(new DirectoryInfo(Application.persistentDataPath), new ManagerOptions { CallbackScheduler = UnityMainThreadScheduler.TaskScheduler });
Database _db = _manager.GetDatabase("test");

var document = _db.CreateDocument();
Dictionary<string, object> properties = new Dictionary<string, object>();
properties.Add("test", "test");
properties.Add("version", 0);
document.PutProperties(properties);

var unsavedRevision = document.CreateRevision();
unsavedRevision.SetAttachment("att", "image/jpeg", attachmentData);
var newRevision = unsavedRevision.Save();

var unsavedRevision2 = newRevision.CreateRevision();
var properties2 = document.UserProperties;
properties2["version"] = 1;
unsavedRevision2.SetProperties(properties2);
var newRevision2 = unsavedRevision2.Save();

var attachment = newRevision2.GetAttachment("att");
attachment.Content.Count();`

throws a NullReferenceException on the last line, the Content property is null.

**Comment by borrrden** [comment]
The error here is this: `unsavedRevision2.SetProperties(properties2);`  You should call `unsavedRevision2.SetUserProperties(properties2);` instead.  If you call `SetProperties` you will overwrite the user AND library properties with just the user properties (including the `_attachments` property that contains the reference to the attachment).
