### ISSUE TITLE
No way to remove a database.

### ISSUE THREAD

**Issue by Ariemeth** [couchbase/couchbase-lite-net#634]
If an encrypted database becomes corrupted or the password for a database is no longer available there does not appear to be a way to remove the database.

**Comment by Ariemeth** [comment]
Currently I am handling this in this fashion
`Directory.Delete(Manager.SharedInstance.Directory, true);
Manager.SharedInstance = null;`

**Comment by borrrden** [comment]
@snej From an API standpoint is there something available for this?

**Comment by snej** [comment]
This came up before but I can't find an issue related to it, so I filed one in the [private] API repo.
