### ISSUE TITLE
"Attempted to read or write protected memory" error from Bonjour.dll

### ISSUE THREAD

**Issue by c0bra** [couchbase/couchbase-lite-net#638]
I'm running a very simple test application that listens for broadcasts. I copied these lines from here: https://github.com/couchbase/couchbase-lite-net/wiki/Listener-Component

``` c#
CouchbaseLiteServiceBrowser browser = new CouchbaseLiteServiceBrowser(new ServiceBrowser());
browser.ServiceResolved += (sender, e) =>
{
    Console.WriteLine("Discovered service: {0}", e.Service.Name);
};

browser.ServiceRemoved += (sender, e) =>
{
    Console.WriteLine("Service destroyed: {0}", e.Service.Name);
};
browser.Start();

Console.ReadKey();
```

It prints out several items, like printers, but then the program crashes with this error:

```
An unhandled exception of type 'System.AccessViolationException'
occurred in Couchbase.Lite.Listener.Bonjour.dll

Additional information: Attempted to read or write protected
memory. This is often an indication that other memory is corrupt.
```

Any ideas?

**Comment by borrrden** [comment]
This is basically the managed equivalent of "invalid pointer dereference."  What platform are you running on?

**Comment by c0bra** [comment]
@borrrden Windows 7 x64

**Comment by borrrden** [comment]
If you can get the stack trace from this exception I could have a better idea of where to look.

**Comment by borrrden** [comment]
@c0bra Did you ever get a stack trace for this?

**Comment by djpongh** [comment]
won't be getting to this
