### ISSUE TITLE
Provide build of ListenerConsole in latestbuilds with each nuget package set.

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-net#639]
This would allow QE tests to consume the binary without worrying about the entire build enviroment. Ideally it would be published with a verision-build. (ex. 1.2.1-10)

**Comment by borrrden** [comment]
@michaelkwok The build process will create another LiteServ folder now in the staging area as part of the .NET 4.5 job.  Simply zip that directory up and put it next to the others and @sethrosetter  should be able to consume it.  I'll keep thinking about if there is a better way or not.

**Comment by sethrosetter** [comment]
@borrrden. This is a good start in my opinion. That will unblock the CI portion of things until there / if there is a more comprehensive option.

**Comment by michaelkwok** [comment]
@borrrden I don't see the new LiteServ folder in .NET 4.5 staging.  I verified against the latest commit just now.

**Comment by borrrden** [comment]
I think the issue is that I didn't add the project to auto build in the Release_Testing configuration, only Packaging.  I added it just now.
