### ISSUE TITLE
Docs taking a really long time to replicate

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-net#640]
Using CBL Net 1.3.0-15

When running this test, i noticed interesting behavior - https://github.com/couchbaselabs/mobile-testkit/blob/feature/implement-test-views/testsuites/listener/shared/replication.robot

Both of the Listener dbs are able to push replicate to sync_gateway quickly but take a very long time to pull replicate (~5 min). Eventually the docs were pulled but it seems like invalid behavior

**Comment by borrrden** [comment]
For what it's worth, the OS X version of this test uses LiteServ which seems to not use web sockets as part of the test.  I'd be interested in testing it with a version that does because .NET also passes when web socket behavior is disabled.

**Comment by borrrden** [comment]
Note:

build LS with the debugger attached, then comment this out https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/listener/shared/client_sg/listener_sg_replication_push_revs_conflict.robot#L78-L83

**Comment by borrrden** [comment]
This is getting caused somehow by the simultaneous push and pull.  Note that the push is behaving badly also because the inserts are going to fast that by the time the push looks for the revision history it is already gone because it has been auto pruned.

**Comment by sethrosetter** [comment]
Seeing some _bulk_docs errors in the log - https://gist.github.com/sethrosetter/c6a60134750d433de67f2b9cf1e24e0e#file-gistfile1-txt-L1979.

Is this being caused by the auto prune or due to something else?

**Comment by borrrden** [comment]
@sethrosetter Yes that is exactly the error I see from the agressive auto pruning.  It means that an empty revisions history got sent.

**Comment by sethrosetter** [comment]
@borrrden I have added an update delay in the test of .1 seconds per doc. I am no longer seeing the _bulk_docs error. However, I still see replication hanging https://gist.github.com/sethrosetter/800aea34684a63b669dba60d8a2839a5#file-gistfile1-txt-L9575-L9595. 

Although it could be possible that my polling for replication idle may not be handling .NET correctly. Here is the implementation that is polling _active_tasks, 

https://github.com/couchbaselabs/mobile-testkit/blob/master/keywords/MobileRestClient.py#L899-L933

**Comment by Steven-Mark-Ford** [comment]
@borrrden Hey Jim, any idea when this fix might be released?

**Comment by borrrden** [comment]
@Steven-Mark-Ford Which fix?  The cause of this is still unclear to me but I hope to find and resolve it as my only task tomorrow. This only happens in a very specific situation though so are you sure you are running into the same issue?

**Comment by Steven-Mark-Ford** [comment]
@borrrden I am not experiencing this issue, it was more to get an idea of the expected release date for 1.3.0. Thanks!

**Comment by borrrden** [comment]
@Steven-Mark-Ford Our code freeze is at long last tomorrow.  .NET has a prerelease as well (I am just having trouble getting the same build to nuget, you can find a link to the nupkg in the github releases)

**Comment by sethrosetter** [comment]
Test failure with 1.3.0-119, exhibiting the same behavoir - http://uberjenkins.sc.couchbase.com/job/net-listener-client-sync-gateway/27/robot/report/log.html#s1-s3-t1

**Comment by sethrosetter** [comment]
Also seeing this with 1.3.0-121 http://uberjenkins.sc.couchbase.com/job/net-listener-client-sync-gateway/36/robot/report/log.html#s1-s3-t1
