### ISSUE TITLE
Manager constructor fails on Windows 10

### ISSUE THREAD

**Issue by emendamus** [couchbase/couchbase-lite-net#643]
Getting the following exception on calling **new Couchbase.Lite.Manager()**:

> 
--NotSupportedException
   at System.Reflection.Emit.InternalAssemblyBuilder.GetManifestResourceStream(String name)
   at Couchbase.Lite.Manager.ReadVersion(Assembly assembly, String& branch, String& hash)
   at Couchbase.Lite.Manager..cctor()
>

**Comment by borrrden** [comment]
What kind of application are you making?

**Comment by emendamus** [comment]
It is just an iOS-App. But I am using VS for IntegrationTests.

**Comment by borrrden** [comment]
You mean MSTest?

**Comment by emendamus** [comment]
I am using nunit. 1.2.1 is running fine though.

**Comment by borrrden** [comment]
You mean 1.2.1 as opposed to 1.2.1.1 ?  Or as opposed to something else?

**Comment by emendamus** [comment]
I mean 1.2.1.1 is running fine in contrast to 1.3(19)

**Comment by borrrden** [comment]
I ran into this exception.  I guess on mobile platforms we are not allowed to read manifest items from assemblies that were loaded via Assembly.Load.  So I will catch and log it (as an info message)
