### ISSUE TITLE
.NET 3.5 Replication Source SSL Timeout

### ISSUE THREAD

**Issue by jeremyswitzer** [couchbase/couchbase-lite-net#645]
My project is .NET 4.0 and references v1.2.1.1 of Couchbase.Lite. We have a Sync gateway set up for push only replication, and I've checked that it's reachable, but shortly after calling the `Start()` method on the Replication object, I see this error in the console: 

```
System.Net.Couchbase.WebException: The request timed out
      at System.Net.Couchbase.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) <0x10b0774e0 + 0x001f4> in <filename unknown>:0 
      at System.Net.Couchbase.HttpWebRequest.GetResponse () <0x10b0678e0 + 0x0005a> in <filename unknown>:0 
      at Couchbase.Lite.NetworkReachabilityManager.CanReach (System.String remoteUri) <0x10b060ee0 + 0x00260> in <filename unknown>:0 
```

I've narrowed it down to a problem with the .NET 3.5 build and any `https://` url by testing the following:
- .NET 4.5 Environment, http works
- .NET 4.5 Environment, https works
- .NET 4.0 Environment, http works
- .NET 4.0 Environment, https fails with timeout

The major difference I can see in the code seems to be the use of `System.Net.Couchbase` classes in place of the standard `System.Net` classes, but I haven't dug too deep beyond that. 

Unfortunately, our client needs run in .NET 4.0 in order to support older versions of Windows, so updating  the runtime is not an option at this point, but we are committed to making this work, so let me know if you need anymore information to help track down this problem. Thanks.

**Comment by borrrden** [comment]
.NET 3.5 runtime has only limited SSL support to begin with.  Are you using any proxies?  Can you hit the endpoint with a regular HttpWebRequest call from a .NET 3.5 application? Most places recommend disabling it but that will not work for .NET 3.5.  I wouldn't expect a timeout error but it's something to look into as well.

**Comment by borrrden** [comment]
Figuring out why SSL does not work is a long and painful exercise usually ending up with "The request is not getting sent by the runtime for whatever reason."  I tried refactoring out the Couchbase classes as an experiment but I had no luck so far.  Very few people use the .NET 3.5 version (it's really only around to support Unity3D while they continue to be ages behind the modern .NET world).  Also be aware that the .NET 4.0 profile is not tested.

**Comment by jeremyswitzer** [comment]
Thanks Jim,

Yes, we're running Sync Gateway behind NGINX as a reverse proxy, but it seems to be a problem with several different https urls, so I don't believe that's the issue. I wrote a quick test app that targets .NET 3.5 just to be sure:
```csharp
using System;
using System.Net;

namespace Net35HttpsRunner
{
    class Program
    {
        static void Main(string[] args)
        {
            var request = WebRequest.Create("https://www.google.com");
            request.Timeout = 10000;
            using (var response = request.GetResponse())
            {
                Console.WriteLine($"Content Length ==> {response.ContentLength}");
            }
        }
    }
}
```

and it seems to have no problem calling our db endpoint, or any other https url. I understand, however, that this is probably an oversimplification of the requests being made in the Couchbase library.

I understand this is small and diminishing support group, but what would be the best way to proceed in the interim while still using https and not changing our .NET Support level? Instead of spending a long and painful time trying to track down this issue, would it be more helpful to create a .NET 4.0 support project?

**Comment by borrrden** [comment]
One thing you could try is using an older version of Couchbase, if possible.  I know one person using SSL with Unity3D, which is based on 1.1.1.  However, keep in mind that I don't think we will develop for .NET less than 4.5 forever.  In fact, once Unity updates their runtime I will recommend that we eliminate it.

**Comment by djpongh** [comment]
Unfortunately, we can not support .NET 3.5.
