### ISSUE TITLE
Sample with SQLCipher

### ISSUE THREAD

**Issue by mathieumack** [couchbase/couchbase-lite-net#646]
Hi,
Is there a sampler available in order to use SQLCipher with encryption ?
When I use the manager.OpenDatabase with encryption options and SQLCipher storage type the database seems to be created without encryption.
Thanks.

**Comment by emendamus** [comment]
Hi,

U can use the following example:

var key = new SymmetricKey("123");
            var options = new DatabaseOptions
            {
                EncryptionKey = key,
                Create = true,
                StorageType = StorageEngineTypes.SQLite
            };

            this._db = manager.OpenDatabase(DbIdentifier,options);

**Comment by mathieumack** [comment]
It works ! thank you very much.
In my tests, I've setted the storage type on the manager object and not correctly in options.
