### ISSUE TITLE
Equivalent to full text search

### ISSUE THREAD

**Issue by mathieumack** [couchbase/couchbase-lite-net#647]
Hi,
Is there a solution to search a string in the database like a full text search research ?
Available samples for queries use only views or Key, so I don't understand how to do a "contains" query.
Thanks

**Comment by borrrden** [comment]
The functionality is not available at this time.  It is planned at a date TDB in the future (once we settle on how exactly to implement it)

**Comment by mathieumack** [comment]
Thanks.
The solution that I've actually applied is to add a PostFilter on Query with a paging limit in order to optimize query performance.
Do you think it's a good way or is there a better solution ?

**Comment by borrrden** [comment]
That's probably the best you will get.

**Comment by borrrden** [comment]
Alright, 4 months later and I have actual FTS implemented!  It will reside on the feature/fts branch until 1.5
