### ISSUE TITLE
Wrong version for LiteServ .NET

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-net#658]
I downloaded this - http://latestbuilds.hq.couchbase.com/couchbase-lite-net/1.3.0/44/

and issued a `GET localhost:59840`

Expected:
```
 {"couchdb":"Welcome","CouchbaseLite":"Welcome","version":".NET Microsoft Windows 10 Pro/x86_64 1.3.0-build0044/c51324a","vendor":{"name":"Couchbase Lite (C#)","version":".NET Microsoft Windows 10 Pro/x86_64 1.3.0-build0044/c51324a"}}
```

Actual: 
```
{"couchdb":"Welcome","CouchbaseLite":"Welcome","version":".NET Microsoft Windows 10 Pro/x86_64 1.3.0-build0040/c51324a","vendor":{"name":"Couchbase Lite (C#)","version":".NET Microsoft Windows 10 Pro/x86_64 1.3.0-build0040/c51324a"}}
```

It appears the build number is not being incremented.

**Comment by borrrden** [comment]
From what I've seen it is getting incremented, but not making it into the DLL for some reason.  Either the build is silently failing or maybe there is some funny business going on with DynamicAssemblyInfo.cs

**Comment by michaelkwok** [comment]
LiteServ was the only change added to the build process.  I am quite certain that does not introduce this issue on the build side.  As for Jenkins, it seems to behavior properly.  There is some odd behavior we need to figure out.

**Comment by sethrosetter** [comment]
More info:
The 47 build of liteserv is reporting itself as 45. 

Steps:
1. Download - http://latestbuilds.hq.couchbase.com/couchbase-lite-net/1.3.0/47/LiteServ.zip
2. `mono LiteServ.exe`
2. Issue `GET http://localhost:59840`
```
{
"couchdb": "Welcome",
"CouchbaseLite": "Welcome",
"version": ".NET OS X 10.11/x86_64 1.3.0-build0045/bf5bc0a",
"vendor": {
"name": "Couchbase Lite (C#)",
"version": ".NET OS X 10.11/x86_64 1.3.0-build0045/bf5bc0a"
}
}
```

**Comment by michaelkwok** [comment]
There might be an issue with some failed platforms did not get flag properly and hence packaging picks up the wrong output.  Jim and I are trying a few things that hopefully may resolve this.

**Comment by borrrden** [comment]
Looks like things are over the hump now.  builds 54 and 55 both have correct versions.
