### ISSUE TITLE
Removed attachments reported by UnsavedRevision

### ISSUE THREAD

**Issue by jefflill** [couchbase/couchbase-lite-net#661]
Couchbase.Lite v1.2.1.1

After creating an unsaved revision for a document with a saved attachment and then removing the attachment, the unsaved revision's `AttachmentNames `property still returns the deleted attachment's name and `GetAttachment()` still returns non-NULL.  Perhaps this is by design but it seems a bit wonky.

Here's my test code:

```
[Fact]
public void REPORT_RemoveAttachment()
{
    // Used to report a Couchbase Lite issue.

    using (var db = Manager.SharedInstance.GetDatabase("wonky"))
    {
        var doc = db.CreateDocument();
        var unsaved = doc.CreateRevision();

        unsaved.SetAttachment("attach", "type", new byte[] { 0, 1, 2, 3, 4 });

        // NOTE: These asserts pass.

        Assert.Equal(1, unsaved.AttachmentNames.Count());
        Assert.NotNull(unsaved.GetAttachment("attach"));

        var saved = unsaved.Save();

        Assert.Equal(1, saved.AttachmentNames.Count());
        Assert.NotNull(saved.GetAttachment("attach"));

        unsaved = saved.CreateRevision();
        unsaved.RemoveAttachment("attach");

        // NOTE: The following two asserts will both fail.

        Assert.Equal(0, unsaved.AttachmentNames.Count());
        Assert.Null(unsaved.GetAttachment("attach"));
    }
}
```

**Comment by borrrden** [comment]
Interesting.  This probably won't take long to fix up.  Thanks for reporting it.

**Comment by jefflill** [comment]
...just trying to do my part :)

--Jeff

**Comment by borrrden** [comment]
I've put this test into our unit test suite and confirmed the problem with attachment names, but for me the `GetAttachment` call correctly returns null.  Perhaps it's something I've done since the 1.2 release.
