### ISSUE TITLE
Add alternate storage options for LiteServ.exe

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-net#662]
Perhaps, mimic-ing the way Mac OSX does it (via cmd line flag when starting) would be the simplest.

Need
- [x] ForestDB
- [ ] SQLCipher
- [ ] ForestDB + Encryption

**Comment by borrrden** [comment]
This is already present actually (check the --help).

**Comment by borrrden** [comment]
I see you checked off one, but ForestDB and ForestDB+Encryption are not different.  SQLCipher is the default now.  If you want to explicitly choose between SQLite and SQLCipher then let me know.
