### ISSUE TITLE
WebSocketChangeTracker does not support using cookies for authentication

### ISSUE THREAD

**Issue by pkramerzoll** [couchbase/couchbase-lite-net#667]
When the WebSocketChangeTracker is instantiated by the ChangeTrackerFactory, there is no mechanism for passing in a cookie when session-based authentication is being used. When the underlying WebSocketSharp.WebSocket is created and attempts to do a handshake with the server, an  exception is thrown that indicates authentication is required. When the session cookie is added to the WebSocket's existing cookie collection, the authentication is successful and the web socket works as expected.

The cookie set on the pull replication via the SetCookie method needs to be propagated to the Puller's ChangeTracker, which then needs to be propagated to the WebSocketSharp.WebSocket. The WebSocket class already contains a cookie collection and it would not need to be modified.

**Comment by borrrden** [comment]
Actually I had to modify the web socket library just to accept custom headers...what version did you try this with?  Try it with the latest package from http://latestbuilds.hq.couchbase.com/couchbase-lite-net/  I think the change I made should cover this too but let me know if it doesn't.

**Comment by pkramerzoll** [comment]
@borrrden Just downloaded 1.3 packages and tried again. Same error as previous version:

6/17/2016 9:51:20 AM|Fatal|WebSocket.connect|WebSocketSharp.WebSocketException: Requires the authentication.
                              at WebSocketSharp.WebSocket.doHandshake()
                              at WebSocketSharp.WebSocket.connect()

The cookie from the Pull replication is still not respected. Here is the puller code:

```
 Replication puller = db.CreatePullReplication(new Uri(_syncGatewayUrl));
            puller.Changed += PullReplication_Changed;
            puller.Channels = new[] { channel };
            puller.SetCookie(_currentSession.SessionName, _currentSession.SessionId, string.Empty, DateTime.MinValue, false, false);
            puller.Continuous = true;
```

**Comment by borrrden** [comment]
Right I remember now that they have a set cookie method.  This should not be hard to implement.  Thanks for the detailed report!
