### ISSUE TITLE
Create simple UWP sample

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-net#68]

**Comment by borrrden** [comment]
I started doing this...but now the spec for the API has changed a lot and so I can't continue until I take care of that...I'll still get it out by DB6 if possible though!

**Comment by borrrden** [comment]
The [mobile training todo](https://github.com/couchbaselabs/mobile-training-todo/tree/api-v2/dotnet) app now has a UWP frontend using the current 2.0 API.  It won't be finished until 2.0 is finished but a lot of basic functionality is working.  This is as far as the other platforms are so it is on par and enough to close this issue.
