### ISSUE TITLE
Add unit test for opening 1.3 databases from iOS/Android

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#684]
Reference:
https://github.com/couchbase/couchbase-lite-ios/issues/1314
https://github.com/couchbase/couchbase-lite-java-core/issues/1283

iOS 1.3.0 database files are here: 
https://github.com/couchbase/couchbase-lite-ios/tree/feature/issue_1314/TestData/replacedb/ios130
https://github.com/couchbase/couchbase-lite-ios/tree/feature/issue_1314/TestData/replacedb/ios130-forestdb

**Comment by borrrden** [comment]
Thanks for reminding me about this!  I will immediately post mine

**Comment by borrrden** [comment]
- [X] iOS
- [ ] Android
