### ISSUE TITLE
Add API for clearing OpenID auth token

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-net#685]

**Comment by pasin** [comment]
@borrrden There is an ongoing issue per discussion last week.

https://github.com/couchbase/couchbase-lite-ios/issues/1345

**Comment by pasin** [comment]
Also does the .NET cookie store per database? In iOS, we just changed the scope from per replicator to per database for 1.3.

**Comment by borrrden** [comment]
@pasin It is per replicator at the moment.  Are you saying we are going to move this method to Database instead?

**Comment by pasin** [comment]
Yes, we have just moved it for iOS.
