### ISSUE TITLE
Pusher not properly setting headers on HTTP requests

### ISSUE THREAD

**Issue by dmunch** [couchbase/couchbase-lite-net#687]
Hi,

we're currently looking into implementing a custom authorization scheme. 

Basically, all we'd need to do is to send an Authorization Header with each request, however we're  struggling in achieving this simple thing. Looking into the code it seems like `ICustomHeadersAuthorizer` should be the way to go, however all the interfaces in `Couchbase.Lite.Auth` seem to be internal. 

I'm currently looking into re-packaging a custom version of Couchbase.Lite, however that's something I'd really like to avoid. So before getting my hands dirty I was wondering about two things:

- Did I oversee something really simple?
- Are there plans in making those interfaces public in the middle to long term?

I'd be more than happy in providing a helping hand and pull requests if necessary.

Thanks a lot in advance, 
Daniel

**Comment by dmunch** [comment]
Ok my college just came up with an ugly solution involving reflection. 

    var clientFactoryProperty = push.GetType().GetTypeInfo().GetProperty("ClientFactory",   BindingFlags.Instance | BindingFlags.NonPublic);
    var clientFactory = clientFactoryProperty.GetValue(push);
    var HeadersProperty = clientFactory.GetType().GetTypeInfo().GetProperty("Headers",    BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);
    var headers = HeadersProperty.GetValue(clientFactory) as IDictionary<string, string>;
    headers["Authorization"] = $"Bearer {bearerToken}";

This works, but is far from ideal. Maybe there's a hidden bug somewhere, since there actually is a property `Headers` in `Replicator`, however setting it has now effect.

**Comment by borrrden** [comment]
Of course stuff using reflection will work but that means you are depending on implementation details.  We don't offer a way to make authenticators like this, but the way you are doing it is exactly the same as our new `OpenIDAuthenticator` class.  You can make a `POST` call using `HttpWebRequest` to Sync Gateway's `_session` endpoint and this will return a context to you (via a cookie) that you can set on the replicators.

I have made a sample for this on a branch, and you can see the flow starting [here](https://github.com/couchbase/couchbase-lite-net/blob/feature/openid-sample/samples/CouchbaseSample.iOS/AppDelegate.cs#L87).

**Comment by borrrden** [comment]
That being said, I just ran the unit test that [tests the Headers property](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs#L1759) and it passed.

**Comment by borrrden** [comment]
Things should be fixed now, let me know in a day or two, or I'll be closing this ticket.

**Comment by borrrden** [comment]
Get a build from our nightly build server

http://latestbuilds.hq.couchbase.com/couchbase-lite-net/

**Comment by dmunch** [comment]
Perfect! Just tested, the headers which we set via `Replicator.Headers` are sent as expected now. Thanks again for the quick fix. Is there any estimation when 1.3 will ship ?

**Comment by borrrden** [comment]
Estimated by the end of this month
