### ISSUE TITLE
Database connection fails to open when iOS apps launch in the background with phone locked

### ISSUE THREAD

**Issue by phamt** [couchbase/couchbase-lite-net#689]
Opening the sqlite database connection will fail due to file protection on iOS apps that launches in the background while the phone is locked.  Currently the default file protection is Complete Unless Open.  This needs to change to None or provide an API to set the file protection to None.

Some uses cases where this occur is if an iOS app uses locations service such as region monitoring that will start/launch the app in the background while the phone is locked and the app is not already running in the background.  Or if an app is launch in the background via usage of an Apple Watch.

**Comment by borrrden** [comment]
This has been a thorny issue for the Objective-C version as well.  There is an API on Manager to change this setting for the database file, but it may or may not be overriden by the setting I have on the actual sqlite file itself.   Can you try using the `ManagerOptions.FileProtection` property when opening the manager?

**Comment by phamt** [comment]
@borrrden 
The only accessible option in ManagerOptions is ManagerOptions.Default

**Comment by borrrden** [comment]
Well yes, you need to make a new instance of `ManagerOptions` and pass it into the `Manager` constructor (i.e. not use `Manager.SharedInstance`)

**Comment by borrrden** [comment]
@phamt Has this helped?

**Comment by phamt** [comment]
@borrrden 
]Yes, creating a new instance of ManagerOptions and setting the FileProtection level to FileProtectionNone fixes the issue I was running into.

**Comment by borrrden** [comment]
Ok, closing this ticket

**Comment by phamt** [comment]
@borrrden This appears to still be an issue with iOS 10.  Even though the file protection level is set to FileProtectionNone, I am still seeing field crashes with devices running iOS 10.x.x with the following exception Couchbase.Lite.CouchbaseLiteException: Failed to open SQLite storage engine at path

I'm seeing this with the latest version 1.3.1.
