### ISSUE TITLE
Xamarin Android secure storage can't delete all tokens

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-net#692]
Need a way to group them by label and/or service (already implemented in iOS and desktop).

**Comment by borrrden** [comment]
@hideki I think this issue will also be present in Java.  The LocalUUID can be null, which means to delete all tokens with the given parameters regardless of UUID.

**Comment by hideki** [comment]
Hi @borrrden, I believe `LocalUUID` is actually `publicUUID`, it should not be `null`.

**Comment by borrrden** [comment]
Jens has a specific note on his that says null there means delete all (used for the static forgetidtokens method)

**Comment by pasin** [comment]
I think iOS static forgetIDTokensForServer: method is used only the unit test.

**Comment by borrrden** [comment]
@pasin That makes sense

**Comment by borrrden** [comment]
This is limited to internal testing, and there is currently not a better way to do it.  It is not really hurting anything so I am closing this.
