### ISSUE TITLE
Xamarin Android SIGSEGV on unit test

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-net#694]
TestParallelViewQueries crashes with ForestDB

**Comment by sethrosetter** [comment]
@borrrden What is the output in logcat / what version / arch of Android are you using?

**Comment by borrrden** [comment]
I don't have the exact output at the moment but it is SIGSEGV on c4view_query every time. Nexus 5 6.0.1 arm7

**Comment by borrrden** [comment]
Oops, I forgot -O0 is "disable optimization" and so is not an acceptable fix
