### ISSUE TITLE
Response status codes during replication

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-net#695]
Original discussion: http://stackoverflow.com/questions/38416841/xamarin-visual-studio-android-c-sharp-how-to-validate-couchbase-lite-credentials

couchbase-lite-java-core subclasses `IOException` in [RemoteRequestResponseException](https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/RemoteRequestResponseException.java) to make the status code available to the application.

couchbase-lite-ios uses the `NSError.code`.

Not sure if this functionality is already available. I ran `push.LastError` and `pull.LastError` in the immediate window and got the following:

```
> pull.LastError
{System.Exception: Change tracker stopped during continuous replication}
	Data: Count = 0
	HResult: -2146233088
	HelpLink: (null)
	InnerException: (null)
	Message: "Change tracker stopped during continuous replication"
	Source: (null)
	StackTrace: (null)
	TargetSite: (null)
	Non-public members: 
````

Xamarin Android
CBL: `Starting Manager version: .NET unknown Android SDK built for x86 API23/x86 1.2.1/434a743`

**Comment by borrrden** [comment]
Any error will overwrite the previous one so there may have been others before the one you got.  There is no real specification for what errors should be stored here, but you should watch the `Changed` event for errors.  The one you are looking for is `HttpResponseException` I think.

**Comment by jamiltz** [comment]
Oh so I should downcast it to `HttpResponseException` to get the status (same as Java version). I didn't try that.

**Comment by jamiltz** [comment]
Verified it's on HttpResponseException. Added to docs in https://github.com/couchbaselabs/couchbase-mobile-portal/commit/5cc9b8c3c64386485b2d1ed45e195a325b845ce2.
