### ISSUE TITLE
Listener crashes against Mono 4.4.1 on MacOS

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-net#697]
The custom `Mono.Security` packaged in the CBL listener nuget is not compatible with Mono 4.4.x, which moved some types around (e.g. [bug 40482](https://bugzilla.xamarin.com/show_bug.cgi?id=40482). When the first document `POST` to the running listener arrives, it will fail to resolve `SslStream` (note: my configuration is not enabling SSL):
```
System.TypeLoadException: Could not load type 'System.Net.Security.SslStream' from assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```
Adding a manual reference to the `Mono.Security` in the GAC resolves this issue, albeit at the loss of your patches in the `Mono.Security.dll` bundled in the Couchbase.Lite.Listener nuget.

**Comment by sethrosetter** [comment]
@zgramana What version of CBL are you using?

**Comment by borrrden** [comment]
I thought this was something I had already run into and fixed (our functional tests run on OS X after all)

**Comment by zgramana** [comment]
This is new in 4.4.1. The hard part will be supporting multiple custom Mono.Security.dlls since nuget doesn't really offer such a capability.

**Comment by borrrden** [comment]
In theory an updated mono.security.dll should mean proper TLS support (via mono new TLS) which means I won't need the custom dll anymore (except for the x509generator on Windows). Is 4.4.1 in stable now ?  Well I'll check this out myself tomorrow first thing.

**Comment by zgramana** [comment]
Yes. It is in stable.

**Comment by borrrden** [comment]
Hmm, so it is the version I have already been using without issue for the past X months.  Is this with 1.2.1 or with the nightlies?

**Comment by zgramana** [comment]
1.2.1

**Comment by borrrden** [comment]
The workaround for this is acceptable and 1.3 works for the newer runtime so I am closing this.

**Comment by zgramana** [comment]
👍🏻Your solution in 1.3 works nicely.
