### ISSUE TITLE
SimpleAndroidSync: API 14 not showing as compatible deployment target.

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-net#699]
- Check out feature/open-id-sample
- Create an API 14 Arm emulator
- Try to deploy android sample to that emulator.

**Comment by borrrden** [comment]
I thought we were only supporting API 15+.  What was the minimum API level you were able to download that time when we went through this exercise?  Anyway "not showing as a compatible deployment target" really just means something in the Android manifest is off.
