### ISSUE TITLE
Implicit Flow (Android): No ID Token returned

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-net#700]
- check out feature/open-id-sample
- Using SimpleAndroidSync sample
- Click the `Sign In` button to initiate implicit flow.
- Enter google login info
- A warning, "No token-id" is returned

Auth flow works as expected.

**Comment by sethrosetter** [comment]
This is a configuration issue after debugging with @pasin. Not a release blocker.

**Comment by borrrden** [comment]
Yes, sorry.  I already knew that and I thought I had told you about it.
