### ISSUE TITLE
Replication Changed Event not firing for 401 Unauthorized when using custom authentication

### ISSUE THREAD

**Issue by smulrich** [couchbase/couchbase-lite-net#703]
I am experiencing behavior similar to a bug that was submitted and closed on the java codebase:
https://github.com/couchbase/couchbase-lite-java-core/issues/576

For my continuous replicator, I am using custom authentication by manually authenticating through Auth0 and then setting the Cookie with Replication.SetCookie().  Sync works fine until something happens with the session that would cause the server to return 401 Unauthorized during replication (for example, if a user's session gets deleted).  In that case, the "Changed" event is never fired and I get the following debug output:

`Replication
    Http Message failed to send: Method: POST, RequestUri: 'http://myserver/sync_gateway/_revs_diff', Version: 1.1, Content: System.Net.Http.ByteArrayContent, Headers:
    {
    Accept: multipart/related,  application/json
    User-Agent: CouchbaseLite/1.2 (.NET motorola Nexus 6 API23/armeabi-v7a 1.2.1/434a743)
    Connection: keep-alive
    Content-Type: application/json
    }
Replication: Http exception
    [HttpResponseException: StatusCode = Unauthorized]
Replication
    	Failed content: {...}
Replication
     Progress: set error = [HttpResponseException: StatusCode = Unauthorized]`

I believe the behavior should be that the Changed event should fire with LastError equal to HttpResponseException so that I can discover this error and either retry the login or log the user out of the app depending on the scenario.

@borrrden mentions using IChallengeResponseAuthenticator in the discussion.  Should I be using this interface for my custom authentication?  Is there documentation somewhere on how to use it?

**Comment by borrrden** [comment]
Can you try with build 143 from https://latestbuilds.hq.couchbase.com/couchbase-lite-net and see if that makes a difference?

**Comment by smulrich** [comment]
I'm not sure if it's my corporate firewall or what but I can't access that site.  I am on the 1.2 Nuget package.  I can try 1.3-pre1 if that would help.

**Comment by borrrden** [comment]
I made a mistake in the URL, the correct one is  http://latestbuilds.hq.couchbase.com/couchbase-lite-net (not HTTPS)

**Comment by smulrich** [comment]
just tried it with build 143.  The app no longer hard crashes due to uncaught exception, so that's good!  However the exception is not bubbling up through the Changed event.  I did get changed event with Status = Stopped but the LastError was null.

Here is some of the debug output, it repeats this a lot.  I assume on each sync attempt.  (Note that I changed the url in the debug output to just "myserver" to protect the innocent.)

> <---
> 
> WARN) SYNC (RemoteSession): [11] 2016-7-28 10:36:26.576-04:00 	Failed content: <redacted>
> INFO) SYNC (Replication): [11] 2016-7-28 10:36:26.590-04:00 Error set during replication (application may continue):
> [HttpResponseException: StatusCode = Unauthorized]
> INFO) SYNC (Replication): [11] 2016-7-28 10:36:26.604-04:00 NotifyChangeListeners (0/0, state=Idle (batch=66, net=1))
> WARN) SYNC (RemoteSession): [17] 2016-7-28 10:36:26.922-04:00 Http Message failed to send, or got error response, passing to callback... http://myserver:4984/sync_gateway/_revs_diff, :
> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> [HttpResponseException: StatusCode = Unauthorized]
>   --- End of inner exception stack trace ---
>   at Couchbase.Lite.CouchbaseLiteHttpClient+<SendAsync>c__AnonStorey2.<>m__1 (System.Threading.Tasks.Task`1 t) [0x00047] in /Users/jenkins/jenkins/workspace/couchbase-lite-net-build/1.3.0/Android/couchbase-lite-net/src/Couchbase.Lite.Shared/Replication/CouchbaseLiteHttpClient.cs:114 
>   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2[TAntecedentResult,TResult].InnerInvoke () [0x00027] in /Users/builder/data/lanes/3415/7db2aac3/source/mono/external/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:207 
>   at System.Threading.Tasks.Task.Execute () [0x00016] in /Users/builder/data/lanes/3415/7db2aac3/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2502 
> ---> (Inner Exception #0) [HttpResponseException: StatusCode = Unauthorized]<---
> 
>   --- End of inner exception stack trace ---
> ---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> [HttpResponseException: StatusCode = Unauthorized]
>   --- End of inner exception stack trace ---
>   at Couchbase.Lite.CouchbaseLiteHttpClient+<SendAsync>c__AnonStorey2.<>m__1 (System.Threading.Tasks.Task`1 t) [0x00047] in /Users/jenkins/jenkins/workspace/couchbase-lite-net-build/1.3.0/Android/couchbase-lite-net/src/Couchbase.Lite.Shared/Replication/CouchbaseLiteHttpClient.cs:114 
>   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2[TAntecedentResult,TResult].InnerInvoke () [0x00027] in /Users/builder/data/lanes/3415/7db2aac3/source/mono/external/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:207 
>   at System.Threading.Tasks.Task.Execute () [0x00016] in /Users/builder/data/lanes/3415/7db2aac3/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2502 
> ---> (Inner Exception #0) [HttpResponseException: StatusCode = Unauthorized]<---
> <---
> 
> WARN) SYNC (RemoteSession): [17] 2016-7-28 10:36:26.942-04:00 	Failed content: <redacted>
> INFO) SYNC (Replication): [17] 2016-7-28 10:36:26.954-04:00 Error set during replication (application may continue):
> [HttpResponseException: StatusCode = Unauthorized]
> INFO) SYNC (Replication): [17] 2016-7-28 10:36:26.967-04:00 NotifyChangeListeners (0/0, state=Running (batch=0, net=1))
> INFO) SYNC (Replication): [17] 2016-7-28 10:36:26.979-04:00 NotifyChangeListeners (0/0, state=Idle (batch=0, net=0))

**Comment by borrrden** [comment]
Are you checking `LastError` on the replication object, or on the event arguments?

**Comment by smulrich** [comment]
My code checks args but replication object LastError is null also.

**Comment by smulrich** [comment]
I also only get the Stopped event once.  Though this error seems to be repeated over and over on the debug console as CBL tries to sync.

**Comment by borrrden** [comment]
This is odd, are you using the callback for more than one replication?  As soon as an error is set in the replication, it calls the Changed event (which happens two lines after the logging output you got).  You should always use the `args` properties because there is no telling if the replication object has changed its values between the time the event was created and the time that it was fired.

**Comment by borrrden** [comment]
Also, the logging output you show doesn't ever show the replication stopping.  Instead it goes to idle (which also probably needs to be fixed)

**Comment by smulrich** [comment]
One possibly unique thing I am doing is changing the Channels on the replicator by tearing down and starting a new one.  I stop the existing one, unsubscribe the event handler, then declare a new one with the updated channels, and start it.  It gets the Changed events for other errors fine (network timeout for example).

**Comment by smulrich** [comment]
Here is another spot where this error comes up:

```
Xamarin caused by: android.runtime.JavaProxyThrowable: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.AggregateException: One or more errors occurred. ---> [HttpResponseException: StatusCode = Unauthorized]
  --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (Boolean includeTaskCanceledExceptions) [0x00014] in /Users/builder/data/lanes/3415/7db2aac3/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2157 
  at System.Threading.Tasks.Task`1[TResult].GetResultCore (Boolean waitCompletionNotification) [0x00034] in /Users/builder/data/lanes/3415/7db2aac3/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Future.cs:562 
  at System.Threading.Tasks.Task`1[TResult].get_Result () [0x00000] in /Users/builder/data/lanes/3415/7db2aac3/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Future.cs:532 
  at Couchbase.Lite.Replication+<SendAsyncMultipartDownloaderRequest>c__AnonStorey5.<>m__0 (System.Threading.Tasks.Task`1 responseMessage) [0x002d2] in /Users/borrrden/Development/couchbase-lite-net/src/Couchbase.Lite.Shared/Replication.cs:1407 
  at System.Threading.Tasks.ContinuationTaskFromResultTask`1[TAntecedentResult].InnerInvoke () [0x00027] in /Users/builder/data/lanes/3415/7db2aac3/source/mono/external/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:159 
  at System.Threading.Tasks.Task.Execute () [0x00016] in /Users/builder/data/lanes/3415/7db2aac3/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2502 
---> (Inner Exception #0) [HttpResponseException: StatusCode = Unauthorized]<---

```

**Comment by borrrden** [comment]
By the way you said "Crashes due to uncaught exception" and I notice some similar wording to issue #664 -> "A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property"

However, I have not been able to reproduce this behavior.  Do you happen to know if it is some kind of setting?

**Comment by borrrden** [comment]
@smulrich I tracked down the issue, the details are in the linked ticket above this comment.

**Comment by smulrich** [comment]
Thanks!  I'm not seeing this anymore since the last update (1.3.1).
