### ISSUE TITLE
SQL Exception caused by trying to query non-existent `maps_#` table

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-net#710]
### Given
On a clean CBL (1.2 and 1.3 RC) instance, I create two views, a map-only `foo` and map-reduce `bar`. The first, `foo`, is created fine and works as expected on subsequent openings of the existing database and view. The second, `bar` appears to be created fine. I can issue a query, see the docs get indexed, and enumerate the results. The next time that I open the database, I retrieve the `bar` view and attempt to query it and enumerate the results.
### Expected
The ability to iterate through the query results.
### Observed
The attempt to advance to the first `QueryRow` results in this exception:
```
SqlitePCLRawStorageEngine: Error executing raw query 'SELECT key, value, docid, revs.sequence FROM 'maps_2', revs, docs WHERE 1  AND revs.sequence = 'maps_2'.sequence AND docs.doc_id = revs.doc_id ORDER BY key, docid LIMIT ? OFFSET ?'
    21: 
    SQLitePCL.Ugly.ugly+sqlite3_exception: Exception of type 'SQLitePCL.Ugly.ugly+sqlite3_exception' was thrown.
      at SQLitePCL.Ugly.ugly.step (SQLitePCL.sqlite3_stmt stmt) [0x00017] in <filename unknown>:0 
      at Couchbase.Lite.Cursor..ctor (SQLitePCL.sqlite3_stmt stmt) [0x0001c] in <filename unknown>:0 
      at Couchbase.Lite.SqlitePCLRawStorageEngine+<IntransactionRawQuery>c__AnonStorey1.<>m__0 () [0x00027] in <filename unknown>:0 
SqliteCouchStore: Error executing SQL query
    21: 
    SQLitePCL.Ugly.ugly+sqlite3_exception: Exception of type 'SQLitePCL.Ugly.ugly+sqlite3_exception' was thrown.
      at SQLitePCL.Ugly.ugly.step (SQLitePCL.sqlite3_stmt stmt) [0x00017] in <filename unknown>:0 
      at Couchbase.Lite.Cursor..ctor (SQLitePCL.sqlite3_stmt stmt) [0x0001c] in <filename unknown>:0 
      at Couchbase.Lite.SqlitePCLRawStorageEngine+<IntransactionRawQuery>c__AnonStorey1.<>m__0 () [0x00027] in <filename unknown>:0 
```
### Notes
In tracing through my code into CBL, I observed that when the `bar` view was first created, the `ViewID` was defaulting to `0` because it the query doing so was using a read-only connection following read-committed semantics. The insert to the `views` table was succeeding, so the `ViewID` should have been `2`. However, because of transaction count was around 3, the transaction itself was not committed until after the above query runs. As a result, the DDL creating the `maps_#` table is executed with a value of `0` instead of `2` resulting in a `maps_0` table. During the subsequent opening of the database, CBL rightly looks for a `maps_2` table and doesn't find it.

### Proposed Fix
It's [apparent](https://www.sqlite.org/lang_savepoint.html) that whether or not a given query needs to read-committed or read-uncommitted depends not only on the current transaction's scope, but also on the scope of any outer transactions they may be nested inside of. Since users can, and are indeed recommended to, wrap internal transactions in an outer transaction via `RunInTransaction`, code that in one context work fine with read-committed semantics can fail in others. The quick fix below addresses this by assuming read-uncommitted for that `ViewID` lookup call.

A more robust fix might be to determine a maximum safe `_transactionCount` per operation. When at, or below, that value at the beginning of an operation, use the read-only connection for performance enhancement. When above that threshold, use the writer connection for read-uncommitted semantics to ensure correctness.
```diff
diff --git a/src/StorageEngines/SQLiteCommon/storage.sqlite.common/src/SqliteViewStore.cs b/src/StorageEngines/SQLiteCommon/storage.sqlite.common/src/SqliteViewStore.cs
index 71dd94e..96c9f02 100644
--- a/src/StorageEngines/SQLiteCommon/storage.sqlite.common/src/SqliteViewStore.cs
+++ b/src/StorageEngines/SQLiteCommon/storage.sqlite.common/src/SqliteViewStore.cs
@@ -104,7 +104,7 @@ namespace Couchbase.Lite.Storage.SQLCipher
         {
             get {
                 if (_viewId < 0) {
-                    _viewId = _dbStorage.QueryOrDefault<int>(c => c.GetInt(0), false, 0, "SELECT view_id FROM views WHERE name=?", Name);
+                    _viewId = _dbStorage.QueryOrDefault<int>(c => c.GetInt(0), true, 0, "SELECT view_id FROM views WHERE name=?", Name);
                 }
 
                 return _viewId;
```

**Comment by borrrden** [comment]
It's interesting that this has not come up before throughout any testing or projects.  Is the difference here creating two views in the same transaction?  This is something I'd like to make a unit test for asap.

**Comment by zgramana** [comment]
It appears like the reproduction case is to call `GetView` once outside of, and then once inside of, a `RunInTransaction` block.

**Comment by borrrden** [comment]
Ok, so to cause this is was actually the reverse.  Create the views *inside* a transaction and observe that their IDs are both 0.  They should be 1 and 2.  I put into place my plan for handling this, as well as a unit test that failed before and passed after the fix (Other relevant tests also pass for sanity check).  This will look like a big commit but most of it is just factoring out the `readUncommit` argument, which will now be determined automatically using this simple metric:

If the library is currently operating on the internal database thread, everything will get read from the privileged (uncommit) connection.  All other threads will use the read only connection.  This has the side effect that a user can query uncommitted information while running in a transaction but if they are going to query inside of a transaction and use the results I'd want them to be accurate anyway.

So the tl;dr is "if _transactionActive && _onDBThread -> read uncommit; else read commit"
