### ISSUE TITLE
Replication - Inconsistent Number of Documents After Replicating

### ISSUE THREAD

**Issue by kf2093** [couchbase/couchbase-lite-net#719]
I am testing a Xamarin iOS and Android app with the Couchbase Lite .NET libraries and am finding that once replication is in sync (or as reported by the library), the number of documents in the mobile Couchbase Lite db is less than the actual number of documents in the CouchDB database which I replicated to.  Also, after trying this several times the number that actually sync to the mobile app varies.

This happens on both an iPhone 4 and a OnePlus 3 (android).  I am not sure what to do, however this seems to be a show stopper.  I am using version 1.3.  I did not see this behaviour in version 1.2.

**Comment by borrrden** [comment]
Hmmm, I am going to need a bit more info on this.  Can you confirm that with all else equal this problem happens on 1.3 and not 1.2?  Is the CouchDB instance being changed?  Is this a push or a pull?  It looks like a pull.  How are you started and monitoring the replication?  Are there any errors in the logs?  Couchbase will log to the device console of both.

**Comment by kf2093** [comment]
The problem happened only on a particular CouchDB instance (which is the instance we use, a different test instance works fine).  However, the problem was not seen on version 1.2, it was seen only on those devices having 1.3.  

Our case has two phases.  In phase 1 we load the required documents into CouchDB, after we sync our devices to the CouchDB instance.  Once we are done with our experiment, in the next phase, we remove all documents from the CouchDB instance and also delete all instances of the CBL databases.  Could this cycle be causing an issue?

We are starting both continuous replications for pull and push initiated on the devices (initially there is only data inside of CouchDB).  We are using CBL's status and performance indicators to determine when the replication is Idle.  

I have to get a setup whereby I can check the logs (currently we are using a Release version) and will revert.

**Comment by kf2093** [comment]
I'm attaching the full debug output.  I have 2090 documents in the CouchDB.  The old version (using CBL 1.2) correctly syncs all documents.  The new version reported just over 1400 documents synced whilst the pull replication stated that it was complete (idle).

[debug.txt](https://github.com/couchbase/couchbase-lite-net/files/435809/debug.txt)

**Comment by borrrden** [comment]
Just so you know, the numbers there are not "document" counts, but "changes feed" counts.  When you make a request to the CouchDB changes feed, what is the final sequence that is shown?  It looks like your local database has up to sequence 1920.

**Comment by kf2093** [comment]
According to CouchDB there are 2090 documents. On the old version with CBL 1.2 I retrieve the document count using GetDocumentCount() and it matches what it should be (2090).

On the new version I believe it was around 1400 (but perhaps it was 1920).  Nonetheless, the document count doors not match the expected count.

**Comment by kf2093** [comment]
I've executed another test on an iPod Touch (using CBL .NET 1.3 in Xamarin).  The log is attached.  After performing a pull replication GetDocumentCount() returns 1423.  When there is 2090 documents in CouchDB.  I'll try to setup a publicly accessible CouchDB repository, perhaps it will help test.

[1423.txt](https://github.com/couchbase/couchbase-lite-net/files/436518/1423.txt)

**Comment by kf2093** [comment]
I've created a public CouchDB instance here: 
54.191.248.4:5984

The CouchDB database name is tixrep.  It has 2109 documents.  

After replicating using CBL .NET 1.3 in a Xamarin app on Android (OnePlus 3): 1681 documents are replicated
CBL .NET 1.3 in a Xamarin app on iOS (iPod Touch): 1166 documents are replicated

I'm attaching the logs for both.  Let me know if I can help in some way.  Thanks!

[1681android.txt](https://github.com/couchbase/couchbase-lite-net/files/437147/1681android.txt)
[1166ios.txt](https://github.com/couchbase/couchbase-lite-net/files/437148/1166ios.txt)

**Comment by borrrden** [comment]
Thanks this will be very helpful!

**Comment by borrrden** [comment]
When I try this on my end, I'm getting some weird exceptions about invalid JSON from CouchDB (unterminated string).  That is causing the replication to stop prematurely on Android.  I also see in your logs that your connection was closed or something (stream disposed).  I'll investigate this some more.

**Comment by borrrden** [comment]
Can you describe your setup?  This is definitely not a normal thing to happen.  The feed gets sort of cut off right in the middle of transfer.  It seems to happen around the same point every time too.  Are there any proxies or load balancers at play here?

**Comment by kf2093** [comment]
This setup has a single wifi router.  iPods and Android devices connect directly to the wifi router.  The first two logs are from a test where the CouchDB instance was on a local machine (connected to the same wifi router).  The last two logs are from a test where the CouchDB was on the public CouchDB instance specified above.

Out of the 4 logs attached 3 of the logs state that there was a JSON deserialisation error.  Replication stops after the error.  

I reverted back to 1.2.1.1 CBL .NET libraries, and everything worked fine :S

**Comment by borrrden** [comment]
Do you happen to have the 1.2 logs as well?

**Comment by kf2093** [comment]
Here's the logs for a test I just did now with the public CouchDB instance on android (finished replicating to 2109 docs correctly).

[ok1211android.txt](https://github.com/couchbase/couchbase-lite-net/files/438317/ok1211android.txt)

**Comment by borrrden** [comment]
One of the differences between 1.2.1 and 1.3 is that the library will use POST _changes by default now instead of GET _changes.  Sending a POST request via postman returns accurate results, but for some reason this issue is happening when reading from the result of the request (maybe because it is streaming it bit by bit?).  Are there are configuration things you are aware of with GET vs POST?  When I forced the library to use GET, then the issue resolved.

**Comment by kf2093** [comment]
Unfortunately not.  I create the pull and push replications, set them to continuous and then start them.

**Comment by borrrden** [comment]
Something in the environment is causing this, and not a logical issue.  What I meant is, perhaps the public instance has a misbehaving load balancer or proxy.  When I traced with Wireshark, the response to the POST _changes request was incomplete, but the one from GET was complete.

**Comment by borrrden** [comment]
Anyway, I may not be able to find the root cause of this, but I did find a way to combat the symptoms.  There is an actionable item to come out of this, and that is to ensure that in this situation that the replicator enters the retry loop (it is failing to in this case).  If the retry loop is set at 60 seconds that unfortunately means that there will be some large delays in getting the data but it is better than not getting it (and the 60 seconds is adjustable).  From my experimentation the retry loop runs 2 - 3 times before successfully completing.

**Comment by kf2093** [comment]
Would it be possible to have a workaround for the short term where by one can specify that they would like to use GET _changes?

**Comment by borrrden** [comment]
For the time being I don't know if I will be able to add this as an options because it requires a consensus with the other leads.  If you want to experiment yourself though, just change [this line](https://github.com/couchbase/couchbase-lite-net/blob/4634a098a2cab8667874f40dcb61b1fb254922e3/src/Couchbase.Lite.Shared/Replication/ChangeTracker.cs#L208) to be false.

**Comment by hideki** [comment]
API Request: https://github.com/couchbaselabs/couchbase-lite-api/issues/162

**Comment by borrrden** [comment]
Potential implementation on `issue/#719` branch

**Comment by borrrden** [comment]
@kf2093 Does the work on that branch look like it will help?

**Comment by kf2093** [comment]
I'll test this out this week and will let you know.

Thanks!

**Comment by kf2093** [comment]
I'm having some troubles using the branch in xamarin.  I've managed to build the dlls:

however when I try to create a nuget package as per instructions from ( https://github.com/couchbase/couchbase-lite-net/tree/master/packaging ) I cannot find the create_package.sh file.  I've tried to create the nuget package manually, using 'nuget pack couchbase-lite.nuspec' however this complains that a staging directory does not exist.  (I need to dig deeper into how nuget works)

I've also tried to create a xamarin component using the instructions in the packaging directory (mono xamarin-component.exe package) however, a warning states that nothing has been built (although I build the dlls in xamarin).   Upon using the xam component in xamarin it then requires a very old version of stateless.

I've also tried to use the dlls built directly in xamarin, however upon building I receive errors that references to System.Net.Http and other references do not exist.  I tried to manually include references to all the ones it complained about, and did manage to compile my application, however upon loading calling a CBL function (new CouchbaseLiteTcpListener(Manager.SharedInstance, 5984)) I received an error due to type loading.

I need to dig a bit deeper into xamarin/nuget/components as I am new to it.  However this is going to take me a while.  If you can wait I may manage to get something working, however if it would be good to have feedback before could you send me nuget packages that I could use?

Sorry about this but I'm new to all this.

**Comment by borrrden** [comment]
Those instructions are out of date, but you are going to have to build everything if you want to make nuget packages so it might not be practical.  It would be better to just add a project reference to the various projects (Couchbase.Lite, Couchbase.Lite.Storage.*, Couchbase.Lite.Listener).  This will ensure that it is built when your project is.  

If you want to build nuget packages you should build all the solutions with the Packaging configuration (as opposed to Debug / Release).  This will ensure everything is copied to the staging directory.

**Comment by kf2093** [comment]
Excellent, I can confirm that this issue has been fixed in the branch.  Thanks :)

**Comment by kf2093** [comment]
Actually, I need to do some more testing.. I've just had a problem with one of the devices.  I've changed _usePost to false and it helped.  I'll do some more testing and will get back.

**Comment by borrrden** [comment]
@kf2093 Ping for update.  I'm ready to merge this branch.

**Comment by kf2093** [comment]
Setting _usePost to false fixes the problem.  Other than that should it work without setting _usePost to false?  Is there some other API call that should be used?  I've tested it and still saw the same issues.

**Comment by borrrden** [comment]
The point of the branch was that now there is a replication option to specify using post or get. Did you notice that change?

**Comment by kf2093** [comment]
I hadn't noticed the replication option.  I'll try this out and will let you know.

**Comment by borrrden** [comment]
@kf2093 What is the update on this?

**Comment by kf2093** [comment]
Sorry for the terribly late reply.  I had troubles compiling the code and have finally figured out how to do it.  This solved the problem for me :)

**Comment by borrrden** [comment]
@kf2093 In the end we opted to not go for this solution and simply restore the old behavior since so many non-SG clients have trouble with POST _changes.

**Comment by borrrden** [comment]
@kf2093 Sorry for the inconvenience, could you check the rebased issue 719 branch?  It doesn't have the replicator option any more but it will default to GET now until it detects that it is talking to Sync Gateway.

**Comment by kf2093** [comment]
Branch 719 solves the issue for me.

Thanks!
