### ISSUE TITLE
All the attachment blobs are deleted from the filesystem.

### ISSUE THREAD

**Issue by ylatuya** [couchbase/couchbase-lite-net#720]
We are using Couchbase.Lite 1.2.1 in a desktop application working on Windows, Linux and OS X and we have received 2 bug reports from our users with database issues.

After examining the database, we saw that the attachements folder was empty, all the attachments files were deleted even though the documents referencing these attachements are still in the DB. So when we try the access to the Attachments contents, an exception is thrown.

`
Attachment attachment = rev.GetAttachment (attachmentName);

return Image.Deserialize (attachment.Content.ToArray ());
`

>[Warn  13:09:12.644] Caught an exception - System.NullReferenceException: Object reference not set to an instance of an object (in `Couchbase.Lite')
  at Couchbase.Lite.StreamExtensions.Reset (System.IO.Stream stream) <0x119298ee0 + 0x0000b> in <filename unknown>:0 
  at Couchbase.Lite.Attachment.get_ContentStream () <0x1192960f0 + 0x000ee> in <filename unknown>:0 
  at Couchbase.Lite.Attachment.get_Content () <0x119295fd0 + 0x00026> in <filename unknown>:0 

We have a user base of around 6000 users and we have just seen this bug happening 2 times in the last months. We haven't been able to reproduce it ourself, but the issue is pretty critical since it could potencially happen again.

I am sorry that we can't add more info to this bug report, but maybe some with knowledge in the code base is able to understand we might be wrong.

**Comment by borrrden** [comment]
That exception itself is something I've seen before and fixed in 1.3.  I've never seen attachments just randomly disappear before though.  Are you calling compact?

**Comment by ylatuya** [comment]
This exception does not seems a programming issue, it just because the file is missing for real. Migrating the database to 1.3 shows a different exception but for the same issue :)

We do call compact once per day.

We have developed an ORM using Couchbase.Lite, the code serializing our objects into documents is [here](https://github.com/fluendo/VAS/blob/master/VAS.DB/DocumentsSerializer.cs). Image properties are converted into attachment using the ImageConverter and that were are are hitting de issue with attachments, but just because the blobs are not there anymore.

gibhub doesn't let me attach a zip file, it complains about not supporting the file type even if zip files are support so I'll put a link here: https://drive.google.com/file/d/0B6hp5-hB-bx1d0NvT2FVRWZUOGs/

**Comment by borrrden** [comment]
Well the exception shouldn't be a null reference exception is what I mean.  If the file is missing then an exception is going to be thrown.  I'm more concerned about why the file is missing.  Without that information I can't move on this.

**Comment by ylatuya** [comment]
We are both concerned about the same problem then :) For some reason, Couchbase.Lite removed all the blobs from the filesystem, and that's the reason why this issue was open. There is a bug somewhere that's deleting blobs from the filesystem, even if the attachment is still in the database.

**Comment by borrrden** [comment]
Unfortunately "For some reason" is not something I can work with.  I need to see this bug in action if I am going to attempt to do anything about it.  I'll try writing a few more unit tests revolving around attachments and compaction to see if I can find anything.

**Comment by borrrden** [comment]
I added in a test to try compacting at various stages and observing attachment behavior but the behavior is correct.  Furthermore, I looked at the link and that is *not* a 1.2.1 database file.  It looks like a 1.1 style database.  Is there an older version of your app floating around perhaps?

**Comment by ylatuya** [comment]
Hi,
I was wrong with the versions, the one shipped with the current release is 1.1 and we will ship 1.3 with the next release.
Thanks for taking the time on reviewing it and adding all the unit tests, let's hope this issue is no longer present in 1.3. I will reopen the if we receive other bug reports.
