### ISSUE TITLE
v1.3 GetPendingDocumentIDs value is cached while offline for Push

### ISSUE THREAD

**Issue by Steven-Mark-Ford** [couchbase/couchbase-lite-net#724]
It is common for our client app to be used in areas of no/poor connectivity/ and we need the device to correctly report on the number of documents pending push (i.e. those stuck on the device) when in an offline state. However, currently the Replication object will cache the GetPendingDocumentIDs value when in this state.
snippet from GetPendingDocumentIDs():

```
if (IsPull || (_stateMachine.State > ReplicationState.Initial && _pendingDocumentIDs != null)) {
   return _pendingDocumentIDs;
}
```

The problem is that for push the above expression is always true when offline because _pendingDocumentIDs is only set to null in the NotifyChangeListeners(ReplicationStateTransition transition = null) method which is not called while offline.

**Comment by Steven-Mark-Ford** [comment]
I tried simply removing the following condition:
`(_stateMachine.State > ReplicationState.Initial && _pendingDocumentIDs != null)`
This resolves the issue in that it now updates the pending document count when offline but it introduces a new issue where on first time starting the app (from a fresh sync / clean db) the pull causes the pending pushes count to grow (like false pending pushes) so say it pulls 1000 changes there will be approx. 1000 pending push changes until I actually add/modify a document then it pushes that change and the PendingDocumentIDS then returns correctly to 0 and behaves correctly from there.

This seems to be caused because on first time loading the app from a clean DB "LastSequence" remains  0 for pusher until an actual doc is modified or added. but when lastSequence of 0 is passed to the following:
```
var revs = LocalDatabase.UnpushedRevisionsSince(lastSequence, LocalDatabase.GetFilter(Filter), FilterParams);
 if (revs != null) {
         _pendingDocumentIDs = new HashSet<string>(revs.GetAllDocIds());
         return _pendingDocumentIDs;
}
```
UnpushedRevisionsSince just keeps returning a larger number as the initial pull continues.

**Comment by borrrden** [comment]
Looks like the implementation of this has changed in the reference source since I ported it.  I'll make sure that the updated implementation gets ported soon!  Thanks for finding so many issues, by the way.  Developing a library like this leads to tunnel vision especially when developing on a one-man team ;).

**Comment by Steven-Mark-Ford** [comment]
@borrrden Glad you going to resolve this in 1.4 

In the interim, I would much appreciate any thoughts/example on the approach to resolve the issue I experienced (as mentioned in previous comment) once I had removed the caching guard clause.

**Comment by borrrden** [comment]
Hmmm, I'm not sure that information is incorrect.  The pending document IDs are the doc IDs that the pusher has **yet to process** and not necessarily **yet to upload**.  I'll check on this, but I have the new implementation done which does not cache while offline.  It will be available soon.

**Comment by borrrden** [comment]
The value is not cached anymore now but I haven't gotten an answer on whether or not the other thing is expected behavior yet.

**Comment by Steven-Mark-Ford** [comment]
Thanks. Out of interest did you experience the other thing on your side?
