### ISSUE TITLE
NotImplementedException@Couchbase.Lite.Util.Platform.GetWindowsName () under Mono && Windows

### ISSUE THREAD

**Issue by vmartos** [couchbase/couchbase-lite-net#730]
When running under Mono/Windows when trying to set Platform.Name it throws a System.NotImplementedException:
https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Util/Platform.cs#L463

Because Mono doesn't implement the Get Method in System.Management.ManagementObjectSearcher:
https://github.com/mono/mono/blob/ef407901f8fdd9ed8c377dbec8123b5afb932ebb/mcs/class/System.Management/System.Management/ManagementObjectSearcher.cs#L100

> [Warn  12:08:09.364] Caught an exception - System.NotImplementedException: The method or operation is not implemented. (in `System.Management')
>   at System.Management.ManagementObjectSearcher.Get () <0x4357600 + 0x0001f> in <filename unknown>:0 
>   at (wrapper remoting-invoke-with-check) System.Management.ManagementObjectSearcher:Get ()
>   at Couchbase.Lite.Util.Platform.GetWindowsName () <0x4357298 + 0x00047> in <filename unknown>:0 
>   at Couchbase.Lite.Util.Platform..cctor () <0x4357228 + 0x00037> in <filename unknown>:0 
> System.TypeInitializationException: The type initializer for 'Couchbase.Lite.Util.Platform' threw an exception. (in `Couchbase.Lite')
>   at Couchbase.Lite.Manager..cctor () <0x4356eb0 + 0x0001b> in <filename unknown>:0 
> System.TypeInitializationException: The type initializer for 'Couchbase.Lite.Manager' threw an exception. (in `VAS.DB')

**Comment by borrrden** [comment]
`Environment.Is64BitOperatingSystem` is not .NET 3.5 compatible, unfortunately so while I am still building .NET 3.5 I cannot use that bit.  I'll try to think of something else

**Comment by borrrden** [comment]
`Environment.Is64BitOperatingSystem` is not .NET 3.5 compatible, unfortunately so while I am still building .NET 3.5 I cannot use that bit.  I'll try to think of something else

**Comment by vmartos** [comment]
Thanks for the fix! Our fix was just a temporal, that's why we use Environment.Is64BitOperatingSystem. We will replace our fix with yours!
Thanks!
