### ISSUE TITLE
Change IViewStoreDelegate.DocumentType to support multiple document types

### ISSUE THREAD

**Issue by jonfunkhouser** [couchbase/couchbase-lite-net#734]
In our application, there are a few cases where we map multiple docTypes into a single View. If the type for IViewStoreDelegate was changed to a collection type, we could take advantage of docType filtering in UpdateIndexes() for these views. This would lead to a big performance improvement for our app.

The type for viewDocTypes in SqliteViewStore.UpdateIndexes() would need to be changed to IDictionary<string, ISet<string>>.

I'm happy to work on a PR for this enhancement if you'd like.

**Comment by borrrden** [comment]
This is going to be a lot more tricky than you think.  First consider:

Existing document types are still all strings and strings alone are not valid JSON unless they are quoted.  

Then consider:
Couchbase Lite Objective-C and Java will also need to be modified at the same time

This is something I will need to bring to the team before I commit to an answer.

**Comment by borrrden** [comment]
@jonfunkhouser In 2.0 this logic is going to be moved to a different area.  I have linked a ticket that I filed for this enhancement.
