### ISSUE TITLE
SIGSEGV when closing a database while replication is still active

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-net#735]
Using `1.3.1-13 ForestDB LiteServ`

Failure with this test case (using 1000 docs per database) while deleting the database in the test teardown. https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/listener/shared/client_client/peer_2_peer_sanity.robot

LiteServ output - https://gist.github.com/sethrosetter/82d2f2903fb791f6ce2e00c13d2b661f
Stacktrack - https://gist.github.com/sethrosetter/6f3a9eb779c8a4180ba47ac44e25e14a

**Comment by sethrosetter** [comment]
this does not fail every time.

**Comment by borrrden** [comment]
Note to self:  Need to work on the close logic to ensure that one thread cannot close another thread's connection!

**Comment by sethrosetter** [comment]
Is this assigned to me because it needs verification?

**Comment by borrrden** [comment]
Yes, that is correct.

**Comment by sethrosetter** [comment]
Job pending - http://uberjenkins.sc.couchbase.com/job/net-listener-client-client/

**Comment by sethrosetter** [comment]
Closing - http://uberjenkins.sc.couchbase.com/job/net-listener-client-client/19/ Clean P2P run with ForestDB .NET `1.4.0-49`
