### ISSUE TITLE
DocumentChange of deleted conflicted rev shown as conflicted when using ForestDB

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-net#738]
https://github.com/couchbase/couchbase-lite-java-core/issues/1429

**Comment by borrrden** [comment]
@hideki Is passing this test enough to consider this issue solved?

**Comment by hideki** [comment]
@borrrden It is not enough. We found current ForestDB behavior is correct. But SQLite behavior is not same with ForestDB, and it is not consistent, DocumentChange.isConflict variable value is depends on RevID which is generated.

**Comment by djpongh** [comment]
We won't be getting to this.
