### ISSUE TITLE
Couchbase Tag: DATABASE (SqlitePCLRawStorageEngine) Message: sqlite3_prepare_v2: 5

### ISSUE THREAD

**Issue by Steven-Mark-Ford** [couchbase/couchbase-lite-net#748]
Hi,

We got this error with no stack trace:
`Couchbase Tag: DATABASE (SqlitePCLRawStorageEngine) Message: sqlite3_prepare_v2: 5`
 I see sqllite code 5 means 'busy'. Any idea why Couchbase might not be handling concurrency correctly internally?

In seconds following this error a variety of SqllitePCL errors are thrown from there:
#1 (no stack):

`Couchbase Tag: DATABASE (SqlitePCLRawStorageEngine) Message: db cannot be null in BuildCommand, throwing...`
#2:

`Couchbase Tag: DATABASE (SqlitePCLRawStorageEngine) Message: Error executing raw query 'SELECT value FROM info WHERE key=?' with values '<redacted>', rethrowing...`
stack:
`{"StackTraceInWords":"  at Couchbase.Lite.Storage.SystemSQLite.SqlitePCLRawStorageEngine.BuildCommand (SQLitePCL.sqlite3 db, System.String sql, System.Object[] paramArgs) <0x966cc910 + 0x0064b> in <filename unknown>:0 \n  at Couchbase.Lite.Storage.SystemSQLite.SqlitePCLRawStorageEngine.RawQuery (System.String sql, System.Object[] paramArgs) <0x965b0218 + 0x00177> in <filename unknown>:0 ","Message":"Value cannot be null.\nParameter name: db","StackTrace":"  at Couchbase.Lite.Storage.SystemSQLite.SqlitePCLRawStorageEngine.BuildCommand (SQLitePCL.sqlite3 db, System.String sql, System.Object[] paramArgs) <0x966cc910 + 0x0064b> in <filename unknown>:0 \n  at Couchbase.Lite.Storage.SystemSQLite.SqlitePCLRawStorageEngine.RawQuery (System.String sql, System.Object[] paramArgs) <0x965b0218 + 0x00177> in <filename unknown>:0 "}`
#3:

`Couchbase Tag: DATABASE (SqlitePCLRawStorageEngine) Message: Error 21, 261 (database is locked) executing sql 'CREATE TABLE docs (         doc_id INTEGER PRIMARY KEY,         docid TEXT UNIQUE NOT NULL)'`
stack:
`{"StackTraceInWords":"  at SQLitePCL.Ugly.ugly.step (SQLitePCL.sqlite3_stmt stmt) <0x965aba50 + 0x00057> in <filename unknown>:0 \n  at Couchbase.Lite.Storage.SystemSQLite.SqlitePCLRawStorageEngine+<ExecSQL>c__AnonStorey8.<>m__0 () <0x965ab458 + 0x0009f> in <filename unknown>:0 ","Message":"Exception of type 'SQLitePCL.Ugly.ugly+sqlite3_exception' was thrown.","StackTrace":"  at SQLitePCL.Ugly.ugly.step (SQLitePCL.sqlite3_stmt stmt) <0x965aba50 + 0x00057> in <filename unknown>:0 \n  at Couchbase.Lite.Storage.SystemSQLite.SqlitePCLRawStorageEngine+<ExecSQL>c__AnonStorey8.<>m__0 () <0x965ab458 + 0x0009f> in <filename unknown>:0 "}`

I'm using CB Lite 1.3 but I see a previous CB release note said:
YOU MUST REMOVE SQLITEPCL.UGLY AND SQLITEPCL.RAW PACKAGES FROM YOUR PROJECT IF YOU ARE UPGRADING FROM AN EARLIER VERSION OF COUCHBASE LITE
These dlls are still referenced in our solution. what would the effect of this be. could this be causing potential concurrency issues?

**Comment by borrrden** [comment]
That note is only valid for that version.  There was a turbulent time when we needed some patches on a downstream dependency, but once they were resolved the dependency on them was readded.  That is not the cause.  

If you have a complete log, or better yet a reproduction case, I'd like to see it.  Otherwise there is not much I can say.  I don't remember ever seeing a DB busy error but it could be something recent.

**Comment by borrrden** [comment]
@Steven-Mark-Ford Do you have either of the things I mentioned?

**Comment by Steven-Mark-Ford** [comment]
@borrrden I will try get full logs sometime next week. Thanks. Also, got a different issue where as soon as we connect a Logger sync slows down almost 10 times even if the logger is empty method. I will created another case for that sometime next week.

**Comment by djpongh** [comment]
Haven't heard back on this. Closing. Feel free to re-open if you get logs for us.
