### ISSUE TITLE
.NET pull replication with Android stops

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-net#752]
I'll post what I found but I'm not sure what the issue is. It could be something with my setup.

Versions:
.NET: 1.3.1/5d1553d
Android: 0.0.0-640

Start a pull replication:
```bash
curl -k -H 'Content-Type: application/json' -vX POST 'http://localhost:5984/_replicate' -d '{"target": "test", "source": "http://192.168.1.76:5984/test", "continuous": true}'
```

The following is then logged in Xamarin Studio: https://gist.github.com/jamiltz/4b2dac8be2c6194cfdfd9f44bc229b91

HEAD request when starting replication with .NET as the source and target. There are 2 HEAD requests sent actually. Test document is then replicated.

![image](https://cloud.githubusercontent.com/assets/2589337/18906542/d20d6a2a-855f-11e6-86d6-b6a754dc5dc5.png)

![image](https://cloud.githubusercontent.com/assets/2589337/18906509/b45ba7da-855f-11e6-924f-44f050d11360.png)

HEAD request when starting replication with .NET as the target and Android as the source. Test document is not replicated.

![image](https://cloud.githubusercontent.com/assets/2589337/18906534/cc5aab4c-855f-11e6-9b95-cf982f332615.png)

**Comment by borrrden** [comment]
The logs indicate that the remote returned a 404 (DB doesn't exist) so it makes sense to stop.

**Comment by jamiltz** [comment]
That's weird because the push replication worked just fine when sending `{"source": "test", "target": "http://192.168.1.76:5984/test"}` to `_replicate`.

Is the HEAD request sent to check that the database exists then? It's returning a 200 and then the replication stops with the `NotFound` error message in the logs.

**Comment by jamiltz** [comment]
I'll try again tomorrow but I wasn't sure what to collect to help diagnose the issue. Verbose logging on the android side didn't show much. I didn't try verbose logging on the windows side yet.

**Comment by borrrden** [comment]
The head is sent to check overall connectivity. It's excessively odd that the 404 doesn't show up in the request trace. I wonder if it is actually getting all the traffic?

**Comment by jamiltz** [comment]
Ok I ran the test again and it worked fine. I probably messed up the first time and the database indeed didn't exist. Closing this.
