### ISSUE TITLE
Pusher does not report "Forbidden" errors

### ISSUE THREAD

**Issue by pkramerzoll** [couchbase/couchbase-lite-net#756]
When the Sync Gateway's Sync Function rejects a document, such as when a user does not have the appropriate role to modify the document, the recommended practice is to throw a "forbidden" exception to reject the document update. 

However, the Pusher class  in the CBL library does not treat ""Forbidden" errors received from the server as a failure, nor does it set the last error to something that can be handled by the replication changed event.

https://github.com/couchbase/couchbase-lite-net/blob/bd2608926efccc909dafae97a3f55c025e40e3a8/src/Couchbase.Lite.Shared/Replication/Pusher.cs#L284

As a consumer of the replication class, it would be very useful to be able to handle these forbidden exceptions being thrown by the Sync Gateway. Otherwise, there is no indication of any kind of failure.

**Comment by borrrden** [comment]
Our sprint plan is tomorrow, I will tag this for review since it is a cross platform change.

**Comment by borrrden** [comment]
Note: treat this as fatal error

**Comment by pkramerzoll** [comment]
Will an exception be bubbled up that can be handled by the push replication for these documents?

**Comment by borrrden** [comment]
@snej Should this action trigger a change to LastError of the replicator (or rather, would there be any issue with it) before skipping?

**Comment by borrrden** [comment]
Ok, there wasn't that much to do on this.  It turns out it was just incomplete (only handled in _bulk_docs).  So I put the work into `issue/#756`.  If you can build and try it out, then I will merge it to master.  Otherwise I will confirm some scenarios next week.
