### ISSUE TITLE
Push replication does not work when attachment content type is missing

### ISSUE THREAD

**Issue by pkramerzoll** [couchbase/couchbase-lite-net#766]
According to the documentation, Couchbase Lite does not use the media type related to an attachment: (http://developer.couchbase.com/documentation/mobile/current/develop/guides/couchbase-lite/native-api/attachment/index.html)

When calling the method UnsavedRevision.SetAttachment, it accepts an empty string for the contentType parameter and does not throw an exception. However, when an attempt is made to push a document with attachments that do not have a content type, an error occurs and the document and attachments are not pushed to the server. 

The following error is logged by CBL:

ERROR) SYNC (Pusher): [17] 2016-10-18 11:56:23.900-06:00 Unhandled exception in Pusher.ProcessInbox, continuing...:
System.ArgumentException: The value cannot be null or empty.
Parameter name: mediaType
   at System.Net.Http.Headers.MediaTypeHeaderValue.CheckMediaTypeFormat(String mediaType, String parameterName)
   at System.Net.Http.Headers.MediaTypeHeaderValue..ctor(String mediaType)
   at Couchbase.Lite.Replicator.Pusher.UploadMultipartRevision(RevisionInternal revision)
   at Couchbase.Lite.Replicator.Pusher.UploadChanges(IList`1 changes, IDictionary`2 revsDiffResults)
   at Couchbase.Lite.Replicator.Pusher.<ProcessInbox>c__AnonStorey4.<>m__0(Object response, Exception e)

It appears the media type is required for building the web request. If media type is, in fact required, the UnsavedRevision.SetAttachment method should not accept an empty value. If it is **not** required, CBL should check the value of the media type before attempting to add it to the header collection when building web requests.

**Comment by borrrden** [comment]
This looks like a case of .NET imposing its will again.  Sending a blank content-type should be fine, but it looks disallowed by the .NET API.  I might have to send a default content type if it is blank.

**Comment by borrrden** [comment]
Ok at our sprint plan meeting we decided to skip writing the header in question if the content type is blank (i.e. the second way you noted)
