### ISSUE TITLE
Changes feed skipping changes on rapid long poll

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-net#767]
https://github.com/couchbase/couchbase-lite-java-core/issues/1495

For 1.3.1-13 on .NET as well

**Comment by borrrden** [comment]
Partially explains #765

**Comment by borrrden** [comment]
Some context:

There is a race at play.  The race between when the listener determines whether or not to go into "hanging GET" mode (when there are no current changes to return) and when it starts listening for changes.  If a change gets introduced in between those two events then it will be skipped.  Two things are needed to fix this:

1) Shorten the time between these two events as much as possible
2) Record the sequence that the changes was originally requested from and on the first time returning changes get the changes from the sequence.  After that, proceed normally by analyzing the changed event.

**Comment by sethrosetter** [comment]
Test failing - http://uberjenkins.sc.couchbase.com/job/listener-client-client/64/testReport/testsuites.listener.shared.client_client/test_peer_2_peer_sanity/test_peer_2_peer_sanity_pull/

**Comment by borrrden** [comment]
Ugh...this never ends.  Ran the test several times with no issue locally only to have it fail on the first attempt on the CI server.
