### ISSUE TITLE
ManagementException in GetWindowsName() of Platform.cs

### ISSUE THREAD

**Issue by jeffreyxuan** [couchbase/couchbase-lite-net#772]
There is an "Access denied" error in couchbase-lite-net/src/Couchbase.Lite.Shared/Util/Platform.cs that makes the Manager() fail to initialize, the error messages and stack trace are as follow. It might due to for some virtual hosting servers (e.g.: mochahost.com), users cannot change the access level, and users do not have access to execute the error codes as follow. Is it possible to get Windows Version by some other ways except the ManagementObjectSearcher() ? At least we should add an exception handling here to return some default messages instead of "Access Denied" error.

========= error codes in Platform.cs  ==================
`......
using(var searcher = new System.Management.ManagementObjectSearcher("SELECT Caption FROM Win32_OperatingSystem")) {
            foreach(var os in searcher.Get()) {
......
`
============= error messages and stack trace ==========
`Access denied

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Management.ManagementException: Access denied 

Stack Trace: 

[ManagementException: Access denied ]
   System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode) +468164
   System.Management.ManagementScope.InitializeGuts(Object o) +352
   System.Management.ManagementScope.Initialize() +177
   System.Management.ManagementObjectSearcher.Initialize() +196
   System.Management.ManagementObjectSearcher.Get() +35
   Couchbase.Lite.Util.Platform.GetWindowsName() +78
   Couchbase.Lite.Util.Platform..cctor() +47

[TypeInitializationException: The type initializer for 'Couchbase.Lite.Util.Platform' threw an exception.]
   Couchbase.Lite.Manager..cctor() +67

[TypeInitializationException: The type initializer for 'Couchbase.Lite.Manager' threw an exception.]
   Couchbase.Lite.Manager..ctor(DirectoryInfo directoryFile, ManagerOptions options) +0`

**Comment by borrrden** [comment]
This is the best way to get the specific Windows version.  The others are basically hacks that don't even work post Windows 8 without creating an actual Windows app.  With this new information, though, I guess I will have to just fall back to a generic Windows version if this happens.
