### ISSUE TITLE
CB 1.3 - Sync progressively slows down when ILogger is set

### ISSUE THREAD

**Issue by Steven-Mark-Ford** [couchbase/couchbase-lite-net#775]
Since updating from CB 1.1.2 to 1.3.0 we found that syncs ran progressively slower as more data was synced to a device. When 100s of  MB of data needed to be synced it was found that the sync could take up to 10x as long. 

We managed to track it down to the ILogger: commenting out Couchbase.Lite.Util.Log.SetLogger made the sync fast again. 

Initially I suspected the error might have been in our apps ILogger implementatoin, e.g. I suspected we  might have been doing some heavy-serialisation of log objects etc. But I created a new ILogger implementation which did nothing (i.e. just implemented the ILogger interface with empty methods) and found the slow sync issue still persisted.

**Comment by borrrden** [comment]
That's incredibly odd because there is still an implementation there even if you don't call SetLogger.  Can you profile to find the hot paths?

**Comment by Steven-Mark-Ford** [comment]
@borrrden Would you be able to run a sync and compare times before and after logger attached. The more data that is synced the bigger the difference in time should be.  If you cannot replicate then let me know and I will see if I can do a profile.

**Comment by borrrden** [comment]
Should I try it with push or pull?  Also you say "before and after logger attached" but I want to clarify that there is a logger attached by default which logs to trace.  Can you remind me that platform in question too?

**Comment by Steven-Mark-Ford** [comment]
@borrrden Please try pull. Before pull starts please ensure you have called SetLogger and passed in a logger interface implementation (just stub out all the methods, they don't actually have to do anything).

This is on Xamarin Android.

**Comment by borrrden** [comment]
I tried this with latest master, and I got nearly identical times for both runs (the dataset I created is huge and takes 58 minutes to pull...).  I am going to repeat with 1.3.1

**Comment by borrrden** [comment]
1.3.1 showed no difference.  1.3.0 slowed by a considerable amount (67 minutes vs 58) both with and without the SetLogger statement.

**Comment by Steven-Mark-Ford** [comment]
@borrrden interesting thank you. So just to clarify are you saying that 1.3.0 seems to have an issue which has since been resolved?

**Comment by borrrden** [comment]
Actually the issue I was thinking of was on 1.3.0 and 1.3.1 both, but 1.3.1 is faster anyway for some reason.  It was issue 742, by the way.  I recommend giving 1.3.1 a shot.

**Comment by borrrden** [comment]
@Steven-Mark-Ford Have you discovered anything else about this?

**Comment by djpongh** [comment]
We haven't been able to repro - do you have any more info for us?

**Comment by djpongh** [comment]
We haven't heard back so closing. Feel free to open if you can repro and get more info.
