### ISSUE TITLE
Replication.Stop() doesn't release sockets

### ISSUE THREAD

**Issue by nicolasalbert** [couchbase/couchbase-lite-net#776]
I use the CBL 1.3.1 on Windows 10.

When I start a replication, sockets are opens (_changes and documents requests).

When I stop a replication, a socket is still open and doesn't close.

When I start a new replication, a new socket is used.

So, I start / stop / start / stop ... many times, many sockets are used.

I can see it with netstat on the Windows client and on the Linux server (hosting the couchDB). I also test through a proxy and the proxy show pending open connections, even after stop.

I also try a database.Delete() or a Manager.ForgetDatabase(database) : same behavior.

All connections are released when the app is closed.

The couchbase-lite-android have a correct socket behavior.

I have a VS2015 reproduction project if needed.

**Comment by borrrden** [comment]
My first thought is that this is lower level than CBL itself, and dependent on the runtime (when I stop a replication with sync gateway I see log messages on the sync gateway side about the connection being closed, but then again it uses web sockets instead of traditional ones).  How many socket connections do you see?  Each replication creates additional ones?

**Comment by borrrden** [comment]
I've been able to verify that this issue is present in 1.3.1 and master.  The changes feed processor is not hanging up as it should.

**Comment by NicoA380** [comment]
It's ok for you ?
You don't need anythings else ?
For your information, I disable websocket for my replicator.
In my application, I also destroy / reopen / replicate a database with the same name in a short delay.

**Comment by borrrden** [comment]
Even if you had websockets enabled, CouchDB doesn't support it anyway.  I have enough information to move on this.  Thanks!

**Comment by borrrden** [comment]
This is more obnoxious than I thought.  Even after I hung up the changes feed for some reason the connections are staying open, even after I have confirmed that HttpClient is being disposed.  After a while some of them will got away (5-10 minutes) but some always remain for pull.  Push seems to clean up everything after a while.

**Comment by borrrden** [comment]
After some work on this I'm convinced that having several sockets open is just the way things work.  As I stop and start replications I will see some buildup but eventually they will bulk close.  The changes feed thing is valid though and I will put that fix in.
