### ISSUE TITLE
Push sync becomes slower as local DB grows, fails to advance lastSequence

### ISSUE THREAD

**Issue by rainerg2000** [couchbase/couchbase-lite-net#778]
My Xamarin Forms app on Android uses Couchbase Lite to log and upload some data (about 10 small docs per min)
I would expect Couchbase Lite to push only the new data. Instead I see far more network traffic than it should be sending. Attached is a log from sync gateway. I have this problem in release 1.3.1 and in master commit e29b8e1aba2011d9861144ae249cce7192edf730 (Nov 25, 2016)

When I inspect the sync checkpoint doc it shows me:

{
"_id": "_local/b8b1dfc0efc49af5d2359ee99f5464b6de9c11ec",
"_rev": "0-718",   **<<<<<<<<<<<<<<<<<<<<<<< _rev goes up with every push sync**
"lastSequence": "2463"    **<<<<<<<<<<<<<<<<< lastSequence remains constant**
}

[CBL Push Sync Slow.txt](https://github.com/couchbase/couchbase-lite-net/files/617077/CBL.Push.Sync.Slow.txt)

**Comment by borrrden** [comment]
I'd need to see the Lite logs, not the sync gateway logs (but those are helpful in pairing with the lite logs).

**Comment by rainerg2000** [comment]
@borrrden 

Some more background info:
The local DB uses storage engine Sqlite, has ~30000 docs, ~ 35MB file size.
The attached Android log came from a build that uses the CB Lite released version 1.3.1.
Attached is the Android log: filtered by "tag:mono"

Thanks.
Rainer.

[CBL Push Sync Slow Android.txt](https://github.com/couchbase/couchbase-lite-net/files/617459/CBL.Push.Sync.Slow.Android.txt)

**Comment by rainerg2000** [comment]
@borrrden 
I suspect that there is an issue with document "MostRecentBluetoothDeviceRecordsTUuVeCcY-vG7qNoDuV8ZqqsuBzvQJIEiPWbQQ1io29o". It has many revisions. In the sync gateway log look for messages like: 
"MostRecentBluetoothDeviceRecordsTUuVeCcY-vG7qNoDuV8ZqqsuBzvQJIEiPWbQQ1io29o" / "1530-bada6bc663fa0a8e41a317477557528a", has been pruned, it has not been inserted into the revision cache

On the mobile side I have implemented simple conflict resolution, which simply deletes the conflicting revisions. Maybe this confuses sync gateway. Just guessing....

**Comment by borrrden** [comment]
I am not sure if that is relevant or not.  It does seem like there is a current revision with a large revision generation and all of the inserts are not changing that.  It also seems like the replication is stopping and storing its checkpoint before all the requests are finished (150 network requests are still queued).  That gives me someplace to check on.

**Comment by borrrden** [comment]
I haven't been able to figure out what is going on with this one yet.  Are there any updates to this you have found?

**Comment by rainerg2000** [comment]
I have not had time to investigate deeper. And until Jan 8th I won't be at
my work computer.

**Comment by rainerg2000** [comment]
@borrrden I have time this week to pick up where I left off last month. Which branch should I checkout ?

**Comment by rainerg2000** [comment]
@borrrden, maybe this helps:
I am running with branch 'master'. Pusher.RemovePending() is only place that I can see where LastSequence gets incremented. My breakpoint on line 230 inside the block "if (wasFirst){...}" never hits. 
I see line 221:  var wasFirst = (_pendingSequences.Count > 0 && seq == _pendingSequences.ElementAt(0).Key);
but I don't understand how this is supposed to work. I'd be happy to debug this some more, if you can suggest where to go next.

**Comment by borrrden** [comment]
That collection is a collection of sequences that have not yet been processed.  They are sorted, and the "checkpoint" cannot advance until the lowest sequence (i.e. the first one) has been processed.  

What is the first sequence number in there each time when it doesn't enter wasFirst?  Perhaps something is preventing it from being processed. 

P.S. master is fine for this

**Comment by rainerg2000** [comment]
Here what I see when Pusher.RemovePending() is called for the first time:
revisionInternal is passed in with Sequence 5088.
_pendingSequences[0] is 2113
The lastSequence checkpoint in my sync gateway is 2112 (has been stuck for weeks):
{
"_id": "_local/b8b1dfc0efc49af5d2359ee99f5464b6de9c11ec",
"_rev": "0-2834",
"lastSequence": "2112"
}

Speculation:
is it possible that my local database has deleted the documents that are related to these old sequence numbers ? So it will not attempt to push them.
I think my current sequence number is in the 200000 range.

**Comment by rainerg2000** [comment]
Update to yesterday's post:
I'm letting the app run the debugger with a breakpoint in RemovePending if wasFirst == true. Every minute the app starts a oneshot push and a oneshot pull replication. 
After ~2 hours the breakpoint hits and wasFirst is actually true ! In the log I see that it was preceeded by many messages like 
"Sequence 147676 not in set, for rev {<redacted> #1-8be3641bfb47b0c56c2c76ca05fcf18a}"

I aborted the app on that breakpoint, so I can't tell you if this would have advanced LastSequence from 2112 to the current.

**Comment by rainerg2000** [comment]
Update to my post from 3 hours ago:
I restarted the app with a breakpoint in RemovePending if wasFirst == true. Again after ~2 hours the breakpoint hits. This time I let it continue. Now finally the lastSequence object in sync gateway gets unstuck, CBL advances it from 2112 to ~170000. It seems that the next few push replications run properly.

However after stopping and restarting my app the issue reappears and the lastSequence object in sync gateway is now back to 2112 (the same number where it was stuck previously). Briefly I saw the lastSequence object set to 0 in sync gateway.

Is there a way to find out which doc was related to seq number 2112 ? Maybe that would give me a clue.

**Comment by borrrden** [comment]
If you want to know the details of a given sequence number there are two approaches you could take:

1) If you want to do it using CBL, start an all documents query using `AllDocsMode.BySequence` and check the `SequenceNumber` of the rows until you find 2112.

2) If you want to do it on the files, find the database folder (with extension `.cblite2`) and open the `db.sqlite3` file with any sqlite browser or sqlite3 CLI.  You will be able to see the sequences and their bodies in the `revs` table.  You can see the document name by checking the `doc_id` field and looking up that document id in the `docs` table.

A replicator will reset to zero if there is a disagreement between the local and remote checkpoint, but that should be pretty rare (and the logs should note it).  Do you have any logs from the run after the one that updated the checkpoint?

**Comment by borrrden** [comment]
Just a heads up if this doesn't move in the next few days it's not going to make it into 1.4.

**Comment by borrrden** [comment]
Thanks for all your patience with this.  I've been able to reproduce this now, and the fix is quite simple (I've also figured out the cause of briefly setting to 0).  Thanks for being so patient, I know if it were me I'd be breathing fire by now.  I'll let you know the build number with this fix in it as well.

**Comment by rainerg2000** [comment]
That's very good news. Thank you.
Rainer.

**Comment by borrrden** [comment]
The build numbers on the server have not switched yet, so this is in [1.4-b0057](http://latestbuilds.hq.couchbase.com/couchbase-lite-net/1.4/57/)
