### ISSUE TITLE
Attachments disappearing from docs when continuous pull is enabled

### ISSUE THREAD

**Issue by ryanthompson0123** [couchbase/couchbase-lite-net#779]
I'm having an issue where pre-existing attachments are disappearing from documents on mobile devices when an edit to the document is made on the web (by posting to the sync gateway REST API). This only happens when the mobile user has a continuous pull replication running. I can reproduce this with Couchbase Lite .NET 1.3.1 and Sync Gateway 1.3.1 using just a small test harness. Here are the steps to reproduce:

1. Start a continuous pull replication on a mobile device.
2. Create a new document in sync gateway (using PUT method).
3. Attach a photo to the new document (using docid/attachmentName PUT method).

Now, if you GET the document from the sync gateway, it looks like this:
```
{
  "_attachments": {
    "photo": {
      "content_type": "image/jpeg",
      "digest": "sha1-ItXuFlL2CL3ERlRgM4Zc51mND94=",
      "length": 734666,
      "revpos": 2,
      "stub": true
    }
  },
  "_id": "bd87de36-9309-42b5-9e70-807848f90c7b",
  "_rev": "2-7ac57d1b2a5ab02ab396841cfff1d5b6",
  "color": "Black",
  "size": "Medium",
  "type": "fruit",
  "name": "Pomegranate"
}
```
The mobile device should also now have the document (my setup is just replicating everything). The properties for the current revision look like this:

```
{
  "_attachments": {
    "photo": {
      "content_type": "image/jpeg",
      "digest": "sha1-ItXuFlL2CL3ERlRgM4Zc51mND94=",
      "length": 734666,
      "revpos": 2,
      "stub": true
    }
  },
  "_id": "bd87de36-9309-42b5-9e70-807848f90c7b",
  "_rev": "2-7ac57d1b2a5ab02ab396841cfff1d5b6",
  "color": "Black",
  "size": "Medium",
  "type": "fruit",
  "name": "Pomegranate"
}
```
So at this point everything is fine. Continuing on:

4. Make an edit to the document by posting to the sync gateway PUT API. For this operation specifically, I'm posting to `https://myserver.com:4985/mySyncGateway/bd87de36-9309-42b5-9e70-807848f90c7b?rev=2-7ac57d1b2a5ab02ab396841cfff1d5b6` and the body looks like this:
```
{
  "_attachments": {
    "photo": {
      "content_type": "image/jpeg",
      "digest": "sha1-ItXuFlL2CL3ERlRgM4Zc51mND94=",
      "length": 734666,
      "revpos": 2,
      "stub": true
    }
  },
  "_id": "bd87de36-9309-42b5-9e70-807848f90c7b",
  "_rev": "2-7ac57d1b2a5ab02ab396841cfff1d5b6",
  "color": "Red",
  "size": "Medium",
  "type": "fruit",
  "name": "Pomegranate"
}
```
So the only thing that's changed is the color. Now, if you GET the doc using sync gateway REST API, everything looks good:
```
{
  "_attachments": {
    "photo": {
      "content_type": "image/jpeg",
      "digest": "sha1-ItXuFlL2CL3ERlRgM4Zc51mND94=",
      "length": 734666,
      "revpos": 2,
      "stub": true
    }
  },
  "_id": "bd87de36-9309-42b5-9e70-807848f90c7b",
  "_rev": "3-2d3079680b2d359e35fd22d2bb1b53ab",
  "color": "Red",
  "size": "Medium",
  "type": "fruit",
  "name": "Pomegranate"
}
```
And the continuous sync kicks in and pulls the new revision, but now the current revision on the mobile device looks like this:
```
{
  "_id": "bd87de36-9309-42b5-9e70-807848f90c7b",
  "_rev": "3-2d3079680b2d359e35fd22d2bb1b53ab",
  "_revisions": {
    "ids": [
      "2d3079680b2d359e35fd22d2bb1b53ab",
      "7ac57d1b2a5ab02ab396841cfff1d5b6"
    ],
    "start": 3
  },
  "color": "Red",
  "size": "Medium",
  "type": "fruit",
  "name": "Pomegranate"
}
```

So at this point, the attachments are gone and `doc.CurrentRevision.AttachmentNames` is empty. I can do `doc.CurrentRevision.Parent.AttachmentNames` and that rev still has its attachment, but I really need to know all the attachments just using the CurrentRevision.

If you repeat these steps, but instead of using continuous pull replication, just do a one shot pull each time a change is made on the web, the attachments sync down. Starting from a blank database on a mobile device also pulls the attachments down on the initial sync.

I'm not sure what's going on here, but any insight would be appreciated.

**Comment by borrrden** [comment]
Does you test also fail on the latest 1.4 CI build?

**Comment by ryanthompson0123** [comment]
I have not tried that build, but I have tried it against the latest master branch. Is that the same thing?

**Comment by borrrden** [comment]
Yes, the CI builds track the master branch.

**Comment by borrrden** [comment]
One last thing that will be helpful is the logs from a test run

**Comment by borrrden** [comment]
Also possibly related to #749

**Comment by ryanthompson0123** [comment]
I've been doing a little digging on this, and would appreciate your insight.

I'm noticing that when I run my test, the method `PullRemoteRevision` is being called in Puller.cs line 546. At line 586, it fetches the single document from the sync gateway. This gets the multipart response from the sync gateway and parses it until finally, `reader.Finish()` is called at RemoteSession.cs line 355.

Inside `reader.Finish()`, there's a method called `RegisterAttachments()` that gets called at MultipartDocumentReader.cs line 188, and it's defined on line 194 of the same file.

At line 198 the `attachments` variable contains my stub attachment when I break there. The code after that seems to process attachments, but since 'follows' is false for a stub attachment, it simply ignores it and moves on. So at line 285, the variable`nuAttachments` is empty, the stub attachment having never been added to it. The puller then goes on to create the newly downloaded revision from this document, with an empty _attachments property.

I noticed that when revisions are downloaded in bulk, there's a completely different code path for managing attachments - and when revisions are actually downloaded in bulk, I don't encounter this issue.

I suppose the easy fix would be to just remove the code in Puller.cs from line 269 to 274. Is there any harm in downloading a single revision in 'bulk'?

**Comment by borrrden** [comment]
I don't think there is any *harm* in particular, it's just a bit more overhead (although it would be much simpler if I could remove that entire code path at some point, but CouchDB only very recently got bulk operations in 2.0, while Sync Gateway has had them for around two years now).  There is probably some issue with the attachment registering since you've followed it all the way down to the point that you did.  It is more than likely a simple fix.  nuAttachments should contain the *edited* old attachments so if one has gone missing then that is a problem.  Thanks for the analysis, this will help move things very quickly.

**Comment by borrrden** [comment]
It turns out there is a needless overwrite of the attachments property in the `RegisterAttachments()` method.  I refactored the method to be a bit cleaner and throw consistent exceptions but the fix is actually that I just entirely removed `nuAttachments`.  The work is up on issue/#779 if you'd like to try it out.

**Comment by borrrden** [comment]
Also P.S. sorry waffle seems to have barfed all over this ticket resulting in about a dozen redundant status changes

**Comment by ryanthompson0123** [comment]
We did extensive testing with your changes and it does indeed fix our issue. Thanks!
