### ISSUE TITLE
using SystemSQLite on android 7 throws a pop error when db init

### ISSUE THREAD

**Issue by brettharrisonzya** [couchbase/couchbase-lite-net#783]
This error seems to be fixed in > 1.0 version of https://github.com/ericsink/SQLitePCL.raw, but there is a bit of work to upgrade, will require new packages and initialization of sql.

**Comment by borrrden** [comment]
System SQLite is not allowed on Android 7+, you will need to either use SQLCipher or CustomSQLite (which is not released yet)

**Comment by brettharrisonzya** [comment]
Is SQLCipher backwards compatible with System SQLite?  So that upgrading an android app that used to work with System SQLite to SQLCipher will work properly?

**Comment by borrrden** [comment]
SQLCipher is a superset of SQLite, compiled from the same source.  They are compatible with each other.  If you don't use encryption you will not notice any difference.

**Comment by borrrden** [comment]
@brettharrisonzya Does that work for you?

**Comment by brettharrisonzya** [comment]
Yes I switched to SQLCipher on android and it works

**Comment by borrrden** [comment]
Thanks!
