### ISSUE TITLE
Replication froze with a huge database with Xamarin iOS

### ISSUE THREAD

**Issue by nicolas-albert** [couchbase/couchbase-lite-net#787]
[BigReplication.zip](https://github.com/couchbase/couchbase-lite-net/files/654339/BigReplication.zip)

Hi,

I encounter a difficulty to replicate a huge database from a CouchDB : 5000 documents with an attachment of 1 MB each.

Works fine with couchbase-lite-net on a desktop WPF application and a Xamarin Android application.

With iOS, the replication don't change after ~1200 documents (less or more) and restarting the replication add a few before froze again.

I have prepare a VS2014 project with the WPF, Android and iOS application, sharing the same code in the file **BigReplication.Common/Common.cs**.

I put the base online http://54.171.110.0:5986/bigbase but I suggest to replicate on your lan before.

Thanks.

**Comment by borrrden** [comment]
At first glance this might be related to #719.  I'll see if I can reproduce this with the provided sample.

**Comment by NicoA380** [comment]
Ok thanks. If it works, the changes of the 719 branch will be include in the next release ?

**Comment by borrrden** [comment]
Yes they have already been merged and will be included in 1.4 (scheduled
for mid-Feb)

**Comment by NicoA380** [comment]
Hi, did you try this sample with the 719 branch ?

**Comment by borrrden** [comment]
Sorry not yet. I will do it tomorrow for sure!

**Comment by borrrden** [comment]
I just ran it, and the replication completed with 8400 changes.  For what it's worth though the issue 719 changes are in the latest CI build (1.4-b0011).  Are there any things I should do when running this sample?  I just ran a debug build on my iPhone 6S+

**Comment by NicoA380** [comment]
Great, were can I find the build 1.4-b0011 to test myself ? I didn't find it here, on nuget.org or with google.
Thx.

**Comment by borrrden** [comment]
Instructions to get it are in the readme of the repo.

**Comment by NicoA380** [comment]
Ok, I'll try to build from sources, I thought you have drop your built package somewhere.

**Comment by borrrden** [comment]
We do, it's the last sentence in the "getting couchbase" section of the
readme.

**Comment by NicoA380** [comment]
Great, I run my sample with success ! I'll try with my real project to confirm that.

**Comment by borrrden** [comment]
How did the real project work out?

**Comment by nicolasalbert** [comment]
Hi, sorry I didn't answer before (end of the year, switch to another projects, etc...).
I have tested once and the replication has never go so far, but I remember it didn't totally finish.
I'm doing an another run right now and I'll confirm soon the success (I hope).
