### ISSUE TITLE
Continuous replication stops/freezes

### ISSUE THREAD

**Issue by kf2093** [couchbase/couchbase-lite-net#793]
I've noticed that continuous replication sometimes stops/freezes.  The status of replication states idle for (both push/pull) however new changes are not received on the device.  This is happening on both iOS and Android devices.  I am not sure what other info I can provide that will help.  I am currently trying to detect when this happens by means of updating a heartbeat couch document, when the document is not updated after a particular time unit I restart the replicators.  However, this is a hack from my end.  Are there any parameters that I should be setting to achieve continuous replication that provides more real-time updating and support for ad hoc joining/leaving networks?

**Comment by borrrden** [comment]
Logs would be nice, as this is a pretty vague description.  If the replication never changes from idle, that means either no new changes came across the changes feed from the other endpoint (for pull) or no new documents were added to the local database (for push).

**Comment by djpongh** [comment]
Any chance to get the logs?

**Comment by kf2093** [comment]
This will take a while, I'll have to get a setup to monitor the app in the deployment we have and monitor when it happens.

**Comment by djpongh** [comment]
Haven't heard back. Closing.
