### ISSUE TITLE
Set ServicePointManager.SecurityProtocol

### ISSUE THREAD

**Issue by unkani** [couchbase/couchbase-lite-net#795]
Is there a way to set the SecurityProtocol to SecurityProtocolType.Tls12 (or anything other than TLS?)

It looks like by default, it is set to SecurityProtocolType.Tls on Line 80:

https://github.com/couchbase/couchbase-lite-net/blob/7e82825a7082960884991ac6b7bd3dec7930acf2/src/Couchbase.Lite.Shared/Replication/CouchbaseLiteHttpClientFactory.cs

I'm getting this error:

Exception in HttpWebRequest#45592480:: - The request was aborted: Could not create SSL/TLS secure channel..

Sorry if there's a super obvious way to do this.

I've already attempted to set ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 after I create a new Manager.

**Comment by borrrden** [comment]
Actually even if you set it, the library is going to change it back.  This is one of the fallbacks of having a globally configurable variable for stuff like this -_-.  I want to change it to 1.2 but I can't because SecurityProtocolType.Tls12 does not exist in .NET 3.5, and until *very* recently Mono only supported TLS 1.0.  Have you confirmed that switching to SecurityProtocolType.Tls12 will solve the problem you are facing?

**Comment by unkani** [comment]
Yeah, when I create and send an HTTPWebRequest manually with TLS 1.0 or 1.1 or SSL3, the request will be aborted.
Only when I switch to TLS1.2 will it work. The IT guys take security seriously I guess.

I did notice that when I switch to 1.2, the initial request will work, but subsequent calls will all fail.

Any ideas for a workaround?

**Comment by borrrden** [comment]
No (sorry), but what I can do is change the library to only change it if it is set to SSL3 which will achieve the same thing for my purposes but leave it open to change by the user.

**Comment by borrrden** [comment]
Since the setting is marked as `[Flags]` I unset the Ssl3 flag and set the `Tls` flag (if you keep setting it to `Tls12`, this should end up as `Tls | Tls12`)

**Comment by sisirak** [comment]
Hi borrrden,  I need to know how to work around the same issue in 1.3.0 release?

**Comment by borrrden** [comment]
The only thing you can do is make a build with the above changes in it.  1.x is well past its end of life at this point (and 1.3 may have even reached the end of paid support) and no more work is being done on it.
