### ISSUE TITLE
LiteServ xamarin keeps crashing

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-net#800]
Nexus 6p,
Android 7.1.1,

LiteServ app does not launch, keeps crashing.

Apparently the app does not have permission to open sockets on the device. Under the app info, it says No Permissions requested and the permissions field is grayed out.

Below is the adb logcat output:

https://gist.github.com/raghusarangapani/41f368f96bd6f4756d0a5b54b09f6fad

**Comment by borrrden** [comment]
Fixed in 5ab7d679aa31b6f04efbbb92b36109070ace02d3
