### ISSUE TITLE
Push replication stays 'active' indefinitely after network glitch

### ISSUE THREAD

**Issue by rainerg2000** [couchbase/couchbase-lite-net#805]
My Xamarin app on Android does a periodic push and pull replication. Sometimes the pull replication gets into a state where it remains 'Active' indefinitely. In that state '#Docs Pending' and '# Docs Completed' remain constant. # Docs Pending will be a sightly higher than # Docs Completed.

While in this state, no new data will be pulled. The replication appears stuck. 
But if I break network connectivity briefly, like go to Airplane mode, and then restore connectivity, the pull replication will continue once. and then it's stuck again.

I can force my app into this state by setting the periodic push/pull replications to 10sec intervals, and then put the phone in and out of airplane mode every few seconds. After a few rounds, the issue reproduces.

**Comment by borrrden** [comment]
What build is this?  This sounds like #803

**Comment by rainerg2000** [comment]
This is on couchbase-lite-net 1.3.1. 
I will compare my logs with those of #803. If it looks like the same root cause I'll test with master.

**Comment by borrrden** [comment]
Well I can save you some time and say that #803 was introduced after 1.3.1 so it can't be the exact problem.

**Comment by rainerg2000** [comment]
Thanks. I'll get you a log anyways. Probably by tomorrow.

**Comment by rainerg2000** [comment]
2 logs filtered by tag:mono both capture a transition into the state with a pull replication that is stuck while I was going in and out of airplane mode 2 or 3 times.
[Issue 805.1.txt](https://github.com/couchbase/couchbase-lite-net/files/720925/Issue.805.1.txt)
[Issue 805.2.txt](https://github.com/couchbase/couchbase-lite-net/files/720926/Issue.805.2.txt)

**Comment by rainerg2000** [comment]
I was able to reproduce the issue with master rev 33282c1f2f6cf0c4c4f66c31df8b8e48727c628d (20-Jan-2017). Here is a log from a test run with master showing several airplane mode on/offs and then a transition into the error state as described above.
[Issue 805.3.txt](https://github.com/couchbase/couchbase-lite-net/files/721767/Issue.805.3.txt)

**Comment by borrrden** [comment]
Sorry that I've been silent on this!  It fell between the cracks and I wonder if you have moved on by now, but from my analysis of the logs it looks like there are some DNS issues getting in the way.  I don't see a clear sign of replication getting stuck from the logs, but I do see a whole bunch of "hostname unknown" errors.  If they cause the replication to reset somehow because of a failed checkpoint write then it's possible that the replication is restarting and that the replicator is catching up to where it already is.

**Comment by borrrden** [comment]
Unfortunately 1.x has reached EOL without ever getting a reasonable fix for this.  If it is still an issue on 2.x then please open another issue.
