### ISSUE TITLE
Purge failing with 1.4 (mono) and ForestDB 

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-net#806]
CBL version - 1.4-30 ForestDB
sync_gateway - 1.2.1-4

It looks like something to do with purging docs and ForestDB

Failing test - http://uberjenkins.sc.couchbase.com/job/net-mono-listener-client-sync-gateway/84/testReport/junit/testsuites.listener.shared.client_sg/test_attachments/test_inline_large_attachments/

**Comment by borrrden** [comment]
In the end this is a cross platform issue regarding the return "reason" status and not something more crazy.  ForestDB is ironically correct here and SQLite needs to be fixed.
