### ISSUE TITLE
Provide ZIP package for releases

### ISSUE THREAD

**Issue by malarky** [couchbase/couchbase-lite-net#817]
Please provide each release as a ZIP archive at:

https://packages.couchbase.com/releases/couchbase-lite/net/${VERSION}/Couchbase.Lite.${VERSION}.zip

This is already done for all other Couchbase Lite platforms.

**Comment by borrrden** [comment]
This release stye does not make sense for .NET.  Why is it needed?

**Comment by malarky** [comment]
Why doesn't it make sense?  What if I literally just want to grab the code?  Working in Support we frequently have to try different release versions when debugging/reproducing customer issues.  I get that in a Windows/VS environment NuGet is the de facto method, but if I'm working in Mono I generally just have all the versions unzipped in a directory.  I also have customers asking where they can get the DLL and the easiest way to give a direct link is at packages.couchbase.com.

**Comment by borrrden** [comment]
Nuget is the defacto method in Mono as well.  Xamarin Studio / Monodevelop both support it and it is easier and less error prone than what you are suggesting.  For example, when you switch back and forth between these DLLs do you also switch out the relevant dependencies?  Switching in Nuget will do all of that for you.

<img width="823" alt="screen shot 2017-02-10 at 21 37 46" src="https://cloud.githubusercontent.com/assets/2470288/22827083/53c59b6c-efd9-11e6-90be-563aaebd22f0.png">

**Comment by JFlath** [comment]
I think we've definitely seen cases where a zip file would have been handy, but as @malarky says, all the other platforms do this - we should be consistent.

Added to that, there's the issue that we're dependant on nuget this way - we're not hosting the releases (be they .nuget or .zip) ourselves.

@djpongh @ssmotra - maybe one for you guys?

**Comment by djpongh** [comment]
We'll see what we can do in the 1.4 time frame.
