### ISSUE TITLE
Trying to port the Xamarin CRM prebuilt app to Couchbase Lite but issue with PCL vs Shared Project

### ISSUE THREAD

**Issue by fbeenaerts** [couchbase/couchbase-lite-net#818]
I want to use the pre-built Xamarin App: XamarinCRM from https://www.xamarin.com/prebuilt

But I want to remove the Azure services and change it with Couchbase Lite. Therefore I installed the package for Couchbase Lite in the 2 mobile projects. Then I created a Shared Project with all the DB code like CRUD operations.

In the PCL XamarinCRM, which calls originally the webservices, I want to replace these calls with CRUD code from the newly created Shared Project.

I always get the error: Type or namespace name 'Couchbase' could not be found. Probably this is because when compiling the XamarinCRM (PCL) it includes the shared project but of course the PCL doesn't know this package.

So there's a conflict: code for Couchbase should be in shared project but most logic of the app is in PCL and I can't link them. See schema of set-up here.
[Referencing.pdf](https://github.com/couchbase/couchbase-lite-net/files/772080/Referencing.pdf)

Anyone an idea of how to solve this? Any help greatly appreciated. If someone could guide me through this via skype, that would be great.

**Comment by borrrden** [comment]
You would have to make an interface in the shared project instead and use dependency injection.  This is a good argument for MVVM.  You can see an example of doing it in Mobile Todo app example.  Also, for 2.0 the library will be a .NET Standard library so you won't need to do this anymore.

https://github.com/couchbaselabs/mobile-training-todo/tree/master/dotnet

**Comment by fbeenaerts** [comment]
Dear Jim, if I create an interface in the shared Project, how can I use it from within the PCL? I cannot make a reference to the shared project in the PCL because then the PCL won't compile anymore (since the shared project is using Couchbase references which are linked to iOS Android projects).

Thanks for your reply

**Comment by borrrden** [comment]
You will interact purely with the interface, and use dependency injection to choose an implementation at runtime.

For example [this service interface](https://github.com/couchbaselabs/mobile-training-todo/blob/master/dotnet/Training.Core/Services/IImageService.cs) is defined in the core project and used by the core functionality.  Then [an implementation](https://github.com/couchbaselabs/mobile-training-todo/blob/master/dotnet/Training.Android/Services/ImageService.cs) is made in the per platform projects.  If you register this implementation with a dependency injection container before you use it, you can get it and use it in the PCL via that container.  I used MvvmCross's implementation and so I register [like this](https://github.com/couchbaselabs/mobile-training-todo/blob/master/dotnet/Training.Android/MvxFormsApplicationActivity.cs#L57) and then use it [like this](https://github.com/couchbaselabs/mobile-training-todo/blob/4719b5b41778bbac536aaea981d813f21f8059d4/dotnet/Training.Core/ViewModels/TaskCellModel.cs#L187)

**Comment by borrrden** [comment]
@fbeenaerts Does that clear things up?

**Comment by djpongh** [comment]
Haven't heard anything. Assume everything is OK.
