### ISSUE TITLE
MapOnly Query Property Not Respected

### ISSUE THREAD

**Issue by jeremyswitzer** [couchbase/couchbase-lite-net#819]
I'm trying to create a single view that I can use for both querying by key and generating an aggregate using the reduce delegate. However, it seems that once the reduce delegate has been set on a view via `View.SetMapReduce` method, you can no longer run regular (non-reduced) queries on that view object. My understanding was that the `Query.MapOnly` property would allow me to specify what type of query to run each time, but it didn't seem to have any effect. 

After investigating further, I can see that the `MapOnly` property is properly being translated to the `QueryOptions.Reduce` property, but it doesn't appear to referenced in any of the storage engine implementations after that. 

I wrote a quick test to illustrate the problem I'm having:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using Couchbase.Lite;
using Xunit;

namespace CouchbaseReduceTest
{
    public class MultiuseViewTest : IDisposable
    {
        private readonly Database _db;
        private readonly View _sut;

        public MultiuseViewTest()
        {
            _db = Manager.SharedInstance.GetDatabase("test");
            _sut = _db.GetView("task-log");
            Setup();
        }

        public void Dispose()
        {
            _db.Close();
            Manager.SharedInstance.DeleteDatabase("test");
        }

        [Fact]
        public void Test_Run_View_Query_When_MapOnly_Is_Set()
        {
            var query = _sut.CreateQuery();
            query.StartKey = new [] {"John"};
            query.EndKey = new object[] {"John", new Dictionary<string, object>()};
            query.MapOnly = true;
            query.GroupLevel = 1;

            var result = query.Run().ToArray();

            // Returns a single Reduce result instead of all keys for "John"
            Assert.Equal(3, result.Length);
        }

        private void Setup()
        {
            _sut.SetMapReduce(
            (doc, emit) =>
            {
                emit(new[] {doc["name"], doc["date"]}, doc["tasks"]);
            },
            (keys, values, re) => values.Sum(Convert.ToInt32), 
            "1");

            AddEntry("John", 3, new DateTime(2017, 1, 1));
            AddEntry("Jane", 12, new DateTime(2017, 1, 1));
            AddEntry("Jim", 1, new DateTime(2017, 1, 1));
            AddEntry("John", 12, new DateTime(2017, 1, 5));
            AddEntry("Jane", 5, new DateTime(2017, 1, 7));
            AddEntry("John", 1, new DateTime(2017, 1, 8));
        }

        private void AddEntry(string name, int tasks, DateTime date)
        {
            var doc = _db.CreateDocument();
            doc.PutProperties(new Dictionary<string, object>
            {
                {"name", name},
                {"tasks", tasks},
                {"date", date.ToString("s")}
            });
        }
    }
}
```
Am I missing a setting, or is there a different workflow that will allow me to be able to query and reduce the same view?

**Comment by borrrden** [comment]
That's odd...I wonder when that happened.  I'll try to track that down.

**Comment by borrrden** [comment]
The group level setting on your query is going to override the map only setting.  Try running it without setting group level (group level > 0 implies a kind of reduction)

**Comment by jeremyswitzer** [comment]
That worked. Thanks!

**Comment by borrrden** [comment]
Excellent!  Just an FYI, but we are considering replacing map / reduce functionality with pure LINQ and/or an abstract query tree syntax for 2.0 (we are definitely including it but whether or not we remove map / reduce is the debate).  Be sure to keep your eye on the upcoming developer builds for .NET (https://www.couchbase.com/nosql-databases/downloads -> Couchbase Mobile -> Couchbase Lite -> Developer tab.  Currently iOS is available but I've implemented all of the features for the DB in .NET as well, it will come soon)

**Comment by jeremyswitzer** [comment]
OK. Thanks for the heads-up. If you get the Linq implementation out in a minor update before 2.0, I'll switch it over before map/reduce gets deprecated.

**Comment by borrrden** [comment]
There will be a LINQ implementation in 1.4, but it isn't going to be quite the same as the one in 2.0 (because the underlying implementation is going to be completely rewritten).  I'm hopeful that this will be transparent to the consumers of Couchbase Lite but just know that the implementation in 1.4 is based on views, while 2.0 is based on the new native query engine (which is text based at the end of the day and does a number of really cool things like searching through binary encoded JSON without parsing it first, but that fact will be hidden behind LINQ).  The 1.4 LINQ is documented in this repo's wiki.  1.4 is unfortunately behind schedule (.NET is mostly ready, but we need to keep a lock step between Objective-C, Java, and Sync Gateway which don't always finish at the same time).  So far I haven't received any feedback about 1.4 LINQ so that means to me that no one has tried to use it yet :(.
