### ISSUE TITLE
.NET not sending all docs to a client pull replication (p2p, SSL)

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-net#826]
check out `feature/enable-ssl-liteserv` and run the below command

```
pytest --pdb -s --enable-ssl --liteserv-one-platform=macosx --liteserv-one-version=1.4-41 --liteserv-one-host=192.168.0.14 --liteserv-one-port=50000 --liteserv-one-storage-engine=SQLite --liteserv-two-platform=net-msft --liteserv-two-version=1.4-48 --liteserv-two-host=192.168.0.57 --liteserv-two-port=51000 --liteserv-two-storage-engine=SQLite -k "test_peer_2_peer_sanity_pull" testsuites/listener/shared/client_client/
```

Mac logs (puller stops after 4800, there should be changes sent up to 4999 - https://gist.github.com/sethrosetter/0e4c5174f4e016d789dd78002810f0be

.NET logs (stops sending changes) -  https://gist.github.com/sethrosetter/f5274341fc4c22e82eeee5349c8936d1

Scenario:
Pull replication (macosx <- net-msft) running on Mac OSX 1.4-41

Behaviorally this is not a regression as this scenario had missing docs for 1.3.1, but the entire changes feed was sent in 1.3.1 minus a few docs. In this case the server stops before sending a large subset of documents. Functionally, this is a regression.

Also, I ran without SSL and everything was fine.

**Comment by borrrden** [comment]
Not entirely clear why this issue occurs more on SSL, but the end result was caused by a regression caused by my fix for #767
