### ISSUE TITLE
Nuget mobile developer release link not working

### ISSUE THREAD

**Issue by dfs-malta** [couchbase/couchbase-lite-net#829]
Hi
I tried accessing http://nuget.mobile.couchbase.com/nuget/Developer/
to no avail

**Comment by borrrden** [comment]
Well this is embarassing, and totally my fault.  That URL should be 

http://mobile.nuget.couchbase.com/nuget/Developer/ (notice it's mobile.nuget, not nuget.mobile)

I'll correct that immediately.

**Comment by jamiltz** [comment]
https://developer.couchbase.com/documentation/mobile/2.0/couchbase-lite/dotnet.html#how-can-i-get-it-quickly

**Comment by Maksonfedin** [comment]
Hi
I tried accessing http://nuget.mobile.couchbase.com/nuget/Developer/
to no avail

**Comment by borrrden** [comment]
It looks like the proxy server for that address has gone down.  I filed an internal ticket for this and will update when it has been resolved.

**Comment by Maksonfedin** [comment]
<img width="572" alt="screen shot 2018-01-05 at 11 40 50" src="https://user-images.githubusercontent.com/15618872/34603608-4f84476a-f20d-11e7-82ff-d9d460551179.png">

**Comment by borrrden** [comment]
The problem has been cleared up.
