### ISSUE TITLE
1.4 breaks custom headers on PUT HTTP requests

### ISSUE THREAD

**Issue by dmunch** [couchbase/couchbase-lite-net#834]
Hi,

we are just about to upgrade to the latest 1.4 release and we're hitting a new issue concerning custom headers. We're in the same scenario as  described in https://github.com/couchbase/couchbase-lite-net/issues/687, however we now see request being send without the custom headers being set. We're still investigating for further details, but it seems like only requests for attachments are affected. 

Best,
Daniel

**Comment by dmunch** [comment]
Seems like https://github.com/couchbase/couchbase-lite-net/commit/fa8b1214002e5be6bc33d1537cdacca69b653dc3#diff-943160e99ba2b155e41572bfd0414d10 changed the way `BulkDownloader` makes HTTP request. If I judge the situation correctly no custom headers are appended.  

The only occurence of `BulkDownloader` seems to be in https://github.com/couchbase/couchbase-lite-net/blob/fa8b1214002e5be6bc33d1537cdacca69b653dc3/src/Couchbase.Lite.Shared/Replication/Puller.cs#L326, however  `Headers`  is not passed into `BulkDownloaderOptions` which might explain the fact that the missing headers only occur when downloading attachments.

**Comment by borrrden** [comment]
The custom headers are part of the overall remote session object now, so they should persist throughout all parts of the replicator's lifetime.  The reason they are not passed in anymore is because instead of creating a new http client for itself, it reuses the existing one.  

That being said, the complexity of the replicator has probably led to another error on my part (this is one of the big overhauls being done for 2.0, to prevent these kinds of things from popping up again and again) so can you let me know how you are setting these headers?

**Comment by dmunch** [comment]
Here's the snippet right from our code which sets the header, where `replication` is an instance of `Couchbase.Lite.Replication`

```csharp
if (replication.Headers != null)
{
    replication.Headers = new Dictionary<string, string>();
}
replication.Headers.Add("Authorization", $"Bearer {bearerToken}");
```

**Comment by dmunch** [comment]
Having a closer (and especially fresh look after the week-end) on the logs it's actually the uploading of attachments which fails. A small peek into the code might suggest that `SendAsyncMultipartRequest` doesn't set the required headers like the other `Send*` methods do. 

i.e. a comparison of 
https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/RemoteSession.cs#L416

and

https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/RemoteSession.cs#L292

might suggest that there's a `AddRequestHeaders(message);` missing.

**Comment by borrrden** [comment]
That does seem quite likely.  I'll put in that change and it will be in the next CI build soon (1.4.1-65 or higher)

**Comment by dmunch** [comment]
Perfect, 1.4.1-b0065 solves the issue. Thanks a lot for the quick reaction!
