### ISSUE TITLE
Cannot find type System.Security.Principal.GenericIdentity in module CommonLanguageRuntimeLibrary.	in UWP

### ISSUE THREAD

**Issue by LittleStar9637** [couchbase/couchbase-lite-net#839]
I added couchbase.lite-pcl to my xamarin project and when I deploy uwp project, I'm getting this error.
How can i fix the issue

**Comment by jamiltz** [comment]
What version of Couchbase Lite are you using? The current GA version (1.4) doesn't support UWP but the upcoming version 2.0 will https://developer.couchbase.com/documentation/mobile/2.0/guides/couchbase-lite/index.html?language=csharp#getting-started

**Comment by djpongh** [comment]
This is not a Couchbase owned project. Please contact @alexrainman as he owns the couchbase.lite-pcl repo.
