### ISSUE TITLE
Could not install package to Xamarin Portable project.

### ISSUE THREAD

**Issue by meteoric9637** [couchbase/couchbase-lite-net#843]
When I install couchbase.lite nuget package to xamarin potable project, I got below error.
I know this sdk doesn't support uwp project. So I'd like to make wpf project instead of uwp project in xamarin potable.
I installed the package to wpf project but I can install it to potable project.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Couchbase.Lite.Storage.SystemSQLite 1.4.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	
Where is there a way how to use couchbase sdk in xamarin uwp of xamarin potable project.

**Comment by borrrden** [comment]
1.x is not compatible with PCL. You won't be able to do this. The best approach is to use a shared project and add the lib to your app directly. 2.0 will be a .NET Standard library though!

**Comment by meteoric9637** [comment]
I'm not sure, Can I add the component to shared project?

**Comment by borrrden** [comment]
No, shared projects are just like a set of files that are compiled as-is in a higher project, so you would make an android and ios project, for example, add a reference to both of them to the shared project, and then add couchbase lite to both the ios and the android project.  The shared project will be compiled into the overall project, and not as a separate assembly.

**Comment by meteoric9637** [comment]
Hi, Thanks for your reply. would you explain how to make shared project.
I made potable project like below image.
(here)[https://firebasestorage.googleapis.com/v0/b/mystorage-ded50.appspot.com/o/Capture.jpg?alt=media&token=7ce515ca-a8ed-425a-8cb0-d618bbb2ca05]
If i make shared project, how can I use neget packages like MVVMcorss.
Thanks

**Comment by meteoric9637** [comment]
Hi when I can use the 2.0 version?

**Comment by borrrden** [comment]
[This project](https://github.com/couchbaselabs/mobile-training-todo/tree/master/dotnet) is setup in the way I described.  The 2.0 version is available as a developer build but some issues with our web page are blocking me from putting out newer versions.  It should be up to build 5 by now, but it is still on build 3 with build 6 scheduled for next week.

Information about 2.0 is [here](https://developer.couchbase.com/documentation/mobile/2.0/guides/couchbase-lite/index.html?language=csharp)
