### ISSUE TITLE
Replication - Couchbase.Lite ChangesCompleted greater than ChangesCount

### ISSUE THREAD

**Issue by jandroalvarez** [couchbase/couchbase-lite-net#844]
I moved this issue from Couchbase forums. Hereunder the issue detected on couchbase-lite-net:

_"I'm developing a Xamarin.Forms application that replicates a CouchDB server using a pull one-shot one-way replication. From time to time, the replication never stops despite the changesCompleted reaches not only the number of changesCount....but it exceeds this number!!"_

It doesn't happen all the time. However, when it happens, the replication never stops.

I've added the logs when I've reproduced the issue:
[logs.zip](https://github.com/couchbase/couchbase-lite-net/files/942298/logs.zip)

For the moment, we've implemented a workaround where we compare our current local couchbase database size with the remote one.

**Comment by borrrden** [comment]
This is an issue that keep popping up.  If I run into it again I will update this ticket.

**Comment by borrrden** [comment]
This is no longer relevant at this level.  In 2.x this logic is handled in LiteCore, so closing as there is already a tracking issue for it there.
