### ISSUE TITLE
LINQ query always return 0

### ISSUE THREAD

**Issue by alexrainman** [couchbase/couchbase-lite-net#845]
I have this AllDocs query:

```
var query = Database.CreateAllDocumentsQuery ();

query.PostFilter = (arg) => arg.Document.Properties.ContainsKey ("type")
&& arg.Document.Properties ["type"].ToString () == "employee";

var rows = query.Run ();
```

It returns the 2 documents i am expecting, but the same in LINQ returns 0:

```
var rows = Database.AsQueryable().Where(x => x.DocumentProperties.ContainsKey("type") && x.DocumentProperties["type"].ToString() == "employee").Select(e => e.Document)
```

Any ideas?

**Comment by borrrden** [comment]
Can you put breakpoints inside that where clause and see if anything is getting called and what the document properties contain?

**Comment by alexrainman** [comment]
I put breakpoints but it says x is unknown identifier

![screen shot 2017-05-04 at 11 09 53 am](https://cloud.githubusercontent.com/assets/3793554/25713436/44a2c804-30ba-11e7-99a1-535d18fb0fa5.png)

**Comment by borrrden** [comment]
How about logging it instead?  Sometimes the debugger can't access info correctly.

**Comment by alexrainman** [comment]
Will try that.

**Comment by djpongh** [comment]
So does this mean you can't log this info for us?

**Comment by alexrainman** [comment]
I tried but the code is never executed.

**Comment by borrrden** [comment]
That's also useful information!  How about the logs for a run of this sample?  Does it show any errors?  I have an almost identical unit test [here](https://github.com/couchbase/couchbase-lite-net/blob/fc2b600ed054a1e78477496e8bb28f1e305366dd/src/Couchbase.Lite.Tests.Shared/ViewsTest.cs#L247) which passes so this query should be functioning!

**Comment by djpongh** [comment]
@alexrainman, any chance to get the logs?

**Comment by djpongh** [comment]
Feel free to reopen if you can post the logs.
