### ISSUE TITLE
Can not get preview packages 

### ISSUE THREAD

**Issue by mohsens22** [couchbase/couchbase-lite-net#855]
Hello.
I get Error 500 when I'm trying to get preview packages.
[http://mobile.nuget.couchbase.com/nuget/Developer/package/Couchbase.Lite/2.0.0-db005](url)
there you can send request and get the error.

**Comment by borrrden** [comment]
Looks like the connection was broken between the feed and the NAS machine that hosts the packages....that worries me but it is back up now.
