### ISSUE TITLE
Couchbase.Lite UWP not supported on ARM

### ISSUE THREAD

**Issue by mohsens22** [couchbase/couchbase-lite-net#858]
Hey, 
Seems that Couchbase.Lite for.NET UWP does not support Windows ARM. So can't be ran in phone and ARM based PCs devices.
Windows Universal platform is distributed into several sort of devices. Including phone(ARM) and Windows (Complete desktop version) running on ARM SoCs.
I can send analytics about my apps and see how much ARM users do they have :)
Please fix that. UWP DEVs are waiting for that :)

**Comment by RaminMT** [comment]
Hi,
I think supporting UWP on ARM devices can gain users & also contributors over this repo. I believe there is numerous UWP developers who's waiting for a UWP ARM release.

**Comment by NGame1** [comment]
please add ARM support for the library .

**Comment by HesamKashefi** [comment]
Yeah we need ARM Indeed! cause Microsoft is shifting to run x86 apps on ARM and in the future ARM will be a big opportunity and replacement for current devices ! Anyway there are just a few apps in Store which does not support ARM devices!

**Comment by borrrden** [comment]
Update (for visibility): Our current infrastructure is not equipped to properly handle this.  The first blocker is that we have no ARM build of OpenSSL.  I found a Microsoft fork that provides this though.  I was able to get a build to finally succeed for ARM, but we have no ARM devices to confirm that anything is working correctly...

**Comment by mohsens22** [comment]
@borrrden  If you have problem with devices, we can provide some for you :)

**Comment by borrrden** [comment]
That comment was for the management team actually (posted here so it doesn't look like I am doing nothing).  Ultimately they will decide if we support this and they will need to be aware of the requirements.

**Comment by borrrden** [comment]
Ok, the build has finally worked for the new way of doing things and it include a native ARM build.  Whether or not it works I'm not sure but it should because it's the same source as something that passes on UWP x64.  This will go out into DB8.  As a bonus, the unit test suite all passed with .NET Native (although I think WACK violations are still there...)

**Comment by borrrden** [comment]
Ok, I need to add the disclaimer that this will still not be an officially supported configuration.  Our resources are way too limited at the moment and we need to focus on getting other configurations officially supported first.  So the official line is "It should work but use at your own risk".  Oh and I got rid of the WACK violations so yay!

**Comment by mohsens22** [comment]
@borrrden  WHAT?
No official ARM support? You must be kidding :|
It's so odd for a UWP library to be not supported by ARM, requirement of C++ runtime in host machine and WACK violations.
So, what's the point?

**Comment by borrrden** [comment]
I know it sounds terrible but maybe it quite as terrible as you think. "Officially supported" means that we can sell paid support for it. So right now we can not sell it because we aren't in a position to test it enough without an actual device and people to set up a testing environment etc. This decision is not up to me, but I can influence it somewhat so I am going to keep trying.

**Comment by borrrden** [comment]
Oh and in regards to the C++ runtime, it should be enough to have the runtime extension installed on your project with DB8 (or b82) and not actually installing the runtime.  This will kill two birds: eliminate that requirement and get rid of the WACK violations.

**Comment by mohsens22** [comment]
Error while trying to run DB8 in an ARM Windows 10 Mobile phone which runs RS1(B14393):

System.TypeInitializationException occurred
  HResult=0x80131534
  Message=The type initializer for 'Couchbase.Lite.Database' threw an exception.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Couchbase.Lite.Database..ctor(String name, DatabaseOptions options)
   at Core.Models.DBH.CreateDB() in C:\Users\Mohsen\Source\Repos\Denna\Denna\Core\Models\DBH.cs:line 23
   at Core.Models.DBH.QueryW() in C:\Users\Mohsen\Source\Repos\Denna\Denna\Core\Models\DBH.cs:line 40
   at Core.Models.TasksModel.Tasks() in C:\Users\Mohsen\Source\Repos\Denna\Denna\Core\Models\TasksModel.cs:line 38
   at Denna.ViewModels.TimeLineViewModel..ctor() in C:\Users\Mohsen\Source\Repos\Denna\Denna\Denna\ViewModels\TimeLineViewModel.cs:line 17
   at Denna.Denna_XamlTypeInfo.XamlTypeInfoProvider.Activate_121_TimeLineViewModel() in C:\Users\Mohsen\Source\Repos\Denna\Denna\Denna\obj\ARM\Debug\XamlTypeInfo.g.cs:line 537
   at Denna.Denna_XamlTypeInfo.XamlUserType.ActivateInstance() in C:\Users\Mohsen\Source\Repos\Denna\Denna\Denna\obj\ARM\Debug\XamlTypeInfo.g.cs:line 4631

Inner Exception 1:
DllNotFoundException: Unable to load DLL 'LiteCore': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

More:
![image](https://cloud.githubusercontent.com/assets/22152065/26513865/3a7bfe56-4283-11e7-805f-7922d3e96765.png)

**Comment by mohsens22** [comment]
I found DB8 super cool, It's working perfectly on ARM (Tested on Windows 10 Mobile build 14393, 15063)
![image](https://cloud.githubusercontent.com/assets/22152065/26669553/93fc482a-46c3-11e7-86a1-724497ddf9d9.png)

**Comment by borrrden** [comment]
Excellent. I assume that means no installed runtime is required on any device, tablet desktop or phone. As far as "support" in the business sense I still have not gotten an answer but I will keep distributing ARM compatible builds anyway unless my management team forbids it (probably not likely that they will forbid it though)

**Comment by mohsens22** [comment]
Whhooops, ARM is still a bug :)
It doesn't write document :(
![image](https://user-images.githubusercontent.com/22152065/26945095-fca357ba-4c9f-11e7-81d2-b7259f48f2a0.png)

**Comment by borrrden** [comment]
I don't think that this ticket is appropriate for this because it's not the same problem. Plus I'll need all possible information and not just a screenshot of the exception type. Please open a new ticket and indicate if it happens only on arm
