### ISSUE TITLE
push replication issue

### ISSUE THREAD

**Issue by meteoric9637** [couchbase/couchbase-lite-net#860]
Hi I saved a document to couchbase lite in my app.
I checked the date from sqlite browser.
But I can see the data from couchbase server.
When I save the document, sync seems gateway worked, this is my log.
INFO) QUERY (Query): [22] 2017-5-19 10:26:19.464-07:00 [Query: Database=Database[C:\Users\Administrator\AppData\Local\sync_gateway.cblite2], Limit=2147483647, Skip=0, Descending=False, StartKey=,
EndKey=, StartKeyDocId=, EndKeyDocId=, InclusiveStart=True, InclusiveEnd=True,
IndexUpdateMode=Before, AllDocsMode=AllDocs, Keys=, MapOnly=True, GroupLevel=0, Prefetch=False,
IncludeDeleted=False, PostFilter=, PrefixMatchLevel=0] running...
INFO) VIEW (SqliteViewStore): [22] 2017-5-19 10:26:19.465-07:00 Checking indexes of (clientdetails_note) for clientdetails_note
INFO) VIEW (SqliteViewStore): [22] 2017-5-19 10:26:19.466-07:00 Updating indexes of (clientdetails_note) from #192768 to #192769 ...
INFO) VIEW (SqliteViewStore): [22] 2017-5-19 10:26:19.466-07:00 ...Finished re-indexing (clientdetails_note) to #192769 (deleted 0, added 1)
INFO) QUERY (SqliteViewStore): [22] 2017-5-19 10:26:19.467-07:00 Query clientdetails_note: SELECT key, value, docid, revs.sequence FROM 'maps_24', revs, docs WHERE 1 AND revs.sequence = 'maps_24'.sequence AND docs.doc_id = revs.doc_id ORDER BY key, docid LIMIT ? OFFSET ?
Arguments: 
INFO) QUERY (View): [23] 2017-5-19 10:26:19.474-07:00 Query clientdetails_note: Returning iterator
INFO) DATABASE (Database): [23] 2017-5-19 10:26:19.487-07:00 Database[C:\Users\Administrator\AppData\Local\sync_gateway.cblite2] posting change notifications: seq [192770]
INFO) SYNC (RemoteSession): [22] 2017-5-19 10:26:20.553-07:00 [Couchbase Sync Gateway: Version=1.4.0]: Server Version: [Couchbase Sync Gateway: Version=1.4.0]
INFO) SYNC (Pusher): [22] 2017-5-19 10:26:20.557-07:00 Pusher 8fbee973-a846-4db6-9319-7a193d2b43fa sending 1 revisions
Push: Active, Pull: Idle
Sync: Push Progress: 0/1;
(0.00)
INFO) CHANGE TRACKER (ChunkedChanges): [20] 2017-5-19 10:26:21.204-07:00 Parse found 1 changes
Push: Active, Pull: Active
Sync: Pull Progress: 0/1;
(0.00)
INFO) CHANGE TRACKER (ChunkedChanges): [22] 2017-5-19 10:26:21.205-07:00 Parsed [{"seq":192746,"id":"clientdetails_note:72","changes":[{"rev":"1-5d247beb9c7e60946e17a1368e4b441f"}]}] (nested count: 0)
INFO) SYNC (Puller): [22] 2017-5-19 10:26:21.207-07:00 Puller 37c4bbd6-dda2-4e63-b532-f727ca45356d Removed 1 already present revisions
INFO) SYNC (Replication): [22] 2017-5-19 10:26:21.209-07:00 Puller 37c4bbd6-dda2-4e63-b532-f727ca45356d checkpointing sequence=192746
Push: Active, Pull: Idle
Sync: Pull Progress: 1/1;
(1.00)
Push: Active, Pull: Idle
Sync: Pull Progress: 0/0;
(0.00)
INFO) SYNC (RemoteSession): [20] 2017-5-19 10:26:21.301-07:00 [Couchbase Sync Gateway: Version=1.4.0]: Server Version: [Couchbase Sync Gateway: Version=1.4.0]
Push: Idle, Pull: Idle
Sync: Push Progress: 0/0;
(0.00)
INFO) SYNC (Replication): [22] 2017-5-19 10:26:21.302-07:00 Pusher 8fbee973-a846-4db6-9319-7a193d2b43fa checkpointing sequence=192770
Push: Idle, Pull: Idle
Sync: Push Progress: 0/0;
(0.00)
INFO) SYNC (RemoteSession): [22] 2017-5-19 10:26:22.084-07:00 [Couchbase Sync Gateway: Version=1.4.0]: Server Version: [Couchbase Sync Gateway: Version=1.4.0]
INFO) SYNC (Replication): [23] 2017-5-19 10:26:22.095-07:00 Pusher 8fbee973-a846-4db6-9319-7a193d2b43fa saved remote checkpoint '192770' (_rev=0-9)
INFO) SYNC (RemoteSession): [13] 2017-5-19 10:26:22.317-07:00 [Couchbase Sync Gateway: Version=1.4.0]: Server Version: [Couchbase Sync Gateway: Version=1.4.0]
INFO) SYNC (Replication): [23] 2017-5-19 10:26:22.340-07:00 Puller 37c4bbd6-dda2-4e63-b532-f727ca45356d saved remote checkpoint '192746' (_rev=0-1479

**Comment by borrrden** [comment]
You mean you *can't* see the data in Couchbase Server?  How are you looking for it?  Can you see the data via Sync Gateway REST API?

**Comment by meteoric9637** [comment]
I logged in admin panel and I tried to see data with query in admin panel?
For example I can see the data with this ID "1-5d247beb9c7e60946e17a1368e4b441f" in sqlite.
document ID of the data is clientdetails_note:72, But I can't the data with the docID in couchbase admin panel

**Comment by borrrden** [comment]
"Admin panel" means Sync gateway's or Couchbase Server's.  Can you access the data via Sync Gateway?  If you can access the data via Sync Gateway but can't find it in Couchbase Server, then I would first ask on the forums for the correct way to do this because in general you shouldn't mess with the backing Couchbase Server directly.

**Comment by meteoric9637** [comment]
I mean Couchbase server, I made two bucket like below image. sales_agent is real bucket and sync_gateway is for sync.
!()[https://firebasestorage.googleapis.com/v0/b/dashboard-cc2cb.appspot.com/o/couchbase_server.PNG?alt=media&token=2046938e-cbbf-420e-a452-63491caa44c0]

**Comment by meteoric9637** [comment]
This is configuration file.
{
  "interface": ":4984",
  "adminInterface": ":4985",
  "log": [ "*" ],
  "databases": {
    "sync_gateway": {
      "server": "walrus:",
      "bucket": "sync_gateway",
      "users": {
        "GUEST": {
          "disabled": false,
          "admin_channels": [ "*" ]
        },
        "user": {
          "admin_channels": [ "*" ],
          "password": "user"
        }
      },
      "sync": `function(doc){ "channel(doc.channels); }`,
      ,
      "shadow": {
        "server": "http://couchbase-dev.thisisdmg.com:8091",
        "bucket": "sales_agent"
      }
    }
  }
}

**Comment by meteoric9637** [comment]
I tried to search like this way.
https://firebasestorage.googleapis.com/v0/b/dashboard-cc2cb.appspot.com/o/couchbase_search.PNG?alt=media&token=8bb7b804-88ea-4907-8802-84a83acae0dd

**Comment by borrrden** [comment]
Like I said, search in Sync Gateway please (see if you can access the documents in Sync Gateway).  If you can access documents in Sync Gateway but not in Couchbase Server then the problem is not at this level.  Couchbase Lite is only responsible for getting the data to its connected endpoint (Sync Gateway in your case)

**Comment by meteoric9637** [comment]
I'm not sure, what do you mean "search in Sync Gateway". I have two buckets "sales_agent" and sync_gateway.
The sales_agent is real bucket. I tried to search the data in both bucket but I can't get nothing.
And see push status from log
Sync: Pull Progress: 1/1;
Sync: Push Progress: 0/0;
It  means the push doesn't work.

**Comment by borrrden** [comment]
Use the [Sync Gateway REST API](https://developer.couchbase.com/documentation/mobile/current/references/sync-gateway/rest-api/index.html#!/document/get_db_doc) to get the document in question is what I mean.  Your configuration file is weird to me...using walrus and shadowing to server?  Why not just sync directly with server?  Your data is going to be saved in a flat file first by using walrus.  It looks like the pusher is not pushing that document because it is a document that it got from a pull replication (it doesn't make sense to push a document to a remote if it is one that it received from the same remote).

**Comment by djpongh** [comment]
@meteoric9637, any updates?

**Comment by djpongh** [comment]
Not enough info to figure out what's going on. Feel free to reopen if you have more info.
