### ISSUE TITLE
Sync gateway session management in V2.0 APIs?

### ISSUE THREAD

**Issue by mohsens22** [couchbase/couchbase-lite-net#862]
Hello.
I'm using CB.Lite.NET.UWP B0082. The question is that is there any way to manage all sessions of sync gateway log ins? Showing, termination and some other management stuff via V2.0 APIs? I saw that there is REST APIs for that and I couldn't find any V2.0 API.

**Comment by borrrden** [comment]
Questions should be asked on the forums, please.  This issue tracker should only report issues using the product.  Could you bring the question to the Couchbase forums and be a little more specific about what you are after?
