### ISSUE TITLE
UWP: CB.Lite.NET does not work on RS1 X86 mobile emulator

### ISSUE THREAD

**Issue by mohsens22** [couchbase/couchbase-lite-net#865]
Hey,
I'm working with CB.Lite.NET in UWP with DB8 prerelease and I saw some abnormal bugs.
in the ARM ticket you noted that it doesn't work in ARM devices. But now I tested a debug X86 build on a RS1 (B14393) mobile emulator and surprisingly it did NOT work. More interesting thing is that it works in RS2 (B15063) just FINE.
The error I get : 
![image](https://cloud.githubusercontent.com/assets/22152065/26513194/64bbc286-427f-11e7-8c9c-a4b97ad5754c.png)

_System.TypeInitializationException occurred
  HResult=0x80131534
  Message=The type initializer for 'Couchbase.Lite.Database' threw an exception.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Couchbase.Lite.Database..ctor(String name, DatabaseOptions options)
   at Core.Models.DBH.CreateDB() in C:\Users\Mohsen\Source\Repos\Denna\Denna\Core\Models\DBH.cs:line 23
   at Core.Models.DBH.QueryW() in C:\Users\Mohsen\Source\Repos\Denna\Denna\Core\Models\DBH.cs:line 40
   at Core.Models.TasksModel.Tasks() in C:\Users\Mohsen\Source\Repos\Denna\Denna\Core\Models\TasksModel.cs:line 38
   at Denna.ViewModels.TimeLineViewModel..ctor() in C:\Users\Mohsen\Source\Repos\Denna\Denna\Denna\ViewModels\TimeLineViewModel.cs:line 17
   at Denna.Denna_XamlTypeInfo.XamlTypeInfoProvider.Activate_121_TimeLineViewModel() in C:\Users\Mohsen\Source\Repos\Denna\Denna\Denna\obj\x86\Debug\XamlTypeInfo.g.cs:line 537
   at Denna.Denna_XamlTypeInfo.XamlUserType.ActivateInstance() in C:\Users\Mohsen\Source\Repos\Denna\Denna\Denna\obj\x86\Debug\XamlTypeInfo.g.cs:line 4631

Inner Exception 1:
DllNotFoundException: Unable to load DLL 'LiteCore': The specified module could not be found. (Exception from HRESULT: 0x8007007E)_

Stack trace:
![image](https://cloud.githubusercontent.com/assets/22152065/26513180/4aac9c26-427f-11e7-95a2-c83efb821b7b.png)

**Comment by mohsens22** [comment]
And here is emulators side by side. Right one (RS2) woks just fine but the left one (RS1) crashes at the very beginning.
![image](https://cloud.githubusercontent.com/assets/22152065/26513284/e7a0962c-427f-11e7-8e41-95a1ceb36d0b.png)

**Comment by borrrden** [comment]
I'm unfamiliar with these emulators.  Are these the devices you are using?  The build you have includes ARM native code so it should run in the same way on the device (and maybe fail in the same way...).

**Comment by borrrden** [comment]
Oh I realize you are talking about versions of Windows now!

**Comment by mohsens22** [comment]
It does NOT work on ARM. At least I tested in TH2(B10586) and RS1(14393) and it crashed!!!

**Comment by borrrden** [comment]
The exception in those instances are the same as the one you posted above?  If so then it's probably the same problem.

**Comment by mohsens22** [comment]
In the Mobile I don't remember the issue. But will test and inform you :)
Having crash in earlier versions of windows and other types of devices (phone, HoloLens, Hub, Xbox, IoT etc) is not good... But I'll test more in different devices and tell you more...

**Comment by mohsens22** [comment]
Yes. It seems that they have the same error

**Comment by borrrden** [comment]
I agree it's not good.  I don't think that this should take long to sort out though (but that's a pure guess).  The error indicates it couldn't *find* the library (i.e. the file was not there).  If it was there and failed to load the exception would be different.  The emulator failed to install for me though so I need to figure out why first...

**Comment by borrrden** [comment]
Ok I finally got the emulator running and I see the same thing.  I take back what I said about the error above; that logic is only for desktop.  DllNotFoundException in this case either means not found or not usable.  I imagine it is the latter, and I need to investigate why.  It might be an invalid "min version" in the native compile.

**Comment by borrrden** [comment]
I finally tracked down the problem due to luck and some obscure documentation references.  Apparently, referencing kernel32.dll is not allowed on Windows Phone (but for some reason in RS2 it became allowed because a "forwarding dll" exists for kernel32.dll while on previous versions it was simply not there and replaced by kernelbase.dll and kernel32_legacy.dll).  I didn't reference this DLL anywhere directly, but it is one of the references that gets added by default when compiling a C++ lib.  So I had to add the `/NODEFAULTLIB kernel32.lib` and after I did things started working on RS1 and RS2.

**Comment by borrrden** [comment]
Phew I got everything packaged in the nick of time for DB8, which is frozen today.  It will be pushed out as soon as I get the go-ahead (keep in mind that Monday is a U.S. holiday, so most people won't be in...but I'm not in the U.S. so I will be :p)

**Comment by mohsens22** [comment]
@borrrden  Then send the build here :D Then I can test and feedback more.

**Comment by borrrden** [comment]
DB8 was pushed out yesterday

**Comment by mohsens22** [comment]
![image](https://cloud.githubusercontent.com/assets/22152065/26668852/c9e4d036-46c0-11e7-81d2-cbf28aa4098b.png)

Seems that it's working!

**Comment by borrrden** [comment]
Cool. I will add an item to my checklist to run on an older emulator before making a DB in the future.

**Comment by mohsens22** [comment]
@borrrden Then check it in build 10240(Which is end of support) and build 10586.
Good job :)
