### ISSUE TITLE
Include XML documentation file with NuGet package

### ISSUE THREAD

**Issue by pkramerzoll** [couchbase/couchbase-lite-net#868]
The Couchbase Lite NuGet package does not contain the XML documentation file for the Couchbase Lite library, which would be helpful to have during development since it drives IntelliSense in Visual Studio.

**Comment by borrrden** [comment]
I'll ignore the fact that I spent 2 1/2 years not knowing this...and sneak it in soon

**Comment by djpongh** [comment]
Also do for 1.4.1
