### ISSUE TITLE
2.0 DB #10 on UWP: replacing a document leaves old properties in dictionary with value null

### ISSUE THREAD

**Issue by rainerg2000** [couchbase/couchbase-lite-net#878]
Replacing an existing document with a new set of properties does not work as expected. It leaves behind the previous properties with null values.

1. Insert a doc with 
```
var props = new Dictionary<string, object>
{
  {"PropName1, "Val1"},
  {"PropName2", 42},
};
var newDoc = new Document("docName", props);
mDB.Save(newDoc);
```

2. Replace the doc with a new set of properties
```
var newProps = new Dictionary<string, object>
{
  {"PropName3, "Val3"},
  {"PropName4", 84},
};
var existingDoc = mDB.GetDocument("docName");
existingDoc.Set(newProps);
mDB.Save(existingDoc);
```
3. Now reading back the document gives me:
```
{
  {"PropName1, null},
  {"PropName2", null},
  {"PropName3, "Val3"},
  {"PropName4", 84},
}
```
Instead I would expect:
{
  {"PropName3, "Val3"},
  {"PropName4", 84},
}

**Comment by borrrden** [comment]
Does this also happen if you use the fluent API?  i.e.

```
existingDoc.Remove("PropName1").Remove("PropName2").Set("PropName3", "Val3").Set("PropName4", 84);
```

**Comment by borrrden** [comment]
Looks like the answer is "yes" and this is a flaw in the `IEnumerator` implementation of the dictionary class.  The save operation should prune out removed values but the `IEnumerator` implementation does it too early and so the save operation just sees them as null (which is a valid thing to save) and so it lets them pass to the DB file.

**Comment by rainerg2000** [comment]
@borrrden  Thank you, Jim, for the quick fix.
Rainer.
