### ISSUE TITLE
Updating package does not update support package automatically.

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-net#881]
<img width="380" alt="screenshot 2017-06-23 14 31 07" src="https://user-images.githubusercontent.com/1365736/27501232-f34937c0-5820-11e7-8aa9-81cb53b5c00b.png">

**Comment by borrrden** [comment]
This is not something I have any control over other than specifying deps.  Updating the main packages *should* update the support packages because the dependency is correctly specified.
