### ISSUE TITLE
Replication with DNS endpoint failing on (at least) Mac

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-net#884]
> WARNING) TASK SCHEDULING (SerialQueue) [12] 2017-06-27T07:07:15.8963410+09:00 Exception during DispatchAsync: System.PlatformNotSupportedException: This platform does not support connecting sockets to DNS endpoints via the instance Connect and ConnectAsync methods, due to the potential for a host name to map to multiple IP addresses and sockets becoming invalid for use after a failed connect attempt. Use the static ConnectAsync method, or provide to the instance methods the specific IPAddress desired.
   at System.Net.Sockets.TcpClient.ConnectAsyncCore(String host, Int32 port)
   at Couchbase.Lite.Sync.WebSocketWrapper.<Start>b__25_0()
   at Couchbase.Lite.Support.SerialQueue.ProcessAsync()

Luckily the exception says what to do.

**Comment by borrrden** [comment]
Actually this is deeper than I thought, and a problem inside of the .NET Core runtime itself.  Most other libraries are simply waiting for .NET Core 2.0 which fixes the problem (confirmed this) so that might be what I do too.  The only other option is to perform DNS resolution manually which is a can of worms itself.

**Comment by djpongh** [comment]
Fixed by using .NET Core 2.0
