### ISSUE TITLE
.NET shared project: database.exists() returns false negative

### ISSUE THREAD

**Issue by thomas1983** [couchbase/couchbase-lite-net#885]
Hi,
My first report so hopefully I do it right.

When checking the database existence in CBL 2.0.0-db011 it returns false when true. 

` var db = Database.Exists("items", "");`

While a record count is correct (e.g. 28)

` var itemDb = new Database("items", new DatabaseConfiguration());
var count = itemDb.Count`

**Comment by borrrden** [comment]
This will work correctly if you pass in the directory where the database is located instead of an empty string.  I will change this so that it uses the default directory if the string is empty like this though.
