### ISSUE TITLE
couchbase/couchbase-lite-net 2.0 DB #11 on Android: Nuget package not usable

### ISSUE THREAD

**Issue by rainerg2000** [couchbase/couchbase-lite-net#887]
My Xamarin project is an Android library compiled using Android SDK 7.1.
I can use Nuget package for 1.4.1 version of the Couchbase.Lite

But when I update my CB Lite Nuget reference to 2.0 DB11 I get the following error. It seems that the monodroid dependency in Coucbase.Lite's nuspec file is not defined correctly.

Package Couchbase.Lite.Support.Android 2.0.0-db011 is not compatible with monoandroid71 (MonoAndroid,Version=v7.1). Package Couchbase.Lite.Support.Android 2.0.0-db011 supports: monodroid (**monodroid,Version=v0.0**)

**Comment by borrrden** [comment]
Hmmm...that's weird....I am not sure what is wrong here.  I am running tests using the package so it at least works on SOME devices.

**Comment by borrrden** [comment]
Looks like this could be a simple spelling mistake possibly.  It might fix it to go to where the nuget package is located and renaming the "monodroid" folders to "monoandroid"

**Comment by rainerg2000** [comment]
That might fix it. I don't have the C++ tool chain installed, so I can't do a full build from source, but if there's an easier way for me to rebuild just the nuget package. I can try to verify the fix for you release DB12

**Comment by borrrden** [comment]
The easy way is to just unzip it, mimic the structure in the nuspec, and then Nuget pack it again.  Or you can unzip the Nuget package and then use a decompiler to extract the native libraries from the support dll and put them in the correct place to build.

**Comment by borrrden** [comment]
Well anyway DB12 will be out early next week so if you don't have time before then, it won't be long before you have something to test ;).

**Comment by rainerg2000** [comment]
I repackaged it with the fixed .nuspec file as you had suggested. It works correctly now. Thanks.
Rainer.
