### ISSUE TITLE
Couchbase lite, NoSQL or SQL?!

### ISSUE THREAD

**Issue by mohammadomt** [couchbase/couchbase-lite-net#891]
Hi!
Couchbase is mentioned a NoSQL database that store data in JSON.
But we see that couchbase lite uses a storage engine (by default SQlite) to store data.

So now, couchbase lite is a small and lightweight version of couchbase using JSON and optimized for small apps or it is SQLite used to sync data with server in future?

(Excuse me if I'm not much informed about db engines)

**Comment by borrrden** [comment]
This is not an appropriate item for a GH issue.  Issues are reserved for bugs and feature requests.  This kind of discussion / question item should be reported on the [forums](http://forums.couchbase.com)
