### ISSUE TITLE
Feature request: expose tokens after auth code flow

### ISSUE THREAD

**Issue by tura08** [couchbase/couchbase-lite-net#893]
As per [forum discussion](https://forums.couchbase.com/t/feature-request-expose-tokens-after-auth-code-flow-net/13464), I was encouraged to post this as an issue:

Could the tokens that are received from the identity provider during Auth Code Flow login (using OpenIdConnectAuthenticator) be exposed publicly (read-only of course) so that they can be used to access other web resources that are also configured with the identity provider. A use case for this is once a user has logged in, the app needs to access some resource from Amazon S3 and in order to do so, they need to pass the id_token in the request so that Amazon can federate with the identity provider and return access credentials. The benefit of this is that it saves the developer from making a separate call to their identity provider which would have to be done adhoc using grant_type=client_credentials (using username/password) if they were to not ask the user to authenticate again.

If so, I am happy to do a PR. I think it's just a matter of changing some properties from "internal" to public {get; private set;} etc.

**Comment by borrrden** [comment]
FYI this change will need to be reviewed by the architect since it is a public API change and involves security.  That means it will likely not happen soon, but I will keep this in mind as we create 2.0 API.  We don't have a timeline for the next 1.x release yet.

**Comment by djpongh** [comment]
Not for the 1.X line
