### ISSUE TITLE
RunInTransaction freeze the whole application

### ISSUE THREAD

**Issue by chinhnguyen** [couchbase/couchbase-lite-net#898]
This is randomly happens solving conflicts on a WPF application.

![image](https://user-images.githubusercontent.com/839032/29160376-3385d236-7ddc-11e7-810c-692bbc7be5df.png)

The application is not using any CPU, however, it is frozen totally, debugging show that it is running a RunInTransaction command.

Any idea on the issue?

**Comment by borrrden** [comment]
I haven't seen a deadlock happen in this way for a long time, but that is my first guess as to what it is.  Can you take a look at your other threads and see what they are doing?  Also is this the latest version?

**Comment by chinhnguyen** [comment]
Thanks Jim! Looks like the code inside the Action is causing the deadlock. Nothing to do with the RunInTrasaction by itself.
