### ISSUE TITLE
EntryPointNotFoundException on Android when trying to connect to SyncGateway

### ISSUE THREAD

**Issue by csasus** [couchbase/couchbase-lite-net#901]
Starting the Replicator in order to connect to SyncGateway on Android results in a System.EntryPointNotFoundException (see below).
Any ideas?

Here's the log extract:
[...]
Loaded assembly: System.Runtime.InteropServices.RuntimeInformation.dll [External]
08-18 20:46:49.292 D/Mono    (12336): Assembly Ref addref System.Runtime.InteropServices.RuntimeInformation[0x836bfa90] -> mscorlib[0x77aa5200]: 58
08-18 20:46:49.312 D/Mono    (12336): DllImport attempting to load: '__Internal'.
08-18 20:46:49.312 D/Mono    (12336): DllImport loaded library '(null)'.
08-18 20:46:49.312 D/Mono    (12336): DllImport searching in: '__Internal' ('(null)').
08-18 20:46:49.312 D/Mono    (12336): Searching for 'mono_get_runtime_build_info'.
08-18 20:46:49.312 D/Mono    (12336): Probing 'mono_get_runtime_build_info'.
08-18 20:46:49.312 D/Mono    (12336): Could not find 'mono_get_runtime_build_info' due to 'Could not find symbol 'mono_get_runtime_build_info'.'.
08-18 20:46:49.312 D/Mono    (12336): Probing 'mono_get_runtime_build_info'.
08-18 20:46:49.312 D/Mono    (12336): Could not find 'mono_get_runtime_build_info' due to 'Could not find symbol 'mono_get_runtime_build_info'.'.
08-18 20:46:49.312 D/Mono    (12336): Probing 'mono_get_runtime_build_infoA'.
08-18 20:46:49.312 D/Mono    (12336): Could not find 'mono_get_runtime_build_infoA' due to 'Could not find symbol 'mono_get_runtime_build_infoA'.'.
08-18 20:46:49.312 D/Mono    (12336): Probing 'mono_get_runtime_build_infoA'.
08-18 20:46:49.312 D/Mono    (12336): Could not find 'mono_get_runtime_build_infoA' due to 'Could not find symbol 'mono_get_runtime_build_infoA'.'.
08-18 20:46:49.312 D/Mono    (12336): DllImport searching in: '__Internal' ('(null)').
08-18 20:46:49.312 D/Mono    (12336): Searching for 'mono_get_runtime_build_info'.
08-18 20:46:49.312 D/Mono    (12336): Probing 'mono_get_runtime_build_info'.
08-18 20:46:49.312 D/Mono    (12336): Could not find 'mono_get_runtime_build_info' due to 'Could not find symbol 'mono_get_runtime_build_info'.'.
08-18 20:46:49.312 D/Mono    (12336): Probing 'mono_get_runtime_build_info'.
08-18 20:46:49.312 D/Mono    (12336): Could not find 'mono_get_runtime_build_info' due to 'Could not find symbol 'mono_get_runtime_build_info'.'.
08-18 20:46:49.312 D/Mono    (12336): Probing 'mono_get_runtime_build_infoA'.
08-18 20:46:49.312 D/Mono    (12336): Could not find 'mono_get_runtime_build_infoA' due to 'Could not find symbol 'mono_get_runtime_build_infoA'.'.
08-18 20:46:49.312 D/Mono    (12336): Probing 'mono_get_runtime_build_infoA'.
08-18 20:46:49.312 D/Mono    (12336): Could not find 'mono_get_runtime_build_infoA' due to 'Could not find symbol 'mono_get_runtime_build_infoA'.'.
08-18 20:46:49.422 D/Mono    (12336): DllImport searching in: '__Internal' ('(null)').
08-18 20:46:49.422 D/Mono    (12336): Searching for 'java_interop_jnienv_call_nonvirtual_float_method_a'.
08-18 20:46:49.422 D/Mono    (12336): Probing 'java_interop_jnienv_call_nonvirtual_float_method_a'.
08-18 20:46:49.422 D/Mono    (12336): Found as 'java_interop_jnienv_call_nonvirtual_float_method_a'.
Thread finished:  #15
08-18 20:46:49.432 W/CouchbaseLite(12336): [16] 2017-8-18 08:46:49.436+02:00 TASK SCHEDULING (SerialQueue) [16] 2017-08-18T20:46:49.3533110+02:00 **Exception during DispatchAsync: System.EntryPointNotFoundException: mono_get_runtime_build_info**
08-18 20:46:49.432 W/CouchbaseLite(12336):   at (wrapper managed-to-native) System.Runtime.InteropServices.RuntimeInformation:mono_get_runtime_build_info ()
08-18 20:46:49.432 W/CouchbaseLite(12336):   at System.Runtime.InteropServices.RuntimeInformation.get_FrameworkDescription () [0x00000] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/System.Runtime.InteropServices.RuntimeInformation/System.Runtime.InteropServices/RuntimeInformation.cs:45 
08-18 20:46:49.432 W/CouchbaseLite(12336):   at Couchbase.Lite.Sync.HTTPLogic.UserAgent () [0x00059] in <416b0f44ba6c49099d6cd0dc54599e52>:0 
08-18 20:46:49.432 W/CouchbaseLite(12336):   at Couchbase.Lite.Sync.HTTPLogic.HTTPRequestData () [0x0002d] in <416b0f44ba6c49099d6cd0dc54599e52>:0 
08-18 20:46:49.432 W/CouchbaseLite(12336):   at Couchbase.Lite.Sync.WebSocketWrapper.OnSocketReady () [0x00000] in <416b0f44ba6c49099d6cd0dc54599e52>:0 
08-18 20:46:49.432 W/CouchbaseLite(12336):   at Couchbase.Lite.Sync.WebSocketWrapper.StartInternal () [0x001f2] in <416b0f44ba6c49099d6cd0dc54599e52>:0 
08-18 20:46:49.432 W/CouchbaseLite(12336):   at Couchbase.Lite.Support.SerialQueue.ProcessAsync () [0x0002f] in <416b0f44ba6c49099d6cd0dc54599e52>:0 
08-18 20:46:56.392 D/Mono    (12336): [0x848c66e8] worker finishing
Thread finished: <Thread Pool> #13

The system setup is the same as the one given in #897 (devices, visual studio version, packages, etc.).

**Comment by borrrden** [comment]
Was this resolved by updating Visual Studio to 15.3?

**Comment by djpongh** [comment]
Haven't heard back. Assuming things are working.
