### ISSUE TITLE
 Null values in documents cause corrupted file data

### ISSUE THREAD

**Issue by csasus** [couchbase/couchbase-lite-net#902]
Hi,

documents with items having null values seem to cause the file data to be inaccessible and labeled corrupt.

Steps to reproduce:
1. Save a document with any null values, i.e.
Document doc = new Document();
string s = null;
doc.Set(someKey, s);
myDatabase.Save(doc);

2. Load this document from the database using some appropriate query. Any query requesting the actual   null value (via select result) will do.
IResultSet rows = someQuery.Run();

Step 2 results in:
LiteCore.LiteCoreException: 'LiteCoreException (23): file data is corrupted’
With the error ocurring here:
Couchbase.Lite.dll!LiteCore.Interop.NativeHandler.Execute(LiteCore.Interop.C4TryLogicDelegate2 block) Unknown
Couchbase.Lite.dll!Couchbase.Lite.Internal.Query.XQuery.Run() Unknown

The error occured in Android and UWP using Couchbase.Lite 2.0 .NET, db014 (and at least back to db012). It might happen with other OS as well but I didn’t check.

**Comment by borrrden** [comment]
Thanks for this.  It has been identified as a problem in the core library, and so I refiled it as https://github.com/couchbase/couchbase-lite-core/issues/221
