### ISSUE TITLE
Memory leak in .NET Standard when updating documents.

### ISSUE THREAD

**Issue by MichaelHudgins** [couchbase/couchbase-lite-net#912]
There appears to be a memory leak in the document when updating with new information.  
The SaveInto function does not appear to release the old lite-core document representation after setting the newly returned one.  
Edit: Submitted pull request #913 as proposed fix

**Comment by borrrden** [comment]
Good find!  By the way how did you find this in particular?  Did you just happen to notice or was there some behavior that you found?

**Comment by MichaelHudgins** [comment]
I was stress testing the engine for an upcoming application i was looking at.  I ran tests creating tree structures between 10,000 and 1,000,000 documents and then doing multiple passes to update them.  I noticed it during that testing.
