### ISSUE TITLE
Nullpointer in Replicator.Dispose

### ISSUE THREAD

**Issue by hr-strunt** [couchbase/couchbase-lite-net#920]
Disposing a Replicator-instance may cause a null pointer exception.

I assume  there is a ? missing in line https://github.com/couchbase/couchbase-lite-net/blob/861bf314c371a0a8dd2eb7f5376ab25556169df9/src/Couchbase.Lite/API/Sync/Replicator.cs#L224

Maybe it should be changed from   _reachability.Stop();   to    _reachability?.Stop();

**Comment by borrrden** [comment]
Is this a static analyzer result or something that actually happened?

**Comment by hr-strunt** [comment]
The null pointer exception acutally happened when disposing the Replicator.

**Comment by borrrden** [comment]
Thanks, I ran into this too actually and it's such a dumb mistake!  It will be fixed in the next DB.
