### ISSUE TITLE
When will 1.4.1 be released?

### ISSUE THREAD

**Issue by tura08** [couchbase/couchbase-lite-net#923]
We're currently using the latest CI build for 1.4.1 because it has many fixes in it that we need. Obviously, it's a bit of a pain to get this into our app and CI pipeline because we have to download it from your CI server. It seems as though all the issues are closed for 1.4.1 milestone, so just wondering when this will be released on nuget?

**Comment by borrrden** [comment]
This is not the place for questions.  GitHub issues are for issues in the library that need to be fixed.  Please direct questions to [the forums](https://forums.couchbase.com/c/mobile).
