### ISSUE TITLE
Opening Mobile Database throws 2 internal exceptions

### ISSUE THREAD

**Issue by peterthecoder** [couchbase/couchbase-lite-net#930]
Version: 2.0.0-db19

This began with the new version. Previously working code stopped when trying to execute the Database constructor.

I tried creating a new, clean, minimal program and the same thing happened. It does the same for my WPF applications.

Exception and code:

<script src="https://gist.github.com/peterthecoder/77bd84cdfdd1f27f4782e5c465ca0ed0.js"></script>

**Comment by borrrden** [comment]
I can't read the link you included, it's just a bunch of unformatted HTML.  Could you redo it?

**Comment by borrrden** [comment]
Nevermind I was able to do it.  Could you let me know what version of Microsoft.Extensions.DependencyInjection you are using?  I recently discovered that the nuspec would allow version 2.0.0 to be used, but that version will crash because it's totally different.  It needs to be 1.x.  I have corrected the nuspec for DB020 which is coming early this week, but could you confirm the version and downgrade if necessary and let me know if that fixes things?

**Comment by peterthecoder** [comment]
Hi Jim:
Indeed, I am using version 2.0. in my WPF project, but niether in my UWP project. The WPF, with the older dependancy package, project throws another exception when executing the line :
Couchbase.Lite.Support.NetDesktop.Activate();

Error details:
System.TypeInitializationException occurred
  HResult=0x80131534
  Message=The type initializer for 'Couchbase.Lite.DI.Service' threw an exception.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Couchbase.Lite.DI.Service.get_IsFinalized()
   at Couchbase.Lite.DI.Service.RegisterServices(Action`1 config)
   at Couchbase.Lite.Support.NetDesktop.Activate() in C:\jenkins\workspace\couchbase-lite-net\couchbase-lite-net\src\Couchbase.Lite.Support.NetDesktop\Activate.cs:line 92
   at test3.MainWindow..ctor() in D:\VS Projects\Tests\test3\MainWindow.xaml.cs:line 20

Inner Exception 1:
FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Inner Exception 2:
FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

with this warning on build:
warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.


I have no idea where to find the logs, that's why they aren't here. Much of VS is new to me.

Incidentally, I love the syntax of CBL version 2. There's a whole lot less frustration.
I'm new to this whole NET/c#/Couchbase environment so a lot of things are a mystery to me.

Peter 

    On Monday, November 20, 2017, 6:37:29 AM EST, Jim Borden <notifications@github.com> wrote:  
 
 
Nevermind I was able to do it. Could you let me know what version of Microsoft.Extensions.DependencyInjection you are using? I recently discovered that the nuspec would allow version 2.0.0 to be used, but that version will crash because it's totally different. It needs to be 1.x. I have corrected the nuspec for DB020 which is coming early this week, but could you confirm the version and downgrade if necessary and let me know if that fixes things?

**Comment by borrrden** [comment]
It sounds like one of your projects has a reference to the 2.0.0 version still.  Check for Microsoft.Extensions.DependencyInjection.Abstractions as well.

**Comment by peterthecoder** [comment]
Hi Jim:
I rolled back all microsoft extensions to 1.1 from 2.0. When I then attempt to install CBL 2.0-db20 it automatically re-installs version 2.0 (2.2) of the microsoft extensions, then complains in the build window about not being compatible.


Peter 

    On Monday, November 20, 2017, 4:56:58 PM EST, Jim Borden <notifications@github.com> wrote:  
 
 
It sounds like one of your projects has a reference to the 2.0.0 version still. Check for Microsoft.Extensions.DependencyInjection.Abstractions as well.

**Comment by borrrden** [comment]
Does one of your other packages have a dependency on version 2.0?  I’m not sure why it would try to install 2.0 otherwise.

**Comment by peterthecoder** [comment]
I went into my clean UWP (my WPF project will ideally become a UWP) that only has 2 items from nugrt: CBL 2.0-db20 and Microsoft.NetCore.UniversalWindowsPlatform.
What I get in build window:
 warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
Sorry, I'm too much of a newby to figure this stuff out. All I know is all my code used to compile and run.


Peter 

    On Tuesday, November 21, 2017, 4:15:57 PM EST, Jim Borden <notifications@github.com> wrote:  
 
 
Does one of your other packages have a dependency on version 2.0? I’m not sure why it would try to install 2.0 otherwise.

**Comment by peterthecoder** [comment]
I just found this. Perhaps it is useful.
+   $exception  {System.TypeInitializationException: The type initializer for 'Couchbase.Lite.Sync.HTTPLogic' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Couchbase.Lite.Sync.HTTPLogic.GetUserAgent()
   at Couchbase.Lite.Sync.HTTPLogic..cctor()
   --- End of inner exception stack trace ---
   at Couchbase.Lite.Logging.Log.get_To()
   at Couchbase.Lite.Database.Open()
   at Couchbase.Lite.Database..ctor(String name, DatabaseConfiguration configuration)
   at UWPTest.MainPage..ctor()
   at UWPTest.UWPTest_XamlTypeInfo.XamlTypeInfoProvider.Activate_0_MainPage()
   at UWPTest.UWPTest_XamlTypeInfo.XamlUserType.ActivateInstance()} System.TypeInitializationException


Peter 

    On Tuesday, November 21, 2017, 4:15:57 PM EST, Jim Borden <notifications@github.com> wrote:  
 
 
Does one of your other packages have a dependency on version 2.0? I’m not sure why it would try to install 2.0 otherwise.

**Comment by borrrden** [comment]
Does installing the System.Runtime.InteropServices.RuntimeInformation Nuget package fix that?

**Comment by peterthecoder** [comment]
I installed the System.Runtime.InteropServices.RuntimeInformation and got this along with the same build warning I told you about yesterday:

System.TypeInitializationException occurred  HResult=0x80131534
  Message=The type initializer for 'Couchbase.Lite.Sync.HTTPLogic' threw an exception.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Couchbase.Lite.Logging.Log.get_To()
   at Couchbase.Lite.Database.Open()
   at Couchbase.Lite.Database..ctor(String name, DatabaseConfiguration configuration)
   at UWPTest.MainPage..ctor() in D:\VS Projects\Hammerhead_UWP\UWPTest\MainPage.xaml.cs:line 16
   at UWPTest.UWPTest_XamlTypeInfo.XamlTypeInfoProvider.Activate_0_MainPage() in D:\VS Projects\Hammerhead_UWP\UWPTest\obj\x86\Debug\XamlTypeInfo.g.cs:line 178
   at UWPTest.UWPTest_XamlTypeInfo.XamlUserType.ActivateInstance() in D:\VS Projects\Hammerhead_UWP\UWPTest\obj\x86\Debug\XamlTypeInfo.g.cs:line 333

Inner Exception 1:
FileLoadException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)



Peter 

    On Tuesday, November 21, 2017, 6:31:43 PM EST, Jim Borden <notifications@github.com> wrote:  
 
 
Does installing the System.Runtime.InteropServices.RuntimeInformation Nuget package fix that?

**Comment by borrrden** [comment]
Which Windows 10 build are you using. The error doesn’t really make sense to me...

**Comment by peterthecoder** [comment]
Hi Jim:
I was running out of ideas, so I tried uninstalling and re-installing System.Runtime.InteropServices.RuntimeInformation as well as CBL and my UWP app started to work. I haven't tried the WPF yet, but may do so tomorrow. Weirdness like this wears me down, but I'm plenty happy I can stop worrying about it.

Thanks for your patience so far!

Peter 

    On Wednesday, November 22, 2017, 6:42:10 PM EST, Jim Borden <notifications@github.com> wrote:  
 
 
Which Windows 10 build are you using. The error doesn’t really make sense to me...
