### ISSUE TITLE
AccessViolationException in UWP app, when using DB encryption

### ISSUE THREAD

**Issue by rainerg2000** [couchbase/couchbase-lite-net#931]
I am seeing System.AccessViolationException in Cb Lite.net 2.0 developer build 18. 
It happens when I insert a new doc after doing a push replication. 
The issue seems to be related to DB encryption in a Windows UWP app. When I disable encryption, the issue does not occur. 
I'd can send sources for a program that reproduces this issue under NDA.  See also https://support.couchbase.com/hc/en-us/requests/20219

**Comment by borrrden** [comment]
I cannot view that page, only the support team can.  If you have filed an issue with them then they will surely get to me with some information soon.  It would be helpful to put in a stack trace here though, especially with this kind of exception which is basically "somewhere some memory was used incorrectly."

**Comment by rainerg2000** [comment]
I will attach a stack trace later today.
Can I also send proprietary source to you under NDA ? If you are a Couchbase employee, it should not be an issue, because we have an NDA with the company already.

**Comment by rainerg2000** [comment]
Stack trace:
    LiteCore.Interop.Native.c4db_endTransaction(C4Database* database, Boolean commit, C4Error* outError)
    at Couchbase.Lite.Database.<>c__DisplayClass71_0.<EndTransaction>b__0(C4Error* err)
    at LiteCore.Interop.NativeHandler.Execute(C4TryLogicDelegate1 block)
    at Couchbase.Lite.Database.EndTransaction(Boolean commit)
    at Couchbase.Lite.Document.Save(IConflictResolver resolver, Boolean deletion)
    at Couchbase.Lite.Document.<Save>b__22_0()
    at Couchbase.Lite.Support.ThreadSafety.DoLocked(Action a)
    at Couchbase.Lite.Document.Save()
    at Couchbase.Lite.Database.<>c__DisplayClass68_0.<Save>b__0()
    at Couchbase.Lite.Support.ThreadSafety.DoLocked(Action a)
    at Couchbase.Lite.Database.Save(Document document)
    at XXXX.YYYY.Business.Database.CaboDatabaseCommon.Create(IDictionary`2 docToCreate)
    at XXXX.YYYY.CbAcceptance.Business.Database.ReplicationTestCases.<TestB_InsertOne>d__8.MoveNext()
    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
    at XXXX.YYYY.CbAcceptance.Business.Database.ReplicationTestCases.TestB_InsertOne()"	string

**Comment by borrrden** [comment]
If  you have everything you need then I am ready to receive it (I didn't know that the NDA was already taken care of, an NDA with the company will apply to me).  What delivery method did you have in mind?

**Comment by rainerg2000** [comment]
Thanks for looking into this. Please send me your OpenPGP key. On Monday I can encrypt and upload it to a file share.
Rainer.

**Comment by borrrden** [comment]
The key is checked into the root of the repo

https://github.com/couchbase/couchbase-lite-net/blob/feature/api-v2/jim_borden.gpg

**Comment by rainerg2000** [comment]
@borrrden, encrypted test program sources here:
https://drive.google.com/file/d/17vfSIjLR4pqaEQkObgi9r-LwAZnU9ZEo/view?usp=sharing

**Comment by rainerg2000** [comment]
my OpenPGP key:
https://drive.google.com/file/d/1bKokd4GZIMu847bJ2wxZoGH6ot6sqcg8/view?usp=sharing

**Comment by borrrden** [comment]
I've narrowed down the issue somewhat thanks to this.  A replicator will copy the native database object inside of LiteCore so that sit can do with it as it pleases independently of whatever the user is doing in CBL-land.  However, it *looks* like the encryption context is being shared between the two which means that when the replicator shuts down and disposes its object, the shared encryption context is also getting disposed, and so it is invalid during the next page write (which usually occurs at transaction end time).

P.S. As for your comment about JToken, I think I can do something about that as well. I'm already handling the case of receiving JObject / JArray, and so tacking on JToken handling should be possible.

**Comment by borrrden** [comment]
Ok I have verified the issues, and fixed it (the tests you sent now pass).  The tracking ticket is [here](https://github.com/couchbase/couchbase-lite-core/issues/311)

**Comment by rainerg2000** [comment]
Thank you for the quick investigation and fix. What is the best best way for me to contribute to your test effort ? I can't promise consistent dev bandwidth, but it is in my interest to see CB Lite.net 2.0 GA soon.

**Comment by borrrden** [comment]
You are already doing plenty to contribute to the testing effort.  Finding issues by doing independent testing is one of the main reasons for us to release developer builds.  The onus now is on the QA team to set up an environment in which we can spin up and down instances and perform functional testing of replication.  It's not a small task and it strains our resources, but it will be worth it once complete.  As far as GA is concerned, in theory we have just one more major API refactor to get through and after that it's just optimizing and fixing for another month or two.
