### ISSUE TITLE
replication not working in DB020

### ISSUE THREAD

**Issue by rainerg2000** [couchbase/couchbase-lite-net#933]
I have some simple test cases that passed in DB018 and DB019, but fail in DB020. They use basic auth against sync_gateway 1.5.0(594;e78dbf1)

The sync-gateway log shows no sign of a connection happening. The local CB Lite log for a pull replication shows this:

{"Timestamp":"2017-11-28T14:41:43.0440312-08:00","Level":"Information","MessageTemplate":"(Replicator)
 [5] 2017-11-28T14:41:43.0440312-08:00 Replicator[< ws://cb1-xxx.es.xxxxxxxxx.int:4984/mdp-integration-test]: Starting","Properties":{"SourceContext":"Sync","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.0641105-08:00","Level":"Information","MessageTemplate":"Opening DataFile C:\\Users\\Rainer\\AppData\\Local\\Packages\\1da5575a-cb6f-458e-bf6d-a093aa4a0c8b_gjq16mqec4pxy\\LocalState\\Cbl-qYgEA\\xxxxxxxxx.Cabo.Business.Database.Uwp.CaboDatabaseUwp.cblite2\\db.sqlite3","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.0681128-08:00","Level":"Verbose","MessageTemplate":"SELECT count(*) FROM sqlite_master","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.0701145-08:00","Level":"Verbose","MessageTemplate":"PRAGMA cache_size=-10240; PRAGMA mmap_size=52428800; PRAGMA synchronous=normal; PRAGMA journal_size_limit=5242880","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.0721154-08:00","Level":"Verbose","MessageTemplate":"... SELECT * FROM sqlite_master WHERE type='table' AND name=?","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.0741172-08:00","Level":"Verbose","MessageTemplate":"... SELECT sequence, flags, 0, version, body FROM kv_info WHERE key=?","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.0761181-08:00","Level":"Verbose","MessageTemplate":"... SELECT sequence, flags, 0, version, body FROM kv_info WHERE key=?","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.0781194-08:00","Level":"Information","MessageTemplate":"{1}--> ->ws:cb1-xxx.es.xxxxxxxxx.int:4984/mdp-integration-test/_blipsync","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.0811216-08:00","Level":"Information","MessageTemplate":"{1} Opening connection...","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.0841238-08:00","Level":"Information","MessageTemplate":"Starting Scheduler<124FF798> with 8 threads","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.0891269-08:00","Level":"Verbose","MessageTemplate":"   task 1 starting","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.0921287-08:00","Level":"Verbose","MessageTemplate":"   task 2 starting","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.0941300-08:00","Level":"Verbose","MessageTemplate":"   task 2 calling Actor<0E6772F0>","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.1061392-08:00","Level":"Verbose","MessageTemplate":"   task 4 starting","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.1121440-08:00","Level":"Verbose","MessageTemplate":"   task 5 starting","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.1161458-08:00","Level":"Verbose","MessageTemplate":"   task 6 starting","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.1201476-08:00","Level":"Verbose","MessageTemplate":"   task 7 starting","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.1231494-08:00","Level":"Verbose","MessageTemplate":"   task 8 starting","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.1241499-08:00","Level":"Verbose","MessageTemplate":"   task 1 calling Actor<1429CCB8>","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.1261512-08:00","Level":"Verbose","MessageTemplate":"BLIP[->ws:cb1-xxx.es.xxxxxxxxx.int:4984/mdp-integration-test/_blipsync] performNextMessage","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.1271525-08:00","Level":"Verbose","MessageTemplate":"Repl->ws:cb1-xxx.es.xxxxxxxxx.int:4984/mdp-integration-test/_blipsync performNextMessage","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.1291534-08:00","Level":"Information","MessageTemplate":"(Replicator) [5] 2017-11-28T14:41:43.1121440-08:00 Replicator[< ws://cb1-xxx.es.xxxxxxxxx.int:4984/mdp-integration-test] is Connecting, progress 0/0","Properties":{"SourceContext":"Sync","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.1341602-08:00","Level":"Verbose","MessageTemplate":"   task 3 starting","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.1356611-08:00","Level":"Verbose","MessageTemplate":"   task 1 calling Actor<1429CCB8>","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.1371615-08:00","Level":"Verbose","MessageTemplate":"BLIP[->ws:cb1-xxx.es.xxxxxxxxx.int:4984/mdp-integration-test/_blipsync] performNextMessage","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.1386628-08:00","Level":"Verbose","MessageTemplate":"   task 1 calling Actor<1429CCB8>","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.1401641-08:00","Level":"Verbose","MessageTemplate":"BLIP[->ws:cb1-xxx.es.xxxxxxxxx.int:4984/mdp-integration-test/_blipsync] performNextMessage","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.1416646-08:00","Level":"Information","MessageTemplate":"(Replicator) [5] 2017-11-28T14:41:43.1396641-08:00 Replicator[< ws://cb1-xxx.es.xxxxxxxxx.int:4984/mdp-integration-test] is Connecting, progress 0/0","Properties":{"SourceContext":"Sync","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.1451672-08:00","Level":"Verbose","MessageTemplate":"   task 1 calling Actor<1429CCB8>","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.1461677-08:00","Level":"Verbose","MessageTemplate":"BLIP[->ws:cb1-xxx.es.xxxxxxxxx.int:4984/mdp-integration-test/_blipsync] performNextMessage","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.1486251-08:00","Level":"Verbose","MessageTemplate":"   task 1 calling Actor<1429CCB8>","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.1506265-08:00","Level":"Verbose","MessageTemplate":"BLIP[->ws:cb1-xxx.es.xxxxxxxxx.int:4984/mdp-integration-test/_blipsync] performNextMessage","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.1516269-08:00","Level":"Verbose","MessageTemplate":"   task 1 calling Actor<1429CCB8>","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.1536282-08:00","Level":"Verbose","MessageTemplate":"BLIP[->ws:cb1-xxx.es.xxxxxxxxx.int:4984/mdp-integration-test/_blipsync] performNextMessage","Properties":{"SourceContext":"LiteCore","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.4295655-08:00","Level":"Information","MessageTemplate":"(WebSocketWrapper) [26] 2017-11-28T14:41:43.4295655-08:00 WebSocket connecting to cb1-xxx.es.xxxxxxxxx.int:4984","Properties":{"SourceContext":"Sync","ContextProperties":{}}}
{"Timestamp":"2017-11-28T14:41:43.4395775-08:00","Level":"Warning","MessageTemplate":"(SerialQueue) [26] 2017-11-28T14:41:43.4355723-08:00 Exception during DispatchAsync: System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Couchbase.Lite.Sync.WebSocketWrapper.StartInternal()\r\n   at Couchbase.Lite.Support.SerialQueue.ProcessAsync()","Properties":{"SourceContext":"Couchbase","ContextProperties":{}}}

**Comment by borrrden** [comment]
Duplicate https://github.com/couchbase/couchbase-lite-net/issues/932

**Comment by borrrden** [comment]
I am planning to republish DB020 because this error is such nonsense and many people are reporting it.

**Comment by borrrden** [comment]
DB020 is currently republishing.  Note: You will need to delete the local package or nuget will think it already has it.  You can confirm that you have the new version in the logs because the version will show up as 2.0.0-b0434.

**Comment by rainerg2000** [comment]
that's great, thank you. Will try it tomorrow.

**Comment by rainerg2000** [comment]
I confirmed that replication with Basic Auth works in the re-released DB020. 
Thank you.
