### ISSUE TITLE
Xamarin Assertion failure 'align > 0'

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-net#934]
[Upstream bug](https://bugzilla.xamarin.com/show_bug.cgi?id=60634)

Not much we can do about this, but keeping it here in case users start hitting it.  The solution is to downgrade to Xamarin Android 8.0 / iOS 11.3 or below.  The upstream bug is marked "fixed" because it was fixed in the mono repo, but those changes didn't propagate into the Xamarin release (They are still using 2017/06 mono)

**Comment by borrrden** [comment]
Testing shows that this causes the issue to go away.  DB021 will include the workaround.

**Comment by DrifterApps** [comment]
Hi, 

Before I open a new issue, I'm still experiencing the Xamarin Assertion failure 'align > 0' with 2.0 DB 21.

To make sure I understand, Is my only choice to downgrade my Xamarin.Android or is the workaround for the default() for unsafe struct supposed to fix the issue??

**Comment by borrrden** [comment]
Downgrading to the appropriate version will work.  I didn't see the issue anymore with the fix I included in db021, but it wasn't guaranteed in all cases I guess.  The downstream fix should be coming in 15.6

**Comment by DrifterApps** [comment]
I fixed the problem, I had to uninstall my app and reinstall it for it to work... something was probably left lingering.

Thanks!
