### ISSUE TITLE
2.0: Request changes based on API review

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-net#941]
## Request changes based on API Review

MostActiveWinsConflictResolver
* [x] Make it non public (API Spec updated)

Database
* [x] AddDocumentChangeListener(documentID, ….) -> AddDocumentChangeListener(id, ….)
* [x] Copy(path, name, config) -> config doesn’t have [CanBeNull].
* [x] public Database(Database other) shouldn’t be public.
* [x] public void InBatch(Action a) -> public void InBatch(Action action) 

DatabaseConfiguration
* [x]  public DatabaseConfiguration(DatabaseConfiguration other) shouldn’t be public.

EncryptionKey
* [x] public EncryptionKey(string password, byte[] salt, int rounds) not in spec. This could be added later based on demand.
* [x] HexData is not in spec.
* ~~Change KeyData to Key.~~

ICountable
* [x] Not in spec.

Document
* [x] Database property is not in spec.

MutableArray
* [x] MutableArray -> MutableArrayObject for naming consistency 

MutableDictionary
* [x] MutableDictionary -> MutableDictionaryObject for naming consistency

MutableDocument
* [x] MutableDocument(string documentID) -> MutableDocument(string id)
* [x] MutableDocument(IDictionary<string, object> dictionary) ->  MutableDocument(IDictionary<string, object> data)
* [x] MutableDocument(string documentID, IDictionary<string, object> dictionary) -> MutableDocument(string id, IDictionary<string, object> data) 

ReplicationStatusChangedEventArgs
* [x] ReplicationStatusChangedEventArgs -> ReplicatorStatusChangedEventArgs
* [ ] Replicator property is missing. 

ReplicationStatus
* [x] ReplicationStatus -> ReplicatorStatus

ReplicationProgress
* [x]  ReplicationProgress -> ReplicatorProgress

HttpLogicException and HttpLogicError
* [ ] Can this be CouchbaseLiteException instead?

OptionsDictionary
* [x] Shound’t be public 

AuthOptionsDictionary
* [x] Shound’t be public.

AuthType
* [x] Shouldn’t be public.

RefCountedDisposable
* [x] Shouldn’t be public. 

Extensions
* [x] Shouldn’t be public. 

ArrayFunction
* [x] Contains(object array, object element) -> Contains(object expression, object value)

Expression
* [x] public static IExpression Parameter(int index) is not part of spec.
* [x] Missing `is` and `isNot` expression
* ~~Missing `concat` expression.~~

Function
* [x] Contains(object str, object item) -> Contains(object expression, object substring)

QueryParameters
* [x] QueryParameters -> Parameters 

Join
* ~~DefaultJoin(dataSource) -> Join(dataSource) ~~
* [x] Remove DefaultJoin(dataSource) for .NET.

Ordering
* [x] Property(string name) -> Property(string property) 

IOrderByRouter
* [x] OrderBy(params IOrdering[] orderBys) -> OrderBy(params IOrdering[] orderings) 

Query
* [x] Select(params ISelectResult[] resultsToSelect) -> Select(params ISelectResult[] results)
* [x] SelectDistinct(params ISelectResult[] resultsToSelect) -> SelectDistinct(params ISelectResult[] results) 

IResultSet
* [x] Count is not part of spec.

QueryResult
* [x] QueryResult -> Result

QueryChangedEventArgs
* [x] Rows -> Results
* [ ] Missing Query property.

IFullTextIndex
* [x] SetLocale(string localeCode) -> Locale(string locale) 

FullTextExpression
* [x] Index(string indexName) -> Index(string name)

IUnicodeCollation
* [x] Locale(string localeCode) -> Locale(string locale)

## Request changes based on API Spec update

See:
https://github.com/couchbaselabs/couchbase-lite-apiv2/commit/df94b46e0e5aa9e7eac2da006964553662cb76b2
https://github.com/couchbaselabs/couchbase-lite-apiv2/commit/ad7a29ae1872da9d41d4f1dfce71aeb28d26c7e3
https://github.com/couchbaselabs/couchbase-lite-apiv2/commit/4b501559f67f9e9f2e131ccbda85e65b244ab4d5

DatabaseConfiguration
* [x] Use builder pattern
* [x] ConflictResolver cannot be null - not allow to set null
* [x] Directory cannot be null - not allow to set null

Database
* [x] Remove contains(String id)
* [x] delete(document) : No ops when deleting a non-existing document or a document that has already been deleted.
* [x] delete(document) : Throws non-allow exception when deleting a newly created document.
* [x] purge(document) : No ops when purging a non-existing document.

DocumentChangedEventArgs
* [x] Add Database property (source of event)

ReplicatorConfiguration
* [x] Use builder pattern
* [x] ConflictResolver cannot be null - not allow to set null
* [x] Add Endpoint interface, NetworkEndpoint class and DatabaseEndpoint class for target.

Parameters
* [x] Use builder pattern
* [x] Add getValue()

Expression
* [x] Add all() to express * (star). This can be used to express count(*) and select *.

FullTextExpression
* [x] Change index(indexName) to index(name).

Function
* [x] Remove all type checking functions.

ResultSet
* ~~Add toList()/toArray()~~

**Comment by pasin** [comment]
Is there documentation/example about the API in DI folder that I can ready? I cannot figure out the DI API from looking at the code.

**Comment by borrrden** [comment]
> Change KeyData to Key.

Key is also not in the spec?

> Replicator property is missing.  / Query property is missing

I made a note about this in my excel sheet on the differences in event handling between .NET and the spec.  Having this property is redundant.

> missing concat

Why is it there if it does nothing?

> DefaultJoin(dataSource) -> Join(dataSource) 

As I've pointed out (in the excel sheet), this is not possible in C# (A class cannot contain a method whose name is the same as the class).

> IResultSet Count

Without this there is no way to count the number of rows in the result without iterating through all of them. Is that OK?

> builder pattern

This seems like overkill just to set a few properties.  If anything the Database and Replicator should be built directly via builders.  What is the motivation for this?

> HttpLogicException and HttpLogicError

They can be CouchbaseLiteException but what code should they be?

Everything else looks alright and I will do it soon.

About DI, it is specific to .NET and shouldn't be affected by the cross platform spec.  It is just there in the API folder in case someone wants to add a new platform that we don't support.  It is needed because .NET goes to multiple platforms and some of the functionality doesn't fall into the cross platform .NET Standard spec.

**Comment by borrrden** [comment]
Oh and as for ICountable, it is necessary to have this interface in order for Count to be used.  Otherwise there is a clash between the Count on `IDictionaryObject` and `IArray`

**Comment by pasin** [comment]
> Key is also not in the spec?

Your are right. Then remove Key too. We could add it later based on demand.

> missing concat
> Why is it there if it does nothing?

Haven't LC already implemented it?

> DefaultJoin(dataSource) -> Join(dataSource) 
> As I've pointed out (in the excel sheet), this is not possible in C# (A class cannot contain a method whose name is the same as the class).

Keep DefaultJoin. I will let you know if I can come up with a better name.

> IResultSet Count
> Without this there is no way to count the number of rows in the result without iterating through all > of them. Is that OK?

We will have toList/Array() to use if users want to know count.

> builder pattern
> This seems like overkill just to set a few properties. If anything the Database and Replicator should > be built directly via builders. What is the motivation for this?

We have tried to not having something like this, but this https://github.com/couchbase/couchbase-lite-ios/issues/1985 issue is the motive. It's not obvious for users to realize the copy behavior and when it happens, it is not easy to debug if users do not sure their code.

> HttpLogicException and HttpLogicError
> They can be CouchbaseLiteException but what code should they be?

The error code / message audit will be started next week. I don't have the info now.

> except I am not happy about the Encryption key using a predefined salt all the time...it defeats the > purpose of a salt so why are we even doing it and claiming that we follow "best security practices"?

IIRC, in 1.x we also don't allow to set salt and I haven't heard anyone have asked for it. Anyway, can you create an issue on the API repo about this?

**Comment by pasin** [comment]
> Keep DefaultJoin. I will let you know if I can come up with a better name.

Let remove DefaultJoin. Users can use InnerJoin for that. If it leads to confusion, we will add back DefaultJoin later.

**Comment by pasin** [comment]
I have just updated the Endpoint classes. Could you please make changes accordingly? Sorry for the immediate changes.

https://github.com/couchbaselabs/couchbase-lite-apiv2/commit/49ac079b06fe7af49fbf8214bd0bab087b42114a

**Comment by borrrden** [comment]
LiteCore has *not* implemented `concat` yet FYI.

> We will have toList/Array() to use if users want to know count.

This is the same as enumerating the entire data set.  

> in 1.x we also don't allow to set salt 

I copied my implementation pretty much verbatim from 1.x.  That implementation was based on [the 1.x implementation in Objective-C](https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBLSymmetricKey.h)

**Comment by borrrden** [comment]
> Remove all type checking functions.

Just to be clear, these are functions like `IsArray` ?

**Comment by pasin** [comment]
> Just to be clear, these are functions like IsArray ?

Yes.

**Comment by pasin** [comment]
> I copied my implementation pretty much verbatim from 1.x. That implementation was based on the 1.x implementation in Objective-C

The CBLSymmetricKey is not public in 1.x. The one that is public is https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/API/CBLManager.h#L35-L46.

**Comment by pasin** [comment]
> This is the same as enumerating the entire data set unless you mean that this should be QueryResultArray in which case calling ToList will invalidate the original result set because random access and iteration cannot coexist.

Do you mean calling c4queryenum_seek(enum, index) will invalidate or move the current row pointer?

**Comment by borrrden** [comment]
> The CBLSymmetricKey is not public in 1.x

Oh, it is public in .NET.  

> Do you mean calling c4queryenum_seek(enum, index) will invalidate or move the current row pointer?

Yes exactly.  That is the way Objective-C is operating as well.  The problem is that there is no way in LiteCore now to make a copy of an enumerator and so we have to reuse the same one.  Either that or go through the entire enumerator and load each object into a new list.

**Comment by pasin** [comment]
I have just quickly tested it by implementing as below and the unit test passes. Have I misunderstood anything?

```Objective-C
- (NSArray<CBLQueryResult*>*) toArray {
    CBLDatabase* db = self.database;
    CBL_LOCK(db) {
        NSInteger count = (NSInteger)c4queryenum_getRowCount(_c4enum, nullptr);
        return [[CBLQueryResultArray alloc] initWithResultSet: self count: count];
    }
}
```

Unit Tests:

```Objective-C
- (void) testResultSetToArray {
    [self loadNumbers: 10];
    
    CBLQuery* q = [CBLQuery select: @[kDOCID]
                              from: [CBLQueryDataSource database: self.db]];
    
    // Call toArray before iterate:
    NSError* error;
    CBLQueryResultSet* rs = [q execute: &error];
    Assert(rs, @"Query failed: %@", error);
    
    NSArray<CBLQueryResult*>* results = [rs toArray];
    CBLQueryResult *r;
    NSUInteger i = 0;
    while ((r = [rs nextObject])) {
        AssertEqualObjects([r valueAtIndex: 0] , [results[i] valueAtIndex: 0]);
        i++;
    }
    
    AssertEqual(results.count, 10u);
    AssertEqual(i, 10u);
    
    // Call toArray after iterate:
    rs = [q execute: &error];
    Assert(rs, @"Query failed: %@", error);
    
    NSMutableArray<CBLQueryResult*>* iResults = [NSMutableArray array];
    while ((r = [rs nextObject])) {
        [iResults addObject: r];
    }
    
    results = [rs toArray];
    
    AssertEqual(results.count, 10u);
    AssertEqual(iResults.count, 10u);
    
    for (i = 0; i < results.count; i++) {
        AssertEqualObjects([iResults[i] valueAtIndex: 0],
                           [results[i] valueAtIndex: 0]);
    }
}
```

**Comment by borrrden** [comment]
Try iterating after calling toArray

**Comment by pasin** [comment]
The test already does that.

**Comment by borrrden** [comment]
[These lines](https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Objective-C/CBLQueryResultSet.mm#L95-L96) Kill iteration if the query has been randomly accessed.

It gets set [in this location](https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Objective-C/CBLQueryResultSet.mm#L145)

This suggests, rightfully, that iteration and random access cannot go on at once.  What is the result of seeking (i.e. array_results[2] followed by a call to [rs nextObject])?

**Comment by pasin** [comment]
I removed those two lines that you mentions above.

**Comment by borrrden** [comment]
But the issue still remains doesn't it?  

If you are iterating and call `nextObject` 5 times, for example, you would expect the next entry to be the 6th one, but a call to toArray()[2] will move back to the third position and the next call to `nextObject` will return the 4th object instead of the 6th.

**Comment by pasin** [comment]
Yeah, doesn't work. The cursor gets messed up.

**Comment by borrrden** [comment]
Well following that, it means that without `Count` on the result set, the only way to get the count is to invalidate the result set itself.

**Comment by borrrden** [comment]
@pasin Let me know what the codes for HTTPLogicException should be.  The Objective-C codebase is not clear since it does not use kCBLErrorDomain (instead using NSURLDomain).  If it is not decided by tomorrow then I think DB022 will be delayed.

**Comment by pasin** [comment]
Let use HTTPLogicException for DB22. You could make up the code now as well if you want to. The error code and message will be done after DB22.
