### ISSUE TITLE
Update LiteCore for replication protocol update

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-net#944]
SG and LiteCore have made a backwards-incompatible change to the 2.0 replication protocol. Need to update the LiteCore submodule to 5ecffee9ce2b1511fd11159c7cf0f1c3d9b66832 or later.

**Comment by snej** [comment]
couchbase/couchbase-lite-core#297

**Comment by borrrden** [comment]
I will do this as soon as there is a viable build for it (Android currently unable to build and Windows crashing for some reason)
