### ISSUE TITLE
CB2.0, DB21, sync gateway 1.5, Replication issus

### ISSUE THREAD

**Issue by SteeveQuadra** [couchbase/couchbase-lite-net#948]
Hi,

I explained most of my problems on this post on the couchbase forum :
[https://forums.couchbase.com/t/couchbase-lite-2-0-db21-replicator-issues/15456](https://forums.couchbase.com/t/couchbase-lite-2-0-db21-replicator-issues/15456)
I'm using couchbase lite 2.0, version db21 with an officiel sync gateway 1.5. My application is in Xamarin c#, I'm realy testing only the UWP project.

When there are some exceptions, or something disturbing the initial replication (around 39000 documents), It won't work well after.
The the visual proof this troubles are the progress numbers (Total and completed) and the numbers of replicate documents which don't match with the bucket. For what I understood, The replicator status should never be with the status Idle and have the total number greater than the completed number. The difference is the number of documents that weren't well replicate. The replicator seems to not be able to correct this situation.
How to reproduce this problem ?
I tried in the issue #945 in sharing a simple windows console solution, unfortulately, Jim borden wasn't able to reproduce it. After some test, I think It's possible to put the application in the same state just in removing the network cable from your computer( or in using a very bad wifi connection) in the initial sync process.
Each time I'm doing it in between the initial start of my application and the end of the initial replication, I've got the problem (It's just a way for you to reproduce the trouble, I have it even without removing my network cable, and I've a good network quality)

I shared a cryted version of my solution for Jim @borrrden to try it, hoping this could help.
[https://github.com/SteeveQuadra/SyncMonitor](https://github.com/SteeveQuadra/SyncMonitor), file mobilotis4.7z.gpg

The replicator should be able to correct the situation when it was not possible the sync correctly some documents previously, due to network reasons or exception, as I have : LiteCoreException (1005): no status code received

Regards,

Steeve

**Comment by borrrden** [comment]
This information seems like it is not worth a new ticket, but rather a comment on the old one #945 so I will close it.
