### ISSUE TITLE
API Enhancement Request

### ISSUE THREAD

**Issue by ssmotra** [couchbase/couchbase-lite-net#950]
After a document is successfully replicated, the replicator should allow for the document to be purged locally.

**Comment by borrrden** [comment]
CC @snej @pasin This will require both LiteCore work and cross platform API work

**Comment by pasin** [comment]
@ssmotra If it is the API enhancement, I think it's better to open the issue on the https://github.com/couchbaselabs/couchbase-lite-apiv2 repo.

**Comment by snej** [comment]
Moved to https://github.com/couchbaselabs/couchbase-lite-apiv2/issues/196
