### ISSUE TITLE
API Enhancement Request - Filtered push replication

### ISSUE THREAD

**Issue by ssmotra** [couchbase/couchbase-lite-net#951]
The push replication should allow for filtering a subset of the local documents that are being pushed to Sync Gateway.

**Comment by borrrden** [comment]
CC @pasin

**Comment by pasin** [comment]
@ssmotra Is this for 2.0 or 2.x?

**Comment by pasin** [comment]
We also have the [issue](https://github.com/couchbaselabs/couchbase-lite-apiv2/issues/57) open on the API repo.

**Comment by djpongh** [comment]
Closing as dup of https://github.com/couchbaselabs/couchbase-lite-apiv2/issues/57
