### ISSUE TITLE
SG doesn't have any docs in its cache after replication

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-net#957]
I create 10 docs in CBL app for .net and then started replication to sync them to SG/CBS. I can see that docs are available in CBS, but there are no docs in SG. Hence the test failed as no. doesn't match from expected value of 10.

SG output
http://172.23.109.132:4984/db/_all_docs
{"rows":[
],
"total_rows":0,"update_seq":11}

CBS bucket 
<img width="734" alt="screenshot 2018-02-06 12 03 18" src="https://user-images.githubusercontent.com/18100038/35845074-adc10bd2-0b36-11e8-866e-b98040bf122f.png">

SG output
<img width="808" alt="screenshot 2018-02-06 12 03 30" src="https://user-images.githubusercontent.com/18100038/35845085-b9993b82-0b36-11e8-9e5c-c59a7395d797.png">

SG logs 
[sgcollect_info.zip](https://github.com/couchbase/couchbase-lite-net/files/1698037/sgcollect_info.zip)

CBL logs:
```
Press any key to exit...
22:32:31.394884| [Couchbase]: (Startup) [3] 2018-02-05T22:32:31.3921778-08:00 CouchbaseLite/2.0.0 (.NET; Microsoft Windows 10.0.16299 ) Build/52 LiteCore/619 Commit/cc0ab52
22:32:36.814314| [BLIP]: {Connection#1}==> class litecore::blip::Connection ->ws:172.23.109.132:4984/db/_blipsync
22:32:36.816029| [BLIP]: {Connection#1} Opening connection...
22:32:36.817263| [Actor]: Starting Scheduler<0000022B4A168BB0> with 4 threads
22:32:36.930244| [BLIP]: {Connection#1} Connected!
22:32:37.064467| [BLIP]: {Connection#1} Close connection
22:32:37.117851| [BLIP]: {Connection#1} Closed with WebSocket status 1000:
22:32:37.119921| [BLIP]: {BLIPIO#2}==> class litecore::blip::BLIPIO 0000022B6483CBA8
22:32:37.121016| [BLIP]: {BLIPIO#2} ~BLIPIO: Sent 1071 bytes, rcvd 214. Max outbox depth was 1, avg 1.00
```

Cluster information:

SG -
 - Build - 2.0.0-773
 - OS - RHEL7

CBS -
 - Build - 5.0.0 -3519
 - OS - RHEL7

.net CBL
 - Build - 2.0.0-b0520

**Comment by borrrden** [comment]
I don't see any indication here that .NET is not doing what it is supposed to do....the SG logs indicate receiving all the revisions and they are present in Couchbase Server...

**Comment by borrrden** [comment]
Oh I do notice one thing now, and that is that the update sequence for android is 31 while .NET is 11.  Could that have something to do with it?

**Comment by borrrden** [comment]
Also which test is this?

**Comment by hrajput89** [comment]
@borrrden, we are trying this test - test_replication_configuration_valid_values

Here is the reference for the test - https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-ver1/testsuites/CBLTester/CBL_Functional_tests/test_replication.py#L48.

What is update sequence is it any package?

**Comment by borrrden** [comment]
Update sequence is the final value in the all docs JSON responses above.

**Comment by borrrden** [comment]
Where is the version of the CBL .NET client that you are using to test?  The one on cbl2.0_dotnet does not compile and there is no version on cbl20-ver1.  Without this I cannot see what is going on

**Comment by hrajput89** [comment]
@borrrden, can you please try with cbl2.0

**Comment by ritamcouchbase** [comment]
@borrrden  and @hrajput89 - Removed the blocker tag from the defect for now, since it is a testware issue.

**Comment by djpongh** [comment]
being a test issue, closing this. Once the test is fixed and re-run, if errors are found, they should be new tickets.
