### ISSUE TITLE
AddLoggerProvider

### ISSUE THREAD

**Issue by hr-strunt** [couchbase/couchbase-lite-net#964]
In Couchbase.Lite 2.0.0-db021 there was a method 

` Couchbase.Lite.Logging.Log.AddLoggerProvider(...);`

This is not available any longer in 2.0.0-db022. 

**Functional Impact:** Cannot create logfiles any longer.

How can you register a LoggerProvider? How can you activate logging to a logfile?

**Comment by borrrden** [comment]
I hate to be the bearer of (at least partially) bad news but that method was removed from the API.  There will be a discussion about what to do regarding custom logging in the future but it didn't happen in time for the 2.0 release (it's more than just .NET, the methodology needs to be consistent with the Java, Swift, and Objective-C variants).

That being said, here is the current state of affairs.  Currently *all* logging goes to a binary encoded log file by default.  The location of this file depends on the platform you use but generally it is nearby to where your databases are stored.  There is also a method on each support library called `EnableTextLogging()`.  Depending on the platform, this could achieve what you are after as on .NET Core and UWP it will log the logs in text format to a log file.  On iOS it will send logs to NSLog and on Android to logcat.  

The ability that is gone at this point is the ability to create custom logging endpoints.  It was removed to have consistency with the other platforms and to aid in getting rid of the Microsoft extensions package dependencies.  I want to add it back eventually as I think it is quite beneficial but if I left it in 2.0 it could have potentially conflicted with future plans.  

If you desire this functionality, and happen to be an enterprise customer, our management will listen to requests for features intently.  Our entire goal with 2.0 is to balance feature creep vs feature demand (for both this release and future ones) and the only way we can do that is with input from users.

If you have further questions, please use the [forums](https://forums.couchbase.com/c/mobile) or enterprise channels if applicable.

**Comment by borrrden** [comment]
Oh you might be wondering "What the hell can I do with arbitrarily encoded log files?"

Good point!  We have a tool for decoding them but we haven't put it anywhere that people can get it yet (in compiled form that is, the source is available in the LiteCore repo).  @djpongh Can you comment on what the plans for this tool are (note:  litecorelog, not cblite).

**Comment by rajagp** [comment]
One more from the forums : https://github.com/couchbase/couchbase-lite-net/issues/964#issuecomment-364804947

**Comment by bdgza** [comment]
Could we configure the path of the Logs directory, like we can with DatabaseConfiguration for databases?

**Comment by borrrden** [comment]
It's not often that I get completely blindsided by something that in hindsight should be pretty obvious!  Good point about that.  So the answer has to be yes, for now obvious reasons.  I think this needs to be provided via the NetDesktop support library since other platforms are all sandboxed and don't have this issue.

**Comment by borrrden** [comment]
Above commit changes `EnableTextLogging` to `EnableTextLogging(string)` and adds a method `SetBinaryLogDirectory(string)`.  This should alleviate the issue without blocking the development of a cross platform specification for this type of logging extension.
