### ISSUE TITLE
2 Microsoft dependency injection seems not to work

### ISSUE THREAD

**Issue by SteeveQuadra** [couchbase/couchbase-lite-net#968]
Hi,

In november 2017, I built a P.O.C. around couchbase lite 2.0, the version was the db19.
In december 2017, I started my application from scratch, an Xamarin form, c# .net standard 2.0, UWP, Android and IOS.
One of the first thing I added in my application was a injector. As I used Microsoft Dependency  injection in a previous project, I decided to use it. My app worked fine. I begun a first page, and came at the time that I needed to store my datas.
Base on my P.O.C., I coded the open of a new couchbase lite database.
And it didn't work. I learned that the microsoft DI was used internaly by couchbase. 2 instances of the DI of it seems not be compatible.
I don't had the time to report this issue in december, I simply change my injector, using SimpleInjector to do the job.

I just wanted to report that when we use couchbase, we don't realy pay attention that it use microsoft DI, and 2 instances of microsoft DI seems not working.

Regards

Steeve

**Comment by borrrden** [comment]
Another user pointed this out and this is the reason I switched to SimpleInjector.

**Comment by borrrden** [comment]
Details [here](https://github.com/couchbase/couchbase-lite-net/issues/953)
