### ISSUE TITLE
LiteCoreException thrown during Pull replication in UWP app

### ISSUE THREAD

**Issue by rainerg2000** [couchbase/couchbase-lite-net#970]
On couchbase-lite-net 2.0 DB022:

I have a short integration test case where my test app inserts a small test object on the Sync Gateway REST API, then it triggers a Pull replication, waits a bit and verifies that the object has appeared in the local DB.
The replication completes within a sec or so (status is Stopped), but the object is not in the local DB.

I am running this in the VS 2017 native debugger with LiteCore C++ sources and am able to give you a decoded stack trace with line numbers.

Attached are:
stack trace
screen shot of Visual Studio 
Sync Gateway Logs from 3 different test runs
![cblitecoreexception](https://user-images.githubusercontent.com/2896215/36330680-83a8be8a-131f-11e8-9da7-2e5ed33b9383.PNG)
[CbLiteCoreException.stack.txt](https://github.com/couchbase/couchbase-lite-net/files/1732909/CbLiteCoreException.stack.txt)
[sync_gateway_error2.log](https://github.com/couchbase/couchbase-lite-net/files/1732922/sync_gateway_error2.log)
[sync_gateway_error1.log](https://github.com/couchbase/couchbase-lite-net/files/1732923/sync_gateway_error1.log)
[sync_gateway_error3.log](https://github.com/couchbase/couchbase-lite-net/files/1732924/sync_gateway_error3.log)

**Comment by borrrden** [comment]
Just to confirm, this is with Sync Gateway 2.0 beta?

@snej Do you have any information about why this would happen?  This seems like one of the sides made a mistake with the protocol during data transfer.

**Comment by snej** [comment]
Almost certainly a version mismatch between client and server. CBL 2 beta requires SG 2 beta. (I've since added some extra version checking to ensure this is more clear.)

**Comment by rainerg2000** [comment]
Not sure. I won't be back in the office until Tuesday. I'll tell you the
Sync Gateway version then.
Rainer.

On Feb 16, 2018 15:07, "Jim Borden" <notifications@github.com> wrote:

Just to confirm, this is with Sync Gateway 2.0 beta?

@snej <https://github.com/snej> Do you have any information about why this
would happen? This seems like one of the sides made a mistake with the
protocol during data transfer.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/couchbase/couchbase-lite-net/issues/970#issuecomment-366384389>,
or mute the thread

**Comment by inatsch** [comment]
@rainerg2000: used Sync Gateway Version is 1.5.1

**Comment by snej** [comment]
CBL 2 beta requires SG 2 beta.
