### ISSUE TITLE
WAL file growing without bound [1.4.1]

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-net#973]
[Forum post](https://forums.couchbase.com/t/v1-4-1-cannot-shrink-db-sqlite3-wal-file/15907) by PMilla:
>I have a long running .net app and I’ve started noticing the temporary WAL file that sqlite generates never seems to shrink and it’s starting to cause problems for me when getting to the GB+ range. I’ve searched and tried Purging documents, compacting the database, and even closing the database all together but to no avail.
>
>[Quick gist demonstrating problem](https://gist.github.com/PaulMilla/f167380af0ce1f7775f37d3e6cf18154)

**Comment by borrrden** [comment]
Closing as this has an open ticket elsewhere.
