### ISSUE TITLE
401 error with test_replication_configuration_with_headers

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-net#974]
### Builds
.net - 2.0.0-b0557, CBS - 5.5.0-1924, SG - 2.0.0-810

### Test ran
pytest -rsx -s --mode=cc --server-version=5.5.0-1924 --sync-gateway-version=2.0.0-810 --liteserv-platform=net-msft --liteserv-host=192.168.33.21 --liteserv-port=55555  --xattrs --create-db-per-suite="test_db" --create-db-per-test=pull-test testsuites/CBLTester/CBL_Functional_tests/test_replication.py -k test_replication_configuration_with_headers --skip-provisioning --liteserv-version=2.0.0-b0557

### Actual
Test fails with 
```
Exception: ('Error while replicating', 'LiteCore.LiteCoreException: LiteCoreException (WebSocketDomain / 401): Unauthorized')
```

The right values seem to be set for replication configuration

![screen shot 2018-02-21 at 5 42 39 pm](https://user-images.githubusercontent.com/24398601/36515831-1e98f450-1730-11e8-8464-9fd21f40934b.png)

### Expected
Replication should work with SG session cookie

**Comment by borrrden** [comment]
This will be blocked, in spirit, https://github.com/couchbase/couchbase-lite-core/issues/418 because without that fix the automated testing is freaking out for builds.

**Comment by borrrden** [comment]
That being said, I found the issue and it is a simple fix.
