### ISSUE TITLE
Nuget mobile developer release link not working (again)

### ISSUE THREAD

**Issue by nat543207** [couchbase/couchbase-lite-net#976]
Similar to issue #829

The NuGet repository link ([http://mobile.nuget.couchbase.com/nuget/Developer/](http://mobile.nuget.couchbase.com/nuget/Developer/)) provided in the GitHub repository README and on the [official documentation page](https://developer.couchbase.com/documentation/mobile/2.0/couchbase-lite/csharp.html) seems to be empty.  Browsing the list of packages it provides in Visual Studio shows only the message '*No packages found*', and the `curl` output for the URL looks something like this:

```
<?xml version="1.0" encoding="utf-8"?>
<service xmlns="http://www.w3.org/2007/app">
    <workspace>
        <title xmlns="http://www.w3.org/2005/Atom">
            Default
        </title>
        <collection href="Packages">
            <title xmlns="http://www.w3.org/2005/Atom">
                Packages
            </title>
        </collection>
    </workspace>
</service>
```

**Comment by borrrden** [comment]
Remember to check the include prereleases box.

**Comment by nat543207** [comment]
Looks like that did the trick.  In case anyone else has a similar problem in the future, you can check [http://mobile.nuget.couchbase.com/nuget/Developer/Search()?$filter=IsAbsoluteLatestVersion&includePrerelease=true](http://mobile.nuget.couchbase.com/nuget/Developer/Search()?$filter=IsAbsoluteLatestVersion&includePrerelease=true) to get a list of all the packages, including prereleases, in the NuGet repo.

Thanks!
