### ISSUE TITLE
Replication fails with LiteCore error (7/1005)

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-net#977]
### Builds
.net 2.0.0-b0571/575, SG 2.0.0-812, CBS 5.5.0-1924

### Test ran
```
pytest -s --mode=cc --server-version=5.5.0-1924 --sync-gateway-version=2.0.0-812 --liteserv-platform=net-msft --liteserv-host=192.168.33.21 --liteserv-port=55555  --xattrs --create-db-per-suite="test_db" --create-db-per-test=pull-test testsuites/CBLTester/CBL_Functional_tests/test_replication.py --liteserv-version=2.0.0-b0567 -k 'test_CBL_tombstone_doc[1000]' --skip-provisioning
```

### Actual
Intermittently replication fails with the below error.

CBL logs:
```
VERBOSE) Sync {IncomingRev#944} All blobs received, now inserting revision
INFO) Sync {Repl#2} Connection closed with WebSocket status 1005: "" (state=2)
ERROR) Sync {Repl#2} Got LiteCore error: no status code received (7/1005)
VERBOSE) DB KeyStore(default) insert sg_docs_62
VERBOSE) Sync {DBWorker#4}     {'sg_docs_63' #1-0b090e3e1d74736d5587ba9afdda0a90}
VERBOSE) DB KeyStore(default) insert sg_docs_63
VERBOSE) Sync {Repl#2} progress +0/+0, 0 docs -- now 223455 / 462668, 17 docs
INFO) Sync {Repl#2} now stopped
```
Test logs:
```
>    raise Exception("Error while replicating", err)
E     Exception: ('Error while replicating', 'LiteCore.LiteCoreException: LiteCoreException (WebSocketDomain / 1005): no status code received')
```

### Expected:
Replication should complete without errors

**Comment by raghusarangapani** [comment]
Replication fails to complete
```
INFO) LiteCore {BLIPIO#3} Can't send RES #476; socket is closed
INFO) LiteCore {BLIPIO#3} Can't send RES #479; socket is closed
INFO) LiteCore {BLIPIO#3} Can't send RES #480; socket is closed
INFO) LiteCore {BLIPIO#3} Can't send RES #482; socket is closed
INFO) LiteCore {BLIPIO#3} Can't send RES #481; socket is closed
INFO) LiteCore {BLIPIO#3} Can't send RES #483; socket is closed
INFO) LiteCore {BLIPIO#3} Can't send RES #484; socket is closed
INFO) LiteCore {BLIPIO#3} Can't send RES #486; socket is closed
```

**Comment by borrrden** [comment]
This is #967 finally, but how do I make it happen?

**Comment by raghusarangapani** [comment]
Issue is intermittent. I was able to see this error with different test cases under test_no_conflicts_cbl.py.

**Comment by raghusarangapani** [comment]
Reproduced the issue with wireshark packet capture going on.

WebSocket Connection Close [FIN] [MASKED]
```
WebSocket
> Payload
   > Close
          Status code: Abnormal Closure (1006)
          Reason: BLIP message invalid checksum
```

Attaching wireshark trace `LiteCoreException_1005.zip
[LiteCoreException_1005.zip](https://github.com/couchbase/couchbase-lite-net/files/1761153/LiteCoreException_1005.zip)
`

.

**Comment by borrrden** [comment]
Which IP address corresponds to which machine?

**Comment by borrrden** [comment]
@snej The wireshark trace shows a 1006, but the logs (coming from LiteCore) are indicated 1005.  I think this is partially the source of confusion.

**Comment by raghusarangapani** [comment]
couchbase_server - 192.168.33.20,
sync_gateway - 192.168.33.22,
sg_accel - 192.168.33.23.

**Comment by snej** [comment]
Is the .NET WebSocket impl not reading the closing status code properly?

**Comment by borrrden** [comment]
I don't see why it would be.  It's not something I explicitly do.  I just pass on whatever comes to me from the runtime.

**Comment by borrrden** [comment]
But what can we do about the 1006 with the invalid checksum message?

**Comment by snej** [comment]
That would be a BLIP error, but it's not clear whether it's in BLIP_Cpp or go-blip. :(

As for the close code: Does the .NET C4Socket impl do the WebSocket framing, or does it just handle raw reads/writes?

**Comment by raghusarangapani** [comment]
Reproduced the issue again in the fourth attempt. Attaching LiteCoreException_1005.zip and TextLog-1519859155.zip

[TextLog-1519859155.zip](https://github.com/couchbase/couchbase-lite-net/files/1769217/TextLog-1519859155.zip)
[LiteCoreException_1005.zip](https://github.com/couchbase/couchbase-lite-net/files/1769218/LiteCoreException_1005.zip)

**Comment by borrrden** [comment]
I finally got this to repro with the UWP test server app.  @snej The 1005 is coming incorrectly from LiteCore to Couchbase Lite as noted in the above linked ticket, so I will close this ticket and open https://github.com/couchbase/couchbase-lite-core/issues/442

**Comment by snej** [comment]
SG should not be sending a 1006 status -- the WebSocket spec states that 1006 "MUST NOT be set as a status code in a Close control frame".

**Comment by snej** [comment]
The WebSocket close message captured by WireShark, above, is coming from LiteCore, not SG.

* SG, or rather go-blip, doesn't set any status code/message when it closes the WebSocket, because Go's WebSocket library doesn't support that. (Look at receiver.stop() in go-blip.)
* `BLIP message invalid checksum` is the exact message LiteCore sends (Code::readAndVerifyChecksum). go-blip's message is worded differently.

That implies it was LiteCore that detected a wrong checksum, but for some reason the server's responding close message is being reported as the error, not the original error.

Also, I need to change the status code sent from 1006 to either 1003 (Unacceptable Data) or 1007 (Inconsistent Message Data).

**Comment by borrrden** [comment]
SG did not send the message, LiteCore sent it to SG, and SG responded with 1000.  The failure comes because the exception will call BLIPConnection's `_closeWithError` which forces a 1006 message.

**Comment by snej** [comment]
I fixed the connection-closing issues in BLIP-Cpp commit fdbcd686.
* Now uses status 1007 (Unexpected Condition)
* The status sent to the delegate is one based on the exception thrown, not the status returned from the peer. I.e. now the replicator knows it was a corrupt-data error, not a 1000 Normal Close.
