### ISSUE TITLE
Replicator enters busy state when in Android (Xamarin) Airplane Mode

### ISSUE THREAD

**Issue by davisChapmanCouchbase** [couchbase/couchbase-lite-net#979]
When running with a continuous two-way replication (CBL 2.0 beta), and put the Android emulator into airplane mode, once the DB has a change to push, the replicator activity status changes to "Busy". Once Airplane mode is exited, the activity status stays "Busy", but the replicator never starts replicating again.

**Comment by davisChapmanCouchbase** [comment]
Here's the log starting from entering Airplane Mode:

[Sync]: {DBWorker#3} Notified of 1 db changes #3012 ... #
 
3012
19:00:26.686966| [Sync]: {Push#4} Read 1 changes: Pusher sending 'changes' with sequences 3012 - 3012
19:00:26.687622| [Sync]: {Repl#2} now busy
[Sync]: (Replicator) [9] 2018-02-27T16:06:54.6878150-05:00 Replicator[<*> ws://10.0.2.2:4984/hubx_mobile] is Busy, progress 0/890
[0:] PushPull Replicator: 0/890, error <none>, activity = Busy
19:00:27.783935| [Sync]: {DBWorker#3} Notified of 1 db changes #3013 ... #3013
19:00:27.835554| [Sync]: {Push#4} Read 1 changes: Pusher sending 'changes' with sequences 3013 - 3013
19:00:27.889222| [Sync]: (Replicator) [9] 2018-02-27T16:06:54.8891310-05:00 Replicator[<*> ws://10.0.2.2:4984/hubx_mobile] is Busy, progress 0/1780
19:00:27.901300| [Sync]: {DBWorker#3} Notified of 1 db changes #3014 ... #3014
19:00:27.901626| [Sync]: {Push#4} Read 1 changes: Pusher sending 'changes' with sequences 3014 - 3014
[0:] PushPull Replicator: 0/1780, error <none>, activity = Busy
19:00:27.993520| [Sync]: {DBWorker#3} Notified of 1 db changes #3015 ... #3015
19:00:27.994540| [Sync]: {Push#4} Read 1 changes: Pusher sending 'changes' with sequences 3015 - 3015
19:00:27.089928| [Sync]: (Replicator) [9] 2018-02-27T16:06:55.0898420-05:00 Replicator[<*> ws://10.0.2.2:4984/hubx_mobile] is Busy, progress 0/3560
[0:] PushPull Replicator: 0/3560, error <none>, activity = Busy
19:00:40.767658|
[Sync]: {DBWorker#3} Notified of 1 db changes #3016
... #3016
19:00:40.770404| [Sync]: {Push#4} Read 1 changes: Pusher sending 'changes' with sequences 3016 - 3016
19:00:40.770959| [Sync]: (Replicator) [16] 2018-02-27T16:07:07.7708700-05:00 Replicator[<*> ws://10.0.2.2:4984/hubx_mobile] is Busy, progress 0/4450
19:00:40.826602| [Sync]: {DBWorker#3} Notified of 1 db changes #3017 ... #3017
19:00:40.826998| [Sync]: {Push#4} Read 1 changes: Pusher sending 'changes' with sequences 3017 - 3017
[0:] PushPull Replicator: 0/4450, error <none>, activity = Busy
19:00:40.940543| [Sync]: {DBWorker#3} Notified of 1 db changes #3018 ... #3018
19:00:40.941016| [Sync]: {Push#4} Read 1 changes: Pusher sending 'changes' with sequences 3018 - 3018
19:00:40.978372| [Sync]: (Replicator) [9] 2018-02-27T16:07:07.9782590-05:00 Replicator[<*> ws://10.0.2.2:4984/hubx_mobile] is Busy, progress 0/6230
[0:] PushPull Replicator: 0/6230, error <none>, activity = Busy
19:00:40.039874| [Sync]: {DBWorker#3} Notified of 1 db changes #3019 ... #3019
19:00:40.040293| [Sync]: {Push#4} Read 1 changes: Pusher sending 'changes' with sequences 3019 - 3019
19:00:40.173609| [Sync]: (Replicator) [9] 2018-02-27T16:07:08.1734730-05:00 Replicator[<*> ws://10.0.2.2:4984/hubx_mobile] is Busy, progress 0/7120
[0:] PushPull Replicator: 0/7120, error <none>, activity = Busy

**Comment by borrrden** [comment]
I thought it was odd that I never saw offline mode entered in this log snippet....so I did some digging and this smells like a Xamarin Android bug with `TcpClient`.  Another user recently seems to have reported [this](https://forums.xamarin.com/discussion/115028/weird-problem-with-tcpclient-and-networkstream-it-never-fails?) in the forums.  Hopefully bumping it will get it some attention.  There is not much I can do about that short of rewriting the entire web socket transport layer to use another class besides `TcpClient`

**Comment by borrrden** [comment]
Ok this seems like an issue when using IP addresses instead of hostnames (localhost not included).  I think this should be considered a bug in the Android networking stack but when a Java socket is opened to an IP address that doesn't need external DNS resolution the socket will never fail to send even if the network is disconnected.  I filed an issue on the Android issue tracker about it so let's see if they say anything.

**Comment by borrrden** [comment]
Ref: https://issuetracker.google.com/issues/74051111

**Comment by borrrden** [comment]
Consolidated to #1011
