### ISSUE TITLE
Exception due to failed handshake

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-net#981]
### Builds
.net 2.0.0-b0589, SG 2.0.0-814, CBS 5.5.0-1992

### Test ran
```
pytest -s --mode=cc --server-version=5.5.0-1992 --sync-gateway-version=2.0.0-814 --liteserv-platform=net-msft --liteserv-host=192.168.33.21 --liteserv-port=55555  --xattrs --create-db-per-suite="test_db" --create-db-per-test=pull-test testsuites/CBLTester/CBL_Functional_tests/test_replication.py --liteserv-version=2.0.0-b0589 -k 'test_CBL_tombstone_doc[1000]' --skip-provisioning
```

### Actual 
Intermittently the .net test server app stops with an unhandled exception in Couchbase.Lite.Support.NetDesktop.dll

Call stack:

![screen shot 2018-02-28 at 3 47 37 pm](https://user-images.githubusercontent.com/24398601/36819948-6054ffa4-1ca0-11e8-9739-415c9c675e2c.png)

Code:

![screen shot 2018-02-28 at 3 46 51 pm](https://user-images.githubusercontent.com/24398601/36819956-6bd8b370-1ca0-11e8-9a05-9f44009d1802.png)

Local vars:

![screen shot 2018-02-28 at 3 47 18 pm](https://user-images.githubusercontent.com/24398601/36819968-748220a6-1ca0-11e8-8661-7b7244886a2d.png)

**Comment by borrrden** [comment]
How does pytest know to set this up as wss instead of ws?

**Comment by borrrden** [comment]
The way to cause this exception is to connect to a non-TLS backend while attempting TLS.  I have ensured that this is caught and reported.
