### ISSUE TITLE
TestServer throws AccessViolationException under heavy write load

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-net#983]
I'm running System testing on .net and app crashes when we tries to update docs in batch. System test tried to add, 1M docs (10000docs in 100 iteration) and then update docs in both SG and CBL with continuous replication, then it delete some docs from both SG and CBL and finally add some more docs to CBl. This is looped over a period of time.

 I'm updating around 750 docs in batch and system crashes with the exception as shown in below image
<img width="1440" alt="screenshot 2018-03-04 16 41 41" src="https://user-images.githubusercontent.com/18100038/36944914-4c78639e-1fcb-11e8-9a83-9cd880b9a3eb.png">

System Test code is available here - https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-ver1/testsuites/CBLTester/CBL_Functional_tests/test_system_testing.py

**Comment by borrrden** [comment]
Please post the test invocation, and build number.

**Comment by hrajput89** [comment]
@borrrden I'm using b0571 nuget build. I'm not very clear what do you mean by "post test invocation". If my understanding is correct, you are asking for below code. If not, please elucidate your expectation.

```
internal static void DatabaseUpdateDocuments([NotNull] NameValueCollection args,
                                   [NotNull] IReadOnlyDictionary<string, object> postBody,
                                   [NotNull] HttpListenerResponse response)
        {
            var docDict = (Dictionary<string, object>)postBody["documents"];
            With<Database>(postBody, "database", db =>
            {
                db.InBatch(() =>
                {
                    foreach (var body in docDict)
                    {
                        string id = body.Key;
                        Dictionary<string, Object> docVal = (Dictionary<string, object>) body.Value;
                        MutableDocument UpdateDoc = db.GetDocument(id).ToMutable();
                        UpdateDoc.SetData(docVal);
                        db.Save(UpdateDoc);
                    }
                });
            });
            response.WriteEmptyBody();           
        }
```

**Comment by hrajput89** [comment]
I ran the test again with 2.0.0-0b607 build and TestServer crashed again, but this time during the last iteration of adding the docs (on 100th iteration).

<img width="1434" alt="screenshot 2018-03-06 13 59 35" src="https://user-images.githubusercontent.com/18100038/37021829-f027a4b0-2146-11e8-9442-09626db01d82.png">

**Comment by borrrden** [comment]
The stack trace from these exceptions would be helpful.

**Comment by gbuggy** [comment]
I am getting the same AccessViolationException under heavy write load in my application.  Here is a stack trace from my log file, hope it helps.

************************************************************************
20180302_11:43:00.995 771d40e6-b77e-4bb6-a841-2fdb5164cf61 AccessViolationException was trapped!  Attempting to recover.
20180302_11:43:00.995 771d40e6-b77e-4bb6-a841-2fdb5164cf61 Exception: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
20180302_11:43:01.011 771d40e6-b77e-4bb6-a841-2fdb5164cf61 Stack Trace:    at LiteCore.Interop.Native.c4doc_dictContainsBlobs(FLDict* dict, FLSharedKeys* sk)
   at Couchbase.Lite.Database.<>c__DisplayClass84_1.<Save>b__2()
   at Couchbase.Lite.Support.ThreadSafety.DoLocked(Action a)
   at Couchbase.Lite.Database.Save(Document doc, C4Document** outDoc, C4Document* baseDoc, Boolean deletion)
   at Couchbase.Lite.Database.<>c__DisplayClass83_1.<Save>b__0()
   at Couchbase.Lite.Support.ThreadSafety.DoLocked[T](Func`1 f)
   at Couchbase.Lite.Database.Save(Document document, Boolean deletion)
  at Couchbase.Lite.Support.ThreadSafety.DoLocked[T](Func`1 f)
   at SP.CBLite.DBManager.<>c__DisplayClass22_0.<SaveDocuments>b__0()
   at Couchbase.Lite.Database.<>c__DisplayClass68_0.<InBatch>b__0()
   at Couchbase.Lite.Support.ThreadSafety.DoLocked(Action a)
   at Couchbase.Lite.Database.InBatch(Action action)
   at SP.CBLite.DBManager.SaveDocuments(String documentStoreName, Dictionary`2 newDocs)
20180302_11:43:01.011 771d40e6-b77e-4bb6-a841-2fdb5164cf61 Closing Database...
20180302_11:43:01.011 771d40e6-b77e-4bb6-a841-2fdb5164cf61 Exception recovering Couchbase database
20180302_11:43:01.011 771d40e6-b77e-4bb6-a841-2fdb5164cf61 Exception: LiteCoreException (26): transaction not closed
 
************************************************************************

**Comment by borrrden** [comment]
I have yet to reproduce this.  I have a change that I made that might be able to prevent this though.  I'm currently running against a version with that change, and all documents have been inserted, and ~500k have been synced so far (sync is quite slow...probably because of the low memory of the VM for CBS and SG @ 2GB per VM)

**Comment by gbuggy** [comment]
In our application, we are not using any sync or replication, just straight saves and gets.  Do sync operations start happening as soon as a record is inserted?  Just wondering if that could affect reproducibility of this issue.

We are seeing the exception intermittently, we have not been able to create an exact scenario to trigger the exception.  We do see it frequently enough to be very concerning though.  The test data set we are using has ~300k records and I have been able to insert them all 10 times over before the exception happens.  Sometimes it will happen after the first couple thousand records.

**Comment by borrrden** [comment]
Sync operations will only happen if you request them to happen.  In the scenario I am using, sync starts after all 1M records are inserted.  The fact that I got to that point suggests that I did not encounter the issue during this run.

**Comment by gbuggy** [comment]
Would it be possible to get a copy of the build you're using?  We are on the db022 release from nuget.

**Comment by borrrden** [comment]
It will be possible very soon (I'm being asked for build numbers for validation for publish).  Our DB schedule was overridden by management policies but DB023 is coming and that will be the first 2.0 RC.  This time it has received more extensive testing as our functional test framework grows.

**Comment by hrajput89** [comment]
I'm able to finish writing 1M docs to the CBL app with build 2.0.0-0b611.

**Comment by hrajput89** [comment]
This issue is no longer reproducible, hence closing it
