### ISSUE TITLE
Count method of .net returns long whereas android and iOS returns int

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-net#984]
Count method of .net returns long whereas android and iOS returns int.

- Android 

```
public int getCount() {
        synchronized (lock) {
            return c4db != null ? (int) getC4Database().getDocumentCount() : 0;
        }
    }
```

- iOS

```
/// The total numbers of documents in the database.
    public var count: UInt64 { get }
```

- .net

```
public ulong Count {
	get;
}
```

**Comment by borrrden** [comment]
It returns `ulong`, and so does iOS.  @pasin The spec is marked as `int` but LiteCore returns a 64-bit unsigned integer.  Which should we conform to?

**Comment by pasin** [comment]
ulong is more correct. I will need to check with Dan if he allows to change the spec or not.

**Comment by pasin** [comment]
@hrajput89 We got approved to change the spec from int to UInt64. For Java, it will return long. Please check with @hideki about the change.

**Comment by hideki** [comment]
@hrajput89 
This difference will be solved with build 418 or later. Thanks!
http://mobile.maven.couchbase.com/feeds/dev//com/couchbase/lite/couchbase-lite-android-ee/2.0.0-418
