### ISSUE TITLE
System.AccessViolationException with test_CBL_push_pull_with_sg_down

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-net#985]
### Builds
Server 5.1.0-5552, SG 2.0.0-821,  CBL .net - 2.0.0-b0611

### Test ran
```
pytest -s --mode=cc --server-version=5.1.0-5552 --sync-gateway-version=2.0.0-821 --liteserv-platform=net-msft --liteserv-host=192.168.33.24 --liteserv-port=55555  --xattrs --create-db-per-suite="test_db" --create-db-per-test=pull-test testsuites/CBLTester/CBL_Functional_tests/test_replication.py --liteserv-version=2.0.0-b0611 -k 'test_CBL_push_pull_with_sg_down'
```

### Actual

The test server app breaks with a System.AccessViolationException

Call stack
![screen shot 2018-03-07 at 4 23 35 pm](https://user-images.githubusercontent.com/24398601/37126721-1c1a76c0-2227-11e8-9482-ee1dba0bd0b6.png)

Locals
![screen shot 2018-03-07 at 4 27 10 pm](https://user-images.githubusercontent.com/24398601/37126739-2c0ab91e-2227-11e8-9627-8319672a2eb3.png)

Threads
![screen shot 2018-03-07 at 4 25 20 pm](https://user-images.githubusercontent.com/24398601/37126749-381babaa-2227-11e8-8e5e-c582bdd5f20b.png)

There was also a dump on the desktop

Call stack
![screen shot 2018-03-07 at 4 39 05 pm](https://user-images.githubusercontent.com/24398601/37126787-5fc020dc-2227-11e8-9508-c1880c48ec8d.png)

Locals
![screen shot 2018-03-07 at 4 39 27 pm](https://user-images.githubusercontent.com/24398601/37126802-6bd809b6-2227-11e8-82d2-d69dc5c19f71.png)

code
![screen shot 2018-03-07 at 4 38 31 pm](https://user-images.githubusercontent.com/24398601/37126809-78451996-2227-11e8-8c4e-69bfb9f07342.png)

**Comment by raghusarangapani** [comment]
Verified with server 5.1.0-5552, sync-gateway 2.0.0-821 and CBL .net b0621:
Test passes.

**Comment by djpongh** [comment]
@raghusarangapani , once verified, please remove the "verify" label.

Thanks
