### ISSUE TITLE
replication get stuck during system testing with 1M docs

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-net#987]
I ran the system test for .net with 1M docs, after adding docs, the replication stops after syncing around 50k docs and never proceed further from it.

this is the pytest command -

pytest -rsx -s --mode=cc --server-version=5.5.0-1992 --sync-gateway-version=2.0.0-814 --liteserv-platform=dotnet --liteserv-version=2.0.0-0b611 --liteserv-host=172.23.121.73 --liteserv-port=55555 --xattrs --create-db-per-suite="suite_db" --create-db-per-test="test_db"  --timeout=216000 --skip-provisioning -k test_system testsuites/CBLTester/System_Test/test_system_testing.py

**Comment by borrrden** [comment]
The fix for this is in 628 (note that 628 was unable to complete automated testing because of some tests that needed updating, but 629 will have that.  It will be identical to 628).

**Comment by hrajput89** [comment]
I tried system testing with 1M doc with build 0b630. It still got stuck after replicating around 46K docs.

**Comment by borrrden** [comment]
The logs indicate build 611 instead of 630.  It is possible it got used by mistake, so I will leave the verify tag until the situation is confirmed.

**Comment by hrajput89** [comment]
The replication getting stuck issue is no more reproducible. After adding 1M docs all of them get replicated to SG/CBS. I'm still continuing with other part of system testing and will update ASA test gets complete.

**Comment by borrrden** [comment]
It's been 12 hours now.  Can we close this ticket if this issue is no longer reproducible?

**Comment by hrajput89** [comment]
closing ticket as issue is no longer reproducible.
