### ISSUE TITLE
Join.join option is missing in query 

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-net#988]
### Builds
.net UWP 2.0.0-b0611

### Issue
.net does not have join option, it has all the others like InnerJoin, LeftJoin, LeftOuterJoin and CrossJoin.

Join options in .net
<img width="145" alt="join_dotnet" src="https://user-images.githubusercontent.com/24398601/37224122-660cd578-2387-11e8-8a41-233fc104461f.png">

Join options in iOS:
<img width="460" alt="join_ios" src="https://user-images.githubusercontent.com/24398601/37224138-70fdf6ba-2387-11e8-9647-67bcb0210c9d.png">

Join options in Android:
<img width="454" alt="join_android" src="https://user-images.githubusercontent.com/24398601/37224155-7a3f69d4-2387-11e8-875c-4858a28c7b6e.png">

**Comment by rajagp** [comment]
Join is functionally equivalent to innerjoin . Of course we should have it for consistency across platforms but just mentioning that it’s not missing equivalent  functionality so not a blocker Imho ...

**Comment by borrrden** [comment]
This was already discussed and cannot happpen due to compiler rules. A class cannot have a static method with the same name as the class (compiler error)
