### ISSUE TITLE
Nuget release schedule

### ISSUE THREAD

**Issue by egeorgiades** [couchbase/couchbase-lite-net#989]
The beta release is fantastic folks, but the nuget pre-release is outdated and faces issues with AOT etc.

Any idea on when you'll have v.23 out on Nuget or the [TODO] Download for the libraries that need to built?

**Comment by borrrden** [comment]
Please open issues only for bug reports. If you have a question you can ask on the [forums](https://forums.couchbase.com/c/mobile).
