### ISSUE TITLE
TestServer app randomly crashes with System.OutOfMemoryException

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-net#990]
### Builds
.net UWP b0634, SG 2.0.0-823, CBS 5.1.0-5552

### Test ran
Started the entire set of replication tests
```
pytest --mode=cc --server-version=5.1.0-5552 --sync-gateway-version=2.0.0-823 --liteserv-platform=net-msft --liteserv-host=192.168.33.24 --liteserv-port=55555  --xattrs --create-db-per-test=pull-test testsuites/CBLTester/CBL_Functional_tests/test_replication.py --liteserv-version=2.0.0-b0634 --sg-ssl
```

### Actual
.net test server app randomly crashes with System.OutOfMemoryException. This issue was not seen on b0611

### CBL logs
I see lots of messages like below
```
VERBOSE) Sync (WebSocketWrapper) [333] 2018-03-12T12:33:58.2063274-07:00 Already closed, ignoring call to CompletedReceive...
VERBOSE) Sync (WebSocketWrapper) [333] 2018-03-12T12:33:58.2063487-07:00 <<< received 0 bytes [now 0 pending]
VERBOSE) Sync (WebSocketWrapper) [333] 2018-03-12T12:33:58.2063709-07:00 Already closed, ignoring call to CompletedReceive...
VERBOSE) Sync (WebSocketWrapper) [333] 2018-03-12T12:33:58.2063902-07:00 <<< received 0 bytes [now 0 pending]
VERBOSE) Sync (WebSocketWrapper) [333] 2018-03-12T12:33:58.2064152-07:00 Already closed, ignoring call to CompletedReceive...
VERBOSE) Sync (WebSocketWrapper) [333] 2018-03-12T12:33:58.2064337-07:00 Already closed, ignoring call to CompletedReceive...
VERBOSE) Sync (WebSocketWrapper) [333] 2018-03-12T12:33:58.2064542-07:00 <<< received 0 bytes [now 0 pending]
VERBOSE) Sync (WebSocketWrapper) [333] 2018-03-12T12:33:58.2064780-07:00 Already closed, ignoring call to CompletedReceive...
VERBOSE) Sync (WebSocketWrapper) [333] 2018-03-12T12:33:58.2064969-07:00 Already closed, ignoring call to CompletedReceive...
VERBOSE) Sync (WebSocketWrapper) [333] 2018-03-12T12:33:58.2065162-07:00 Already closed, ignoring call to CompletedReceive...
VERBOSE) Sync (WebSocketWrapper) [333] 2018-03-12T12:33:58.2065351-07:00 Already closed, ignoring call to CompletedReceive...
VERBOSE) Sync (WebSocketWrapper) [333] 2018-03-12T12:33:58.2065548-07:00 <<< received 0 bytes [now 0 pending]
VERBOSE) Sync (WebSocketWrapper) [333] 2018-03-12T12:33:58.2065794-07:00 Already closed, ignoring call to CompletedReceive...
VERBOSE) Sync (WebSocketWrapper) [333] 2018-03-12T12:33:58.2065992-07:00 <<< received 0 bytes [now 0 pending]
VERBOSE) Sync (WebSocketWrapper) [333] 2018-03-12T12:33:58.2066238-07:00 <<< received 0 bytes [now 0 pending]
VERBOSE) Sync (WebSocketWrapper) [333] 2018-03-12T12:33:58.2066468-07:00 <<< received 0 bytes [now 0 pending]
```
### Callstack
<img width="529" alt="screen shot 2018-03-12 at 12 51 48 pm" src="https://user-images.githubusercontent.com/24398601/37306318-933adcec-25f4-11e8-9bfc-df0452df992f.png">

### Locals
<img width="623" alt="screen shot 2018-03-12 at 12 53 18 pm" src="https://user-images.githubusercontent.com/24398601/37306333-a191ea24-25f4-11e8-8653-186ab0ac0e45.png">

### Code
<img width="924" alt="screen shot 2018-03-12 at 12 53 54 pm" src="https://user-images.githubusercontent.com/24398601/37306353-ad141f8e-25f4-11e8-9da7-bb516423b2c8.png">

**Comment by borrrden** [comment]
I believe this is probably due to the lack of memory flushing going on. I think the flush memory endpoint should be called at the end of every test and not every suite or else too many things will be forced into memory.

**Comment by raghusarangapani** [comment]
This issue was not seen with b0611. The test code hasn't changed. The CBL logs above are also new

**Comment by raghusarangapani** [comment]
I will try adding functionality to flush per test case the next time the app crashes and report if the issue goes away.

**Comment by borrrden** [comment]
The test code has not changed?  I think new tests have been added since 611 meaning more tests will be run before the memory is cleared.  The messages above don't deal with anything memory related, it just means that the web socket connection was closed.  I'll see what happens when I run it though.

**Comment by raghusarangapani** [comment]
I added an option locally --flush-memory-per-test, and if provided, will call flushMemory at the test teardown. This time it crashed in Marshal.cs with test_CBL_tombstone_doc[1000] with the same out of memory error

**Comment by borrrden** [comment]
The fix will be in build 636

**Comment by raghusarangapani** [comment]
Verified with server 5.1.0-5552, sync-gateway 2.0.0-823, .net build 2.0.0-b0636.
Issue is fixed.
