### ISSUE TITLE
System.OutOfMemoryException with ToString()

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-net#991]
### Builds
.net b0634, SG 2.0.0-823, CBS 5.1.0-5552

### Test ran
```
pytest --mode=cc --server-version=5.1.0-5552 --sync-gateway-version=2.0.0-823 --liteserv-platform=net-msft --liteserv-host=192.168.33.24 --liteserv-port=55555  --xattrs --create-db-per-test=pull-test testsuites/CBLTester/CBL_Functional_tests/test_replication.py --liteserv-version=2.0.0-b0634 --sg-ssl
```

### Actual
Test server randomly crashes with System.OutOfMemoryException while converting ToString().
A message popped up saying that ToString() took a long time and had to be aborted
Logging a separate issue since the error message and stack trace looks different from #990 

### Call stack

<img width="736" alt="screen shot 2018-03-12 at 1 21 06 pm" src="https://user-images.githubusercontent.com/24398601/37308012-e7ae5cc2-25f9-11e8-9928-7a572c29ba67.png">

### Locals
<img width="713" alt="screen shot 2018-03-12 at 1 20 35 pm" src="https://user-images.githubusercontent.com/24398601/37308022-ef9cd120-25f9-11e8-9e07-c46ab3b73b63.png">

### Code
<img width="891" alt="screen shot 2018-03-12 at 1 21 23 pm" src="https://user-images.githubusercontent.com/24398601/37308027-f7330936-25f9-11e8-9cce-e42c40e99390.png">

**Comment by borrrden** [comment]
I'm going to treat this the same as #990
