### ISSUE TITLE
2.0db023 SetBinaryLogDirectory(string) path ignored, still written to AppContext.BaseDirectory

### ISSUE THREAD

**Issue by bdgza** [couchbase/couchbase-lite-net#994]
Couchbase Lite version 2.0db023. Windows 10 1709, .NET 4.7.1, Windows Forms.

The method `Couchbase.Lite.Support.NetDesktop.SetBinaryLogDirectory(string)` added for #964 doesn't work. The binary log files still get written to AppContext.BaseDirectory next to the exe as before. The similar `Couchbase.Lite.Support.NetDesktop.EnableTextLogging(string)` does work as expected, and writes the text logs to the given path.

### Reproduce

Create a new project, add the Couchbase Lite and Couchbase Lite NetDesktop Support NuGets. Write:

```
Couchbase.Lite.Support.NetDesktop.Activate();
Couchbase.Lite.Support.NetDesktop.SetBinaryLogDirectory(@"C:\Users\username\Desktop\LogTestBinary\");
Couchbase.Lite.Support.NetDesktop.EnableTextLogging(@"C:\Users\username\Desktop\LogTest\");
```

LogTest will be created on the desktop, LogTestBinary will not. Instead the binary logs will appear in the default directory next to the exe.

**Comment by borrrden** [comment]
Try calling it before the call to `Activate()`

**Comment by borrrden** [comment]
Nevermind...that's not going to work since the static constructor will initialize the binary logger before that method takes effect -_-.  I have an idea of what to do though.
