### ISSUE TITLE
2.0.0-db023 LiteCore error: Forbidden

### ISSUE THREAD

**Issue by stcleezy** [couchbase/couchbase-lite-net#995]
Replication starts fine w/ 2.0.0-db022:
`14:45:40.142237| [Couchbase]: (Startup) [1] 2018-03-15T14:45:40.1372427-07:00 CouchbaseLite/2.0.0 (.NET; Microsoft Windows 10.0.16299 ) Build/52 LiteCore/619 Commit/cc0ab5214:45:40.453901| [BLIP]: {Connection#1}==> class litecore::blip::Connection ->ws:10.101.44.219:4984/cases/_blipsync
14:45:40.455848| [BLIP]: {Connection#1} Opening connection...
14:45:40.456833| [Actor]: Starting Scheduler<000001C5EBFE5D00> with 4 threads Couchbase: Change detected
14:45:45.585743| [BLIP]: {Connection#1} Connected!`

But when I update to 2.0.0-db023 I get the following:
`14:48:56.378634| [Couchbase]: (Startup) [1] 2018-03-15T14:48:56.3727938-07:00 CouchbaseLite/2.0.0 (.NET; Microsoft Windows 10.0.16299 ) Build/636 LiteCore/732 Commit/c18ebea
14:48:56.558104| [Actor]: Starting Scheduler<00000278AD7540F0> with 4 threads Couchbase: Change detected
14:48:57.938703| [WS] WARNING: {C4SocketImpl#1}==> class litecore::websocket::C4SocketImpl ws:10.101.44.219:4984/cases/_blipsync
14:48:57.953951| [WS] WARNING: {C4SocketImpl#1} Unexpected or unclean socket disconnect! (reason=WebSocket status, code=403)
14:48:57.970685| [Sync] ERROR: {Repl#2}==> class litecore::repl::Replicator C:\Git\BITBUCKET\couchbase-demo\CouchbaseCcuListener\CouchbaseCcuListener\bin\Debug\netcoreapp2.0\CouchbaseLite\cases.cblite2\ ->ws:10.101.44.219:4984/cases/_blipsync
14:48:57.972262| [Sync] ERROR: {Repl#2} Got LiteCore error: Forbidden (7/403)`

[log-1521150536.zip](https://github.com/couchbase/couchbase-lite-net/files/1817209/log-1521150536.zip)

Sync Gateway logs show:
` Error: Client doesn’t support WS protocol BLIP_3a2, only BLIP_3+CBMobile_2`

Which seems to be the same issue as: https://forums.couchbase.com/t/sync-gateway-2-0-client-doesnt-support-ws-protocol-blip-3a2/16014

Do I need to build Sync Gateway from source? Is there any other way around this without rolling back couchbase-lite (I have countless replication issues w/ b22)?

Thank you!

**Comment by borrrden** [comment]
You are using beta 1 with CBL beta 2 and these two are not compatible.  You need to get a build of Sync Gateway beta 2.  There will be an announcement when it is officially posted to the website (currently in progress), but you can get it earlier by referencing [this forum post](https://forums.couchbase.com/t/when-will-the-db23-of-couchbase-2-0-be-available/16113/8) and downloading it directly from the backing store.

**Comment by stcleezy** [comment]
Perfect, thank you!
