### ISSUE TITLE
AccessViolationException in db023

### ISSUE THREAD

**Issue by gbuggy** [couchbase/couchbase-lite-net#997]
Still seeing AccessViolationException in db023, was previously reported here: https://github.com/couchbase/couchbase-lite-net/issues/983

This issue has been happening sporadically for us since db022.  I am testing with a dataset of around 300,000 records.  The error seems to come up randomly.  In this case it happened after about 2400 records were saved in a newly created database.  Attached is a screenshot of our code, and a screenshot of the log file complete with stack trace.

![accessviolationexception - db023](https://user-images.githubusercontent.com/37115170/37538134-0a71ea6a-2926-11e8-95a9-55fafa887404.png)

![accessviolationexception - db023 - log](https://user-images.githubusercontent.com/37115170/37538138-0bd83788-2926-11e8-8b3c-67ed8d4c56d8.png)

**Comment by borrrden** [comment]
At this point I think I will need a reproduction case, but first a confirmation.  If you enable text logging do you see the correct build number getting logged to the text logs (Should be 636).

**Comment by gbuggy** [comment]
Confirmed build 636, from the logfile:
Build/636 LiteCore/732 Commit/c18ebea

I am working on a test harness for this.

**Comment by gbuggy** [comment]
I made this test project to produce the error.  It creates a Couchbase Lite database and saves 10,000 batches of 750 records.  I ran it 100 times, 50 times each on two different machines and it only made it to 10,000 once.  It only got above 1,000 batches a few times.  There doesn't seem to be any rhyme or reason to when it will fail.

The app logs the current status to the console and shows a MessageBox on failure.  It creates a log file in its folder and records the AccessViolationException when it happens.

Any files or folders created are contained in the folder the app is run from.

https://www.dropbox.com/s/u6wm2fed9x3im2y/CouchbaseLiteAVETest.zip?dl=0

**Comment by gbuggy** [comment]
Glad you found the project helpful.  Not sure if this helps, but I noticed that the error never happens when I have the batch size set to 248 records or less.

**Comment by snej** [comment]
For `c4doc_dictContainsBlobs` to crash, I think the FLDict parameter would have to be bogus. In that case a C# reimplementation would crash too, right?

>garbage collection is playing a part by freeing native memory in a non-threadsafe way

Make sure your finalizers are making thread-safe calls to LiteCore!

**Comment by borrrden** [comment]
@snej That’s not possible to do. You cannot safely access other managed objects inside of a finalizer because the references are not gamuaranteed to be valid.

**Comment by borrrden** [comment]
Well maybe it is ( the requirement is that the finalizer not block waiting on locks or other long ops ) but actually I don’t see c4doc_free on the thread safety list. Is there a way it could affect this situation?

**Comment by snej** [comment]
> I don’t see c4doc_free on the thread safety list. Is there a way it could affect this situation?

It blows away the C4Document, so it can't be called while any other thread is using the document. If it's being called on a random background thread with no locks, that's definitely a crasher...

**Comment by snej** [comment]
...but that crash would only happen if there is a native reference to the C4Document, but the C# object with the finalizer has no live references. Is that possible?

**Comment by borrrden** [comment]
Yes, that was why I was thinking it would be ok to do it, and so far I haven't seen any other signs of this causing crashes.  The finalizer is only called if the object is not disposed, and no longer reachable from any references.  It's possible that LiteCore might still be doing stuff with it, but would that affect dictContainsBlobs?  The document it is working on should still be alive.  Note that this is just one concurrent thing that I saw.  The other was a mistaken DB change listener, but I corrected that and still observed the issue.  This test runs entirely single threaded, except for the GC.

**Comment by borrrden** [comment]
Thanks to @snej I have an even better fix, and a root cause.  The explanation is fairly complicated but the end result is that I am creating a C# byte array to represent the binary encoding of a document, and sending those bytes to the unmanaged layer for LiteCore to parse.  However, what I get back from one of the calls is a native pointer (i.e. IntPtr) which itself has a pointer to those bytes (pointer to a managed object is a no-no!).  With heavy GC activity it is likely that those bytes will be moved inside the managed heap even with such a short time between creation and use which means that the unmanaged pointer will be pointing to managed heap garbage.  The solution is to pin the C# array during these calls so that the garbage collector cannot move them.

**Comment by hrajput89** [comment]
I ran the test project for on windows platform and was able to successfully run the complete test. The test took around 45 mins to complete.

<img width="723" alt="screenshot 2018-03-23 15 00 38" src="https://user-images.githubusercontent.com/18100038/37826385-3ccb58b4-2eb9-11e8-9dcb-b00509720831.png">
